version = 1
cond = "connected"
modem_make = "SIMCom"
modem_model = "SIM7600NA-H"
modem_firmware = "LE20B01SIM7600NA_210506"

[[field_map]]
parser_field = "entries[].pci"
quantity = "lte_neighbor_pci"
sources = [
    { kind = "qmi", value = "QMI_NAS GetCellLocationInfo" },
]

[[field_map]]
parser_field = "entries[].earfcn"
quantity = "lte_neighbor_earfcn_dl"
sources = [
    { kind = "qmi", value = "QMI_NAS GetCellLocationInfo" },
]

[[field_map]]
parser_field = "entries[].rsrp"
quantity = "lte_neighbor_rsrp_dbm"
sources = [
    { kind = "qmi", value = "QMI_NAS GetSignalInfo" },
    { kind = "at", value = "AT+CPSI?" },
]

[[field_map]]
parser_field = "entries[].rsrq_rx0"
quantity = "lte_neighbor_rsrq_db_rx0"
sources = [
    { kind = "qmi", value = "QMI_NAS GetSignalInfo" },
]

[[field_map]]
parser_field = "entries[].rsrq_rx1"
quantity = "lte_neighbor_rsrq_db_rx1"
sources = [
    { kind = "qmi", value = "QMI_NAS GetSignalInfo" },
]
