version = 8
cond = "connected"
modem_make = "Sierra"
modem_model = "EM9190"
modem_firmware = "SWIX55C_03.17.04.00"

[[field_map]]
parser_field = "measurement_raw"
quantity = "lte_intrafreq_neighbor_rsrp_or_rsrq_raw_candidate"
sources = [
    { kind = "at", value = "AT!LTEINFO?" },
]

[[field_map]]
parser_field = "measured_cell_count"
quantity = "lte_intrafreq_neighbor_count"
sources = [
    { kind = "at", value = "AT!LTEINFO?" },
]
