"""0x1456 — GNSS Heartbeat (11B fixed; 5 named bytes + 6 reserved-zero invariants).

Cross-chipset RE corpus (2026-05-08 corpus walk, 67,045 records / 194
captures / 15 chipset families): 11-byte fixed payload with 6 invariant
zero bytes at offsets [0, 3, 4, 5, 9, 10] (100.0% across 67,045 records)
and 5 varying bytes at [1, 2, 6, 7, 8].

Byte map (validated against the full corpus):
  [0]   u8  version       = 0x00 (CONSTANT 67045/67045)
  [1]   u8  flag          ∈ {0x00 (38.6%), 0x01 (61.4%)} — bistate
  [2]   u8  state         multi-valued enum; 0x00 dominant (34.6%),
                             long-tail of state codes follow
  [3]   u8  reserved      = 0x00 (CONSTANT)
  [4]   u8  reserved      = 0x00 (CONSTANT)
  [5]   u8  reserved      = 0x00 (CONSTANT)
  [6]   u8  aux6          ∈ {0x00 (92.6%), 0x01 (7.4%)} — bistate
  [7]   u8  aux7          multi-valued; 0x00 dominant (85.0%)
  [8]   u8  aux8          multi-valued; 0x00 dominant (97.8%)
  [9]   u8  reserved      = 0x00 (CONSTANT)
  [10]  u8  reserved      = 0x00 (CONSTANT)

The pairing pattern observed in single-capture FN980m cold-reset
(430 records, 4 unique payload variants):
  (flag=1, state=3): 384 records — bulk steady-state
  (flag=0, state=2): 43 records  — quiescent
  (flag=1, state=1): 2 records   — transitional
  (flag=0, state=0): 1 record    — null/idle
Plausibly: `flag` is a "GNSS engine active" boolean, `state` is a phase
code.  Without a QXDM/external reference, the exact field semantics
remain hypotheses — but the byte-layout is now corpus-stable.

Tracked by GH issue #N.  Body-decode for the 5 varying bytes is
preserved as raw u8s so downstream consumers can apply their own
semantics if a reference surfaces.

Split from `gnss_demod.py` per #N tier-2 batch 12.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_CGPS_MC_TRACK_DPO_STATUS_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        LOG_CGPS_MC_TRACK_DYNAMIC_POWER_OPTIMIZATION_STATUS
            source: qxdm_3_12_714_2017_diag_log_codes
        LOG_RMAC_CARRIER_STATE_CHANGED
            source: qxdm_3_12_714_2017_diag_log_codes
        LOG_CGPS_MC_TRACKING_DPO_STATUS
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from diaggrok.registry import register

LOG_GNSS_HEARTBEAT_1456 = 0x1456

_1456_VERSION = 0x00


# Ground-truth capture recipe (#N / #N — <redacted-ref> 2026-06-07). ONE recipe:
# v=0x00 on the Telit LM960A18 (SDX20), corpus-attested (39 LM960 captures).
# Authored OFFLINE, hw_run_performed=False — a later hardware run flips it.
#
# Vendor name (LOG_CGPS_MC_TRACK_DPO_STATUS_C, qualcomm_diag_log_codes_h /
# vendor_official) identifies this as the GNSS tracking-engine Dynamic Power
# Optimization (DPO) status: DPO duty-cycles the tracking hardware to save power
# while a fix is held. The parser's observed pairing — (flag=1,state=3) bulk
# steady-state, (flag=0,state=2) quiescent, (flag=1,state=1) transitional,
# (flag=0,state=0) null/idle — fits a (engine-active, phase) reading. Ground on
# the LM960 with the Telit GNSS AT stack: flag tracks GNSS power/active state
# (AT$GPSP?), and state should advance toward the steady-state code as $GPSACP
# reports a held fix. aux6/aux7/aux8 are opaque DPO sub-state bytes with no
# known AT reference — left as honest hypotheses. version is a structural
# constant (0x00), not grounded.
#
# NOT YET VALIDATED. The bench LM960 (e3296e3) can't validate it now: the DIAG
# port fails the diaggulp log-mask handshake (#N/#N), so no 0x1456 stream
# is capturable yet.

@dataclass
class Diag0x1456:
    log_time: int
    version: int      # byte 0 — corpus-wide constant 0x00
    flag: int         # byte 1 — bistate
    state: int        # byte 2 — multi-valued state enum
    aux6: int         # byte 6 — bistate
    aux7: int         # byte 7 — multi-valued
    aux8: int         # byte 8 — multi-valued
    payload_size: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1456',
            'log_time': self.log_time,
            'version': self.version,
            'flag': self.flag,
            'state': self.state,
            'aux6': self.aux6,
            'aux7': self.aux7,
            'aux8': self.aux8,
            'payload_size': self.payload_size,
        }


@register(
    LOG_GNSS_HEARTBEAT_1456,
    name="0x1456",
    description="GNSS heartbeat/status (0x1456) — 11B fixed; 5 named bytes + 6 reserved-zero invariants",
    version=3,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v1 (2026-04-12) RE from FN980m SDX55 — exposed only `status` at "
        "byte 2.  v2 (2026-05-08) cross-validated against 67,045-record "
        "corpus / 194 captures / 15 chipset families; 11-byte fixed size "
        "confirmed.  6 invariant-zero bytes at [0, 3, 4, 5, 9, 10]; 5 "
        "varying bytes at [1, 2, 6, 7, 8] now exposed as named u8 fields."
    ),
    source_url="",
    fields_identified=8, fields_parsed=8,
    issues=(),
    primary_issue=None,
    supported_versions=[0x00],
    field_invariants={'version': {'enum': [0x00]}},
)
def parse_0x1456(log_time: int, data: bytes) -> Diag0x1456 | None:
    if len(data) != 11:
        return None
    if data[0] != _1456_VERSION:
        return None
    # Defensive: reject if reserved bytes aren't all zero — across 67,045
    # corpus records they always are, so any deviation indicates a
    # framing collision with another 0x14xx code.
    if data[3] != 0 or data[4] != 0 or data[5] != 0:
        return None
    if data[9] != 0 or data[10] != 0:
        return None
    return Diag0x1456(
        log_time=log_time,
        version=data[0],
        flag=data[1],
        state=data[2],
        aux6=data[6],
        aux7=data[7],
        aux8=data[8],
        payload_size=len(data),
    )
