"""LTE RRC OTA message parser (0xB0C0).

Standard LTE RRC Over-The-Air message log, present on all Qualcomm modems.
Contains ASN.1 PER-encoded RRC messages (SIBs, RRC Connection Setup/Reconfig,
measurement reports, handover commands, etc.).

Version 20 layout (SDX20/SDX55/MDM9607):
    [0]     u8   version (20)
    [1]     u8   rrc_release (14 = Rel-14)
    [2]     u8   constant 0x30 (NOT the channel - see #N)
    [3]     u8   reserved
    [4:6]   u16  physical_cell_id
    [6:8]   u16  earfcn
    [8:10]  u16  sfn_subfn (SFN << 4 | subfn)
    [10]    u8   pdu_number
    [11]    u8   encoding info (uncharacterized on v20; not the sib_mask)
    [12]    u8   channel_type (the REAL channel selector - see #N)
    [13:17] u32  sib_mask (SIB-presence bitmap, LE - see #N / sib_mask field)
    [17:19] u16  msg_length (bytes of ASN.1 PER-encoded RRC message)
    [19:]   bytes msg_data

Version 27 layout (SDX62/SDX55, the NR-capable header - RM520N-GL, RM500Q):
    [0]     u8   version (27)
    [1]     u8   rrc_release
    [2]     u8   rrc_ver_major
    [3]     u8   rrc_ver_minor
    [4]     u8   log-encoding constant (0x60 SDX62 / 0x90 SDX55; NOT the bearer)
    [5]     u8   radio_bearer_id (0=common/SRB0, 1=SRB1, 2=SRB2 - see #N)
    [6:8]   u16  physical_cell_id
    [8:12]  u32  earfcn (u32 - carries >65535 EARFCNs, e.g. B66)
    [12:14] u16  sfn_subfn
    [14]    u8   channel_type
    [15:19] u32  sib_mask (SIB-presence bitmap, LE)
    [19:21] u16  msg_length
    [21:]   bytes msg_data
The sib_mask sits in the 4 bytes immediately after channel_type on every
version, always followed by msg_length (u16). See the sib_mask field docstring
for the bit=SIB mapping and the "mask=0 means unpopulated" caveat.

⚠️ #N - the v20 channel selector lives at raw byte[12], NOT byte[2]. byte[2]
is a constant 0x30 on every observed v20 record (290/290 across EG18-NA + EG25-G,
both wire version 20), so reading the channel from byte[2] mislabelled EVERY
record as BCCH-DL-SCH (0x30) and mis-decoded PCCH/UL-CCCH. The byte[12] field
uses a DIFFERENT, contiguous small-integer enum from the legacy byte[2]-era
_CHANNEL_NAMES (see _V20_CHANNEL_NAMES below).

v20 channel_type enum at byte[12] - the observed enum {2,5,6,7,8,9} is now
both content-verified (#N, 2026-06-27 corpus sweep) AND qcsuper-byte-join
confirmed (#N, 2026-06-28, <redacted-host>); only never-observed values 1/3/4 (incl.
BCCH-BCH) await a bearing capture. The byte-join (qcsuper_capture_2026-04-06
EG25-G connected-mode capture) matched 56/56 v20 PDUs to qcsuper's GSMTAP
frames by raw RRC-PDU bytes, with 0 disagreements - qcsuper consulted as an
OUTPUT oracle only (we parse the pcap it wrote, never its source), enum
mapping cross-checked against tshark's independent GSMTAP dissection:
    2  BCCH-DL-SCH  - System Information / SIB1 (content-verified: only ch==2
                      records decode as SIB1 cell-access info; byte-join 18/18)
    5  PCCH         - Paging (qcsuper byte-join 19/19 + idle-camp frequency)
    6  DL-CCCH      - RRCConnectionSetup (content-verified: 30/30 ch==6 PDUs
                      decode as rrcConnectionSetup, a DL-CCCH-exclusive message;
                      qcsuper byte-join 2/2)
    7  DL-DCCH      - Reconfig/Release/SMC/dlInfoXfer (content-verified: all 68
                      ch==7 PDUs decode as DL-DCCH-exclusive messages; byte-join 6/6)
    8  UL-CCCH      - RRC Connection Request (qcsuper byte-join 2/2 - now
                      directly oracle-confirmed, not just v15-analogy + rarity)
    9  UL-DCCH      - SetupComplete/measReport/ulInfoXfer (content-verified: all
                      54 ch==9 PDUs decode as UL-DCCH-exclusive messages; byte-join 9/9)

Legacy byte[2]-era channel constants (LTE_RRC_CHANNEL_*) are retained for the
non-v20 multi-version path, which reads its channel from byte[12]/[14] and maps
through _CHANNEL_NAMES - that enum's per-version correctness is tracked
separately (see #N "confirm per wire version" item).

Reverse-engineered from SDX20 (LM960) and MDM9607 (EG25-G) DLF captures.
Cross-referenced with QCSuper and scat open-source DIAG parsers.

Techplayon QXDM field reference (sources/web/2026-04-07_techplayon_qxdm-log-packets.wacz),
canonical names per docs/qualcomm/techplayon-field-validation.md (#N Track 1)
+ docs/qualcomm/techplayon-cross-refs.md (#N Track 2):
    0xB0C0 - LTE RRC OTA Packet
        pkt_version, rrc_release_num, radio_bearer_id, phys_cell_id (a.k.a. pci),
        earfcn, sfn, subframe_number, pdu_bytes, pdu_length, sib_mask

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_LTE_RRC_OTA_MSG_LOG_C
        source: qualcomm_qxdm5_user_guide_80v124125i (authority: vendor_official)
    aliases:
        LOG_LTE_RRC_OTA_MESSAGE
            source: qxdm_3_12_714_2017_diag_log_codes
        LOG_OTA_MESSAGE
            source: qxdm_3_12_714_2017_diag_log_codes
        LOG_LTE_RRC_OTA_PACKET
            source: qxdm_itemtype_list_zukgit_2025_04_03
        LTE RRC OTA Packet
            source: qualcomm_qxdm_isf_filter_merge_perl_2020

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass, field
from struct import unpack_from
from typing import Any

from diaggrok.codes import LOG_LTE_RRC_OTA_MSG
from diaggrok.parsers.uper import UperReader
from diaggrok.parsers.asn1_helpers import read_open_type_length
from diaggrok.registry import register

# Channel type constants (3GPP TS 36.331)
LTE_RRC_CHANNEL_BCCH_BCH   = 0x01
LTE_RRC_CHANNEL_BCCH_DL_SCH = 0x30
LTE_RRC_CHANNEL_PCCH        = 0x0C
LTE_RRC_CHANNEL_DL_CCCH     = 0x08
LTE_RRC_CHANNEL_DL_DCCH     = 0x09
LTE_RRC_CHANNEL_UL_CCCH     = 0x0A
LTE_RRC_CHANNEL_UL_DCCH     = 0x0B

_CHANNEL_NAMES = {
    0x01: "BCCH-BCH",
    0x08: "DL-CCCH",
    0x09: "DL-DCCH",
    0x0A: "UL-CCCH",
    0x0B: "UL-DCCH",
    0x0C: "PCCH",
    0x30: "BCCH-DL-SCH",
}

# #N - v20 channel selector. The v20 wire format carries the RRC logical
# channel at raw byte[12] using a contiguous small-integer enum that is DISTINCT
# from the legacy byte[2]-era LTE_RRC_CHANNEL_* constants above. Only values
# actually witnessed in the corpus are mapped; an unobserved value falls back to
# a hex string ("0x03" etc.) so a future BCCH-BCH-bearing capture surfaces as an
# honest unknown rather than a fabricated name.
#
# The full observed enum {2,5,6,7,8,9} is now CONTENT-VERIFIED across the corpus
# (#N, 2026-06-27 corpus sweep, 5.4K v20 records / 720 captures). 2/5/8 were
# already pinned (SIB1 content + qcsuper oracle); 6/7/9 were surfaced by
# connected-mode captures (LTE attach, per-channel sweeps, SIM power-cycle/reboot
# - 152 dedicated-channel records the prior idle-only EG18-NA/EG25-G corpus never
# exercised) and content-verified clean-room: every record's RRC PDU decodes (our
# UperReader, TS 36.331 Rel-8 c1 CHOICE order) as a message EXCLUSIVE to its
# channel, ZERO cross-channel contamination:
#   6 -> DL-CCCH : 30/30 rrcConnectionSetup
#   7 -> DL-DCCH : dlInformationTransfer 33 / rrcConnRelease 26 / Reconfig 4 /
#                  ueCapabilityEnquiry 3 / securityModeCommand 2 (all DL-DCCH-only)
#   9 -> UL-DCCH : rrcConnSetupComplete 30 / ulInformationTransfer 12 /
#                  ReconfigComplete 4 / securityModeComplete 3 / measReport 3 /
#                  ueCapabilityInformation 2 (all UL-DCCH-only)
# Internal consistency: ch6 rrcConnSetup (30) == ch9 rrcConnSetupComplete (30) -
# each DL setup answered by one UL complete during attach. This EXACTLY matches
# the qcsuper-pinned v15 byte[12] enum below, confirming v20 and v15 share the
# contiguous enum. Values 1/3/4 (incl. BCCH-BCH) remain unobserved -> hex fallback.
#
# Black-box CONFIRMATION (#N, 2026-06-28, <redacted-host>): the clean-room enum above is
# now independently confirmed by a qcsuper byte-join on the EG25-G connected-mode
# capture qcsuper_capture_2026-04-06.dlf - 56/56 v20 PDUs matched qcsuper's GSMTAP
# frames by raw RRC-PDU bytes, 0 disagreements, full enum coverage incl. 6->DL-CCCH
# (2/2), 7->DL-DCCH (6/6), 9->UL-DCCH (9/9), and 8->UL-CCCH (2/2, the one value
# previously pinned only by v15-analogy). qcsuper is an OUTPUT oracle here (we read
# the pcap it emitted, never its source - see tools/blackbox/AGENTS.md); the
# GSMTAP sub-type->channel mapping is the osmocom spec enum, cross-checked against
# tshark's independent dissection of the same pcap.
LTE_RRC_V20_CHANNEL_OFFSET = 12
LTE_RRC_V20_CHANNEL_BCCH_DL_SCH = 2
LTE_RRC_V20_CHANNEL_PCCH = 5
LTE_RRC_V20_CHANNEL_DL_CCCH = 6
LTE_RRC_V20_CHANNEL_DL_DCCH = 7
LTE_RRC_V20_CHANNEL_UL_CCCH = 8
LTE_RRC_V20_CHANNEL_UL_DCCH = 9

_V20_CHANNEL_NAMES = {
    LTE_RRC_V20_CHANNEL_BCCH_DL_SCH: "BCCH-DL-SCH",  # SystemInformation / SIB1
    LTE_RRC_V20_CHANNEL_PCCH: "PCCH",                # Paging
    LTE_RRC_V20_CHANNEL_DL_CCCH: "DL-CCCH",          # RRCConnectionSetup/Reject
    LTE_RRC_V20_CHANNEL_DL_DCCH: "DL-DCCH",          # Reconfig/Release/SMC/dlInfoXfer
    LTE_RRC_V20_CHANNEL_UL_CCCH: "UL-CCCH",          # RRCConnectionRequest
    LTE_RRC_V20_CHANNEL_UL_DCCH: "UL-DCCH",          # SetupComplete/measReport/ulInfoXfer
}

# #N - per-wire-version channel enums for the NON-v20 parse path, each pinned
# by a byte-identical join of our RRC PDUs against the qcsuper GSMTAP output
# (clean-room: qcsuper is consulted as an OUTPUT oracle only, never as source).
# The channel enum is genuinely per-version - there is NO single non-v20 map:
#   * v15 (MDM9x50) uses the SAME small-int enum as v20's byte[12] enum.
#   * v26/v27 (SDX55/SDX62) use a DIFFERENT enum (DL-CCCH..UL-DCCH at 8..11).
#   * v9 (MDM9230) and v2 (MDM9600) are distinct again.
# Only channel_type values actually OBSERVED and byte-joined are mapped; an
# unobserved value falls back to a hex string (honest unknown). We deliberately
# do NOT fall back to the legacy byte[2]-era _CHANNEL_NAMES here - it is WRONG
# for these versions (e.g. it mislabelled v9 ct=11 as UL-DCCH when the oracle
# proves it is PCCH, and v15 ct=8/9 as DL-CCCH/DL-DCCH when they are UL-CCCH/
# UL-DCCH). Extend a version's map only from a fresh qcsuper byte-join.
_NONV20_CHANNEL_NAMES_BY_VERSION: dict[int, dict[int, str]] = {
    # MC7700 / MDM9600 (SWI9200X). Idle camp - only PCCH (paging) observed.
    2: {4: "PCCH"},
    # EM7455 / MDM9230. Idle camp - SIB broadcast + paging.
    9: {9: "BCCH-DL-SCH", 11: "PCCH"},
    # Quectel EG95-NA (MDM9207). #N 2026-07-09 recheck: a NEW version that
    # entered the corpus after the v18 pin (490 records / 20 captures). Shares
    # v9's contiguous small-int enum at byte[12]. qcsuper byte-join on the EG95-NA
    # idle diag capture matched 38/38 PDUs by raw RRC bytes: ct=9->BCCH-DL-SCH
    # (17/17, also content-verified - 59 SIB1 + 72 SI decode via our UperReader)
    # and ct=11->PCCH (21/21). Rare byte[12] values 12/13/14/15 (2..4 records each,
    # never oracle-decoded) stay unmapped -> honest hex.
    12: {9: "BCCH-DL-SCH", 11: "PCCH"},
    # Quectel EP06-A (MDM9x40). #N 2026-07-09 recheck: a NEW version (142
    # records / 5 captures). qcsuper byte-join on the EP06-A gnss-comparison idle
    # capture matched 65/65 PDUs: ct=4->PCCH (65/65). Only PCCH observed in the
    # idle window; other channels await a connected-mode v13 capture -> honest hex.
    13: {4: "PCCH"},
    # MDM9x50 (EM7565 SWI9X50C_01.08.04.00, MC7411). Same enum as v20 byte[12].
    15: {2: "BCCH-DL-SCH", 5: "PCCH", 6: "DL-CCCH", 7: "DL-DCCH",
         8: "UL-CCCH", 9: "UL-DCCH"},
    # SDX55 (Wistron LV55). Distinct enum: dedicated/CCCH at 8..11.
    26: {3: "BCCH-DL-SCH", 7: "PCCH", 8: "DL-CCCH", 9: "DL-DCCH",
         10: "UL-CCCH", 11: "UL-DCCH"},
    # SDX62 (RM520N-GL, CFW-3212). Identical enum to v26.
    27: {3: "BCCH-DL-SCH", 7: "PCCH", 8: "DL-CCCH", 9: "DL-DCCH",
         10: "UL-CCCH", 11: "UL-DCCH"},
    # v30 (0x1E, Foxconn T99W640). #N (2026-07-12): the byte-join now PASSES
    # byte-identically once the v30 msg_length read is corrected (see the
    # `version == 30` PDU fix in _parse_common). qcsuper's GSMTAP LTE-RRC payload
    # equals data[21:end] (rawlen-21) EXACTLY on all 7 records; the header u16 at
    # [19:21] is NOT the PDU length (it consistently holds PDU_len - 3, and the
    # trailing 3 bytes vary per record -> they are PER-message content, not a
    # trailer). With the PDU matching, the channel enum is pinned from qcsuper's
    # GSMTAP sub_type: byte[14]=3 -> BCCH-DL-SCH (4/4 records, sub_type 5),
    # byte[14]=7 -> PCCH (3/3 records, sub_type 6) - the same {3,7} pair as the
    # v26/v27 SDX55/SDX62 family. Connected-mode channels (CCCH/DCCH) await a
    # richer v30 capture; only idle BCCH/PCCH are in the 7-record bringup capture.
    30: {3: "BCCH-DL-SCH", 7: "PCCH"},
}

_V20_HEADER_SIZE = 19  # bytes before msg_data


@dataclass
class Diag0xB0C0:
    """Parsed LTE RRC OTA message."""
    log_time: int
    version: int
    rrc_release: int
    channel_type: int
    channel_name: str
    pci: int
    earfcn: int
    sfn: int
    subfn: int
    pdu_number: int
    msg_length: int
    msg_data: bytes    # raw ASN.1 PER-encoded RRC message
    # Radio bearer id (#N) - Techplayon-documented `radio_bearer_id`
    # (TS 36.331 rb-Identity). On the version>=25 header this is the HIGH byte of
    # the 2-byte field at [4:6] (byte[5]) that the parser previously skipped over
    # when jumping to pci@6. Values seen: 0 = common / broadcast (SRB0 - every
    # BCCH-DL-SCH/PCCH/DL-CCCH/UL-CCCH record), 1 = SRB1, 2 = SRB2 (dedicated
    # DL/UL-DCCH). The partition is byte-clean across BOTH SDX62 (RM520N-GL) and
    # SDX55 (Inseego M2000): a common channel never carries 1/2, a DCCH never
    # carries 0. The LOW byte [4] is a per-chipset log-encoding CONSTANT (0x60 on
    # SDX62, 0x90 on SDX55 - invariant within a capture, orthogonal to the bearer)
    # so it is deliberately NOT folded into this value. None on versions whose
    # header places pci at byte[4] (no separate bearer field on the wire there).
    radio_bearer_id: int | None = None
    # SIB mask (#N) - Techplayon-documented `sib_mask` ("Qualcomm-internal
    # bitmap of decoded SIB IDs"). A u32-LE bitmap in the 4 bytes immediately
    # AFTER channel_type on every version (v20: byte[13:17]; v>=8 non-v20: the 4
    # bytes the length-probe skips), immediately followed by msg_length (u16-LE).
    # bit N (1..31) set <=> SystemInformationBlockTypeN is present in this SI
    # message; bit0 is unused. RE'd clean-room by correlating the field against
    # the SIBs the PDU decodes to across 791 BCCH-DL-SCH records (SIB1->0x02,
    # SIB2+SIB3->0x0c, SIB4->0x10, SIB5->0x20; adversarially verified, zero
    # wrong-bit counterexamples). The mask ALSO independently flags bit8=SIB8
    # (CDMA2000, rides with SIB5 as 0x120; body decoded into sib8_cdma_time, #N)
    # and bit24=SIB24 (NR cell reselection, broadcast by the 5G-capable SDX62 as
    # the lone 0x1000000 records; body not yet decoded - #N). Non-SI channels
    # (DCCH/CCCH/PCCH) carry 0. FAITHFUL to the wire: ~8.5% of BCCH-DL-SCH records
    # (mostly v20) carry a real SIB with mask=0 on the wire - so sib_mask==0 means
    # "field unpopulated", NOT "no SIBs present". The authoritative SIB-presence
    # signal is the decoded sibN_* fields; sib_mask is the firmware's own hint
    # (and the only signal for SIB24, whose body we do not yet decode). None when
    # the record carries no mask field.
    sib_mask: int | None = None
    # SIB numbers whose bit is set in sib_mask (derived; empty list when
    # sib_mask is 0 or None). See the sib_mask caveat above: an empty list does
    # not prove the SI carries no SIBs.
    sibs_present: list[int] = field(default_factory=list)
    # RRC release minor/patch - populated on non-v20 versions where the wire
    # carries them at byte[2]/byte[3] (QCAT label: "RRC Release Number.Major.
    # minor"). v20 puts channel_type/reserved at those offsets, so they
    # remain None on v20. Matches the lte_nas_ota.py naming convention (#N).
    # Ground truth: QCAT decodes a v15 record's "RRC Release Number.Major.
    # minor = 13.2.1" → rrc_rel=13, rrc_ver_major=2, rrc_ver_minor=1. See
    # sources/qualcomm/community/tool_analysis_qcat/
    # 05-22_signaling.txt.layers.yaml § wire_frame_fields.
    rrc_ver_major: int | None = None
    rrc_ver_minor: int | None = None
    # SIB1 decoded fields (populated when message is SIB1)
    sib1_mcc: str | None = None
    sib1_mnc: str | None = None
    sib1_tac: int | None = None
    sib1_cell_id: int | None = None
    # NAS-tunneling decode (populated for DCCH InformationTransfer carrying
    # dedicatedInfoNAS - see _try_decode_nas_tunneled). nas_tunneled is True
    # iff the dedicatedInfoNAS path was matched and dedicated_info_nas holds
    # the extracted NAS PDU bytes.
    nas_tunneled: bool = False
    dedicated_info_nas: bytes | None = None
    # measConfig auto-decode (#N) - populated when a DL-DCCH record carries
    # an RRCConnectionReconfiguration whose measConfig is present. Decoded by
    # lte_rrc_reconfig.decode_rrc_reconfig_meas_config. meas_objects is the list
    # of MeasObjectEUTRA (each: earfcn/bandwidth/offset + CellToAddMod list);
    # has_meas_gap / s_measure are the measConfig scalars. Empty/None when the
    # record is not a reconfiguration, carries no measConfig, or fails to decode.
    meas_objects: list[Any] = field(default_factory=list)
    meas_has_gap_config: bool = False
    meas_s_measure: int | None = None
    # MeasurementReport auto-decode (#N) - populated when a UL-DCCH record
    # carries a MeasurementReport. Decoded by
    # lte_rrc_meas_report.decode_measurement_report. meas_report_id is the
    # measId (1..maxMeasId); pcell_rsrp/rsrq are the serving-cell measurements
    # in dBm/dB; meas_report_neighbors is the list of MeasResultCell. None when
    # the record is not a MeasurementReport or fails to decode.
    meas_report_id: int | None = None
    meas_report_pcell_rsrp: float | None = None
    meas_report_pcell_rsrq: float | None = None
    meas_report_neighbors: list[Any] = field(default_factory=list)
    # SIB2/SIB3/SIB4 auto-decode (#N/#N/#N / #N) - populated when a
    # BCCH-DL-SCH record carries a SystemInformation container with the
    # respective SIB. Decoded in ONE container walk by
    # lte_rrc_sib_time.decode_si_sibs: sib2_access = access barring / RACH /
    # common radio config; sib3_resel = intra-freq cell-reselection params
    # (q-Hyst, threshServingLow, priority, s-IntraSearch…); sib4_neighbors =
    # intra-freq neighbor cells (PCI + q-offset), excluded PCI ranges, CSG
    # range. Each is None when the record is a SIB1 or carries no such SIB.
    sib2_access: Any | None = None
    sib3_resel: Any | None = None
    sib4_neighbors: Any | None = None
    # SIB5 auto-decode (#N / #N) - populated when a BCCH-DL-SCH record
    # carries a SystemInformation container with SIB5, via the same fused
    # decode_si_sibs walk (per-carrier inter-freq reselection info +
    # neighbor/excluded lists + v8h0/v9e0 multi-band overlays + Ext-r12
    # additional carriers). None when the record is a SIB1 or carries no SIB5.
    sib5_inter_freq: Any | None = None
    # SIB6 auto-decode (#N) - populated when a BCCH-DL-SCH record carries a
    # SystemInformation container with SIB6 (UTRAN/3G neighbor freqs). Decoded
    # by lte_rrc_sib_time.decode_si_sib6. None when the record is a SIB1 or
    # carries no SIB6. SIB6 is absent from the on-host corpus (US 3G sunset);
    # wired for future 3G-neighbor captures, validated via pycrate vectors.
    sib6_neighbors: Any | None = None
    # SIB7 auto-decode (#N) - populated when a BCCH-DL-SCH record carries a
    # SystemInformation container with SIB7 (GERAN/2G neighbor freqs). Decoded
    # by lte_rrc_sib_time.decode_si_sib7. None when the record is a SIB1 or
    # carries no SIB7. SIB7 is absent from the on-host RM520N-GL corpus (0/2886
    # 0xB0C0 records; US 2G sunset - SIB5 present in the same scan proves the
    # walk is live); wired for future 2G-neighbor captures, validated via pycrate.
    sib7_neighbors: Any | None = None
    # SIB8 CDMA system-time anchor (#N) - a SibTimeInfo (source="sib8")
    # populated when a BCCH-DL-SCH record carries a SystemInformation container
    # with SIB8 (CDMA2000 synchronousSystemTime), via the same fused
    # decode_si_sibs walk. None when the record is a SIB1 or carries no SIB8.
    # Present in the RM520N-GL corpus on band-12 cells still broadcasting a
    # CDMA2000 neighbour config (EARFCN 5230); the decoded UTC is a wall-clock
    # time anchor for DIAG ts64 calibration (10ms tick, TS 36.331 §6.3.1).
    sib8_cdma_time: Any | None = None
    # SIB16 auto-decode (#N) - populated when a BCCH-DL-SCH record carries a
    # SystemInformation container with SIB16 (UTC/GPS network time). Decoded by
    # lte_rrc_sib_time.decode_si_sib16 in the same fused container walk. Full
    # fields (time_info_utc / utc_datetime / leap_seconds / dst /
    # local_time_offset), not just the time anchor. None when the record is a
    # SIB1 or carries no SIB16. SIB16 is absent from the on-host corpus (US
    # operators anchor time via SIB8/GNSS); wired for future SIB16-bearing
    # captures, validated via pycrate vectors.
    sib16_time: Any | None = None
    # SIB24 auto-decode (#N) - populated when a BCCH-DL-SCH record carries a
    # SystemInformation container with SIB24 (NR/5G inter-RAT cell reselection).
    # Decoded by lte_rrc_sib_time.decode_si_sib24 in the same fused container
    # walk. Per-carrier NR ARFCN / band / reselection priority + sub-priority /
    # threshX / q-RxLevMin / p-MaxNR / q-QualMin / SSB spacing + duration, plus
    # t-ReselectionNR. Presence is flagged by the sib_mask bit24 (#N); the
    # SDX62 RM520N-GL broadcasts it in the corpus. None when the record is a
    # SIB1 or carries no SIB24.
    sib24_nr_resel: Any | None = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            'type': 'Diag0xB0C0',
            'log_time': self.log_time,
            'version': self.version,
            'rrc_release': self.rrc_release,
            'channel_type': self.channel_type,
            'channel_name': self.channel_name,
            'pci': self.pci,
            'earfcn': self.earfcn,
            'sfn': self.sfn,
            'subfn': self.subfn,
            'pdu_number': self.pdu_number,
            'msg_length': self.msg_length,
            # The raw ASN.1 PER-encoded RRC message - the whole point of an RRC
            # OTA log (#N): downstream ASN.1 decode / pcap export (QCSuper-style)
            # needs the PDU bytes, not just its length. Hex like dedicated_info_nas.
            'msg_data': self.msg_data.hex() if self.msg_data else '',
        }
        # radio_bearer_id (#N) - present-only, header-level field.
        if self.radio_bearer_id is not None:
            d['radio_bearer_id'] = self.radio_bearer_id
        # sib_mask (#N) - present-only. Emit the raw bitmap AND the derived
        # SIB-number list so downstream (WiGLE / pcap / SI analysis) sees which
        # SIBs the firmware flagged, including SIB24 (bit24) we do not deep-decode.
        if self.sib_mask is not None:
            d['sib_mask'] = self.sib_mask
            d['sibs_present'] = self.sibs_present
        if self.rrc_ver_major is not None:
            d['rrc_ver_major'] = self.rrc_ver_major
            d['rrc_ver_minor'] = self.rrc_ver_minor
        if self.sib1_tac is not None:
            d['sib1_mcc'] = self.sib1_mcc
            d['sib1_mnc'] = self.sib1_mnc
            d['sib1_tac'] = self.sib1_tac
            d['sib1_cell_id'] = self.sib1_cell_id
        if self.nas_tunneled:
            d['nas_tunneled'] = True
            d['dedicated_info_nas'] = (
                self.dedicated_info_nas.hex()
                if self.dedicated_info_nas is not None
                else None
            )
        # measConfig (#N) - only emit when a reconfiguration actually
        # carried meas objects, mirroring the SIB1/NAS "present-only" pattern.
        if self.meas_objects:
            d['meas_objects'] = [m.to_dict() for m in self.meas_objects]
            d['meas_has_gap_config'] = self.meas_has_gap_config
            if self.meas_s_measure is not None:
                d['meas_s_measure'] = self.meas_s_measure
        # MeasurementReport (#N) - keyed on meas_report_id being set.
        if self.meas_report_id is not None:
            d['meas_report_id'] = self.meas_report_id
            d['meas_report_pcell_rsrp'] = self.meas_report_pcell_rsrp
            d['meas_report_pcell_rsrq'] = self.meas_report_pcell_rsrq
            d['meas_report_neighbors'] = [
                c.to_dict() for c in self.meas_report_neighbors
            ]
        # SIB2/SIB3/SIB4 (#N/#N/#N / #N) - present-only, mirroring
        # the SIB1/NAS pattern.
        if self.sib2_access is not None:
            d['sib2_access'] = self.sib2_access.to_dict()
        if self.sib3_resel is not None:
            d['sib3_resel'] = self.sib3_resel.to_dict()
        if self.sib4_neighbors is not None:
            d['sib4_neighbors'] = self.sib4_neighbors.to_dict()
        # SIB5 (#N) - present-only, mirroring the SIB2 pattern.
        if self.sib5_inter_freq is not None:
            d['sib5_inter_freq'] = self.sib5_inter_freq.to_dict()
        # SIB6 (#N) - present-only, mirroring the SIB2 pattern.
        if self.sib6_neighbors is not None:
            d['sib6_neighbors'] = self.sib6_neighbors.to_dict()
        # SIB7 (#N) - present-only, mirroring the SIB2 pattern.
        if self.sib7_neighbors is not None:
            d['sib7_neighbors'] = self.sib7_neighbors.to_dict()
        # SIB8 CDMA system time (#N) - present-only, mirroring the pattern.
        if self.sib8_cdma_time is not None:
            d['sib8_cdma_time'] = self.sib8_cdma_time.to_dict()
        # SIB16 (#N) - present-only, mirroring the SIB2 pattern.
        if self.sib16_time is not None:
            d['sib16_time'] = self.sib16_time.to_dict()
        # SIB24 NR cell reselection (#N) - present-only, mirroring the pattern.
        if self.sib24_nr_resel is not None:
            d['sib24_nr_resel'] = self.sib24_nr_resel.to_dict()
        return d


# Ground-truth recipe (#N). Hardware-validated on the connected EG25-G.

@register(LOG_LTE_RRC_OTA_MSG, domain="rrc",
    name="0xB0C0",
    description="Standard LTE RRC Over-The-Air message with ASN.1 PER-encoded content",
    version=23,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v22 (2026-07-09, #N new-data recheck): the corpus grew 720->966 "
        "captures since the v18 non-v20 pin, surfacing THREE 0xB0C0 wire versions "
        "that did not exist at the last analysis - v12 (0x0C, Quectel EG95-NA / "
        "MDM9207, 490 records / 20 captures), v13 (0x0D, Quectel EP06-A / MDM9x40, "
        "142 / 5), and v30 (0x1E, Foxconn T99W640, 7 / 1). Pinned v12 "
        "{9:BCCH-DL-SCH, 11:PCCH} and v13 {4:PCCH} by a byte-identical join of our "
        "RRC PDUs against the qcsuper GSMTAP output (clean-room OUTPUT oracle, "
        "never source): v12 38/38 PDUs (ct=9->BCCH-DL-SCH 17/17, ALSO "
        "content-verified via 59 SIB1 + 72 SI decodes with our UperReader; "
        "ct=11->PCCH 21/21), v13 65/65 (ct=4->PCCH). v12 shares v9's enum; v13's "
        "value 4 collides numerically with v2's PCCH but sits at a different wire "
        "offset (byte[12] vs v2 byte[10]) - the per-version map handles it. "
        "v23 (2026-07-12, #N): v30 (0x1E, Foxconn T99W640) is now PINNED "
        "{3:BCCH-DL-SCH, 7:PCCH}. The v22 byte-join failure was a msg_length "
        "read bug, not a header defect: on v30 the u16 at [19:21] is NOT the PDU "
        "byte length (it consistently holds PDU_len - 3), and the true RRC PDU is "
        "the remainder of the record after the 21-byte header (rawlen-21). "
        "Correcting the v30 length read to rest-of-record makes our msg_data equal "
        "the qcsuper GSMTAP LTE-RRC payload byte-identically on all 7 records "
        "(4 BCCH-DL-SCH ct=3 / GSMTAP sub_type 5, 3 PCCH ct=7 / sub_type 6); with "
        "the PDU matching, the {3,7} enum is pinned by the same clean byte-join "
        "discipline as v26/v27 (whose {3,7} it shares). There is NO 3-byte trailer: "
        "the trailing bytes vary per record (PER-encoded message content), so "
        "reading (b) 'rawlen-24 + trailer' is refuted; reading (a) 'PDU = rawlen-21' "
        "is confirmed. Connected-mode channels (CCCH/DCCH) await a richer v30 "
        "capture; only idle BCCH/PCCH are in the 7-record bringup capture. Rare "
        "v12 byte[12] values "
        "12/13/14/15 (2..4 records each, never oracle-decoded) also stay unmapped. "
        "v21 (2026-07-02, #N): DECODE - the two previously-unparsed header "
        "regions are now named fields, taking the container to 100% byte "
        "accounting. (1) radio_bearer_id (Techplayon rb-Identity): the HIGH byte "
        "of the version>=25 [4:6] field (byte[5]) - 0=common/SRB0 (every "
        "BCCH/PCCH/CCCH record), 1=SRB1, 2=SRB2 (dedicated DL/UL-DCCH). "
        "Byte-clean partition across BOTH SDX62 (RM520N-GL) and SDX55 (Inseego "
        "M2000); the LOW byte [4] is a per-chipset log-encoding constant (0x60 "
        "SDX62 / 0x90 SDX55), documented but not folded in. (2) sib_mask "
        "(Techplayon 'bitmap of decoded SIB IDs'): the u32-LE bitmap in the 4 "
        "bytes immediately after channel_type (v20: byte[13:17]; v>=8 non-v20: "
        "the 4 bytes the length-probe already skipped), bit N=SIBN present. RE'd "
        "clean-room by correlating the field against the SIBs the PDU decodes to "
        "(SIB1->0x02, SIB2+3->0x0c, SIB4->0x10, SIB5->0x20) across 791 "
        "BCCH-DL-SCH records; adversarially verified with ZERO wrong-bit "
        "counterexamples. The mask also independently flags bit8=SIB8 (CDMA2000, "
        "rides with SIB5 as 0x120; body decoded into sib8_cdma_time via #N) and "
        "bit24=SIB24 (NR cell reselection, the lone 0x1000000 records the 5G SDX62 "
        "broadcasts; body not yet decoded - #N). FAITHFUL to the wire: ~8.5% of "
        "BCCH records (mostly v20) "
        "carry a real SIB with mask=0 - sib_mask==0 means 'unpopulated', not 'no "
        "SIBs'; the authoritative presence signal stays the decoded sibN_* "
        "fields. Additive-only: reads exactly the bytes the parser previously "
        "discarded; verified 0/2793 records change any other field. "
        "v18 (2026-06-27, #N): FIX - non-v20 channel naming. Each wire version "
        "has its OWN channel enum; the old non-v20 path used the legacy byte[2]-era "
        "_CHANNEL_NAMES, which DROPPED the small-int values and MISLABELLED the "
        "collisions. Pinned per-version enums by a byte-identical join of our RRC "
        "PDUs against the qcsuper GSMTAP output (clean-room: qcsuper OUTPUT oracle, "
        "never source), 100% PDU match on every capture: "
        "v15 (EM7565+MC7411) {2:BCCH-DL-SCH,5:PCCH,6:DL-CCCH,7:DL-DCCH,8:UL-CCCH,"
        "9:UL-DCCH} (== the v20 byte[12] enum); v26 (LV55) == v27 (RM520N-GL) "
        "{3:BCCH-DL-SCH,7:PCCH,8:DL-CCCH,9:DL-DCCH,10:UL-CCCH,11:UL-DCCH}; "
        "v9 (EM7455) {9:BCCH-DL-SCH,11:PCCH}; v2 (MC7700) {4:PCCH}. Concrete bugs "
        "fixed: v15 ct=8/9 were emitted as DL-CCCH/DL-DCCH but are UL-CCCH/UL-DCCH; "
        "v9 ct=11 was 'UL-DCCH' but is PCCH (the recipe note carried that mislabel "
        "- now corrected, and the capture's own F3 PCCH_DL_DATA_IND agrees). "
        "Unmapped (version,ct) → honest hex (no legacy guess). _try_decode_nas_"
        "tunneled re-keyed on channel NAME (DCCH value is version-dependent). "
        "Native GSMTAP pcap (#N) inherits the corrected labels; v20 path "
        "unchanged. Verified end-to-end: regenerated v15 pcap channels now match "
        "qcsuper. "
        "v17 (2026-06-27, #N): FIX - the v20 RRC channel selector is raw "
        "byte[12], not byte[2]. byte[2] is a constant 0x30 on 290/290 observed "
        "v20 records (EG18-NA 2026-04-08 + EG25-G 2026-04-24), so the old "
        "channel_type=data[2] read mislabelled EVERY v20 record BCCH-DL-SCH and "
        "mis-decoded PCCH/UL-CCCH. v20 uses its own small-int enum at byte[12] "
        "{2:BCCH-DL-SCH, 5:PCCH, 8:UL-CCCH} - distinct from the legacy "
        "byte[2]-era _CHANNEL_NAMES. ch==2->BCCH-DL-SCH is CONTENT-VERIFIED "
        "(only ch==2 decodes as SIB1; 10 unique cells on EG18-NA); 5/8 from the "
        "qcsuper pcap oracle + frequency. SIB1 auto-decode trigger switched from "
        "channel_type==0x30 to channel_name=='BCCH-DL-SCH' so it survives the "
        "enum change (and stays correct on the non-v20 path). PARTIAL recipe: "
        "the full byte[12] enum (1/3/4/6/7/9) and per-version confirmation "
        "(v2/v15/v26/v27 channel offset/enum) await DL-CCCH/DCCH/BCCH-BCH "
        "captures - #N stays open for that. Native GSMTAP pcap (#N, "
        "tools/diag_pcap.py) inherits the corrected channel labels. "
        "v16 (2026-06-20, #N/#N <redacted-ref>, host <redacted-host>): cross-keyed the "
        "MC7411 wire-version 15 (0x0F) layout to a SECOND MDM9x50 Sierra device - "
        "added a Sierra EM7565 (Snapdragon X16 LTE-A, SWI9X50C_01.08.04.00) "
        "per-modem v15 recipe. REGISTERED on a private CBRS B48 cell (PLMN 315/010, "
        "EARFCN 55340, PCI 451): the v8..24 path (pci=u16@4, earfcn=u32) decodes "
        "pci=451 (50/51) and earfcn=55340 (37/51 serving-dominant; 43190/43390 = "
        "COPS-rescan sweep) - both VERIFIED by identity vs QMI "
        "GetCellLocationInfo serving PCI 451 / EUTRA RF Channel 55340, AT!GSTATUS, "
        "and co-captured verified 0xB116 config_word=451 (2157/2157) + 0xB193 "
        "earfcn=55340 (2155/2155). SIB1 deep-decode (sib1_tac/sib1_cell_id) NOT "
        "exercised (no BCCH-DL-SCH SystemInformation record decoded in-window). "
        "Own full-mask dual-mask DIAG+F3 capture (if00, no SPC - Sierra DIAG "
        "unauthenticated; COPS dereg→recamp cycle). F3 (qdb GUID 3be39d44, "
        "em7511 sibling-build-identical) RRC subsystem (rrctmr.c/rrcmcm.c) confirms "
        "RRC-OTA. Capture promoted Step 5b. "
        "v15 (2026-06-20, #N/#N <redacted-ref>, host <redacted-host>): added two new "
        "FieldGrounds to the LM960 v0x14 recipe - sib1_tac and sib1_cell_id, both "
        "VERIFIED. A 3-cell AT#BND band-lock drive (B66→B2→B12, CFUN re-acq) on "
        "unit 287b0ebd @ 32.01.140 read SIB1 on three distinct serving cells; the "
        "SIB1 ASN.1 fields match AT#MONI/#RFSTS broadcast TAC + cellIdentity BY "
        "IDENTITY (hex): sib1_tac 11544/3328 == TAC 0x2D18 (B66/B12)/0x0D00 (B2), "
        "sib1_cell_id 21579779/3359266/46903831 == Id 0x1494803/0x334222/0x2CBB217. "
        "Unlike the u16-truncated earfcn header field, the SIB1-body ECI/TAC decode "
        "is full-width and correct. F3 lte_rrc_sib.c (qdb GUID 209a8edf slot_3, "
        "0x99 resolved 100%%) confirms per-cell SIB1 reads. "
        "v13 (2026-06-18, #N <redacted-ref>, host <redacted-host>): added the Quectel "
        "RM520N-GL (NATIVE Qualcomm SDX62, R03A04 01.203.01.203) per-modem recipe "
        "at wire version 27 (0x1B) - own dual-mask DIAG+F3 idle capture, camped "
        "Verizon B66: pci=310 (31/31) and earfcn=66536 (31/31) == AT+QENG serving, "
        "TRIPLE-anchored by co-captured verified 0xB116 config_word=310 + 0xB193 "
        "serving pci=310/earfcn=66536 => pci AND earfcn VERIFIED. First RM520N-GL "
        "keying of 0xB0C0 (was sibling-able); confirms the SDX62 RRC-OTA header "
        "layout on native Quectel firmware (vs the CFW-3212 SDX62-OpenCPU v27). "
        "v12 (2026-06-14, #N <redacted-ref>, host <redacted-host>): added a Telit "
        "LM960A18 (SDX20) sibling at wire version 0x14, F3-ground-truth round (0x99 "
        "resolved 100%% vs qdb GUID 2f5667ef). The firmware's own lte_rrc_sib.c "
        "per-SIB 'phy_cell_id = %d & freq = %d' labels anchor every decoded SIB: "
        "pci VERIFIED (6/6 PCIs == F3 phy_cell_id across a LIMSRV reselection), "
        "earfcn REFUTED - the v0x14 earfcn field is u16 and TRUNCATES u32 EARFCNs "
        "(F3 freq 66986→decoded 1450, 66536→1000 = mod 65536; correct only ≤65535). "
        "Needs widening to u32 (0x1748-class fix); EG25-G v0x14 verified earfcn only "
        "on ≤65535 cells so it didn't surface this. "
        "v11 (2026-06-14, #N <redacted-ref>, host <redacted-host>): added a Sierra "
        "EM7455 (MDM9230) sibling at wire version 0x09 - a new version. LIMSRV B4 "
        "EARFCN 2300 / serving PCI 236. pci VERIFIED (236, 27/27) + earfcn VERIFIED "
        "(2300, 27/27) by serving identity vs AT!GSTATUS?/AT!LTEINFO?. SIB1 "
        "cell_id/tac not exercised (no BCCH-DL-SCH window; all records UL-DCCH). F3 "
        "(0x79 plaintext, no SWI9X30C qdb) confirms the LTE RRC subsystem. "
        "v10 (2026-06-12, #N <redacted-ref>, LV55 round): UPGRADED the LV55 v26 "
        "earfcn field partial->verified. The prior 'no independent EARFCN readback "
        "on this reference FW' gap is closed by AT$QCRSRP? - a Qualcomm-reference "
        "AT command (no AT+QENG on this FW) whose serving row (PCI 310, the "
        "JSONRPC-confirmed serving PCI) reports EARFCN 66536, an identity match to "
        "the decoded earfcn. Triple-anchored: AT$QCRSRP? + co-captured 0xB193 "
        "earfcn=66536 (190/190) + the F3 0x79 stream echoing '$QCRSRP: 310,66536'. "
        "Fresh 4-min all-diag+F3+AT+JSONRPC capture (registered, CEREG 0,1). First "
        "SDX55-CPEALL F3 capture in the corpus (5,230 0x79 + 126,535 0x99 / 843 "
        "hashes; no SDX55-CPEALL qdb yet, 0x99 archived for retroactive resolution). "
        "v9 (2026-06-12, #N <redacted-ref>, MC7411 round): added the mandated F3 "
        "cross-check to the v8 MC7411 0x0F recipe - the co-captured 136,428 0x99 "
        "QSR4 records resolved at 1.0 against qdb GUID 04b8d441 (extracted-firmware "
        "SWI9X50C_01.14.03.00), and the firmware's own prints witness both fields: "
        "lte_ml1_common_rssi_ind.c:767 \"serving earfcn = 66786\", :847 \"pci = 236\", "
        "rflte_mc_rx.c:9069 channel:66786. Added F3 Sources (with qdb provenance) to "
        "both FieldGrounds; corrected the v8 'no qdb yet' note. Recipe-only. "
        "v8 (2026-06-12, #N <redacted-ref>, MC7411 round): per-version recipe "
        "for the Sierra MC7411-CP (Qualcomm MDM9650 / SDX50M) at wire version 15 "
        "(0x0F) - a NEW version (v8..24 path: pci=u16@4, earfcn=u32). HW RUN via "
        "a 4-min all-diag + all-F3 + AT+QMI loop capture, LIMSRV no-SIM on a "
        "T-Mobile band-66 cell. pci=236 (100/100) VERIFIED four ways (QMI "
        "GetCellLocationInfo + AT!GSTATUS + co-captured 0xB116 config_word=236 + "
        "0xB193 pci=236); earfcn=66786 (100/100, u32 band 66) VERIFIED by "
        "co-captured 0xB193 earfcn=66786 + AT!GSTATUS B66 + F3 firmware witnesses "
        "lte_ml1_common_rssi_ind.c:767 \"serving earfcn = 66786\" / :847 "
        "\"pci = 236\" / rflte_mc_rx.c:9069 channel:66786. The QMI cell-loc "
        "'EARFCN 1250' is the u16 truncation (66786 mod 65536 = 1250) - the DIAG "
        "u32 earfcn field is the only undamaged serving channel. First Sierra "
        "MDM9650 F3 capture in the corpus; the 136,428 0x99 QSR4 records resolved "
        "at 1.0 against qdb GUID 04b8d441 (extracted-firmware SWI9X50C_01.14.03.00). "
        "v7 (2026-06-12, #N <redacted-ref>, host <redacted-host>, RM500Q-AE round): "
        "per-version recipe for the Quectel RM500Q-AE (Qualcomm SDX55) at wire "
        "version 27 - the FIRST v27 observation on SDX55 (v27 was previously "
        "SDX62-only), so v27 spans both silicon. pci AND earfcn VERIFIED by "
        "multi-value identity: decoded {pci:earfcn} co-vary {473:66986, 148:800, "
        "110:1100} across a LIMSRV serving reselection (105 records) == AT+QENG="
        "\"servingcell\", TRIPLE-anchored by co-captured verified 0xB116 "
        "config_word {473,148,110} + 0xB193 earfcn {66986,800,1100}; F3 (qdb GUID "
        "404921d3) rflte_mc_rx_tune channel:66986 witnesses the >65535 EARFCN. "
        "The v>=25 path (pci=u16@6, earfcn=u32@8) decodes SDX55 v27 correctly. "
        "SDX20/MDM9607 DLF capture analysis, cross-ref QCSuper/scat. v2 adds "
        "rrc_ver_major/minor (byte[2]/[3]) on non-v20 versions per QCAT-decoded "
        "ground truth in tool_analysis_qcat/05-22_signaling.txt.layers.yaml - "
        "v15 record at line 6 decodes as 'RRC Release Number.Major.minor = 13.2.1'. "
        "Same naming convention as lte_nas_ota.py (#N). v20 has channel_type "
        "at byte[2] and lacks the major/minor fields entirely. "
        "v3 (2026-06-08, #N <redacted-ref>): hardware-validated pci (u16@4) and "
        "earfcn (u16@6) by identity vs AT+QENG=\"servingcell\" on the connected "
        "EG25-G - both 63/63 (236 / 2300). See the ground_truth/0xB0C0/ store. "
        "v4 (2026-06-09, #N <redacted-ref>): per-version recipe for the Sierra "
        "MC7700 (MDM9600/SWI9200X) at wire version 2 - earfcn verified vs "
        "AT!GSTATUS (24/24 == 2300) across a CFUN-induced cell reselection; pci "
        "partial (no AT PCI anchor on Sierra). "
        "v5 (2026-06-10, #N <redacted-ref> <redacted-ref>, LV55-focused round): "
        "per-version recipe for the Wistron LV55 (Qualcomm SDX55) at wire "
        "version 26 - pci VERIFIED by identity (310, 28/28) vs JSONRPC "
        "get_modem_signalinfo pci_4g=310 + co-captured 0xB116 config_word=310 "
        "(reference FW has no AT+QENG); earfcn partial (66536/band 66, "
        "cross-code corroborated, no independent EARFCN readback on this FW)."
    ),
    source_url="https://github.com/lukejenkins",
    issues=(),
    primary_issue=None,
    wigle_direct=True,
    wigle_roles=("identity", "timing-anchor:periodic", "rat-context"),
    # Header binary fields, ALL now decoded into named to_dict fields (#N -
    # 100% byte accounting): version, rrc_release, radio_bearer_id, channel_type,
    # pci, earfcn, sfn, subfn, pdu_number, sib_mask, msg_length, msg_data (12).
    # Non-v20 adds rrc_ver_major/minor (2). Deep-decoded SIB1 contributes 4
    # (mcc, mnc, tac, cell_id) from the msg_data ASN.1 PER decode. NAS tunnel
    # detection adds 2 (nas_tunneled flag, dedicated_info_nas bytes). = 20
    # counted quantities, ALL parsed. channel_name (derived from channel_type)
    # and sibs_present (derived from sib_mask) are presentations, not counted.
    # The two formerly-unparsed regions are closed: the sib_mask region is now
    # the decoded u32 SIB bitmap, and msg_data is surfaced as hex for downstream
    # ASN.1 / pcap consumers (the whole point of an RRC-OTA log, #N) AND deep-
    # decoded in-band (SIB1-7/16, NAS tunnel, measConfig, MeasurementReport).
    fields_identified=20,
    fields_parsed=20,
)
def parse_0xb0c0(log_time: int, data: bytes) -> Diag0xB0C0 | None:
    """Parse 0xB0C0 - LTE RRC OTA Message.

    Version 20 (primary, SDX20/MDM9607/SDX55):
        Fixed 19-byte header with u16 EARFCN at offset 6.

    Other versions (9, 12, 13, 14, 15, 16, 19, 24, 25, 26):
        Variable header with version-dependent EARFCN width and SIB mask.
        Based on QCSuper's multi-version approach.
    """
    if len(data) < 6:
        return None

    version = data[0]
    rrc_release = data[1]

    # Version 20: use the known fixed layout
    if version == 20:
        if len(data) < _V20_HEADER_SIZE:
            return None
        # #N: the channel selector is byte[12], NOT byte[2] (byte[2] is a
        # constant 0x30 on every observed v20 record). v20 uses its own
        # small-integer channel enum (_V20_CHANNEL_NAMES), not _CHANNEL_NAMES.
        channel_type = data[LTE_RRC_V20_CHANNEL_OFFSET]
        pci = unpack_from('<H', data, 4)[0]
        earfcn = unpack_from('<H', data, 6)[0]
        sfn_subfn = unpack_from('<H', data, 8)[0]
        sfn = sfn_subfn >> 4
        subfn = sfn_subfn & 0xF
        pdu_number = data[10]
        # #N - sib_mask: the u32-LE SIB-presence bitmap in the 4 bytes right
        # after channel_type (byte[12]) → byte[13:17]. In-bounds by len>=19 gate.
        sib_mask = unpack_from('<I', data, LTE_RRC_V20_CHANNEL_OFFSET + 1)[0]
        msg_length = unpack_from('<H', data, 17)[0]
        header_size = _V20_HEADER_SIZE

        msg_data = bytes()
        if msg_length > 0 and len(data) >= header_size + msg_length:
            msg_data = data[header_size:header_size + msg_length]

        channel_name = _V20_CHANNEL_NAMES.get(channel_type, f"0x{channel_type:02X}")
        return _build_result(log_time, version, rrc_release, channel_type,
                             channel_name, pci, earfcn, sfn, subfn,
                             pdu_number, msg_length, msg_data, data,
                             sib_mask=sib_mask)

    # Other versions: QCSuper-style multi-version parsing.
    # Non-v20 wire layout (per QCAT layers.yaml ground truth) carries
    # rrc_ver_major/minor at bytes 2/3 - name parity with lte_nas_ota.py (#N).
    rrc_ver_major = data[2]
    rrc_ver_minor = data[3]

    radio_bearer_id: int | None = None
    if version >= 25:
        if len(data) < 8:
            return None
        # #N - radio_bearer_id is the HIGH byte of the [4:6] field (byte[5]):
        # 0=common/SRB0 (broadcast), 1=SRB1, 2=SRB2. byte[4] is a per-chipset
        # log-encoding constant (0x60 SDX62 / 0x90 SDX55) - not part of the id.
        radio_bearer_id = data[5]
        pci = unpack_from('<H', data, 6)[0]
        ext_offset = 8
    else:
        pci = unpack_from('<H', data, 4)[0]
        ext_offset = 6

    if ext_offset + 5 > len(data):
        return None

    # EARFCN width depends on version
    if version < 8:
        earfcn = unpack_from('<H', data, ext_offset)[0]
        sfn_subfn = unpack_from('<H', data, ext_offset + 2)[0]
        channel_type = data[ext_offset + 4]
        len_offset = ext_offset + 5
    else:
        if ext_offset + 7 > len(data):
            return None
        earfcn = unpack_from('<I', data, ext_offset)[0]
        sfn_subfn = unpack_from('<H', data, ext_offset + 4)[0]
        channel_type = data[ext_offset + 6]
        len_offset = ext_offset + 7

    # SIB mask detection. The 4 bytes at len_offset are the u32-LE sib_mask
    # (#N); msg_length follows it. When the low u16 of the mask != the
    # remaining byte count, that region is the mask (not the length) → capture
    # it and skip past it to the real msg_length. Reading here (pre-shift) only
    # touches bytes that were already being discarded, so it cannot perturb any
    # other field (adversarially verified regression-safe over the corpus).
    sib_mask: int | None = None
    if len_offset + 2 <= len(data):
        test_len = unpack_from('<H', data, len_offset)[0]
        remaining = len(data) - len_offset - 2
        if test_len != remaining and len_offset + 6 <= len(data):
            sib_mask = unpack_from('<I', data, len_offset)[0]
            len_offset += 4

    msg_length = unpack_from('<H', data, len_offset)[0] if len_offset + 2 <= len(data) else 0
    header_size = len_offset + 2

    # v30 (0x1E, Foxconn T99W640) length fix (#N). On v30 the u16 at [19:21]
    # is NOT the PDU byte length - it consistently holds (PDU_len - 3). The true
    # RRC PDU is the remainder of the record after the 21-byte header, confirmed
    # byte-identical to the qcsuper GSMTAP LTE-RRC payload on all 7 records
    # (4 BCCH-DL-SCH + 3 PCCH). There is no 3-byte trailer: the trailing bytes
    # vary per record (part of the PER-encoded message). Take the PDU as
    # rest-of-record so msg_data matches the oracle exactly; this is what lets
    # the v30 channel enum be pinned in _NONV20_CHANNEL_NAMES_BY_VERSION.
    if version == 30 and header_size <= len(data):
        msg_length = len(data) - header_size

    sfn = sfn_subfn >> 4
    subfn = sfn_subfn & 0xF
    pdu_number = 0

    msg_data = bytes()
    if msg_length > 0 and len(data) >= header_size + msg_length:
        msg_data = data[header_size:header_size + msg_length]

    # #N - name the channel via the per-version oracle-pinned enum, NOT the
    # legacy byte[2]-era _CHANNEL_NAMES (which is wrong for non-v20: it dropped
    # the small-int values and MISLABELLED the ones that collided with a legacy
    # key, e.g. v15 ct=8/9 as DL-CCCH/DL-DCCH when they are UL-CCCH/UL-DCCH).
    # Unmapped (version, channel_type) → honest hex string, never a legacy guess.
    chan_map = _NONV20_CHANNEL_NAMES_BY_VERSION.get(version, {})
    channel_name = chan_map.get(channel_type, f"0x{channel_type:02X}")

    return _build_result(log_time, version, rrc_release, channel_type,
                         channel_name, pci, earfcn, sfn, subfn,
                         pdu_number, msg_length, msg_data, data,
                         rrc_ver_major=rrc_ver_major,
                         rrc_ver_minor=rrc_ver_minor,
                         radio_bearer_id=radio_bearer_id,
                         sib_mask=sib_mask)


def _try_decode_nas_tunneled(channel_name: str, msg_data: bytes) -> bytes | None:
    """Detect DCCH InformationTransfer + extract dedicatedInfoNAS bytes.

    Implements the minimum-viable bit-pattern match per #N (Option A):
    walk just enough UPER prefix to confirm the CHOICE path is
    DLInformationTransfer / ULInformationTransfer → dlInformationTransfer-r8
    / ulInformationTransfer-r8 → dedicatedInfoType=NAS, then read the
    DedicatedInfoNAS OCTET STRING length determinant and the payload bytes.

    Returns the dedicatedInfoNAS bytes on a successful match, or None for
    any other channel/message - including DCCH messages that aren't
    InformationTransfer (reconfig, security mode, capability info, etc.)
    and InformationTransfer records whose dedicatedInfoType is CDMA2000
    rather than NAS.

    Bit layout (per 3GPP TS 36.331 §6.2.2 + ITU-T X.691 UPER):

      DL-DCCH path (channel_type = 0x09):
        0    : DL-DCCH-MessageType outer CHOICE (0 = c1)
        1-4  : c1 inner CHOICE index (1 = dlInformationTransfer)
        5-6  : RRC-TransactionIdentifier (INTEGER(0..3))
        7    : DLInformationTransfer criticalExtensions CHOICE (0 = c1)
        8-10 : c1 inner CHOICE (0 = dlInformationTransfer-r8)
        11   : DLInformationTransfer-r8-IEs optional bitmap
               (1 bit, nonCriticalExtension presence - value is irrelevant
               because the optional field comes AFTER dedicatedInfoType in
               UPER encoding order)
        12-13: dedicatedInfoType CHOICE (3 alternatives, 2 bits;
               0 = dedicatedInfoNAS, 1/2 = CDMA2000 variants)
        14+  : DedicatedInfoNAS OCTET STRING (length determinant + bytes)

      UL-DCCH path (channel_type = 0x0B): same shape, but
        - no RRC-TransactionIdentifier (saves 2 bits)
        - ULInformationTransfer-r8-IEs has NO optional fields (saves 1 bit)
        - effective offset to dedicatedInfoType is bit 9 vs. bit 12 on DL

    The length determinant of an unconstrained OCTET STRING is the
    standard UPER length form (X.691 §10.9.3.6):
        0xxxxxxx                - 7-bit length (0..127)
        10xxxxxx xxxxxxxx       - 14-bit length (128..16383)
        11xxxxxx                - fragmented (16384+; not currently observed)
    Decoded via ``asn1_helpers.read_open_type_length`` (#N), which handles
    all three forms; the fragmented branch is summed per X.691 §11.9.
    """
    if not msg_data:
        return None
    # #N - gate on the canonical channel NAME, not the raw integer: the DCCH
    # channel_type value differs per wire version (v15 DL-DCCH=7/UL-DCCH=9 vs
    # v26/v27 DL-DCCH=9/UL-DCCH=11 vs the legacy 0x09/0x0B), so the old raw-int
    # gate fired on the wrong records for non-v20 captures.
    if channel_name not in ("DL-DCCH", "UL-DCCH"):
        return None

    r = UperReader(msg_data)
    try:
        if channel_name == "DL-DCCH":
            if r.read_bits(1) != 0:
                return None  # messageClassExtension, not c1
            if r.read_bits(4) != 1:
                return None  # not dlInformationTransfer
            r.read_bits(2)  # rrc-TransactionIdentifier (don't care, 0..3)
            if r.read_bits(1) != 0:
                return None  # criticalExtensionsFuture
            if r.read_bits(3) != 0:
                return None  # spare1..7 instead of dlInformationTransfer-r8
            r.read_bits(1)  # nonCriticalExtension OPTIONAL flag - see docstring
            if r.read_bits(2) != 0:
                return None  # CDMA2000 variant, not NAS
        else:
            if r.read_bits(1) != 0:
                return None
            if r.read_bits(4) != 9:
                return None  # not ulInformationTransfer
            if r.read_bits(1) != 0:
                return None
            if r.read_bits(3) != 0:
                return None
            if r.read_bits(2) != 0:
                return None

        # Open-type length determinant via toolkit (#N) - handles the
        # 7-bit / 14-bit / fragmented forms per X.691 §11.9.
        nas_len = read_open_type_length(r)

        if nas_len == 0:
            return b""

        nas_bytes = bytearray(nas_len)
        for i in range(nas_len):
            nas_bytes[i] = r.read_bits(8)
        return bytes(nas_bytes)
    except (IndexError, ValueError):
        return None


def _build_result(
    log_time: int, version: int, rrc_release: int, channel_type: int,
    channel_name: str, pci: int, earfcn: int, sfn: int, subfn: int,
    pdu_number: int, msg_length: int, msg_data: bytes, raw_data: bytes,
    rrc_ver_major: int | None = None,
    rrc_ver_minor: int | None = None,
    radio_bearer_id: int | None = None,
    sib_mask: int | None = None,
) -> Diag0xB0C0:
    """Build Diag0xB0C0 with optional SIB1 auto-decode."""
    # #N - derive the SIB-number list from the sib_mask bits (bit N = SIBN;
    # bit0 unused). Empty when sib_mask is 0 or None (see the sib_mask field
    # docstring: an empty list does not prove the SI carries no SIBs).
    sibs_present: list[int] = (
        [n for n in range(1, 32) if sib_mask & (1 << n)]
        if sib_mask else []
    )
    sib1_mcc = sib1_mnc = None
    sib1_tac = sib1_cell_id = None
    # Trigger on the canonical channel NAME, not the raw integer: v20 encodes
    # BCCH-DL-SCH as byte[12]==2 (_V20_CHANNEL_NAMES) while the legacy/non-v20
    # path encodes it as 0x30 (_CHANNEL_NAMES). Keying on channel_name keeps SIB1
    # auto-decode correct across both enums (#N).
    sib2_access = sib3_resel = sib4_neighbors = None
    sib5_inter_freq = sib6_neighbors = sib7_neighbors = sib16_time = None
    sib8_cdma_time = sib24_nr_resel = None
    if channel_name == "BCCH-DL-SCH" and msg_data:
        from diaggrok.parsers.lte_rrc_sib import decode_sib1_cell_access
        sib1 = decode_sib1_cell_access(msg_data)
        if sib1 and sib1.plmn_list:
            sib1_mcc = sib1.plmn_list[0].mcc
            sib1_mnc = sib1.plmn_list[0].mnc
            sib1_tac = sib1.tracking_area_code
            sib1_cell_id = sib1.cell_identity
        else:
            # Not a SIB1 → walk the SystemInformation container ONCE for
            # SIB2 + SIB3 + SIB4 + SIB5 + SIB6 + SIB7 + SIB16 + SIB24
            # (#N/#N/#N/#N/#N/#N/#N/#N). decode_si_sibs self-gates
            # (returns None unless it's an SI message carrying a target SIB),
            # so this never mis-fires on SIB1 / other SIBs.
            from diaggrok.parsers.lte_rrc_sib_time import decode_si_sibs
            sibs = decode_si_sibs(msg_data)
            if sibs is not None:
                sib2_access = sibs.sib2
                sib3_resel = sibs.sib3
                sib4_neighbors = sibs.sib4
                sib5_inter_freq = sibs.sib5
                sib6_neighbors = sibs.sib6
                sib7_neighbors = sibs.sib7
                sib8_cdma_time = sibs.sib8
                sib16_time = sibs.sib16
                sib24_nr_resel = sibs.sib24

    nas_bytes = _try_decode_nas_tunneled(channel_name, msg_data)
    nas_tunneled = nas_bytes is not None

    # measConfig / MeasurementReport auto-decode (#N). Both decoders re-walk
    # the ASN.1 CHOICE bits themselves and self-gate (return None if the message
    # is not their target type), so dispatch keys on the SRB channel name alone -
    # RRCConnectionReconfiguration rides DL-DCCH, MeasurementReport rides UL-DCCH.
    # Mirrors the SIB1/NAS "decode-and-flatten" pattern above. Lazy import keeps
    # the hot path (PCCH/BCCH records, which never hit these branches) free of
    # the reconfig/meas-report module import cost.
    meas_objects: list[Any] = []
    meas_has_gap_config = False
    meas_s_measure: int | None = None
    meas_report_id: int | None = None
    meas_report_pcell_rsrp: float | None = None
    meas_report_pcell_rsrq: float | None = None
    meas_report_neighbors: list[Any] = []
    if channel_name == "DL-DCCH" and msg_data:
        from diaggrok.parsers.lte_rrc_reconfig import (
            decode_rrc_reconfig_meas_config,
        )
        mc = decode_rrc_reconfig_meas_config(log_time, msg_data)
        if mc is not None and mc.meas_objects:
            meas_objects = mc.meas_objects
            meas_has_gap_config = mc.has_gap_config
            meas_s_measure = mc.s_measure
    elif channel_name == "UL-DCCH" and msg_data:
        from diaggrok.parsers.lte_rrc_meas_report import (
            decode_measurement_report,
        )
        mr = decode_measurement_report(log_time, msg_data)
        if mr is not None:
            meas_report_id = mr.meas_id
            meas_report_pcell_rsrp = mr.pcell_rsrp
            meas_report_pcell_rsrq = mr.pcell_rsrq
            meas_report_neighbors = mr.neighbor_cells

    return Diag0xB0C0(
        log_time=log_time,
        version=version,
        rrc_release=rrc_release,
        channel_type=channel_type,
        channel_name=channel_name,
        pci=pci,
        earfcn=earfcn,
        sfn=sfn,
        subfn=subfn,
        pdu_number=pdu_number,
        msg_length=msg_length,
        msg_data=msg_data,
        radio_bearer_id=radio_bearer_id,
        sib_mask=sib_mask,
        sibs_present=sibs_present,
        rrc_ver_major=rrc_ver_major,
        rrc_ver_minor=rrc_ver_minor,
        sib1_mcc=sib1_mcc,
        sib1_mnc=sib1_mnc,
        sib1_tac=sib1_tac,
        sib1_cell_id=sib1_cell_id,
        nas_tunneled=nas_tunneled,
        dedicated_info_nas=nas_bytes,
        meas_objects=meas_objects,
        meas_has_gap_config=meas_has_gap_config,
        meas_s_measure=meas_s_measure,
        meas_report_id=meas_report_id,
        meas_report_pcell_rsrp=meas_report_pcell_rsrp,
        meas_report_pcell_rsrq=meas_report_pcell_rsrq,
        meas_report_neighbors=meas_report_neighbors,
        sib2_access=sib2_access,
        sib3_resel=sib3_resel,
        sib4_neighbors=sib4_neighbors,
        sib5_inter_freq=sib5_inter_freq,
        sib6_neighbors=sib6_neighbors,
        sib7_neighbors=sib7_neighbors,
        sib8_cdma_time=sib8_cdma_time,
        sib16_time=sib16_time,
        sib24_nr_resel=sib24_nr_resel,
    )
