"""0x147C — split from gnss_nav_db.py per #N tier-3.

See module body for the per-code RE history and field map.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_GNSS_PE_WLS_POSITION_REPORT_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        RESERVED
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass, field
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


# ---------------------------------------------------------------------------
# 0x147C — GNSS PE WLS Position Report (per-SV measurement cache)
# ---------------------------------------------------------------------------
#
# Canonical name LOG_GNSS_PE_WLS_POSITION_REPORT_C tells us this is the
# **Position-Engine Weighted-Least-Squares per-SV measurement contributions**,
# NOT raw subframe-derived broadcast ephemeris (the issue body's RINEX-NAV
# framing was an aspirational scope; this code carries PE inputs/outputs,
# not the Keplerian set the RINEX .nav format wants — that would need a
# different log code).
#
# v=0x0D (SDX62 RM520N-GL) — body decode landed v4 (#N <redacted-ref>):
#
# Layout: [44B preamble] + [N × 47B slot grid]
#     The slot grid splits into two classes:
#       - "head slots"  : 15 slots (705 B) of reserved/template space with
#                         session-state floats embedded at fixed positions
#                         (the rest is filled with a snake-aligned
#                         `00000000_4912620f` u64 padding constant — likely
#                         an allocator's per-8B fill marker)
#       - "SV records"  : one 47-byte record per actively-tracked SV
#
# Verified across 11 distinct payload sizes (796..1407 B) on 1,842 records
# from `<redacted-pii>`: every size satisfies
# `(size - 44) % 47 == 0` exactly.  For size classes 937..1125 (1,585 / 1,842
# records = 86%), `head_slots` is locked at exactly 15; 1219+ sizes have a
# variable head (18..22 slots) — likely state-transition or different
# constellation pages.  The 796B class (238 records) is a no-SV-tracked
# state — preamble follows the same template but with session-variable
# bytes in different positions.
#
# Per-SV record layout (47 bytes, cross-capture stable):
#     [0:5]    `00 00 75 11 01`     5-byte signature
#     [5]      0x00                 reserved
#     [6]      u8                   PRN (GPS SV ID; 1..32)
#     [7]      0x00                 reserved
#     [8:10]   `00 07`              record-type marker (LE u16 = 0x0700)
#     [10]     u8                   subframe-type / status flags (per-SV
#                                   constant across consecutive records;
#                                   varies between PRNs — likely IODE or
#                                   tracking-channel state)
#     [11:15]  f32 LE  wls_f1       per-SV measurement; range ±10
#     [15:19]  f32 LE  wls_f2       per-SV measurement; range [2..16),
#                                   often exactly 5.0 (likely constellation
#                                   or # of tracked frequencies)
#     [19:23]  f32 LE  wls_f3       per-SV measurement; range [0.1..1.0],
#                                   often exactly 1.0 (validity weight?)
#     [23:27]  f32 LE  wls_f4       per-SV measurement; range [0.05..1.0]
#                                   (normalized elevation cosine?)
#     [27:31]  f32 LE  wls_f5       per-SV measurement; range [600..30000]
#                                   (likely a measurement magnitude in m)
#     [31:35]  f32 LE  wls_f6       per-SV measurement; range [10..5000]
#                                   (likely a measurement variance)
#     [35:39]  f32 LE  wls_f7       per-SV measurement; range ±0.02
#                                   (small residual; Doppler-rate-like)
#     [39:43]  f32 LE  wls_f8       per-SV measurement; range [0.01..0.6]
#                                   (per-PRN tight range — possibly C/N0
#                                   noise-floor quantization step)
#     [43:47]  f32 LE  wls_f9       per-SV measurement; range [0.7..1.0],
#                                   usually exactly 1.0 (validity flag)
#
# Field names are deliberately generic (wls_f1..wls_f9) pending semantic
# RE — the magnitudes and ranges are documented above but assigning RINEX/
# GPS-ICD names to them requires cross-correlation with a known-position
# fix and per-SV LOS computation. The structural layout is locked.
#
# 44B preamble — variance pass on 1,136 records of one capture vs cross-
# capture comparison vs a 2nd RM520N-GL capture yields these invariants:
#
#     Cross-capture CONSTANTS (= 22 of 44 bytes):
#         [0]      0x0D                 version byte (matches v=0x0D enum)
#         [4]      0x00                 separator
#         [8:13]   00 00 00 00 00       reserved
#         [15]     0x0F                 magic byte (low byte of session magic)
#         [16:21]  00 00 00 00 00       reserved
#         [21]     0x04                 sub-version / field-count marker
#         [22:32]  00 ... 00 (10 B)     reserved
#         [32]     0x72                 magic byte
#
#     SESSION-stable (constant within session, varies across sessions):
#         [13:15], [33], [42:44] — firmware-state magic bytes
#
#     VARIABLE (per-record):
#         [1:4]    u24 LE counter (increments by ~1000 per record)
#         [5:7]    u16 LE counter (related)
#         [34:42]  session-state floats / TOW
#
# Other versions (v=0x06, 0x07, 0x08, 0x0A) — body still opaque pending
# their own RE pass; the layer-1 version gate is preserved and
# `wls_records` is left empty on those versions until per-version RE lands.
#
# v=0x0A variance map (<redacted-ref> iter2 finding, #N):
#
#   Cross-vendor per-byte variance pass over EM9190 SWIX55C 1133 records
#   (4641 B fixed) revealed **99.4% of body bytes are LOCKED** (only 29
#   varying offsets in the EM9190 sample). FN980m SDX55 (1166 records)
#   has only 11 varying offsets, ALL of which are a strict subset of
#   EM9190's 29. The 11 common varying positions are the cross-vendor
#   universal-format core:
#
#     1, 2, 3      — counter triplet (byte 1: 32-unique bitfield with
#                     `x & 0x07 == 7`; byte 2: full-range 256 unique;
#                     byte 3: narrow 18-unique slow counter)
#     5, 6, 7      — mirror of 1-3 (related counter pair)
#     77, 78       — 256/5-unique 2-byte region
#     97, 98, 99   — 256/256/9-unique 3-byte region
#
#   Locked f32 anchor at body offset [41:44] = `59 fc 5a 46` (f32 LE =
#   ~14015) appears EXACTLY ONCE in the full 4641 B body. The "3 slots
#   at 30/51/61" pattern from the prior <redacted-ref>-05-27 recon is
#   **EM9190-specific** (not seen on FN980m at all) — likely a Sierra
#   vendor extension, not core 0x147C v=0x0A structure.
#
#   EM9190-only varying offsets: 30-32, 51-53, 61-63, 488, 490, 502-503,
#   506, 547-548, 552, 554. The 488-554 region's 0/1 toggle pattern
#   looks like state flags or SV-availability bitmaps.
#
#   **Falsified prior hypothesis**: 0x147C v=0x0A is NOT a per-SV
#   measurement record with 10/11/13 B per-SV slots. The 4641 B size
#   is overwhelmingly zero-padded reserved space, not a slotted array.
#   The actual semantic content occupies ~29 bytes (EM9190) or ~11
#   bytes (FN980m) — the rest is template padding.
#
#   Next-step recipe for the next session that picks up this body
#   decode: focus on the 11 universal-format positions first
#   (cross-vendor stable). Decode the 1-3 / 5-7 dual-counter region as
#   "sub-tick counter + slow coarse counter" pair (matches the GNSS
#   engine 256,000-per-record cadence the v=0x0D body also shows).
#   The 77-99 region's small uniq count suggests status flags rather
#   than a measurement. Then per-vendor extensions can be layered on
#   top once the core decode is locked.

# ---- v=0x0D structural constants -----------------------------------------

_V0D_PREAMBLE_LEN = 44
_V0D_SLOT_STRIDE = 47
_V0D_SV_SIG = b'\x00\x00\x75\x11\x01'  # 5-byte cross-capture-stable SV-record signature

# Cross-capture preamble invariants — the 17 bytes that hold across every
# v=0x0D capture surveyed (20 captures × 30 records each = 600 records
# spanning normal, warm-restart, reboot, SIM-power-cycle, and airplane-mode
# operational states). Bytes that are "mostly constant" but change during
# state transitions (4, 8, 15, 16, 17, 21, 32) are deliberately EXCLUDED
# from this invariant set — they're per-session firmware-state and would
# misleadingly fail otherwise-valid records during boot.
#
# `preamble_invariants_ok=False` is a real falsification: a v=0x0D body
# that fails any of these 17 bytes is structurally suspect (not just in
# a transitional state).
_V0D_PREAMBLE_CONSTS: dict[int, int] = {
    0: 0x0D,
    9: 0x00, 10: 0x00, 11: 0x00, 12: 0x00,
    18: 0x00, 19: 0x00, 20: 0x00,
    22: 0x00, 23: 0x00, 24: 0x00, 25: 0x00, 26: 0x00,
    27: 0x00, 28: 0x00, 29: 0x00, 30: 0x00,
}


# ---- v=0x0A structural constants (#N) ---------------------------------
#
# v=0x0A (SDX55: EM9190 / FN980 / FN980m / sim8202g-m2 / RM500Q-AE) is a
# FIXED 4641-byte sparse GNSS-engine state record — NOT a per-SV slot array
# (that hypothesis was falsified; see the variance-map comment above). Two
# recon sessions + this session's cross-vendor walk (EM9190 1,133 recs +
# FN980 1,166 recs, sequential per the <redacted-ref> memory-safety rule) established
# that only 11 byte positions carry cross-vendor-universal semantic content;
# the rest is template padding or per-firmware constants.
#
# Cross-vendor-VERIFIED universal fields (hold on BOTH EM9190 and FN980):
#     [0:4]    u32 LE  tick_a  — GNSS-engine clock tick, +256,000 / record.
#                               byte[0] is pinned at 0x0A so it doubles as
#                               the version gate (256000 % 256 == 0, so the
#                               low byte never changes).
#     [4:8]    u32 LE  tick_b  — second clock tick, also +256,000 / record
#                               (byte[4] pinned 0x00). Matches the same GNSS-
#                               engine cadence the v=0x0D body shows.
#     [77:79]  u16 LE  state_x — per-record SEQUENCE COUNTER, strictly +1 each
#                               record (0,1,2,…). Verified offline against the
#                               gpsd_ref ground truth, #N <redacted-ref>: all
#                               1132 deltas == 1 over the canonical EM9190 walk.
#                               The earlier "77-78: 256/5-uniq status region" is
#                               just this counter's full-cycling low byte + the
#                               high byte (0..4 over 1133 records) — NOT a flag.
#     [97:100] u24 LE  state_y — monotonic engine tick, +~467 / record (range
#                               462..479, dominant 463/464). A distinct, slower
#                               cadence from tick_a/tick_b (+256000/rec) — NOT a
#                               status field. Same #N offline walk.
#
# Cross-vendor-VERIFIED locked anchors (the v=0x0A preamble validator):
#     [0]==0x0A, [4]==0x00, [8:23]==0x00 (15 B reserved), [23]==0x01
#
# NOT universal — deliberately EXCLUDED from the validator (verified to
# DIFFER across vendors this session, #N): byte[33] is 0x41 on EM9190 but
# 0x84 on FN980; the f32 anchor at [41:45] is 59fc5a46 (~14015) on EM9190 but
# 4d903754 on FN980 — locked WITHIN a firmware but per-firmware, not a shared
# format anchor. The [30:33]/[51:53]/[61:63] triplets vary on EM9190 (Sierra)
# but are locked non-zero constants on FN980 — a per-firmware region, not core
# structure. The 488-554 toggle region is EM9190-only. All left undecoded.
_V0A_PAYLOAD_SIZE = 4641
_V0A_PREAMBLE_CONSTS: dict[int, int] = {0: 0x0A, 4: 0x00, 23: 0x01}
_V0A_RESERVED_ZERO = range(8, 23)  # 15-byte zero block [8:23]
# v7 (#N): the EM9190-only [488:554] toggle region — the 9 low-cardinality
# byte positions that carry per-record STATE FLAGS (NOT clocks/counters; no
# monotonic u32 anywhere in [480:560]). Established by the corpus-complete walk
# of the canonical EM9190 fixture (1,133 records): these are the only varying
# bytes in the region. They co-vary in 3 correlated groups (a 134-record state,
# a 50-record state, an 87-record state — see source_detail), so the flags are
# ~3 independent GNSS-engine state indicators. On FN980 (Telit SDX55) all 9 are
# zero (the region is a Sierra vendor extension), so toggle_region is exposed
# raw and NOT asserted in the cross-vendor validator.
_V0A_TOGGLE_OFFSETS: tuple[int, ...] = (488, 490, 502, 503, 506, 547, 548, 552, 554)


@dataclass
class WlsSvRecord:
    """One per-SV 47-byte record from a 0x147C v=0x0D body."""
    prn: int                # GPS SV ID (1..32)
    subframe_type: int      # byte [10] — per-PRN constant within a session
    wls_f1: float; wls_f2: float; wls_f3: float
    wls_f4: float; wls_f5: float; wls_f6: float
    wls_f7: float; wls_f8: float; wls_f9: float

    def to_dict(self) -> dict[str, Any]:
        return {
            'prn': self.prn,
            'subframe_type': self.subframe_type,
            'wls_f1': round(self.wls_f1, 6),
            'wls_f2': round(self.wls_f2, 6),
            'wls_f3': round(self.wls_f3, 6),
            'wls_f4': round(self.wls_f4, 6),
            'wls_f5': round(self.wls_f5, 4),
            'wls_f6': round(self.wls_f6, 4),
            'wls_f7': round(self.wls_f7, 8),
            'wls_f8': round(self.wls_f8, 6),
            'wls_f9': round(self.wls_f9, 6),
        }


@dataclass
class Diag0x147C:
    """GNSS PE WLS Position Report (0x147C) — header + v=0x0D body decode."""
    log_time: int
    version: int        # byte 0
    counter_hi: int     # byte 1 (v1-compat name; v=0x0D this is LSB of u24LE counter)
    counter_lo: int     # byte 2 (v1-compat name; v=0x0D this is mid byte of counter)
    payload_size: int
    body_raw: bytes

    # v4 (#N <redacted-ref>): v=0x0D structural decode. None on other
    # versions until per-version RE lands.
    n_slots: int | None              # (size - 44) // 47
    n_sv_records: int | None         # count of `00 00 75 11 01` signatures
    head_slots: int | None           # n_slots - n_sv_records
    preamble_invariants_ok: bool | None  # version-specific preamble anchor set present?
    seq_counter: int | None          # u24LE at [1:4] — per-record incrementing counter

    # v5 (#N): v=0x0A universal-core decode. None on other versions.
    tick_a: int | None = None        # u32 LE [0:4]  — GNSS clock tick (+256000/rec)
    tick_b: int | None = None        # u32 LE [4:8]  — GNSS clock tick (+256000/rec)
    state_x: int | None = None       # u16 LE [77:79]
    state_y: int | None = None       # u24 LE [97:100]

    # v6 (#N): v=0x0A per-record measurement-extension region. These three
    # offsets are the only LIVE (per-record-varying) fields beyond the universal
    # core — isolated by diffing two consecutive EM9190 records (13 differing
    # bytes total: tick_a/tick_b low words, state_x, state_y, and these). They
    # decode as LE f32; magnitude is firmware-specific (EM9190 SDX55 ≈ 15.4,
    # high word stable → real-valued measurement; FN980 holds a different-scale
    # pattern at the same offsets), so they are exposed as raw candidates, NOT
    # asserted in the cross-vendor validator. The 10-byte blocks [51:61] and
    # [61:71] are a verified cross-vendor MIRROR (ext_mirror_ok, 3/3 fixtures),
    # so ext_f32_61 duplicates ext_f32_51. Physical semantics (C/N0 vs LNA gain
    # vs clock-bias) pending NMEA / AT-state cross-ref. None off-version/off-size.
    #
    # F3 grounding (2026-07-13, #N <redacted-ref>): the per-firmware nature is now
    # confirmed on a 3RD chipset -- a build-matched-qdb correlation of the 260
    # v=0x0A records in the RM500Q-AE (SDX55) -f3 capture reads these offsets as
    # ~0.0 / 0.021 / 0.0, distinct again from EM9190 (~15.4) and FN980
    # (~3.15e12). So exposing them RAW/unasserted is corpus-validated across 3
    # firmwares; the "~15.4 physical unit" is specifically an EM9190 question.
    # Co-temporal F3 (RM500Q qdb, delta<=3000) grounds the v=0x0A subsystem as
    # GNSS search-strategy (mc_gnsssearchstrategy.c / mc_gnssconfig.c /
    # mc_srchstrategy.c) + TCXO/clock manager (tcxomgr_data.c "XO Trim
    # Factory/Field/Curr", tcxomgr_rot_client_handling.c "Temp/Rot/VCO"),
    # corroborating the tick_a/tick_b GNSS-engine-clock reading and the
    # hardware/clock-class hypothesis for the EM9190 ext_f32.
    ext_f32_30: float | None = None  # f32 LE [30:34]
    ext_f32_51: float | None = None  # f32 LE [51:55]
    ext_f32_61: float | None = None  # f32 LE [61:65] — mirror of ext_f32_51
    ext_mirror_ok: bool | None = None  # data[51:61] == data[61:71]

    # v7 (#N): v=0x0A EM9190-only [488:554] state-flag region. 9 byte values
    # at the corpus-attested toggle offsets (_V0A_TOGGLE_OFFSETS), in order.
    # All-zero on FN980 (Telit) and on the ~88% of EM9190 records in an inactive
    # state. None off-version/off-size. Physical semantics (GNSS-engine mode/
    # health bits) still pending NMEA / AT-state cross-ref — structure complete.
    toggle_region: tuple[int, ...] | None = None

    wls_records: list[WlsSvRecord] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x147C',
            'log_time': self.log_time,
            'version': self.version,
            'counter_hi': self.counter_hi,
            'counter_lo': self.counter_lo,
            'payload_size': self.payload_size,
            'n_slots': self.n_slots,
            'n_sv_records': self.n_sv_records,
            'head_slots': self.head_slots,
            'preamble_invariants_ok': self.preamble_invariants_ok,
            'seq_counter': self.seq_counter,
            'tick_a': self.tick_a,
            'tick_b': self.tick_b,
            'state_x': self.state_x,
            'state_y': self.state_y,
            'ext_f32_30': self.ext_f32_30,
            'ext_f32_51': self.ext_f32_51,
            'ext_f32_61': self.ext_f32_61,
            'ext_mirror_ok': self.ext_mirror_ok,
            'toggle_region': list(self.toggle_region) if self.toggle_region is not None else None,
            'wls_records': [r.to_dict() for r in self.wls_records],
        }


def _parse_v0d_body(data: bytes) -> tuple[int, int, int, bool, int, list[WlsSvRecord]]:
    """Decode the v=0x0D body. Returns (n_slots, n_sv, head_slots, preamble_ok,
    seq_counter, wls_records)."""
    sz = len(data)
    # Slot-count check — already enforced by formula in caller.
    n_slots = (sz - _V0D_PREAMBLE_LEN) // _V0D_SLOT_STRIDE

    preamble_ok = all(data[o] == v for o, v in _V0D_PREAMBLE_CONSTS.items())
    seq_counter = data[1] | (data[2] << 8) | (data[3] << 16)

    # Scan ONLY the slot grid (not the preamble) for SV-record signatures.
    # The grid starts at offset _V0D_PREAMBLE_LEN.
    wls_records: list[WlsSvRecord] = []
    pos = _V0D_PREAMBLE_LEN
    while True:
        i = data.find(_V0D_SV_SIG, pos)
        if i < 0:
            break
        if i + _V0D_SLOT_STRIDE > sz:
            break
        # Only count signatures aligned on the slot grid — guards against
        # accidental matches inside the head-slot padding (which is mostly
        # the `0f621249` fill but could in theory align).
        if (i - _V0D_PREAMBLE_LEN) % _V0D_SLOT_STRIDE != 0:
            pos = i + 1
            continue
        floats = unpack_from('<9f', data, i + 11)
        wls_records.append(WlsSvRecord(
            prn=data[i + 6],
            subframe_type=data[i + 10],
            wls_f1=floats[0], wls_f2=floats[1], wls_f3=floats[2],
            wls_f4=floats[3], wls_f5=floats[4], wls_f6=floats[5],
            wls_f7=floats[6], wls_f8=floats[7], wls_f9=floats[8],
        ))
        pos = i + _V0D_SLOT_STRIDE

    head_slots = n_slots - len(wls_records)
    return n_slots, len(wls_records), head_slots, preamble_ok, seq_counter, wls_records


def _parse_v0a_body(
    data: bytes,
) -> tuple[int, int, int, int, bool, float, float, float, bool, tuple[int, ...]]:
    """Decode the v=0x0A body. Returns (tick_a, tick_b, state_x, state_y,
    preamble_ok, ext_f32_30, ext_f32_51, ext_f32_61, ext_mirror_ok,
    toggle_region). Caller guarantees len(data) == _V0A_PAYLOAD_SIZE."""
    tick_a = unpack_from('<I', data, 0)[0]
    tick_b = unpack_from('<I', data, 4)[0]
    state_x = unpack_from('<H', data, 77)[0]
    state_y = data[97] | (data[98] << 8) | (data[99] << 16)
    preamble_ok = (
        all(data[o] == v for o, v in _V0A_PREAMBLE_CONSTS.items())
        and all(data[o] == 0 for o in _V0A_RESERVED_ZERO)
    )
    # Per-record measurement-extension region (the 3 live offsets beyond the
    # universal core). f32 magnitude is firmware-specific — exposed raw.
    ext_f32_30 = unpack_from('<f', data, 30)[0]
    ext_f32_51 = unpack_from('<f', data, 51)[0]
    ext_f32_61 = unpack_from('<f', data, 61)[0]
    ext_mirror_ok = data[51:61] == data[61:71]
    # v7: EM9190-only [488:554] state-flag region — 9 byte values in offset order.
    toggle_region = tuple(data[o] for o in _V0A_TOGGLE_OFFSETS)
    return (tick_a, tick_b, state_x, state_y, preamble_ok,
            ext_f32_30, ext_f32_51, ext_f32_61, ext_mirror_ok, toggle_region)


# ---------------------------------------------------------------------------
# Ground-truth recipe (#N) — v=0x0D, RM520N-GL (Quectel SDX62)
# ---------------------------------------------------------------------------
# v=0x0D is the only version whose BODY is decoded (per-SV WLS records). Of
# its decoded fields, exactly one is a clean cross-checkable anchor — the GPS
# PRN at slot byte [6] — plus a SV-used count. The nine wls_f* floats are a
# deliberate DISCOVERY design (#N/#N-style): the structural layout is
# locked but the f-slot -> physical-quantity mapping is unknown. The parser's
# own decode of PRN=1 (f5=11.54, f6=56.79, f9=0.99) gives magnitude evidence
# for candidate semantics — f6 sits in the GNSS C/N0 dB-Hz band, f9 looks like
# a normalized WLS weight. The recipe's job is to let a hardware capture
# recover WHICH slot is which quantity (and its scale) by correlating against
# the per-SV GSV columns. Structural counters (seq_counter, tick_*) carry no
# physical-quantity AT source and are intentionally left out of the field_map.

@register(
    0x147C, domain="gnss",
    name="0x147C",
    description=(
        "GNSS PE WLS Position Report — v=0x0D (SDX62) body decoded to "
        "per-SV WLS measurement records (#N v4); v=0x0A (SDX55) decoded "
        "to its cross-vendor universal core (dual clock-tick + 2 state "
        "regions, #N v5) plus a per-record measurement-extension region "
        "(#N v6) and the EM9190-only [488:554] state-flag region "
        "(#N v7); v=0x06/0x07/0x08 remain header-only pending RE. "
        "v8 (#N, 2026-06-11): first per-modem HW validation (#N) on "
        "Quectel RM520N-GL @ RM520NGLAAR03A03M4G (SDX62, <redacted-ref> 5174, "
        "live 3D fix) — wls_records.prn VERIFIED (6/6 decoded PRNs ⊆ live GPS "
        "PRN set), n_sv_records PARTIAL"
    ),
    version=8,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v1 (header-only, #N). v2/v3 (#N May 2026): version enum "
        "widened to {0x06, 0x07, 0x08, 0x0A, 0x0D} after corpus walk "
        "surfaced four older-chipset variants. v3 also recorded the per-"
        "version chipset attribution (v=0x06 MDM9230, v=0x07 MDM9x07, "
        "v=0x08 SDX20, v=0x0A SDX55, v=0x0D SDX62) and the confirmed "
        "v=0x0D variable-size formula `N_slots = (size - 44) / 47`. "
        "v4 (2026-05-27, #N <redacted-ref>): full v=0x0D body decode. "
        "Verified `(size - 44) % 47 == 0` across all 11 distinct payload "
        "sizes (796..1407 B, 1,842 records) of "
        "<redacted-pii> For size classes 937..1125 "
        "(1,585 records, 86% of corpus) head_slots is exactly 15 — body "
        "layout is `[44B preamble] + [15 × 47B reserved/template slots] "
        "+ [N × 47B per-SV records]`. Per-SV record layout cross-capture "
        "validated against 3 RM520N-GL captures (gnss_comparison_2026-05-10, "
        "2026-04-24_diag_at_correlate, 2026-05-10_diag_at_correlate): "
        "11-byte fixed prefix (5B signature `0000 7511 01`, PRN at [6], "
        "0x0007 marker, subframe_type byte) + 9 LE f32 measurement fields. "
        "Cap3 decode of PRN=1 yielded sensible WLS magnitudes (f5=11.54, "
        "f6=56.79, ..., f9=0.99). Corpus-wide validation (20 captures, "
        "5,443 v=0x0D records, 29,532 per-SV records decoded): 100% decode "
        "success, 0 exceptions. 17 of 44 preamble bytes are TRUE cross-"
        "capture invariants (`preamble_invariants_ok` exposes the validator) "
        "— these hold across normal, warm-restart, reboot, SIM-power-cycle, "
        "and airplane-mode operational states. Bytes that are 'mostly "
        "constant' but change during state transitions (4, 8, 15, 16, 17, "
        "21, 32) are deliberately EXCLUDED from the invariant set — they're "
        "per-session firmware-state. "
        "Field NAMES (wls_f1..wls_f9) are deliberately generic pending "
        "ephemeris/LOS cross-correlation with known-position fixes — the "
        "structural layout is locked but the semantic mapping (residual "
        "vs weight vs elevation-cos vs C/N0 vs Doppler-rate) needs a "
        "separate RE pass. Canonical name LOG_GNSS_PE_WLS_POSITION_REPORT_C "
        "indicates this is per-SV WLS measurement contributions, NOT "
        "subframe-derived Keplerian ephemeris (the issue body's RINEX-NAV "
        "framing was an aspirational scope; broadcast-ephemeris decode "
        "would need a different log code). "
        "v5 (2026-05-28, #N): v=0x0A (SDX55) universal-core decode. "
        "Cross-vendor per-byte walk on EM9190 SWIX55C (1,133 recs) + FN980 "
        "(1,166 recs) — sequential per the <redacted-ref> memory-safety rule — showed "
        "the fixed 4641 B body is 99%+ template padding, NOT a per-SV slot "
        "array (the issue's original `wls_records`-analogous framing was "
        "falsified). Only 11 byte positions carry cross-vendor-universal "
        "content: `tick_a`=u32[0:4] and `tick_b`=u32[4:8] (BOTH increment by "
        "exactly 256,000 / record — same GNSS-engine cadence as the v=0x0D "
        "body), `state_x`=u16[77:79], `state_y`=u24[97:100]. The validator "
        "asserts only the cross-vendor-VERIFIED anchors ([0]=0x0A, [4]=0x00, "
        "[8:23]=0, [23]=0x01); byte[33] (0x41 EM9190 / 0x84 FN980) and the "
        "f32 at [41:45] (59fc5a46 EM9190 / 4d903754 FN980) are per-firmware "
        "constants, NOT shared anchors, so they are excluded. "
        "v6 (2026-05-28, #N): the [30/51/61] measurement-extension region "
        "is now exposed. A consecutive-record diff (two adjacent EM9190 v=0x0A "
        "records differ in only 13 bytes: tick_a/tick_b low words, state_x, "
        "state_y, and offsets [30:32]/[51:53]/[61:63]) confirmed these three "
        "are the only LIVE per-record fields beyond the universal core. They "
        "decode as LE f32 (`ext_f32_30/_51/_61`); on EM9190 SDX55 they read "
        "≈15.42/15.44/15.44 (high word stable → real-valued measurement), "
        "while FN980 holds a different-magnitude pattern, so they are exposed "
        "as raw candidates and NOT added to the validator. The 10-byte blocks "
        "[51:61] and [61:71] are a cross-vendor-VERIFIED MIRROR "
        "(`ext_mirror_ok`, 3/3 fixtures), so `ext_f32_61` duplicates "
        "`ext_f32_51`. Physical semantics (C/N0 vs LNA gain vs clock-bias) "
        "still pending NMEA/AT-state cross-ref. "
        "v7 (2026-05-29, #N): the EM9190-only [488:554] state-flag region "
        "is now exposed as `toggle_region` (9 byte values at offsets "
        "488/490/502/503/506/547/548/552/554). The corpus-complete walk of "
        "the canonical EM9190 fixture (1,133 records) established these as the "
        "ONLY varying bytes in [480:560] — low-cardinality STATE FLAGS, not "
        "clocks (no monotonic u32 anywhere in the region). They co-vary in 3 "
        "correlated groups: off=488 <-> off=506 (same 134 records), "
        "off=490 <-> off=547 <-> off=552 (same 50 records), and "
        "off=502 <-> off=503 (same 87 records) — i.e. ~3 independent "
        "GNSS-engine state indicators. All-zero on FN980 (Sierra vendor "
        "extension) and on ~88% of EM9190 records in an inactive state, so "
        "`toggle_region` is exposed raw and NOT asserted in the cross-vendor "
        "validator. This completes the corpus-derivable v=0x0A structure; the "
        "only remaining work is PHYSICAL semantics of the flags + "
        "ext_f32_30/_51/_61 via NMEA / AT-state cross-ref (out of scope for "
        "offline corpus RE)."
    ),
    source_url="",
    issues=(),
    primary_issue=None,
    fields_identified=24,  # version, counter_hi/lo, n_slots, n_sv_records,
                            # head_slots, preamble_invariants_ok, seq_counter,
                            # v=0x0A: tick_a, tick_b, state_x, state_y,
                            # ext_f32_30/_51/_61, ext_mirror_ok, toggle_region,
                            # plus per-SV: prn, subframe_type, wls_f1..f9 (11 fields)
    fields_parsed=24,
    field_invariants={
        "version": {"enum": [0x06, 0x07, 0x08, 0x0A, 0x0D]},
    },
)
def parse_0x147c(log_time: int, data: bytes) -> Diag0x147C | None:
    if len(data) < 8:
        return None
    version = data[0]
    if version not in (0x06, 0x07, 0x08, 0x0A, 0x0D):
        return None

    n_slots: int | None = None
    n_sv: int | None = None
    head_slots: int | None = None
    preamble_ok: bool | None = None
    seq_counter: int | None = None
    tick_a: int | None = None
    tick_b: int | None = None
    state_x: int | None = None
    state_y: int | None = None
    ext_f32_30: float | None = None
    ext_f32_51: float | None = None
    ext_f32_61: float | None = None
    ext_mirror_ok: bool | None = None
    toggle_region: tuple[int, ...] | None = None
    wls_records: list[WlsSvRecord] = []

    # v=0x0D structural decode (per-SV slot grid). v=0x06/0x07/0x08 stay
    # header-only pending their own RE — their fixed sizes (4163/4395/4579 B)
    # do NOT satisfy the v=0x0D formula and would silently mis-parse.
    if version == 0x0D:
        sz = len(data)
        if sz >= _V0D_PREAMBLE_LEN and (sz - _V0D_PREAMBLE_LEN) % _V0D_SLOT_STRIDE == 0:
            (n_slots, n_sv, head_slots,
             preamble_ok, seq_counter, wls_records) = _parse_v0d_body(data)
    # v=0x0A universal-core decode (#N). Fixed 4641 B sparse state record;
    # gate on the exact size so off-size v=0x0A records (none observed) don't
    # read past meaningful offsets.
    elif version == 0x0A and len(data) == _V0A_PAYLOAD_SIZE:
        (tick_a, tick_b, state_x, state_y, preamble_ok,
         ext_f32_30, ext_f32_51, ext_f32_61, ext_mirror_ok,
         toggle_region) = _parse_v0a_body(data)

    return Diag0x147C(
        log_time=log_time,
        version=version,
        counter_hi=data[1],
        counter_lo=data[2],
        payload_size=len(data),
        body_raw=data[8:],
        n_slots=n_slots,
        n_sv_records=n_sv,
        head_slots=head_slots,
        preamble_invariants_ok=preamble_ok,
        seq_counter=seq_counter,
        tick_a=tick_a,
        tick_b=tick_b,
        state_x=state_x,
        state_y=state_y,
        ext_f32_30=ext_f32_30,
        ext_f32_51=ext_f32_51,
        ext_f32_61=ext_f32_61,
        ext_mirror_ok=ext_mirror_ok,
        toggle_region=toggle_region,
        wls_records=wls_records,
    )
