"""GNSS position-fix record (log code 0x1837).

Emitted at ~1 Hz in sync with the position-fix cadence - one record per
GPS PVT.  Runs alongside the NMEA-over-DIAG stream (0x1384) as a
structured, floating-point-native counterpart to the ASCII NMEA GGA
sentence.

Observed on every Qualcomm GNSS-capable modem in our corpus: FN980m
SDX55, EG18-NA SDX20 V2, EP06-A MDM9x07, LM960 SDX20, EG25-G MDM9207,
RM500Q SDX55, EM7511 MDM9650 (SWI9X50C_01.14.22.00) at version=3 / 61B.
A second variant — version=2 / 53B — is emitted on Sierra MC7455
(MDM9x30, SWI9X30C_02.24.03.00); see "v=2 layout" below.

## v=3 layout (61 bytes, little-endian throughout)

    [0]      u8   version                (observed 3 across every generation)
    [1:9]    u64  timestamp              (monotonic ms counter, ~1000 per sec)
    [9]      u8   subtype                (observed 2 constant - fix variant)
    [10:18]  f64  latitude_deg           (decimal degrees, positive = North)
    [18:26]  f64  longitude_deg          (decimal degrees, positive = East)
    [26:34]  f64  altitude_m             (meters, likely WGS-84 ellipsoidal)
    [34:42]  f64  position_uncertainty_m (horizontal position error estimate)
    [42:46]  u32  session_marker         (constant within a capture, varies by
                                          chipset/session: FN980m=95, LM960=95,
                                          EG25-G=95, EG18-NA=385364063,
                                          EP06-A=3003495007, EM7511=2785990239 -
                                          a boot-time schema/session tag)
    [46:50]  u32  counter_a              (monotonic per-record counter)
    [50:54]  u32  counter_b              (monotonic per-record counter)
    [54:58]  u32  reserved_zero_1        (observed zero across every capture)
    [58:61]  u24  reserved_zero_2        (observed zero across every capture -
                                          3-byte little-endian tail)

## v=2 layout (53 bytes — MC7455 MDM9x30 only)

    [0]      u8   version                (=2)
    [1:5]    u32  timestamp              (ms counter, ~1000 per sec - 32b
                                          here vs 64b in v=3)
    [5:9]    u32  seq_num                (per-record monotonic 0,1,2,3,...
                                          — NEW field in v=2, replaces the
                                          upper 32 bits of v=3's u64 ts)
    [9]      u8   subtype                (=2, same as v=3)
    [10:18]  f64  latitude_deg
    [18:26]  f64  longitude_deg
    [26:34]  f64  altitude_m
    [34:42]  f64  position_uncertainty_m
    [42:46]  u32  session_marker         (e.g. 95 / 4169560671 observed
                                          across two MC7455 captures)
    [46:50]  u32  counter_a              (monotonic)
    [50:53]  u24  counter_b              (monotonic, increments ~+4 per
                                          record — 3-byte tail; the v=3
                                          tail-byte u32+u24 (reserved_zero_1
                                          + reserved_zero_2) is absent)

Total v=2 width: 1+4+4+1+8+8+8+8+4+4+3 = 53 bytes.

Cross-corpus verification (#N): 433 v=2 records across 3 MC7455
captures all decode to lat ≈ 41.215 / lon ≈ -111.936 (Utah / Wasatch
Front), subtype invariant at 2, version invariant at 2, seq_num strictly
monotonic from 0.

## Field naming note

The plan originally hypothesized `reserved_95` under the assumption
that offset 42..46 held a schema constant equal to 95 on every modem.
Cross-generation scouting disproved this: the value is stable within a
capture but changes between chipsets (95 on Telit-branded, ~3e8-3e9 on
Quectel-branded).  The field is renamed `session_marker` to reflect
what the data actually shows - it behaves like a session or boot-time
tag, not a universal constant.

Cross-generation validation per integration tests:

    test_gnss_1837_integration_fn980m    - SDX55
    test_gnss_1837_integration_eg18na    - SDX20 V2
    test_gnss_1837_integration_ep06a     - MDM9x07
    test_gnss_1837_integration_lm960     - SDX20
    test_gnss_1837_integration_eg25g     - MDM9207
    test_gnss_1837_integration_em7511    - MDM9650 (SWI9X50C_01.14.22.00)

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_EVENTS_DS_GSM_AMR_CMC_TURNAROUND_TIME
        source: qxdm_3_12_714_2017_diag_log_codes (authority: community)
    aliases:
        LOG_EVENTS_GSM_DS_AMR_CMC_TURNAROUND_TIME
            source: qxdm_3_12_714_2017_diag_log_codes
        RESERVED
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


PAYLOAD_SIZE_V3 = 61
PAYLOAD_SIZE_V2 = 53

# Ground-truth capture recipe (#N). ONE recipe authored here: v=3 / 61B on
# the Quectel RM520N-GL (SDX62), the per-fix PVT variant our corpus attests
# for that modem. v=2 (MC7455 MDM9x30) is left for a separate Sierra recipe.
#
# 0x1837 is a near-ideal recipe target: unlike most ML1 measurement codes its
# physical fields are already FULLY DECODED (lat/lon/alt as IEEE-754 doubles),
# so a paired diag_correlate_at_poll capture validates the parser by direct
# numeric equality against the modem's own fix, no offset RE required. The
# Quectel vendor stack gives a field-by-field ground via AT+QGPSLOC=2 and the
# raw NMEA sentences the modem also emits (AT+QGPSGNMEA="GGA"/"RMC"). Recommend
# the RM520N-GL because it has the vendor QGPS stack and is corpus-attested at
# v=3. Companion structured-vs-ASCII cross-check: 0x1384 NMEA-over-DIAG (#N).
#
# Honesty caveats baked into the field map:
#  * cond:sky-fix — the modem must hold a real 3D fix or it emits stale/zero
#    PVT. Drive or sky-view the GNSS antenna; QGPSLOC returns +CME ERROR 516
#    ("not fixed now") until then, which is itself a useful negative control.
#  * altitude: the parser comment marks altitude_m as *likely WGS-84
#    ellipsoidal*, but NMEA $GxGGA reports MSL (orthometric) altitude in field 9
#    with the geoid separation broken out in field 11. On the Wasatch Front the
#    geoid undulation is ≈ -18 m, so an ellipsoidal-vs-MSL comparison must add
#    the separation back before claiming agreement — left as status=hypothesis.
#  * position_uncertainty_m: no command in the AT/QMI poller allow-list returns
#    HEPE directly. Grounded only loosely (NMEA HDOP as a shape proxy, QGPSLOC
#    has no uncertainty column) — status=hypothesis, weakest field in the map.
ALLOWED_VERSIONS = (2, 3)


@dataclass
class Diag0x1837:
    """GNSS per-fix position record (log code 0x1837)."""

    log_time: int
    version: int
    timestamp: int
    subtype: int
    latitude_deg: float
    longitude_deg: float
    altitude_m: float
    position_uncertainty_m: float
    session_marker: int
    counter_a: int
    counter_b: int
    # v=3 only — None on v=2 records (where the trailing 7 bytes are absent).
    reserved_zero_1: int | None
    reserved_zero_2: int | None
    # v=2 only — None on v=3 records (where [5:9] is the upper half of u64 ts).
    seq_num: int | None

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1837',
            'log_time': self.log_time,
            'version': self.version,
            'timestamp': self.timestamp,
            'subtype': self.subtype,
            'latitude_deg': self.latitude_deg,
            'longitude_deg': self.longitude_deg,
            'altitude_m': self.altitude_m,
            'position_uncertainty_m': self.position_uncertainty_m,
            'session_marker': self.session_marker,
            'counter_a': self.counter_a,
            'counter_b': self.counter_b,
            'reserved_zero_1': self.reserved_zero_1,
            'reserved_zero_2': self.reserved_zero_2,
            'seq_num': self.seq_num,
        }


@register(
    0x1837, domain="gnss",
    name="0x1837",
    description=(
        "Per-fix GNSS PVT record emitted at ~1 Hz alongside NMEA-over-DIAG "
        "(0x1384). Carries lat/lon/altitude as IEEE-754 doubles plus a "
        "position-uncertainty estimate. v=3 / 61B on MDM9x07/9x50 + SDX20/55; "
        "v=2 / 53B on MC7455 MDM9x30 (timestamp shrinks u64→u32 + seq_num at "
        "[5:9], trailing 7B reserved fields absent)."
    ),
    version=4,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v=3 (61B): clean-room RE from FN980m SDX55; cross-validated on "
        "EG18-NA SDX20V2, EP06-A MDM9x07, LM960 SDX20, EG25-G MDM9207, "
        "EM7511 MDM9650. v=2 (53B): MC7455 MDM9x30 SWI9X30C_02.24.03.00 "
        "— 433 records / 3 captures (gnss_live, gnss_comparison, "
        "warm_gnss_restart); [0:50] byte-compatible with v=3 except "
        "[1:9] splits u64 ts → u32 ts + u32 seq_num; tail [50:53] is u24 "
        "counter_b (no reserved_zero_1/2). #N."
    ),
    source_url="",
    fields_identified=13,
    fields_parsed=13,
    issues=(),
    primary_issue=None,
    # Layer-2 invariants — paired with the in-parser hard gates below.
    # Catches the silent-mis-parse trap if a future firmware ships a
    # different layout under a new version byte (per project core
    # memory: size invariance ≠ format invariance for DIAG payloads).
    field_invariants={
        "version": {"enum": list(ALLOWED_VERSIONS)},
        "subtype": {"const": 2},
        # reserved_zero_* are v=3-only fields (None on v=2); the registry
        # skips invariant checks when observed is None (registry.py:492),
        # so these still pin v=3 records to 0 without rejecting v=2 ones.
        "reserved_zero_1": {"const": 0},
        "reserved_zero_2": {"const": 0},
    },
)
def parse_0x1837(log_time: int, data: bytes) -> Diag0x1837 | None:
    # Version-byte-first audit (#N): gate the version BEFORE any
    # structural decode. Two versions accepted (2, 3); per-version layouts
    # diverge in the [1:9] band and in the trailing bytes.
    if len(data) < 1:
        return None
    version = data[0]
    if version not in ALLOWED_VERSIONS:
        return None

    if version == 3:
        if len(data) < PAYLOAD_SIZE_V3:
            return None
        timestamp = unpack_from('<Q', data, 1)[0]
        seq_num: int | None = None
        counter_b = unpack_from('<I', data, 50)[0]
        reserved_zero_1: int | None = unpack_from('<I', data, 54)[0]
        # reserved_zero_2 is a 3-byte LE integer occupying [58:61];
        # decode via int.from_bytes (always 0 across 1839 records / 6
        # QCA generations).
        reserved_zero_2: int | None = int.from_bytes(data[58:61], 'little')
    else:  # version == 2
        if len(data) < PAYLOAD_SIZE_V2:
            return None
        timestamp = unpack_from('<I', data, 1)[0]
        seq_num = unpack_from('<I', data, 5)[0]
        counter_b = int.from_bytes(data[50:53], 'little')
        reserved_zero_1 = None
        reserved_zero_2 = None

    subtype = data[9]
    latitude_deg = unpack_from('<d', data, 10)[0]
    longitude_deg = unpack_from('<d', data, 18)[0]
    altitude_m = unpack_from('<d', data, 26)[0]
    position_uncertainty_m = unpack_from('<d', data, 34)[0]
    session_marker = unpack_from('<I', data, 42)[0]
    counter_a = unpack_from('<I', data, 46)[0]

    return Diag0x1837(
        log_time=log_time,
        version=version,
        timestamp=timestamp,
        subtype=subtype,
        latitude_deg=latitude_deg,
        longitude_deg=longitude_deg,
        altitude_m=altitude_m,
        position_uncertainty_m=position_uncertainty_m,
        session_marker=session_marker,
        counter_a=counter_a,
        counter_b=counter_b,
        reserved_zero_1=reserved_zero_1,
        reserved_zero_2=reserved_zero_2,
        seq_num=seq_num,
    )
