"""0x18F8 — GNSS misc status, 20B fixed, EM7511 mode-transition edge-case (#N).

Split from `lte_misc.py` per #N tier-3 batch 14.

Emitted during LTE mode transitions (airplane-mode cycle, SIM power cycle).
12 records total: 5 per airplane cycle, 5 per SIM cycle, 2 pre-reboot.

Layout (20 B fixed, version 0x01):
  [0]     u8   version    = 0x01 (const; the Qualcomm version byte)
  [1]     u8   type_b     = 0x02 (const)
  [2:6]   u32  sentinel_a = 0xFFFFFFFF (const)
  [6:8]   u16  measurement — valid range 121-168; 0xFFFF = not available
  [8:10]  u16  sentinel_b  = 0xFFFF (const)
  [10:12] u16  reserved_0  = 0x0000 (const)
  [12:14] u16  sentinel_c  = 0xFFFE (const; literal bytes fe ff)
  [14]    u8   reserved_1  = 0x00 (const)
  [15]    u8   const_7d    = 0x7D (const; 125 decimal)
  [16:20] u32  sentinel_d  = 0xFFFFFFFF (const)

The only varying field is [6:8].  Observed values: 0x0079=121, 0x007B=123,
0x0083=131, 0x00A8=168, 0xFFFF=not-available (during mode-off phase).
Semantic: unknown; possible location accuracy in 0.1 m units or an RF metric.

#N version-compliance — byte[0] is the version discriminant, not a
generic "type".  The corpus partitions byte[0] cleanly by firmware:
0x01 on the EM7511/MC7411 family (this RE'd 20-B layout), 0x02 on
em9291 SWIX65C.  The 0x02 records carry different sentinel content
(sentinel_a/sentinel_d are NOT 0xFFFFFFFF) and a separate 72-B variant —
a distinct format this parser does not model.  byte[0] is therefore
renamed ``type_a`` -> ``version`` and gated to the RE'd value 0x01 (both
layer-1 and via ``field_invariants['version']``), so an em9291 0x02
record (or any future version) fails fast rather than being mis-decoded
under the v1 layout (core-memory rule, 2026-05-08).

Closure: #N.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_MCS_VBATT_INFO
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


@dataclass
class Diag0x18F8:
    """GNSS misc status (0x18F8) — 20B fixed, emitted on LTE mode transitions."""
    log_time: int
    version: int     # [0] const 0x01 — Qualcomm version byte (#N)
    type_b: int      # [1] const 0x02
    sentinel_a: int  # [2:6] const 0xFFFFFFFF
    measurement: int # [6:8] varying; 0xFFFF = not available
    sentinel_b: int  # [8:10] const 0xFFFF
    reserved_0: int  # [10:12] const 0x0000
    sentinel_c: int  # [12:14] const 0xFFFE
    reserved_1: int  # [14] const 0x00
    const_7d: int    # [15] const 0x7D (125)
    sentinel_d: int  # [16:20] const 0xFFFFFFFF

    @property
    def measurement_valid(self) -> bool:
        return self.measurement != 0xFFFF

    def to_dict(self) -> dict[str, Any]:
        # All fields are exposed so layer-2 check_invariants can audit the
        # sentinels (per #N silent-mis-parse protection pattern). Sentinels
        # are constants in the observed corpus; downstream consumers can
        # ignore them, but auditors need them visible.
        d: dict[str, Any] = {
            'type': 'Diag0x18F8',
            'log_time': self.log_time,
            'version': self.version,
            'type_b': self.type_b,
            'sentinel_a': self.sentinel_a,
            'measurement': self.measurement if self.measurement_valid else None,
            'measurement_valid': self.measurement_valid,
            'sentinel_b': self.sentinel_b,
            'reserved_0': self.reserved_0,
            'sentinel_c': self.sentinel_c,
            'reserved_1': self.reserved_1,
            'const_7d': self.const_7d,
            'sentinel_d': self.sentinel_d,
        }
        return d


# --- Ground-truth recipe (#N) ---------------------------------------
# Authored offline (hw_run_performed=False). DISCOVERY recipe: 19/20 bytes
# are constants/sentinels and `measurement` is the lone variable field with
# UNKNOWN semantics (range 121-168, 0xFFFF=N/A). The community-only name
# LOG_MCS_VBATT_INFO (lowest source-precedence) HINTS battery voltage but is
# NOT authoritative; the observation-based RE called it "possible location
# accuracy in 0.1 m units or an RF metric". This recipe names the candidate
# quantities and what a correlation must recover; it does NOT assert one.
#
# ⚠️ TARGET = Sierra EM7511 (MDM9650), NOT the RM520N-GL house default:
# the RM520N-GL (SDX62) emits 0x18F8 ONLY at v=0x02 (verified via the
# 2026-06-07 diag_at_correlate scan: every 20B AND 72B record has byte0=0x02),
# which this v=0x01 parser does not model. v=0x01 is the EM7511/MC7411 MDM9650
# layout this parser was RE'd from — so the recipe targets the EM7511 we own.
# Sierra AT dialect (AT!*/AT+CESQ), not Quectel AT+Q*.

@register(
    0x18F8,
    name="0x18F8",
    description="GNSS misc status (0x18F8) — 20B fixed v0x01, version-gated (#N)",
    version=2,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room RE from 12 EM7511 MDM9650 records across airplane-mode + SIM + "
        "reboot transitions 2026-04-20; 19 of 20 bytes constant (#N). "
        "v2 (#N): byte[0] renamed type_a->version and gated to 0x01 — the "
        "corpus partitions byte[0] by firmware (0x01 EM7511/MC7411, 0x02 em9291 "
        "with different sentinels + a 72-B variant); the v1 layout only models 0x01."
    ),
    issues=(),
    fields_identified=10,
    fields_parsed=10,
    field_invariants={
        # Layer-2 drift detection. 19 of 20 bytes are constant across all 12
        # EM7511 MDM9650 records — these are the version/sentinel discriminators
        # that protect against a future firmware shipping a different layout
        # in the same 20-byte envelope (core-memory rule, 2026-05-08).
        # ``measurement`` (the lone varying field) is deliberately NOT enumerated
        # — 12 records yields 4 distinct values + the 0xFFFF not-available
        # sentinel, too small a sample to claim a closed enum (small-N rule,
        # <redacted-ref> v1.4.0).
        # #N: byte[0]=version, gated to 0x01 at layer-1 (parser body) too.
        "version":    {"enum": [0x01]},
        "type_b":     {"enum": [0x02]},
        "sentinel_a": {"enum": [0xFFFFFFFF]},
        "sentinel_b": {"enum": [0xFFFF]},
        "reserved_0": {"enum": [0x0000]},
        "sentinel_c": {"enum": [0xFFFE]},
        "reserved_1": {"enum": [0x00]},
        "const_7d":   {"enum": [0x7D]},
        "sentinel_d": {"enum": [0xFFFFFFFF]},
    },
)
def parse_0x18f8(log_time: int, data: bytes) -> Diag0x18F8 | None:
    if len(data) < 20:
        return None
    # #N first-byte version-gate. byte[0]=0x01 is the only version this
    # 20-B layout models; em9291's 0x02 (different sentinels + 72-B variant)
    # and any future version are rejected here rather than mis-decoded.
    if data[0] != 0x01:
        return None
    return Diag0x18F8(
        log_time=log_time,
        version=data[0],
        type_b=data[1],
        sentinel_a=unpack_from('<I', data, 2)[0],
        measurement=unpack_from('<H', data, 6)[0],
        sentinel_b=unpack_from('<H', data, 8)[0],
        reserved_0=unpack_from('<H', data, 10)[0],
        sentinel_c=unpack_from('<H', data, 12)[0],
        reserved_1=data[14],
        const_7d=data[15],
        sentinel_d=unpack_from('<I', data, 16)[0],
    )
