"""0x18F8 — modem misc status word, mode-transition edge-case (#N).

Split from `lte_misc.py` per #N tier-3 batch 14.

⚠️ SUBSYSTEM: **unconfirmed — NOT GNSS.** The original filing (2026-04-20)
guessed "GNSS/location misc" purely from the 0x18xx code range. That guess is
**refuted** by two independent lines of evidence gathered since:
  * The records fire in **LTE/NR RF state-transition** captures (airplane-mode
    cycle, SIM power cycle, reboot, PSM/eDRX) — GNSS is *not* active in any of
    them. On the Sierra EM7511 the trigger is the LTE mode change, not a fix.
  * **F3 co-temporal check (2026-07-19, RM520N-GL 6552b4be, 4.06M F3 frames):**
    no F3 print co-fires with a 0x18F8 record (median nearest-F3 distance sits
    at the correlation-window edge). The ambient F3 in-window is dominated by
    **RF front-end device programming** (FEM/ELNA/PA/ASM port selection,
    tx_agc) — the signature of an RF state transition — with only trace GNSS-RF
    background. This is an RF/mode-transition context, not a GNSS measurement.
So the parser is **undomained** (``domain=None``); the topical bucket is left
unset rather than mis-filed under ``gnss``. Semantics of the varying fields
remain open RE (AT-correlation, not F3 — F3 does not label this code).

Two versions coexist in the corpus, partitioned by byte[0] (the Qualcomm
version byte). The corpus is now **~97% v0x02** — the original v0x01 RE covered
only the residual ~3%.

--- v0x01 (20 B fixed) — EM7511 / MC7411 (MDM9650) -------------------------
Emitted during LTE mode transitions. RE'd 2026-04-20 from 12 EM7511 records.
  [0]     u8   version    = 0x01 (const; the Qualcomm version byte)
  [1]     u8   type_b     = 0x02 (const)
  [2:6]   u32  sentinel_a = 0xFFFFFFFF (const)
  [6:8]   u16  measurement — valid range 121-168; 0xFFFF = not available
  [8:10]  u16  sentinel_b  = 0xFFFF (const)
  [10:12] u16  reserved_0  = 0x0000 (const)
  [12:14] u16  sentinel_c  = 0xFFFE (const; literal bytes fe ff)
  [14]    u8   reserved_1  = 0x00 (const)
  [15]    u8   const_7d    = 0x7D (const; 125 decimal)
  [16:20] u32  sentinel_d  = 0xFFFFFFFF (const)
The lone varying field is [6:8] (0x0079=121, 0x007B=123, 0x0083=131,
0x00A8=168, 0xFFFF=N/A). Semantics: unknown; a candidate RF/mode metric.

--- v0x02 — RM520N-GL (SDX62) + EM9291 (SDX65) ----------------------------
A DISTINCT dual-shape format, discriminated by byte[1] (``record_type``). Each
mode-transition event emits a **pair** — one 72 B record (record_type=0x01)
and one 20 B record (record_type=0x02); the corpus counts the two shapes in
near-lockstep. Cross-gen attested: the layouts are **byte-identical across
SDX62 and SDX65** (2 QCA generations, no HW needed).

  v0x02-A (72 B, record_type=0x01): a firmware-static capability/config table —
    every one of the 72 bytes is invariant across both chipset gens. Structure:
    three blocks, each ``[4 sequential u16 IDs][zeros][2 u16 values]`` —
    IDs 200-203 / 190-193 / 180-183, values ~2400-3200. Semantics unconfirmed
    (looks like a thermal/RF-power reference table); preserved as ``table_raw``.

  v0x02-B (20 B, record_type=0x02): richer than v0x01 — byte[2] is a real
    per-record value (30-36 on SDX62, 57-61 on SDX65 — firmware-scaled) where
    v0x01 carries the 0xFF sentinel there. byte[3] varies (0x0b-0x10). The u16
    at [6:8] (byte7=0x00) ranges 131-216 — overlapping v0x01's [6:8]
    ``measurement`` (121-168), so it is very likely the **same quantity
    continued into v0x02**. Named ``measurement`` for continuity.

#N version-compliance: byte[0] is the version discriminant. Both v0x01 and
v0x02 are now modelled; a future v0x03 (or a v0x02 sub-shape with an unknown
record_type) fails fast rather than being mis-decoded (core-memory rule,
2026-05-08 — size invariance ≠ format invariance).

Closure: #N.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_MCS_VBATT_INFO
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===

⚠️ The community name ``LOG_MCS_VBATT_INFO`` (battery voltage) is the
LOWEST-authority source and is **not corroborated** by evidence: the F3 check
above found VBATT/VADC telemetry *exists* in this firmware but **never
co-fires with a 0x18F8 record**, and the ``measurement`` range (121-216) does
not match any observed VADC microvolt/threshold value. Treat the VBATT name as
unverified index noise, not a decode hint.
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


@dataclass
class Diag0x18F8:
    """0x18F8 v0x01 — 20B fixed, EM7511/MC7411 MDM9650, LTE mode transitions."""
    log_time: int
    version: int     # [0] const 0x01 — Qualcomm version byte (#N)
    type_b: int      # [1] const 0x02
    sentinel_a: int  # [2:6] const 0xFFFFFFFF
    measurement: int # [6:8] varying; 0xFFFF = not available
    sentinel_b: int  # [8:10] const 0xFFFF
    reserved_0: int  # [10:12] const 0x0000
    sentinel_c: int  # [12:14] const 0xFFFE
    reserved_1: int  # [14] const 0x00
    const_7d: int    # [15] const 0x7D (125)
    sentinel_d: int  # [16:20] const 0xFFFFFFFF

    @property
    def measurement_valid(self) -> bool:
        return self.measurement != 0xFFFF

    def to_dict(self) -> dict[str, Any]:
        # All fields are exposed so layer-2 check_invariants can audit the
        # sentinels (per #N silent-mis-parse protection pattern). Sentinels
        # are constants in the observed corpus; downstream consumers can
        # ignore them, but auditors need them visible.
        d: dict[str, Any] = {
            'type': 'Diag0x18F8',
            'log_time': self.log_time,
            'version': self.version,
            'type_b': self.type_b,
            'sentinel_a': self.sentinel_a,
            'measurement': self.measurement if self.measurement_valid else None,
            'measurement_valid': self.measurement_valid,
            'sentinel_b': self.sentinel_b,
            'reserved_0': self.reserved_0,
            'sentinel_c': self.sentinel_c,
            'reserved_1': self.reserved_1,
            'const_7d': self.const_7d,
            'sentinel_d': self.sentinel_d,
        }
        return d


@dataclass
class Diag0x18F8V2:
    """0x18F8 v0x02 — dual-shape, RM520N-GL (SDX62) + EM9291 (SDX65).

    ``record_type`` (byte[1]) selects the shape: 0x01 → 72 B static table,
    0x02 → 20 B per-record status. Byte-identical across both chipset gens
    (cross-gen attested; see the module docstring).
    """
    log_time: int
    version: int          # [0] const 0x02 — Qualcomm version byte
    record_type: int      # [1] 0x01 (72B table) | 0x02 (20B status)
    length: int           # record length (72 or 20)
    # v0x02-B (20B) named fields — None on the 72B shape:
    field_2: int | None       # [2] per-record value (30-36 SDX62 / 57-61 SDX65)
    field_3: int | None       # [3] varies 0x0b-0x10
    measurement: int | None   # [6:8] u16 — same offset/range as v0x01 measurement
    # v0x02-A (72B) static table — None on the 20B shape:
    table_raw: str | None     # [2:72] hex; firmware-static, cross-gen-identical

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            'type': 'Diag0x18F8V2',
            'log_time': self.log_time,
            'version': self.version,
            'record_type': self.record_type,
            'length': self.length,
        }
        if self.record_type == 0x02:
            d['field_2'] = self.field_2
            d['field_3'] = self.field_3
            d['measurement'] = self.measurement
        elif self.record_type == 0x01:
            d['table_raw'] = self.table_raw
        return d


# --- Ground-truth recipe (#N) ---------------------------------------
# Authored offline (hw_run_performed=False). DISCOVERY recipe for the v0x01
# EM7511 layout: 19/20 bytes are constants/sentinels and `measurement` is the
# lone variable field with UNKNOWN semantics (range 121-168, 0xFFFF=N/A).
#
# ⚠️ NOT a GNSS measurement and NOT battery voltage:
#   * F3 co-temporal check (2026-07-19) shows the in-window F3 is RF-front-end
#     device programming, not GNSS — see module docstring. The recipe grounds
#     `measurement` against RF/mode AT surfaces (AT+CESQ / AT!GSTATUS?), not
#     GNSS or CGNSSINFO.
#   * The community `LOG_MCS_VBATT_INFO` name is uncorroborated (no co-temporal
#     VBATT F3; range mismatch) — do NOT chase battery voltage.
#
# ⚠️ v0x01 TARGET = Sierra EM7511 (MDM9650): RM520N-GL/EM9291 emit ONLY v0x02,
# which this recipe's v0x01 layout does not cover. Sierra AT dialect
# (AT!*/AT+CESQ), not Quectel AT+Q*.

@register(
    0x18F8, domain=None,
    name="0x18F8",
    description="Modem misc status (0x18F8) — v0x01 20B + v0x02 dual-shape, version-gated (#N)",
    version=3,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room RE. v0x01: 12 EM7511 MDM9650 records, airplane/SIM/reboot "
        "transitions 2026-04-20, 19/20 bytes constant. v0x02 (v3, 2026-07-19): "
        "dual-shape (72B record_type=0x01 static table + 20B record_type=0x02 "
        "status), byte-identical across RM520N-GL SDX62 + EM9291 SDX65 — "
        "cross-gen attested over the on-host corpus. Subsystem is NOT gnss "
        "(F3 co-temporal check + LTE/NR-transition emission context); domain "
        "left unset. See module docstring."
    ),
    issues=(),
    fields_identified=13,
    fields_parsed=13,
    field_invariants={
        # Layer-2 drift detection. version is the shared discriminant across
        # both modelled layouts. The remaining v0x01 sentinels and the v0x02
        # discriminators are named per-layout; check_invariants() skips any
        # invariant whose field is absent from a given record's to_dict()
        # (registry.py:1330), so v0x01 and v0x02 invariants coexist harmlessly
        # in one dict — each fires only on records of its own version.
        #
        # ``measurement`` (v0x01) and ``field_2``/``field_3`` (v0x02) are the
        # varying fields and are deliberately NOT enumerated (small-N rule,
        # <redacted-ref> v1.4.0).
        # #N: byte[0]=version, gated at layer-1 (parser body) too.
        "version":       {"enum": [0x01, 0x02]},
        # --- v0x01 constants (skipped for v0x02 records) ---
        "type_b":     {"enum": [0x02]},
        "sentinel_a": {"enum": [0xFFFFFFFF]},
        "sentinel_b": {"enum": [0xFFFF]},
        "reserved_0": {"enum": [0x0000]},
        "sentinel_c": {"enum": [0xFFFE]},
        "reserved_1": {"enum": [0x00]},
        "const_7d":   {"enum": [0x7D]},
        "sentinel_d": {"enum": [0xFFFFFFFF]},
        # --- v0x02 discriminator (skipped for v0x01 records) ---
        "record_type":   {"enum": [0x01, 0x02]},
    },
)
def parse_0x18f8(log_time: int, data: bytes) -> Diag0x18F8 | Diag0x18F8V2 | None:
    if len(data) < 2:
        return None
    # #N first-byte version-gate (Layer-1). Only the two RE'd versions are
    # modelled; a future v0x03 (or unknown) fails fast rather than being
    # mis-decoded. Explicit `data[0] not in (...)` form for the version-gate
    # ratchet audit (test_parser_version_gate_ratchet).
    if data[0] not in (0x01, 0x02):
        return None
    version = data[0]
    if version == 0x01:
        if len(data) < 20:
            return None
        return Diag0x18F8(
            log_time=log_time,
            version=data[0],
            type_b=data[1],
            sentinel_a=unpack_from('<I', data, 2)[0],
            measurement=unpack_from('<H', data, 6)[0],
            sentinel_b=unpack_from('<H', data, 8)[0],
            reserved_0=unpack_from('<H', data, 10)[0],
            sentinel_c=unpack_from('<H', data, 12)[0],
            reserved_1=data[14],
            const_7d=data[15],
            sentinel_d=unpack_from('<I', data, 16)[0],
        )
    if version == 0x02:
        record_type = data[1]
        if record_type == 0x01:
            # 72B static table (cross-gen-identical). Preserve the body.
            if len(data) < 72:
                return None
            return Diag0x18F8V2(
                log_time=log_time,
                version=version,
                record_type=record_type,
                length=len(data),
                field_2=None, field_3=None, measurement=None,
                table_raw=data[2:72].hex(),
            )
        if record_type == 0x02:
            # 20B per-record status.
            if len(data) < 20:
                return None
            return Diag0x18F8V2(
                log_time=log_time,
                version=version,
                record_type=record_type,
                length=len(data),
                field_2=data[2],
                field_3=data[3],
                measurement=unpack_from('<H', data, 6)[0],
                table_raw=None,
            )
        # Unknown v0x02 sub-shape — fail fast (do not mis-decode).
        return None
    return None
