"""0x1589 — structural stub (legacy `GnssStatus1589`, EG18-NA SDX20 V2 remaining batch).

Split from `lte_misc.py` per #N tier-3 batch 30.

Promoted from the "EG18-NA SDX20 V2 remaining" `_simple_parser` tuple loop so the ID-only
naming convention applies (registry name "0x1589", class `Diag0x1589`,
type string `Diag0x1589`).

Structural decode (2026-06-22 <redacted-ref>, N=30 / 8 vendor-chipset combos;
re-verified 2026-06-26 <redacted-ref> at N=48):
fixed-size 17-byte record, byte-0 version gate (corpus-wide 0x00), two
variants by byte[1] (A: all-zero header, B: vendor-tagged), with
corpus-wide invariant markers at [10]=0x00 / [11]=0x01 / [12]=0x00 /
[16]=0x00. See the `Diag0x1589` dataclass for the full field map. The
prior u32@4 `config_word` field was a bulk-registration artifact (it
straddled the [3:10] varying chunk) and has been replaced by the
named structural fields.

2026-06-26 <redacted-ref> new-data re-check: corpus grew N=30 -> 48 (new
`foxconn t99w175` variant-A record + June RM500QAE/SIM8202 wardrives).
All five locked invariants (version=0x00, markers [10]/[11]/[12]/[16])
still hold 48/48. The variant-B `vendor_tag` (byte[1]) observed set
widened to {0x6d,0x6e,0x6f,0x71,0x73,0x75,0x76} — deliberately NOT in
`field_invariants` (it is the vendor/firmware tag and is expected to
grow per build). `triplet` ([13:16]) semantics remain undecoded: the
constellation-sat-count hypothesis was *refuted* against the one on-disk
LG290P oracle (`eg18na gnss_comparison_lg290p_2026-04-11`) — that
capture's modem NMEA is GPS-only (498 $GPGSV, zero GL/GA/GB, 15 GPS SV
in view), so triplet (03,02,05) is neither modem-side multi-constellation
SV-in-view counts nor matches the single-constellation magnitude. Closure
of the *triplet* stays gated on a multi-GNSS-NMEA-armed correlation capture.

## 2026-07-17 <redacted-ref> (F3-directed) — SUBSYSTEM CONFIRMED = GNSS SAP-SDP; IPsec canonical name REFUTED

The earlier "F3 verified-negative across the whole 0x1589 corpus" claim was
STALE — newer captures bear 0x1589 *with* full-rate decodable F3 (SimCom
2026-06-12 wardrives; EG18-NA `edge_cases_2026-07-07`). Extracting F3 from
`01_cold_gnss_start` (pure GNSS engine start, no reboot, no NAS re-search) and
inspecting the co-temporal window of the lone 0x1589 emission (ts64
3284755660642) shows the record fires in lockstep (dt≈-866 ticks) with the
GNSS **SAP-SDP** state machine — grounding the alias, refuting the canonical:

  - `sdp_core.c:3616  event 9 for state 3` / `sdp_core.c:3310  valid event 9 …`
  - `lbs_sdp_crd.c:467  CRD : Reset` · `lbs_sdp_ssd.c:717  SDP : SSD initialized`
  - `sdp_core.c:6486  SDP: Vehicle sensors state machine event = 3 state = 1`
  - `mc_peak.c:5627  SV … updating as tentative` · `loc_task.c:308  Loc enabled 1`
  - ZERO IPsec/IKE/NAT F3 anywhere in the window.

`sdp_core.c` / `lbs_sdp_*` is the **SAP-SDP** (Sensor-Assisted Positioning /
Sensor Data Processor) subsystem — a direct match to the alias
`LOG_GNSS_SAP_SDP_EVENTS`. Emission-context corroborates: on the same EG18-NA
run, 0x1589 fires in the 3 GNSS scenarios (cold/warm GNSS start, boot+gnss) and
is ABSENT from the 3 NAS scenarios (lte_airplane, sim_power, manual_plmn_scan).
So the higher-precedence community canonical `LOG_EVENT_IPSEC_IKE_NAT_DETECTED`
is **refuted by F3** and demoted; the operative subsystem is GNSS SAP-SDP.

New interpretation lead (supersedes the refuted SV-count reading): the
`sdp_core.c` prints are (event, state) pairs, so the `triplet` [13:16] and/or
`chunk_3_10` may encode SDP event/state/substate rather than constellation SV
counts — to be tested against the co-temporal `sdp_core.c` event/state values.

Tracked under the size-unknown stub roll-up #N.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_EVENT_IPSEC_IKE_NAT_DETECTED
        source: qxdm_3_12_714_2017_diag_log_codes (authority: community)
    aliases:
        LOG_GNSS_SAP_SDP_EVENTS
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from diaggrok.registry import register


@dataclass
class Diag0x1589:
    """0x1589 — fixed-size 17-byte GNSS record, structural decode.

    Field map (corpus-grounded at N=30 / 8 vendor-chipset combos,
    refreshed 2026-06-22 <redacted-ref>):

      [0]      version         corpus-wide 0x00 (Layer-1 gate)
      [1]      vendor_tag      0x00 (variant A) or 0x6d..0x76 (variant B)
      [2]      record_type     0x00 (variant A) or 0x09 (variant B)
      [3:10]   chunk_3_10      7-byte varying chunk (candidate counter/u56 ts)
      [10]     marker_10       corpus-wide 0x00
      [11]     marker_11       corpus-wide 0x01
      [12]     marker_12       corpus-wide 0x00
      [13:16]  triplet         GNSS-shaped 3-tuple (candidate SV/constellation counts)
      [16]     reserved_16     corpus-wide 0x00

    ``variant`` is derived: "A" when vendor_tag==0x00 else "B". Triplet and
    chunk_3_10 field semantics are undecoded. Subsystem is F3-confirmed GNSS
    SAP-SDP (co-temporal `sdp_core.c` event/state prints — 2026-07-17); F3
    does not directly label the [13:16] triplet, so its value closure is still
    correlation-gated, now against the SDP event/state machine (candidate)
    rather than the refuted per-constellation SV-count reading.
    """
    log_time: int
    version: int
    vendor_tag: int
    record_type: int
    variant: str
    chunk_3_10: bytes
    marker_10: int
    marker_11: int
    marker_12: int
    triplet: tuple[int, int, int]
    reserved_16: int
    data_density: float
    payload_size: int
    body_raw: bytes

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": "Diag0x1589",
            "log_time": self.log_time,
            "version": self.version,
            "vendor_tag": self.vendor_tag,
            "record_type": self.record_type,
            "variant": self.variant,
            "chunk_3_10": self.chunk_3_10,
            "marker_10": self.marker_10,
            "marker_11": self.marker_11,
            "marker_12": self.marker_12,
            "triplet": self.triplet,
            "reserved_16": self.reserved_16,
            "data_density": self.data_density,
            "payload_size": self.payload_size,
            "body_raw": self.body_raw,
        }


# Ground-truth recipe (#N / #N / umbrella #N). 0x1589 is a 17-byte
# structural stub whose semantics are NOT closed: the GNSS-shaped triplet
# [13:16] was hypothesised as per-constellation SV counts and *refuted* against
# the only on-disk LG290P oracle (that capture's modem NMEA is GPS-only, so a
# multi-constellation triplet (03,02,05) cannot be modem-side SV-in-view).
# So this recipe does NOT ground triplet against a value by chance — it states
# the falsifiable mapping and names the multi-GNSS-NMEA capture that would
# actually test it. RM520N-GL emits the code (1 record, full-reboot edge case,
# RM520NGLAAR03A03M4G); per the per-modem rule it gets its own Quectel-AT recipe.
#
# ✅ SUBSYSTEM CONFIRMED = GNSS SAP-SDP (2026-07-17, F3-grounded). The
# DIAG_LOG_INDEX names disagreed: canonical (community, qxdm 3.12) was
# LOG_EVENT_IPSEC_IKE_NAT_DETECTED (IPsec/IKE — NOT GNSS), alias (zukgit 2025)
# LOG_GNSS_SAP_SDP_EVENTS (GNSS Sensor-Assisted Positioning / SDP). F3 settled
# it: co-temporal with a 0x1589 emission in the EG18-NA `01_cold_gnss_start`
# capture, the firmware prints `sdp_core.c` "event N for state M" + `lbs_sdp_*`
# SDP init/reset (SAP-SDP state machine), with SV-tracking / Loc-enable GNSS
# context and ZERO IPsec/IKE/NAT. Emission-context agrees (fires in GNSS
# scenarios, absent in lte_airplane/sim_power/manual_plmn_scan). So the IPsec
# canonical name is REFUTED/demoted; the alias LOG_GNSS_SAP_SDP_EVENTS holds.
# The recipe's former step-0 "ground the subsystem" is now RESOLVED (GNSS
# SAP-SDP); remaining hypotheses are the per-field values (triplet/chunk).

@register(
    0x1589, domain="gnss",
    name="0x1589",
    description="0x1589 — GNSS SAP-SDP event record (F3-confirmed), structural-header decode (17 B, EG18-NA SDX20 V2 remaining corpus)",
    version=3,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail="EG18-NA SDX20 V2 remaining `_simple_parser` corpus; promoted from stub per #N tier-3 batch 30. v2 (2026-06-26, #N): added an RM520N-GL (SDX62) GroundTruth recipe. v3 (2026-07-17, #N, <redacted-ref> F3-directed): SUBSYSTEM CONFIRMED = GNSS SAP-SDP by co-temporal F3 (sdp_core.c 'event N for state M' + lbs_sdp_* SDP init, zero IPsec/IKE/NAT) in EG18-NA 01_cold_gnss_start; the higher-precedence canonical name LOG_EVENT_IPSEC_IKE_NAT_DETECTED is refuted/demoted, the alias LOG_GNSS_SAP_SDP_EVENTS holds. The stale 'F3 verified-negative' claim is scrubbed (newer captures carry decodable F3). Triplet [13:16] value semantics remain a hypothesis (F3 does not label the bytes directly).",
    source_url="",
    issues=(),
    primary_issue=None,
    field_invariants={
        "version": {"enum": [0x00]},
        "marker_10": {"enum": [0x00]},
        "marker_11": {"enum": [0x01]},
        "marker_12": {"enum": [0x00]},
        "reserved_16": {"enum": [0x00]},
    },
    supported_versions=(0x00,),
    fields_identified=9,
    fields_parsed=9,
)
def parse_0x1589(log_time: int, data: bytes) -> Diag0x1589 | None:
    # Layer-1 gate FIRST (byte-0 version rule, #N): reject before any
    # size assumptions. Then the fixed-size gate — every corpus record of
    # 0x1589 is exactly 17B (size-invariance is the strongest layout signal).
    if len(data) < 1 or data[0] != 0x00:
        return None
    if len(data) < 17:
        return None
    version = data[0]
    vendor_tag = data[1]
    record_type = data[2]
    variant = "A" if vendor_tag == 0x00 else "B"
    chunk_3_10 = bytes(data[3:10])
    triplet = (data[13], data[14], data[15])
    nonzero = sum(1 for b in data[2:] if b != 0)
    density = round(nonzero / max(len(data) - 2, 1), 2)
    return Diag0x1589(
        log_time=log_time,
        version=version,
        vendor_tag=vendor_tag,
        record_type=record_type,
        variant=variant,
        chunk_3_10=chunk_3_10,
        marker_10=data[10],
        marker_11=data[11],
        marker_12=data[12],
        triplet=triplet,
        reserved_16=data[16],
        data_density=density,
        payload_size=len(data),
        body_raw=bytes(data[17:]),
    )
