"""0x14B0 — 166B fixed (LOG_GNSS_DATA_14B0, #N).

Split from gnss_nav_db.py per #N tier-3.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_MOBISENS_OUTPUT_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        LOG_SENSOR_MOBISENS_OUPUT
            source: qxdm_3_12_714_2017_diag_log_codes
        RESERVED
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


@dataclass
class Diag0x14B0:
    """GNSS data report (0x14B0) — 166 bytes fixed size.

    Clean-room RE across 6 DLF captures / 4 QCA generations (1514 records
    total, 2026-04-19 pass 3 adds em7511/MDM9650, #N):

        [0]        u8   version = 0x32 (50) — const across all captures
        [1:4]      3B   counter_block — per-record counter (monotonic-ish,
                        exact encoding still opaque; low byte wraps fast)
        [4:7]      3B   build_marker — per-chipset firmware-generation
                        fingerprint (stable across all records of a single
                        capture, differs between firmware versions):
                          EP06A  (MDM9x07) : 13 6e 09
                          EG18-NA(MDM9x07) : 1f 6d 09  (some variants 23 6d 09)
                          MC7455 (MDM9x30) : 1e 6e 09
                          LM960  (SDX55)   : 23 6d 09
                          FN980m (SDX55)   : 1f 6d 09
                          EM7511 (MDM9650) : 00 6f 09
                        Byte [6]=0x09 is constant across all generations.
        [7:11]     f32  value_a — small positive float, range
                        ~6.2e-4 .. 0.534 across fixtures (semantics TBD;
                        possibly a clock-jitter or frequency-error estimate)
        [11:15]    f32  value_b — small positive float, range
                        ~0.054 .. 1.20 across fixtures (semantics TBD;
                        possibly a companion variance/confidence metric)
        [15]       u8   const = 0x00
        [16:20]    4B   const = ff ff ff ff (sentinel / unused slot marker)
        [20:111]   91B  zero-padding — all 0x00 across all 1221 records
        [111:115]  f32  lead_f32 — small-to-large positive float
                        (range ~3e-9 .. 9000 across fixtures; likely a
                        magnitude/scale indicator — varies per-record on
                        most captures, const-ish on MC7455 RRLP-idle)
        [115]      u8   tag_05 = 0x05  (const all)
        [116]      u8   reserved = 0x00  (const all)
        [117:121]  f32  param_5 — discrete values in {2,3,5,10,20}
        [121]      u8   tag_01 = 0x01  (const all)
        [122:126]  f32  param_1 — discrete values {1e-3, 1e-9, 1, 9, 27, 30}
        [126]      u8   tag_02 = 0x02  (const all)
        [127:131]  f32  param_2 — discrete values {0.48, 1, 1.2, 3}
        [131]      u8   tag_03 = 0x03  (const all)
        [132:136]  f32  param_3 — variable float, range ~1.0 .. 5.0
        [136]      u8   tag_04 = 0x04  (const all)
        [137:141]  f32  param_4 — const=1.0 across 1221 records
        [141:165]  24B  trailing SV/slot status region — structurally
                        decoded 2026-04-19 pass 3 (em7511/MDM9650 +
                        existing fixtures) as **6 × 4-byte slots**:
                          slot_N at [141+4N:145+4N], for N in 0..5
                        Each slot's 4th byte (abs [144,148,152,156,160,164])
                        has **low nibble = 0 in 100% of em7511 non-zero
                        tails** (161/161) — this is a packed flag/status
                        nibble.  Exact semantic mapping per-slot (is it a
                        per-SV tracking entry? per-constellation summary?)
                        is still pending cross-capture correlation with
                        Diag0x1544 (GNSS SV Aggregate) / Diag0x148A (GNSS
                        SV Status) in the same epoch.
        [165]      u8   tail_trailer — 1-byte epilogue (per-record varies,
                        unique=60 on em7511; semantics TBD)

    The tag bytes at [115], [116], [121], [126], [131], [136] are 100 %
    stable across **1514 records** spanning EP06A (MDM9x07), EG18-NA
    (MDM9x07), MC7455 (MDM9x30), LM960 (SDX55), FN980m (SDX55) and
    EM7511 (MDM9650) — this is clearly a fixed GNSS configuration /
    parameter frame (tags 1-5 identify the 5 tagged parameter slots).

    Trailing tail structure (6-slot × 4-byte layout, v5):
      - ``tail_slots``: tuple of 6 × 4-byte blocks (slot_0..slot_5)
        occupying [141:165]; each slot's byte[3] has low nibble = 0 in
        100% of em7511 non-zero tails (161/161) — only the high nibble
        of byte[3] carries state information
      - ``tail_trailer``: u8 at [165]

    Per-slot semantics (which constellation/SV each slot maps to, and
    what the high nibble of byte[3] encodes) remain TBD — epoch
    correlation of 233 paired 14B0+1477 records from the 2026-04-19
    highsignal capture showed no simple SV-count or CN0 mapping.

    References: field layout derived solely from byte-variance analysis
    of the fixtures listed above; no external Qualcomm/OEM sources
    were consulted for this parser.
    """
    log_time: int
    version: int
    counter_block: bytes   # [1:4] 3-byte per-record counter (raw)
    build_marker: bytes    # [4:7] 3-byte per-chipset firmware fingerprint
    value_a: float         # [7:11] f32
    value_b: float         # [11:15] f32
    reserved_15: int       # [15] const 0x00
    sentinel_16_20: bytes  # [16:20] const 0xffffffff
    lead_f32: float        # [111:115] f32
    tag_05: int            # [115] const 0x05
    reserved_116: int      # [116] const 0x00
    param_5: float         # [117:121] f32
    tag_01: int            # [121] const 0x01
    param_1: float         # [122:126] f32
    tag_02: int            # [126] const 0x02
    param_2: float         # [127:131] f32
    tag_03: int            # [131] const 0x03
    param_3: float         # [132:136] f32
    tag_04: int            # [136] const 0x04
    param_4: float         # [137:141] f32
    tail_slots: tuple      # 6 × 4-byte blocks [141:165] — slot[N] at [141+4N:145+4N]
    tail_trailer: int      # u8 at [165]
    payload_size: int

    @property
    def counter(self) -> int:  # backward-compat with v2 field layout
        """Compatibility alias: legacy ``counter`` = first byte of counter_block."""
        return self.counter_block[0] if self.counter_block else 0

    @property
    def sub_counter(self) -> int:  # backward-compat
        """Compatibility alias: legacy ``sub_counter`` = second byte of counter_block."""
        return self.counter_block[1] if len(self.counter_block) > 1 else 0

    @property
    def const_block(self) -> bytes:
        """Compatibility alias: legacy ``const_block`` = counter_block[2]|build_marker."""
        # Reconstructs the v2 4-byte [3:7] slice (counter low-high boundary + marker)
        return bytes([self.counter_block[2] if len(self.counter_block) > 2 else 0]) + self.build_marker

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x14B0',
            'log_time': self.log_time,
            'version': self.version,
            'counter': self.counter,
            'sub_counter': self.sub_counter,
            'counter_block_hex': self.counter_block.hex(),
            'build_marker_hex': self.build_marker.hex(),
            'const_block_hex': self.const_block.hex(),
            'value_a': self.value_a,
            'value_b': self.value_b,
            'lead_f32': self.lead_f32,
            'param_1': self.param_1,
            'param_2': self.param_2,
            'param_3': self.param_3,
            'param_4': self.param_4,
            'param_5': self.param_5,
            'tag_01': self.tag_01,
            'tag_02': self.tag_02,
            'tag_03': self.tag_03,
            'tag_04': self.tag_04,
            'tag_05': self.tag_05,
            'tail_slots_hex': [s.hex() for s in self.tail_slots],
            'tail_trailer': self.tail_trailer,
            'payload_size': self.payload_size,
        }


@register(
    0x14B0, domain="gnss",
    name="0x14B0",
    description="GNSS data report (0x14B0) — 166B fixed, full decode: header + 6-slot tail + trailer (#N)",
    version=6,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room RE across 1514 records from EP06A + EG18-NA (MDM9x07) + "
        "MC7455 (MDM9x30) + LM960 + FN980m (SDX55) + EM7511 (MDM9650) DLFs "
        "2026-04-17/2026-04-19 (#N pass 3/4); trailing_raw removed v5. "
        "v6 (2026-05-11, #N audit follow-up — Wave 3 G1): added byte-0 "
        "version-byte hard gate (version == 0x32 across all 1514 corpus "
        "records / 6 chipsets / 4 QCA generations) before the tail-slice "
        "read at [141:166]. Audit flagged 'tail = bytes(data[141:166]) "
        "first' as the silent-mis-parse hazard — byte 0 was never read or "
        "validated. Also added layer-2 field_invariants on version + "
        "payload_size and the 6 constant tag bytes."
    ),
    source_url="",
    issues=(),
    field_invariants={
        # v6 (2026-05-11, #N audit follow-up): byte 0 is 0x32 across
        # 1514 records / 6 chipsets — single-value version. The 6 tag
        # bytes are corpus-constant in #N RE; promoted to layer-2.
        "version": {"enum": [0x32]},
        "payload_size": {"enum": [166]},
        "tag_05": {"enum": [0x05]},
        "tag_01": {"enum": [0x01]},
        "tag_02": {"enum": [0x02]},
        "tag_03": {"enum": [0x03]},
        "tag_04": {"enum": [0x04]},
    },
)
def parse_0x14b0(log_time: int, data: bytes) -> Diag0x14B0 | None:
    """Parse LOG_GNSS_DATA_14B0 (166B fixed)."""
    if len(data) < 141:
        return None
    # v6 (#N audit follow-up): hard gate on version byte before tail
    # slice read. Audit flagged 'tail = bytes(data[141:166]) first' as
    # the silent-mis-parse hazard. Corpus: 1514 records / 6 chipsets all
    # have version == 0x32.
    if data[0] != 0x32:
        return None
    tail = bytes(data[141:166]) if len(data) >= 166 else bytes(data[141:]).ljust(25, b'\x00')
    tail_slots = tuple(tail[i:i+4] for i in range(0, 24, 4))
    tail_trailer = tail[24] if len(tail) >= 25 else 0
    return Diag0x14B0(
        log_time=log_time,
        version=data[0],
        counter_block=bytes(data[1:4]),
        build_marker=bytes(data[4:7]),
        value_a=unpack_from('<f', data, 7)[0],
        value_b=unpack_from('<f', data, 11)[0],
        reserved_15=data[15],
        sentinel_16_20=bytes(data[16:20]),
        lead_f32=unpack_from('<f', data, 111)[0],
        tag_05=data[115],
        reserved_116=data[116],
        param_5=unpack_from('<f', data, 117)[0],
        tag_01=data[121],
        param_1=unpack_from('<f', data, 122)[0],
        tag_02=data[126],
        param_2=unpack_from('<f', data, 127)[0],
        tag_03=data[131],
        param_3=unpack_from('<f', data, 132)[0],
        tag_04=data[136],
        param_4=unpack_from('<f', data, 137)[0],
        tail_slots=tail_slots,
        tail_trailer=tail_trailer,
        payload_size=len(data),
    )
