"""0x14A6 — split from gnss_nav_db.py per #N tier-3.

See module body for the per-code RE history and field map.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_CGPS_SM_EPH_RANDOMIZATION_INFO_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        RESERVED
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


# --- #N ground-truth recipe -------------------------------------------
# 0x14A6 is a GNSS per-SV ephemeris snapshot: a 12-slot table of (sv_id,
# iode) plus SV-count fields. sv_id grounds against the modem's NMEA GSV PRN
# set under a real sky fix (HW-VERIFIED 2026-06-11, sv_id == GPS PRN). The
# per-SV `iode` scalar was previously guessed as C/N0 (`cno_metric`); the
# F3-grounded #N analysis refuted that (frozen-per-session u8, reaches 235;
# real C/N0 lives in the co-temporal `mc_glodebits`/`mc_meas` F3). IODE has NO
# NMEA source — ground it against a RINEX .nav ephemeris IODE per PRN or a
# 0x99/QSR4 F3 IODE print, NOT GSV SNR. Authored offline (3ccc playbook).
# --- end #N recipe ----------------------------------------------------


# ---------------------------------------------------------------------------
# 0x14A6 — GNSS per-SV CNo snapshot (151B fixed) (#N)
# ---------------------------------------------------------------------------
# Corpus: 3195 records / 151B fixed / 12 chipset+firmware pairs (2026-04-21).
#
# Full-byte decode (every byte named — zero body_raw):
#   [0]      u8  version = 2 (constant 3195/3195)
#   [1]      u8  flag_1 ∈ {0, 1}
#   [2:10]   8B  stats_header — 8 per-family status bytes
#   [10]     u8  reserved_10 = 0 (constant across RE corpus + EM7565).
#   [11:13]  u16 nav_state (LE) — RE'd in #N. 0x0000 (clear) or 0x0110
#                (set: byte[11]=0x10, byte[12]=0x01). Zero across the entire
#                3195-record cross-chipset RE corpus, but on Sierra EM7565
#                SWI9X50C it is a **latching GNSS receiver-state / nav-
#                maturity flag**: in the gnss_comparison_2026-06-06 capture
#                it transitions exactly ONCE (164 clear → 175 set, in
#                capture-time order) and never reverts. It is orthogonal to
#                the SV-count fields — two record shapes with byte-identical
#                counts (fam=fix=trk=6, subset=0, flag_15=0) differ only in
#                nav_state (12 clear vs 30 set), which rules out any "derived
#                from counts" reading. The clear→set edge coincides with the
#                receiver maturing from initial GPS-only acquisition (fix=5)
#                toward steady-state navigation (fix up to 7, tracked up to
#                8); C/N0 is comparable across both states so it is not a
#                signal-quality gate. Value is kept raw (size-invariance ≠
#                format-invariance) — a future capture may show other values.
#                Cross-modem scope (#N, <redacted-ref>): nav_state is
#                **EM7565-build-specific**. Across all 10 in-corpus EM7511
#                captures (1271 records, BOTH SWI9X50C_01.08.04.00 and
#                01.14.22.00 firmwares) offsets [11]/[12] are 0x00 in 1271/1271
#                — even though EM7511 is the same MDM9x50-class silicon and the
#                same SWI9X50C firmware family. So the flag is emitted only by
#                the EM7565 build's GNSS stack, not by the chipset family.
#   [13]     u8  reserved_13 = 0 (constant across RE corpus + EM7565).
#   [14]     u8  num_sv_family_a ∈ {0, 4, 5, 6, 8}
#   [15]     u8  flag_15 ∈ {0, 1}
#   [16]     u8  num_sv_fix ∈ {0..11} — sv-count-like field.  Matches the
#                populated-slot count on 2295/3195 records (72%); on the
#                remainder, populated is higher than byte[16] (typical
#                range: byte[16] < populated ≤ byte[18]).  Semantic
#                interpretation: count of SVs included in the current
#                fix, vs byte[18] which is the tracked-SV total.
#   [17]     u8  num_sv_subset ∈ {0..9}
#   [18]     u8  num_sv_tracked ∈ {0..12} — upper bound on populated
#                slot count; populated slots ≤ byte[18] on 3195/3195.
#   [19]     u8  aux_19
#   [20]     u8  aux_20
#   [21]     u8  fw_tag ∈ {0, 0x6d, 0x6e, 0x6f, 0x74, 0x75, 0x7a} — same
#                build-channel tag that 0x1509 exposes at its byte[1]: cross-
#                parser invariant. ASCII letters 'm'/'n'/'o'/'t'/'u'/'z'
#                (sierra SWIX65C contributed 't', #N; sierra EM7565
#                SWI9X50C contributed 'u', #N/<redacted-ref>; quectel EG18-NA
#                EG18NAPAR01A06M4G/MDM9640 contributed 'z', #N — the tag is
#                thus neither chipset- nor vendor-locked).
#   [22]     u8  sub_type ∈ {0, 9} (= 0 only on empty records)
#   [23:71]  48B sv_slots — 12 slots × 4 bytes each:
#                - slot[i][0:2]  u16 LE sv_id
#                - slot[i][2:4]  u16 LE iode (was `cno_metric` ≤v8; #N)
#                (sv_id and iode values fit in u8 range, hence the
#                 "every other byte is zero" pattern.)
#                Populated count matches byte[16] on 3195/3195 records.
#   [71:151] 80B reserved_tail = 0 (constant 3195/3195)

@dataclass
class GnssSvCno14A6Slot:
    """One slot in the 12-slot SV table of 0x14A6.

    (Class name retained for API stability; the ``Cno`` in it is historical —
    the per-SV scalar was renamed ``cno_metric`` → ``iode`` in v9, see #N.)
    """
    sv_id: int         # u16 LE
    iode: int          # u16 LE (u8-range) — per-SV Issue Of Data, Ephemeris (#N)

    @property
    def cno_metric(self) -> int:
        """Deprecated back-compat alias for :attr:`iode`.

        The field was named ``cno_metric`` (a C/N0 guess) from v2's structural
        RE. The 2026-07-14 F3-grounded analysis (#N) refuted C/N0: the scalar
        is frozen per-SV across whole captures (0-1 changes over 600-1259
        records, in stationary *and* moving drives) and reaches raw 235 —
        impossible for any dB-Hz scale — while co-temporal F3 (`mc_glodebits`
        CNo / `mc_meas` G_CNo) carries the *actual*, time-varying C/N0. The
        frozen-until-eph-refresh u8 behaviour + the canonical name
        ``LOG_CGPS_SM_EPH_RANDOMIZATION_INFO_C`` identify it as IODE. Alias
        kept so existing consumers keep working; new code should read ``iode``.
        """
        return self.iode

    @property
    def is_populated(self) -> bool:
        return self.sv_id != 0 or self.iode != 0


@dataclass
class Diag0x14A6:
    """GNSS per-SV ephemeris (IODE) snapshot (0x14A6) — 151B fixed, fully decoded.

    Renamed from the pre-v2 stub (which called the same class GnssData14A6
    but only exposed version/sub_type/counter/body_raw).  The post-v2
    decode exposes every byte as a named field or structured slot.
    """
    log_time: int
    version: int
    flag_1: int
    stats_header: bytes      # [2:10]
    reserved_10: int         # [10]    constant 0
    nav_state: int           # [11:13] u16 LE — latching nav-maturity flag (#N)
    reserved_13: int         # [13]    constant 0
    num_sv_family_a: int     # [14]
    flag_15: int             # [15]
    num_sv_fix: int          # [16]  see module docstring for semantics
    num_sv_subset: int       # [17]
    num_sv_tracked: int      # [18]  upper bound on populated slots
    aux_19: int              # [19]
    aux_20: int              # [20]
    fw_tag: int              # [21]
    sub_type: int            # [22]
    sv_slots: list[GnssSvCno14A6Slot]  # 12 slots from [23:71]
    reserved_tail: bytes     # [71:151]
    payload_size: int

    @property
    def counter(self) -> int:
        """Back-compat alias (prior stub named byte[2] as `counter`)."""
        return self.stats_header[0]

    @property
    def reserved_mid(self) -> bytes:
        """Back-compat: the [10:14] blob, pre-#N a single `reserved_mid`
        field. Now reconstructed from reserved_10 / nav_state / reserved_13
        so existing consumers (and the zero-region tests on the RE-corpus
        fixtures) keep working."""
        return bytes((self.reserved_10,)) + \
            self.nav_state.to_bytes(2, 'little') + \
            bytes((self.reserved_13,))

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x14A6',
            'log_time': self.log_time,
            'version': self.version,
            'flag_1': self.flag_1,
            'stats_header': self.stats_header.hex(),
            # reserved_mid_zero now means the *truly*-reserved bytes [10] and
            # [13] are zero; [11:13] is the named nav_state field (#N).
            'reserved_mid_zero': self.reserved_10 == 0 and self.reserved_13 == 0,
            'nav_state': self.nav_state,
            'num_sv_family_a': self.num_sv_family_a,
            'flag_15': self.flag_15,
            'num_sv_fix': self.num_sv_fix,
            'num_sv_subset': self.num_sv_subset,
            'num_sv_tracked': self.num_sv_tracked,
            'aux_19': self.aux_19,
            'aux_20': self.aux_20,
            'fw_tag': self.fw_tag,
            'sub_type': self.sub_type,
            'sv_slots': [
                # `iode` is the canonical key (v9, #N). `cno_metric` is a
                # deprecated back-compat mirror for existing consumers (e.g. the
                # 0x147D f32-outlier `_cno_summary` walker + external JSON
                # readers); it carries the identical value and will be dropped
                # once those consumers migrate to `iode`.
                {'sv_id': s.sv_id, 'iode': s.iode, 'cno_metric': s.iode}
                for s in self.sv_slots if s.is_populated
            ],
            'reserved_tail_zero': self.reserved_tail == b'\x00' * 80,
            'payload_size': self.payload_size,
        }


@register(
    0x14A6, domain="gnss",
    name="0x14A6",
    description="GNSS per-SV ephemeris (IODE) snapshot (0x14A6) — 151B fixed, fully decoded",
    version=9,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room RE from 3195-record cross-chipset corpus (2026-04-21): "
        "EG12-GT, eg18na SDX20 V2, eg25g MDM9207, em7511 MDM9650, ep06a MDM9x07, "
        "fn980 SDX55, lm960 SDX20 (5 firmware gens), rm500q SDX65. "
        "12 × 4-byte per-SV table at [23:71] with populated count at byte[16]. "
        "Every byte named; body_raw eliminated. "
        "v3 (2026-05-11, #N audit follow-up — Wave 3 G1): added byte-0 "
        "version-byte hard gate (version == 0x02 across all 3195 corpus "
        "records / 9 chipsets) before the SV-slot loop at offset 23+. The "
        "audit flagged 'SV-slot loop reads bytes 23+ first' as the silent-"
        "mis-parse hazard. field_invariants declares version=[0x02] and "
        "payload_size=[151]. NOTE: reserved_mid and reserved_tail are "
        "verified zero across 3195/3195 corpus records in tests but are "
        "NOT enforced via field_invariants — registry layer-2 enum gating "
        "operates on scalar fields, not bytes-type fields. "
        "v4 (2026-05-28, #N): widened fw_tag enum to include 0x74 "
        "('t') after 300 invariant-violation records from Sierra EM9291 "
        "SWIX65C_02.17.08.00 (SDX65). The 'm'/'n'/'o'/'t' progression "
        "matches the ASCII-letter-tag interpretation of fw_tag — Sierra "
        "EM929x adds a new family letter; cross-parser invariant with "
        "0x1509 byte[1] is preserved (both widen together). "
        "v5 (2026-06-06, #N, <redacted-ref>): widened fw_tag enum to "
        "include 0x75 ('u') after 339/339 invariant-violation records "
        "from Sierra EM7565 SWI9X50C_01.08.04.00 (MDM9x30) in the "
        "gnss_comparison_2026-06-06 capture. 'u' is the next ASCII letter "
        "after 't', continuing the m/n/o/t/u build-channel progression. "
        "payload_size=151 and version=0x02 both held, so the fw_tag "
        "widening is sound. The record is NOT fully structurally identical, "
        "though: 175/339 EM7565 records carry 0x10/0x01 at offsets 11-12 — "
        "inside the region documented as reserved_mid (zero across the 3195 "
        "RE corpus). That divergence is tracked separately in #N and does "
        "not affect fw_tag. "
        "The paired 0x1509 corroboration is CONFIRMED: the same EM7565 "
        "capture emitted 18 × 0x1509 records, all 18 carrying byte[1]=0x75 "
        "('u') — an exact match for this code's fw_tag, so the cross-parser "
        "invariant holds and both codes widen together as in the v4 't' "
        "case. 0x1509's byte[1] documented value set is widened to include "
        "'u' to match (verified via the em7565.dlf .scan.json offset_dist). "
        "v6 (2026-06-06, #N): RE'd the [11:13] sub-region of the former "
        "reserved_mid blob. Split reserved_mid[10:14] into reserved_10 (u8, "
        "constant 0), nav_state (u16 LE @ [11:13]) and reserved_13 (u8, "
        "constant 0). nav_state is zero across the entire 3195-record RE "
        "corpus but on Sierra EM7565 SWI9X50C it is a latching GNSS receiver-"
        "state / nav-maturity flag: in the gnss_comparison_2026-06-06 capture "
        "(339 records) it toggles exactly once (164×0x0000 → 175×0x0110, in "
        "capture-time order) and never reverts, and it is orthogonal to the "
        "SV-count fields (two record shapes with identical fam=fix=trk=6 / "
        "subset=0 / flag_15=0 split 12 clear vs 30 set on nav_state alone). "
        "Value kept raw, NOT enum-gated (it is a value field, not a format "
        "discriminator — version byte already gates layout). reserved_mid is "
        "retained as a back-compat property. Added gnss_14a6_em7565.bin "
        "fixture (fix=7, fw_tag=0x75, nav_state=0x0110). "
        "v7 (2026-06-11, #N): first per-modem HW validation (#N) — Quectel "
        "RM520N-GL @ RM520NGLAAR03A03M4G (SDX62, <redacted-ref>, host t480, live 3D "
        "fix). sv_slots.sv_id VERIFIED: 10/10 GPS-range sv_id contained in the GSV "
        "GPS PRN set (sv_id == GPS PRN, no offset). num_sv_fix / num_sv_tracked / "
        "cno_metric → PARTIAL (GPS-family counts ~10, not the multi-constellation "
        "QGPSLOC nsat / 53-SV GSV total; cno raw→dB-Hz scale unrecovered). "
        "v8 (2026-07-07, #N): widened fw_tag enum to include 0x7a ('z') "
        "after Quectel EG18-NA (EG18NAPAR01A06M4G, MDM9640) surfaced 290/290 "
        "invariant-violation records with fw_tag=122 in the gnss_comparison_"
        "2026-07-07 4-stream capture (eg18na.corpus_sweep.yaml). This is the "
        "first NON-Sierra contributor to the tag ('m'/'n'/'o'/'t'/'u' were all "
        "Sierra/Quectel-QCA builds; 'z' from Quectel MDM9640 confirms the tag "
        "is a generic Qualcomm firmware-family letter, neither chipset- nor "
        "vendor-locked). payload_size=151 and version=0x02 both held (0 parse "
        "errors — pure enum rejection), so the format is identical; build-"
        "channel tag only. Explicit-value widening (not whole-range) keeps the "
        "invariant meaningful. Cross-parser 0x1509 CORROBORATION: the same "
        "capture emitted 41 × 0x1509 records, all 41 carrying byte[1]=0x7a "
        "('z') — exact match, so both codes widen together as in the v4/v5 "
        "cases (0x1509's byte[1] doc set widened to 'z'; it is doc-only there, "
        "not layer-2 gated). SEPARATE finding for #N: all 290 EG18-NA "
        "records also carry nav_state=0x0010 at [11:13] (non-zero on a non-"
        "EM7565 chipset — a new nav_state data point, tracked out of this "
        "fw_tag-scoped change). "
        "v9 (2026-07-14, #N): RENAMED per-SV scalar sv_slots.cno_metric → "
        "sv_slots.iode. The v2 structural RE named the u16 at slot[2:4] "
        "'cno_metric' (a C/N0 guess) with no signal-quality ground truth; the "
        "F3-grounded <redacted-ref> analysis refutes C/N0. Evidence: the scalar is "
        "FROZEN per-SV across whole captures (slot-set changes/record = 0/1104 "
        "on the RM520N-GL R03A04 F3 characterization capture, 1/1259 on a "
        "MOVING R03A03 drive, 1/605 on EM9291 — the single change is always the "
        "fix→no-fix transition), whereas live C/N0 jitters every 1 Hz epoch; "
        "and it reaches raw 235 (EM9291), impossible for any dB-Hz scale "
        "(ceiling ~50). The co-temporal 0x79 F3 carries the ACTUAL time-varying "
        "C/N0 (mc_glodebits 'GLOID n CNo v' at 0.1 dB-Hz; mc_meas G_CNo/S_CNo) "
        "— orthogonal to these frozen values. Frozen-until-eph-refresh u8 + the "
        "canonical name LOG_CGPS_SM_EPH_RANDOMIZATION_INFO_C identify it as "
        "IODE (Issue Of Data, Ephemeris). `cno_metric` retained as a deprecated "
        "back-compat property + to_dict mirror key. IODE label is corpus-"
        "behaviour-inferred; a 0x99/QSR4 F3 IODE per-PRN print (needs GUID-"
        "matched qdb) or a multi-hour value-step-at-refresh capture would "
        "upgrade it from inferred to confirmed. No structural/byte change; "
        "field name + semantics only."
    ),
    source_url="",
    issues=(),
    primary_issue=None,
    # version, flag_1, stats_header, reserved_10, nav_state, reserved_13,
    # num_sv_family_a, flag_15, num_sv_fix, num_sv_subset, num_sv_tracked,
    # aux_19, aux_20, fw_tag, sub_type, sv_slots, reserved_tail,
    # payload_size — 151/151 bytes named across 12-chipset corpus + EM7565
    # (#N, #N).
    fields_identified=18,
    fields_parsed=18,
    field_invariants={
        # v3 (2026-05-11, #N audit follow-up): byte 0 is 0x02 across
        # 3195 records / 9 chipsets — single-value version. Layer-2
        # protection against any future drift; parser-body gate is the
        # primary defense.
        "version": {"enum": [2]},
        "payload_size": {"enum": [151]},
        # 2026-05-23 <redacted-ref>: tighten layer-2 on two other documented-
        # constant header bytes that were named in v2 RE but never
        # enum-locked. fw_tag (byte[21]) is a cross-parser build-channel
        # invariant — same value space as 0x1509's byte[1] per the
        # 2026-04-21 cross-parser observation; sub_type (byte[22]) is
        # the populated-vs-empty record discriminator. The "we know
        # WHAT this byte IS" closure stance means every byte we've
        # documented as enum-bounded should be enum-bounded at layer 2.
        # 2026-05-28 #N: added 0x74 ('t') after EM9291 SWIX65C
        # corpus surfaced 300 records with fw_tag=116. The Sierra SDX65
        # build channel uses 't', sequential with the existing 'm'/'n'/'o'
        # set.
        # 2026-06-06 #N (<redacted-ref>): added 0x75 ('u') after EM7565
        # SWI9X50C_01.08.04.00 (MDM9x30) surfaced 339/339 records with
        # fw_tag=117. Next ASCII letter after 't'; payload_size/version
        # unchanged so the record format is identical — build-channel tag
        # only. Paired 0x1509 NOT widened (EM7565 emitted no 0x1509).
        # 2026-07-07 #N (v8): added 0x7a ('z') after Quectel EG18-NA
        # (EG18NAPAR01A06M4G / MDM9640) surfaced 290/290 records with
        # fw_tag=122 — first non-Sierra contributor. Paired 0x1509 DID
        # co-occur here (41 records, all byte[1]=0x7a), so both widen
        # together (0x1509 doc-only, fw_tag not gated at layer-2 there).
        "fw_tag": {"enum": [0, 0x6d, 0x6e, 0x6f, 0x74, 0x75, 0x7a]},
        "sub_type": {"enum": [0, 9]},
    },
)
def parse_0x14a6(log_time: int, data: bytes) -> Diag0x14A6 | None:
    if len(data) != 151:
        return None
    # v3 (#N audit follow-up): hard gate on version byte before the
    # SV-slot loop. Audit flagged this as 'SV-slot loop reads bytes 23+
    # first' — i.e. byte 0 was never validated. Corpus: 3195 records / 9
    # chipsets all have version == 0x02.
    if data[0] != 0x02:
        return None
    slots: list[GnssSvCno14A6Slot] = []
    for i in range(12):
        base = 23 + i * 4
        slots.append(GnssSvCno14A6Slot(
            sv_id=unpack_from('<H', data, base)[0],
            iode=unpack_from('<H', data, base + 2)[0],
        ))
    return Diag0x14A6(
        log_time=log_time,
        version=data[0],
        flag_1=data[1],
        stats_header=bytes(data[2:10]),
        reserved_10=data[10],
        nav_state=unpack_from('<H', data, 11)[0],
        reserved_13=data[13],
        num_sv_family_a=data[14],
        flag_15=data[15],
        num_sv_fix=data[16],
        num_sv_subset=data[17],
        num_sv_tracked=data[18],
        aux_19=data[19],
        aux_20=data[20],
        fw_tag=data[21],
        sub_type=data[22],
        sv_slots=slots,
        reserved_tail=bytes(data[71:151]),
        payload_size=len(data),
    )
