"""0x1C90 — GNSS LocEng stub (legacy `GnssLocEng1C90`, 6693B fixed, SDX62 RM520N-GL).

Split from `lte_misc.py` per #N tier-3 batch 20.

Promoted from the `_simple_parser` factory call so the ID-only naming
convention applies (registry name "0x1C90", class `Diag0x1C90`, type
string `Diag0x1C90`). Structural layout unchanged: byte 0 version = 0x06
on the SDX62 RM520N-GL corpus, u32@4 config_word, density + size.
Tracked under #N — see test_5gofast_2026_04_23.py::Test1C90 for the
single-modem fixture coverage.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_GNSS_CLIENT_API_SV_REPORT
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.parsers.diag_0x1384 import parse_nmea_sentence
from diaggrok.parsers.diag_0x1cb2 import _verify_nmea_checksum
from diaggrok.registry import register

# $ + talker(2) + type(3) , body ... *XX. The body class excludes $, \r, \n so
# a match cannot run past a sentence boundary into the next sentence or into
# binary. Gated by NMEA 0183 XOR checksum so binary-float noise that happens to
# match the shape is rejected (the corpus walk found ZERO checksum-invalid
# matches across 25,052 sentences — the shape+checksum pair is precise).
_NMEA_RE = re.compile(rb"\$[A-Z]{2}[A-Z]{3},[\x20-\x7e]*?\*[0-9A-Fa-f]{2}")


def _extract_nmea(data: bytes) -> list[str]:
    """Checksum-valid NMEA sentences embedded in the LocEng snapshot body.

    0x1C90 is a heterogeneous LocEng state dump; the GNSS body region carries
    whole, checksum-valid NMEA across every constellation (GP/GL/GA/GB/GQ/GN).
    Presence is fractional and NOT keyed on ``seq_counter`` (a seq=0 record can
    carry 100+ sentences) — consistent with seq_counter being a counter, not a
    format key (#N v4). Returned in body order.
    """
    out: list[str] = []
    for m in _NMEA_RE.finditer(data):
        s = m.group().decode("ascii", "replace")
        if _verify_nmea_checksum(s):
            out.append(s)
    return out


@dataclass
class Diag0x1C90:
    """0x1C90 — GNSS Location-Engine diagnostic snapshot (legacy `GnssLocEng1C90`, 6693B fixed).

    Content identity (2026-05-31 ASCII-lens re-walk, 13,103 records / 100%
    parse, all version 0x06 / 6693 B). Each record is a heterogeneous
    LocEng state dump that embeds, in plaintext:

    * the modem's **NMEA output** — full, checksum-valid sentences across
      every constellation (``$GPGGA``/``$GPRMC``/``$GxGSA``/``$GxVTG``/
      ``$GxGSV``/``$GNGNS`` for GP/GL/GA/GB/GQ/GN talkers);
    * the **``+QGPSLOC:``** Quectel AT location response;
    * **``+QTEMP:``** Quectel AT thermal readings (e.g.
      ``"modem-sdr0-pa1","0"``, ``"aoss-0-usr","29"``);
    * Linux **``thermal_zone*`` / ``cooling_device*``** sysfs node names;
    * f3-debug trace lines (``cmd name:+QGPSLOC``, ``w pkt addr=0x...``,
      ``ql_add_response() : used=N``) and float32 binary arrays.

    ⚠️ **Retracted: payload[1] is NOT a format-dispatch key.** The v3
    parser (and the 2026-05-08 finding) modelled byte 1 as a "subtype"
    selecting one of {0x00, 0x01, 0x26, 0x2E}. The 2026-05-31 re-walk
    observes **51 distinct values spanning 0x00..0x38** and shows byte 1
    is a **monotonically-increasing per-record sequence/block counter**
    (it climbs within a capture and resets on GNSS-engine restart — visible
    in the warm-restart / sim-cycle edge-case captures). A format tag would
    give 0%/100% NMEA-presence per value; instead mid-range values are
    *fractional* (0x10→18%, 0x1d→42%, 0x1e→54%, 0x1c→78%), which a
    discriminated union cannot produce. The byte is now named
    ``seq_counter``. Content tri-partitions by counter range: 0x00-0x01
    thermal header (no NMEA), 0x02-0x20 GNSS body (NMEA + QGPSLOC), and
    0x21-0x38 binary-float trailer (no NMEA).
    """
    log_time: int
    version: int
    seq_counter: int  # payload[1]: monotonic per-record counter (NOT a format key — #N v4)
    config_word: int
    data_density: float
    payload_size: int
    body_raw: bytes
    nmea_sentences: tuple[str, ...] = ()   # checksum-valid NMEA from the body (#N v5)
    nmea_talkers: tuple[str, ...] = ()      # distinct talker IDs present, sorted

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": "Diag0x1C90",
            "log_time": self.log_time,
            "version": self.version,
            "seq_counter": self.seq_counter,
            "config_word": self.config_word,
            "data_density": self.data_density,
            "payload_size": self.payload_size,
            "nmea_sentence_count": len(self.nmea_sentences),
            "nmea_talkers": list(self.nmea_talkers),
            "nmea_sentences": list(self.nmea_sentences),
            "body_raw": self.body_raw,
        }


EXPECTED_VERSION_1C90 = 0x06


# Ground-truth recipe (#N). RM520N-GL SDX62 emits v0x06 (6693B) — ~38k
# records. Names-block: LOG_GNSS_CLIENT_API_SV_REPORT (GNSS subsystem → GNSS
# AT vocab). The record embeds, in plaintext, the modem's OWN checksum-valid
# NMEA output + the +QGPSLOC: AT response, so the cleanest ground is the
# modem's NMEA itself: AT+QGPSGNMEA / AT+QGPSLOC=2 should return the same
# sentences/fix the body carries co-temporally. Offline author.

@register(
    0x1C90, domain="gnss",
    name="0x1C90",
    description="0x1C90 — GNSS Location-Engine diagnostic snapshot (legacy GnssLocEng1C90, 6693B fixed, SDX62 RM520N-GL, byte0=0x06). v5 extracts the embedded checksum-valid NMEA (nmea_sentences/nmea_talkers, all constellations); also embeds +QGPSLOC/+QTEMP AT responses + thermal sysfs names; payload[1] is a per-record counter, NOT a format key.",
    version=5,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail="v5 (2026-06-01, <redacted-ref> ASCII-lens follow-up to 824a): structural extraction of the embedded NMEA into nmea_sentences (checksum-valid only) + nmea_talkers. Extractability walk (tools/diag_1c90_nmea_extract.py, 4,000 records / 10 captures): the 0x02-0x20 'gnss-body' seq band carries NMEA in 56% of records, 25,052 sentences ALL checksum-valid (0 invalid) across GP/GL/GA/GB/GQ/GN talkers (GSA/GSV/VTG/GNS/RMC/GGA). NMEA presence is fractional and NOT seq-band-gated (a seq=0 record carries 100+ sentences) — reinforcing the v4 seq_counter-is-a-counter finding — so extraction scans the whole body, not keyed on seq_counter. The $XXYYY,...*HH shape + NMEA-0183 XOR checksum gate rejected every binary-float false positive (float-trailer records: 0 matches). v4 (2026-05-31, <redacted-ref> ASCII-lens, 13,103 records / 100% parse, all v0x06 / 6693B): re-identified the body as a GNSS Location-Engine diagnostic snapshot (embedded checksum-valid NMEA across all constellations + +QGPSLOC + +QTEMP + thermal_zone/cooling_device sysfs + f3-debug). RETRACTED the v3 'payload[1] = subtype/format-dispatch key' model: byte 1 takes 51 distinct values (0x00..0x38) and is a monotonic per-record sequence/block counter (resets on GNSS-engine restart); mid-range NMEA-presence is fractional (0x1d→42%, 0x1e→54%), impossible for a discriminated union. Field renamed subtype→seq_counter. v3 (2026-05-21): version-byte enforcement; v2/v1 stub promotion per #N tier-3 batch 20.",
    source_url="",
    issues=(),
    fields_identified=5,
    fields_parsed=5,
    field_invariants={"version": {"enum": [EXPECTED_VERSION_1C90]}},
    # ASCII audit (#N slice 6 + #N v4): GNSS LocEng snapshot carrying
    # checksum-valid NMEA (GGA/RMC/GSA/VTG/GSV/GNS, all constellations),
    # +QGPSLOC/+QTEMP AT responses (config-token), thermal_zone/cooling_device
    # sysfs labels, and f3-debug lines (`ql_add_response() : used=12`,
    # `cmd name:+QGPSLOC`, `w pkt addr=0x...`).
    ascii_kinds=("nmea", "config-token", "label", "f3-debug"),
)
def parse_0x1c90(log_time: int, data: bytes) -> Diag0x1C90 | None:
    if len(data) < 2:
        return None
    version = data[0]
    if version != EXPECTED_VERSION_1C90:
        return None
    seq_counter = data[1]
    if len(data) >= 8:
        config_word = unpack_from('<I', data, 4)[0]
    else:
        config_word = 0
    if len(data) > 2:
        nonzero = sum(1 for b in data[2:] if b != 0)
        total = max(len(data) - 2, 1)
        density = round(nonzero / total, 2)
    else:
        density = 0.0
    nmea = _extract_nmea(data)
    talkers = tuple(sorted({s[:6] for s in nmea}))
    return Diag0x1C90(
        log_time=log_time,
        version=version,
        seq_counter=seq_counter,
        config_word=config_word,
        data_density=density,
        payload_size=len(data),
        body_raw=data[1:],
        nmea_sentences=tuple(nmea),
        nmea_talkers=talkers,
    )
