"""NR5G RRC OTA message parser (0xB821).

NR RRC Over-The-Air message log — the NR equivalent of LTE's 0xB0C0.
Contains ASN.1 PER-encoded NR RRC messages (SIB1, RRC Setup/Reconfiguration,
measurement reports, etc.).

Header layout per SCAT's ``diagnrlogparser.parse_nr_rrc`` (validation-only
reference at ``.venv-blackbox/lib/python3.13/site-packages/scat/parsers/
qualcomm/diagnrlogparser.py:275-419``). The pre-#N RE incorrectly read
byte[5] as ``channel_type`` and dispatched downstream decode on it. byte[5]
is actually ``rrc_rel_min`` (release minor); the real channel discriminator
is ``pdu_id`` at a version-keyed offset (byte[17] on v9, byte[16] on v12/v14,
byte[24] on v17+). The audit confirming this lives in #N; the fix
issue is #N.

Version 9 layout (SDX55 / RM500Q, Rel-15):
    [0:4]   u32  version (9)
    [4]     u8   rrc_release (15)         (SCAT: rrc_rel_maj)
    [5]     u8   rrc_rel_min              (was mislabeled channel_type)
    [6]     u8   bearer_id                (SCAT: rbid)
    [7:9]   u16  physical_cell_id
    [9:13]  u32  nr_arfcn
    [13:17] u32  sfn_subfn (LE u32; low 16 bits encode sfn<<4|slot)
    [17]    u8   pdu_id                   (channel discriminator)
    [18:22] u32  sib_mask
    [22:24] u16  msg_length
    [24:]   bytes msg_data

Version 12 / 14 layout (SDX55 EM9190, SDX62 RM520N v14):
    Same as v9 but sfn_subfn is 3 bytes ([13:16]) and pdu_id shifts to
    byte[16]. sib_mask at [17:21] (4 bytes), msg_length at [21:23],
    msg_data starts at offset 23.

Version 17 layout (SDX62 RM520N, Rel-16):
    [0:4]   u32  version (17)
    [4]     u8   rrc_release (16)
    [5]     u8   rrc_rel_min
    [6]     u8   bearer_id
    [7:9]   u16  physical_cell_id
    [9:17]  u64  cell_global_id (NCGI — SCAT decodes as 60-bit bitstring;
                  upper 32 bits are a constant 0x01300621 marker across the
                  observed corpus and the lower 28-32 bits carry the per-cell
                  identifier — full PLMN+marker decode pending)
    [17:21] u32  nr_arfcn
    [21:24] u24  sfn_subfn (3 bytes)
    [24]    u8   pdu_id                   (channel discriminator)
    [25:29] u32  sib_mask
    [29:31] u16  msg_length
    [31:]   bytes msg_data

Version 26 layout (SDX72 RG650V, Rel-17):
    Same as v17 through msg_length, plus 4 reserved bytes inserted between
    msg_length and msg_data — header grows 31→35. Observed at zero across
    the v26 corpus; SCAT's v23/v24/v26 struct exposes them as
    ``unk1/unk2/unk3/segment_id`` (RRC segmentation — segment_id values 1-7
    indicate a chunked PDU). Treated as opaque here.

Version 7 layout (early Rel-15):
    Same byte positions as v9 (24-byte header, msg_length at offset 22,
    pdu_id at byte[17]). SCAT does not handle pkt_ver=7; our coverage comes
    from QCAT-decoded ground-truth records in
    sources/qualcomm/community/tool_analysis_qcat/
        UlDl-90-9-1_signaling.txt.layers.yaml. byte[5] (``rrc_rel_min``) is
    a constant 0x41 across all four QCAT records. byte[17] (``pdu_id``)
    matches the SCAT v9 map for BCCH-BCH (pdu_id=1) and RRC-RECONF-COMPLETE
    (pdu_id=10), but the RADIO_BEARER_CONFIG record has byte[17]=0x18=24
    which is unmapped — the authoritative discriminator for v7 lives in the
    DLF outer-header byte 4 (per the .layers.yaml inner_dispatch table:
    0xED/0x43/0xA7/0x90 for MIB/RRC_RECONFIG/RADIO_BEARER_CONFIG/
    RRC_RECONFIG_COMPLETE respectively). This parser sees only the payload,
    so v7 channel_name is best-effort: it resolves when the pdu_id happens
    to match the v9 map and is empty otherwise.

Layout verified at 100% over the in-repo corpus and across 1,544+ DLF
records spanning EM9190 (SDX55), RM500Q (SDX55), RM520N-GL (SDX62), and
RG650V (SDX72): ``header_size + msg_length == record_size`` for every
record. Cross-chipset byte[24] constancy (audit step 4) is asserted by
tests against three independent v17 fixtures.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_NR5G_RRC_OTA_MSG
        source: qualcomm_qcat_trace_endc_rlf_scg_failure_2021_07_16 (authority: community)
    aliases:
        LOG_NR5G_RRC_OTA_PACKET
            source: qxdm_itemtype_list_zukgit_2025_04_03
        NR5G RRC OTA Packet
            source: qualcomm_qxdm_isf_filter_merge_perl_2020

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass, field
from struct import unpack_from
from typing import Any, Optional

from diaggrok.codes import LOG_NR5G_RRC_OTA_MSG
from diaggrok.registry import register
from diaggrok.parsers.nr5g_rrc_sib1_uper import decode_nr_sib1_uper
from diaggrok.parsers.nr5g_rrc_si import decode_nr_si
from diaggrok.parsers.nr5g_rrc_mib import decode_nr_mib
from diaggrok.parsers.nr5g_rrc_smc import decode_nr_security_mode_command
from diaggrok.parsers.nr5g_rrc_dlccch import decode_nr_dl_ccch
from diaggrok.parsers.nr5g_rrc_meas_report import decode_nr_measurement_report
from diaggrok.parsers.nr5g_rrc_reconfig import (
    decode_nr_meas_config,
    decode_nr_meas_config_direct,
)

# Per-version header sizes (bytes from start of payload to start of msg_data).
# v23 (0x17, SDX72 T99W640) shares the v26 layout exactly (NCGI-inserted, 35B
# header) — confirmed 86/86 corpus records by header_size + msg_length == len
# (#N). It differs from v26 only in the channel map (no RRC-RECONF shift).
_HEADER_SIZE = {7: 24, 9: 24, 12: 23, 14: 23, 17: 31, 23: 35, 26: 35}
# Per-version offset of msg_length u16 LE.
_MSG_LEN_OFFSET = {7: 22, 9: 22, 12: 21, 14: 21, 17: 29, 23: 29, 26: 29}
# Per-version offset of pdu_id u8 (the channel discriminator). v9-shape
# layouts put pdu_id directly after the 4-byte sfn_subfn; v12/v14 trim
# sfn_subfn to 3 bytes; v17+ insert NCGI before nr_arfcn and use a 3-byte
# sfn_subfn.
_PDU_ID_OFFSET = {7: 17, 9: 17, 12: 16, 14: 16, 17: 24, 23: 24, 26: 24}
# Per-version offset of sfn_subfn (u16-LE for the low 16 bits → sfn<<4|slot).
_SFN_SUBFN_OFFSET = {7: 13, 9: 13, 12: 13, 14: 13, 17: 21, 23: 21, 26: 21}
# Per-version offset of sib_mask u32 LE.
_SIB_MASK_OFFSET = {7: 18, 9: 18, 12: 17, 14: 17, 17: 25, 23: 25, 26: 25}

# SCAT's pdu_id → channel name maps, keyed by parser version. Five distinct
# tables in SCAT (rrc_type_map for pkt_ver in 0x09/0x0c, 0x0e, 0x11/0x13,
# 0x14/0x17/0x18, 0x1a). The maps differ: pdu_id=5 is PCCH on
# 0x09/0x0c/0x0e/0x11/0x13 but MCCH on 0x14/0x17/0x18/0x1a; PCCH shifts to 6
# in the latter group. v26 (0x1a) also shifts RRC-RECONF/RRC-RECONF-COMPLETE
# from 9/10 to 11/12.
_RRC_TYPE_MAP_PRE_MCCH = {
    1: 'BCCH-BCH', 2: 'BCCH-DL-SCH', 3: 'DL-CCCH', 4: 'DL-DCCH',
    5: 'PCCH', 6: 'UL-CCCH', 7: 'UL-CCCH1', 8: 'UL-DCCH',
    9: 'RRC-RECONF', 10: 'RRC-RECONF-COMPLETE',
}
_RRC_TYPE_MAP_V26 = {
    1: 'BCCH-BCH', 2: 'BCCH-DL-SCH', 3: 'DL-CCCH', 4: 'DL-DCCH',
    5: 'MCCH', 6: 'PCCH', 7: 'UL-CCCH', 8: 'UL-CCCH1', 9: 'UL-DCCH',
    11: 'RRC-RECONF', 12: 'RRC-RECONF-COMPLETE',
}
# 0x14/0x17/0x18 group (v23 = 0x17, SDX72): same MCCH insertion as v26
# (MCCH@5, PCCH@6, shifting the DL/UL channels by +1 vs the pre-MCCH group),
# but WITHOUT the v26 RRC-RECONF/COMPLETE shift to 11/12 (existing behavioral
# note above). The corpus exercises pdu_id {1,2,6} here → BCCH-BCH /
# BCCH-DL-SCH / PCCH; pdu_id 7-9 follow the same MCCH-shifted order as v26.
# RRC-RECONF/COMPLETE position is not yet corpus-grounded for this group (no
# pdu_id>=10 records observed) — deliberately omitted so an unmapped pdu_id
# renders the empty unmapped signal rather than a guessed label.
_RRC_TYPE_MAP_MCCH_NOSHIFT = {
    1: 'BCCH-BCH', 2: 'BCCH-DL-SCH', 3: 'DL-CCCH', 4: 'DL-DCCH',
    5: 'MCCH', 6: 'PCCH', 7: 'UL-CCCH', 8: 'UL-CCCH1', 9: 'UL-DCCH',
}
# Parser-version → rrc_type_map. v7 piggybacks on v9 (SCAT does not parse
# pkt_ver=7; the v9 map is best-effort for the records where pdu_id happens
# to match — see module docstring).
_RRC_TYPE_MAPS = {
    7: _RRC_TYPE_MAP_PRE_MCCH,
    9: _RRC_TYPE_MAP_PRE_MCCH,
    12: _RRC_TYPE_MAP_PRE_MCCH,
    14: _RRC_TYPE_MAP_PRE_MCCH,
    17: _RRC_TYPE_MAP_PRE_MCCH,
    23: _RRC_TYPE_MAP_MCCH_NOSHIFT,
    26: _RRC_TYPE_MAP_V26,
}


def pkt_ver_to_channel_name(pkt_ver: int, pdu_id: int) -> str:
    """Resolve (pkt_ver, pdu_id) → 3GPP TS 38.331 channel name.

    Returns the channel-class name (``BCCH-BCH`` / ``BCCH-DL-SCH`` / ``DL-CCCH``
    / ``DL-DCCH`` / ``PCCH`` / etc.) per SCAT's pkt_ver-keyed rrc_type_map
    tables. Returns an empty string when pkt_ver is unsupported or pdu_id is
    outside the map for that version — callers must treat empty as the
    unmapped signal (the parser does this in ``channel_name``).
    """
    rrc_map = _RRC_TYPE_MAPS.get(pkt_ver)
    if rrc_map is None:
        return ""
    return rrc_map.get(pdu_id, "")


# Per-channel inner-c1 CHOICE width in bits, as defined by 3GPP TS 38.331.
# The outer ``<Channel>-MessageType`` CHOICE is always 1 bit (c1 vs
# messageClassExtension). The c1 alternative-count differs per channel:
#   BCCH-BCH     → outer CHOICE has just (mib, messageClassExtension),
#                  no inner c1 wrapper; treat as a special case.
#   BCCH-DL-SCH.c1   → 2 alternatives → 1 bit
#   DL-CCCH.c1       → 4 alternatives → 2 bits
#   DL-DCCH.c1       → 16 alternatives → 4 bits
#   PCCH.c1          → 2 alternatives (paging, spare1) → 1 bit
#   UL-CCCH.c1       → 4 alternatives → 2 bits
#   UL-CCCH1.c1      → 2 alternatives (rrcResumeRequest1, spare1) → 1 bit
#   UL-DCCH.c1       → 16 alternatives → 4 bits
_C1_CHOICE_BITS = {
    'BCCH-DL-SCH': 1,
    'DL-CCCH': 2,
    'DL-DCCH': 4,
    'PCCH': 1,
    'UL-CCCH': 2,
    'UL-CCCH1': 1,
    'UL-DCCH': 4,
}

# (channel_name, c1_index) → 3GPP TS 38.331 message class name. DL-DCCH /
# DL-CCCH / BCCH-DL-SCH validated against pycrate's NR_RRC_Definitions
# (pycrate is validation-only, never runtime). The DL-DCCH-r17 family
# previously listed under channel_type 0x80 is merged here under DL-DCCH —
# the byte[5] discriminator was incorrect, so the "r17" carve-out was a
# RE artifact, not a real ASN.1 family.
_MSG_CLASS_NAMES: dict[tuple[str, int], str] = {
    # BCCH-DL-SCH (1-bit c1)
    ('BCCH-DL-SCH', 0): 'systemInformation',
    ('BCCH-DL-SCH', 1): 'systemInformationBlockType1',
    # PCCH (1-bit c1)
    ('PCCH', 0): 'paging',
    ('PCCH', 1): 'spare1',
    # DL-CCCH (2-bit c1)
    ('DL-CCCH', 0): 'rrcReject',
    ('DL-CCCH', 1): 'rrcSetup',
    ('DL-CCCH', 2): 'spare2',
    ('DL-CCCH', 3): 'spare1',
    # DL-DCCH (4-bit c1)
    ('DL-DCCH', 0): 'rrcReconfiguration',
    ('DL-DCCH', 1): 'rrcResume',
    ('DL-DCCH', 2): 'rrcRelease',
    ('DL-DCCH', 3): 'rrcReestablishment',
    ('DL-DCCH', 4): 'securityModeCommand',
    ('DL-DCCH', 5): 'dlInformationTransfer',
    ('DL-DCCH', 6): 'ueCapabilityEnquiry',
    ('DL-DCCH', 7): 'counterCheck',
    ('DL-DCCH', 8): 'mobilityFromNRCommand',
    ('DL-DCCH', 9): 'dlDedicatedMessageSegment-r16',
    ('DL-DCCH', 10): 'ueInformationRequest-r16',
    ('DL-DCCH', 11): 'dlInformationTransferMRDC-r16',
    ('DL-DCCH', 12): 'loggedMeasurementConfiguration-r16',
    ('DL-DCCH', 13): 'spare3',
    ('DL-DCCH', 14): 'spare2',
    ('DL-DCCH', 15): 'spare1',
    # UL-CCCH (2-bit c1) per 38.331 v16
    ('UL-CCCH', 0): 'rrcSetupRequest',
    ('UL-CCCH', 1): 'rrcResumeRequest',
    ('UL-CCCH', 2): 'rrcReestablishmentRequest',
    ('UL-CCCH', 3): 'rrcSystemInfoRequest',
    # UL-CCCH1 (1-bit c1)
    ('UL-CCCH1', 0): 'rrcResumeRequest1',
    ('UL-CCCH1', 1): 'spare1',
    # UL-DCCH (4-bit c1)
    ('UL-DCCH', 0): 'measurementReport',
    ('UL-DCCH', 1): 'rrcReconfigurationComplete',
    ('UL-DCCH', 2): 'rrcSetupComplete',
    ('UL-DCCH', 3): 'rrcReestablishmentComplete',
    ('UL-DCCH', 4): 'rrcResumeComplete',
    ('UL-DCCH', 5): 'securityModeComplete',
    ('UL-DCCH', 6): 'securityModeFailure',
    ('UL-DCCH', 7): 'ulInformationTransfer',
    ('UL-DCCH', 8): 'locationMeasurementIndication',
    ('UL-DCCH', 9): 'ueCapabilityInformation',
    ('UL-DCCH', 10): 'counterCheckResponse',
    ('UL-DCCH', 11): 'ueAssistanceInformation',
    ('UL-DCCH', 12): 'failureInformation',
    ('UL-DCCH', 13): 'ulInformationTransferMRDC',
    ('UL-DCCH', 14): 'scgFailureInformation',
    ('UL-DCCH', 15): 'scgFailureInformationEUTRA',
}


def decode_ncgi(cell_global_id: Optional[int]) -> Optional[tuple[str, str, int]]:
    """Decode a v17+ ``cell_global_id`` into (mcc, mnc, nci).

    The 60-bit NR Cell Global Identity (NCGI, 3GPP TS 38.413) packs a
    24-bit PLMN-Identity in the high bits and the 36-bit NR Cell Identity
    (NCI) in the low bits::

        bits [59:36]  PLMN-Identity (3 octets, TS 24.008 §10.5.1.3 BCD)
        bits [35: 0]  NR Cell Identity (36-bit NCI)

    The PLMN octets are nibble-swapped BCD: octet1 = MCC2<<4|MCC1,
    octet2 = MNC3<<4|MCC3, octet3 = MNC2<<4|MNC1 (MNC3 == 0xF ⇒ 2-digit MNC).

    Returns ``None`` for a zero/absent id or when the PLMN nibbles are not
    valid BCD digits (so an unexpected layout yields no fabricated PLMN
    rather than garbage). Verified against the SCAT/QSCAN black-box oracle
    on RM520N-GL SDX62 R03A04 (#N): cgi 0x130184087eac028 →
    MCC 311 / MNC 480 / NCI 0x087EAC028 (Verizon n5).
    """
    if not cell_global_id:
        return None
    nci = cell_global_id & 0xFFFFFFFFF
    plmn = (cell_global_id >> 36) & 0xFFFFFF
    o1 = (plmn >> 16) & 0xFF
    o2 = (plmn >> 8) & 0xFF
    o3 = plmn & 0xFF
    mcc1, mcc2 = o1 & 0xF, o1 >> 4
    mcc3, mnc3 = o2 & 0xF, o2 >> 4
    mnc1, mnc2 = o3 & 0xF, o3 >> 4
    if any(d > 9 for d in (mcc1, mcc2, mcc3, mnc1, mnc2)):
        return None
    if mnc3 != 0xF and mnc3 > 9:
        return None
    mcc = f"{mcc1}{mcc2}{mcc3}"
    mnc = f"{mnc1}{mnc2}" if mnc3 == 0xF else f"{mnc1}{mnc2}{mnc3}"
    return mcc, mnc, nci


@dataclass
class Diag0xB821:
    """Parsed NR5G RRC OTA message."""
    log_time: int
    version: int
    rrc_release: int                # byte[4], SCAT rrc_rel_maj
    rrc_rel_min: int                # byte[5], previously mislabeled channel_type
    bearer_id: int                  # SCAT rbid
    pci: int
    arfcn: int
    sfn: int
    slot: int
    # Full-width sfn_subfn field (4 bytes on v7/v9, 3 bytes on v12/v14/v17+).
    # sfn/slot are the low 16 bits (sfn<<4|slot); the upper byte(s) are LIVE,
    # not reserved (#N — non-zero in 6/12 fixtures; SCAT derives subframe/slot
    # from them). Exposed raw so no on-wire byte is discarded.
    sfn_subfn_raw: int
    pdu_id: int                     # actual channel discriminator (#N)
    sib_mask: int                   # 4-byte u32 sib_mask
    msg_length: int
    msg_data: bytes                 # raw ASN.1 PER-encoded NR RRC message
    # v17+ only: 60-bit NR Cell Global Identity (NCGI) inserted between
    # bearer_id and arfcn — the CAMPED serving cell's identity, stamped onto
    # every record (constant across a camp, NOT per-record/per-neighbour).
    # Decomposes as PLMN-Identity (high 24 bits, BCD) + NR Cell Identity
    # (low 36 bits); see decode_ncgi(). None on v7/v9/v12/v14.
    # (Pre-#N this was documented as an opaque "0x01300621 marker"; that
    # was a single operator's PLMN+NCI-prefix misread as a constant.)
    cell_global_id: Optional[int] = None
    # NCGI decode (#N): camped serving PLMN + NCI from cell_global_id.
    ncgi_mcc: str = ""
    ncgi_mnc: str = ""
    ncgi_nci: Optional[int] = None
    # Channel-class label resolved from (version, pdu_id) via SCAT's
    # pkt_ver-keyed rrc_type_map. Empty when pdu_id is unmapped — downstream
    # tooling treats empty as the unmapped signal.
    channel_name: str = ""
    # ASN.1 c1 CHOICE index decoded from the leading bits of msg_data. None
    # when channel has no c1 (BCCH-BCH), msg_data is empty, or the outer
    # CHOICE selects messageClassExtension.
    msg_class_index: Optional[int] = None
    # 3GPP TS 38.331 message-class name resolved from (channel_name,
    # msg_class_index) via _MSG_CLASS_NAMES, or the special "mib" string on
    # BCCH-BCH outer=0 (no inner c1).
    msg_class_name: str = ""
    # SIB1 cell identity (auto-decoded when channel_name == 'BCCH-DL-SCH')
    sib1_mcc: str = ""
    sib1_mnc: str = ""
    sib1_tac: Optional[int] = None
    sib1_cell_id: Optional[int] = None
    # SI-container walk (#N) of a BCCH-DL-SCH systemInformation message
    # (via nr5g_rrc_si.decode_nr_si): declared sib-TypeAndInfo size + the
    # tag sequence walked ('sib2'..'sib9'), in order. Empty/None on non-SI
    # records and on SI records whose criticalExtensions selects the r16
    # future branch. The observed corpus carries exactly two layouts —
    # [sib2,sib4,sib5] and [sib2,sib4,sib5,sib9] — tshark-verified 225/225.
    si_sib_count: Optional[int] = None
    si_sib_tags: list[str] = field(default_factory=list)
    # NR SIB2 serving-cell reselection parameters (#N SIB2 row) —
    # NrSib2 from nr5g_rrc_sib_decode.decode_sib2. None when no sib2 decoded.
    sib2_params: Optional[Any] = None
    # NR SIB4 inter-frequency neighbour carriers (#N SIB4 row) — NrSib4
    # from decode_sib4; carriers each carry dl_carrier_freq (NR ARFCN),
    # freq_band_list, reselection thresholds and any interFreqNeighCellList
    # PCIs. None when no sib4 decoded.
    sib4_params: Optional[Any] = None
    # NR SIB5 inter-RAT EUTRA neighbour carriers (#N SIB5 row) — NrSib5
    # from decode_sib5; carriers each carry carrier_freq (EUTRA EARFCN),
    # reselection thresholds and any eutra-FreqNeighCellList PCIs. None when
    # no sib5 decoded.
    sib5_params: Optional[Any] = None
    # NR SIB9 network time (#N/#N) — decoded by the walker when the
    # SI message carries sib9 (rides LAST behind sib2/sib4/sib5 in the
    # observed corpus). timeInfoUTC raw value is 10 ms units since
    # 1900-01-01 00:00:00 UTC (TS 38.331 semantics, wall-clock-validated).
    sib9_time_info_utc: Optional[int] = None
    sib9_utc_iso: str = ""
    sib9_leap_seconds: Optional[int] = None
    sib9_dst: Optional[int] = None
    sib9_local_time_offset: Optional[int] = None
    # MIB PHY/access config (auto-decoded when channel_name == 'BCCH-BCH' and
    # the outer CHOICE selects mib). 3GPP TS 38.331 MasterInformationBlock.
    mib_scs_common: str = ""           # 'scs15or60' | 'scs30or120'
    mib_ssb_subcarrier_offset: Optional[int] = None
    mib_dmrs_typeA_position: str = ""  # 'pos2' | 'pos3'
    mib_coreset0: Optional[int] = None
    mib_searchspace0: Optional[int] = None
    mib_cell_barred: str = ""          # 'barred' | 'notBarred'
    mib_intra_freq_reselection: str = ""  # 'allowed' | 'notAllowed'
    mib_sfn_msb: Optional[int] = None  # 6 MSBs of the 10-bit SFN
    # SecurityModeCommand AS-security algorithms (auto-decoded when
    # channel_name == 'DL-DCCH' and the c1 index resolves to
    # securityModeCommand). 3GPP TS 38.331 §6.3.2 SecurityAlgorithmConfig.
    smc_rrc_transaction_id: Optional[int] = None
    smc_ciphering_algorithm: Optional[int] = None
    smc_ciphering_algorithm_name: str = ""       # 'nea0'..'nea3' | spare
    smc_integrity_prot_algorithm: Optional[int] = None
    smc_integrity_prot_algorithm_name: str = ""  # 'nia0'..'nia3' | spare
    # NR DL-CCCH message (#N): auto-decoded when channel_name == 'DL-CCCH'
    # and the c1 index resolves to rrcSetup / rrcReject. Decoded by
    # nr5g_rrc_dlccch.decode_nr_dl_ccch (3GPP TS 38.331 6.2.2). These are the
    # RRC connection-establishment messages a gNB sends before an SRB1/DCCH
    # exists. dl_ccch_message_type is 'rrcSetup' | 'rrcReject';
    # dl_ccch_rrc_transaction_identifier is the rrcSetup leading scalar (the
    # RadioBearerConfig + masterCellGroup CellGroupConfig bodies are heavy and
    # intentionally left structural); dl_ccch_wait_time is the rrcReject
    # RejectWaitTime seconds (INTEGER 1..16). All None/"" on non-DL-CCCH records.
    dl_ccch_message_type: str = ""
    dl_ccch_rrc_transaction_identifier: Optional[int] = None
    dl_ccch_wait_time: Optional[int] = None
    # NR MeasurementReport (#N) — auto-decoded when channel_name == 'UL-DCCH'
    # and the c1 index resolves to measurementReport. Decoded by
    # nr5g_rrc_meas_report.decode_nr_measurement_report (3GPP TS 38.331 §6.2.2).
    # meas_report_id is the measId; serving_* are the serving-cell results
    # (any of RSRP dBm / RSRQ dB / SINR dB may be absent → None);
    # meas_report_neighbors is the list of NrMeasResultCell. None/empty when the
    # record is not a MeasurementReport or fails to decode.
    meas_report_id: Optional[int] = None
    meas_report_serving_rsrp: Optional[float] = None
    meas_report_serving_rsrq: Optional[float] = None
    meas_report_serving_sinr: Optional[float] = None
    meas_report_neighbors: list[Any] = field(default_factory=list)
    # NR measConfig (#N wiring; #N decoder). Auto-decoded when the c1 index
    # resolves to rrcReconfiguration on the DL-DCCH channel (via
    # nr5g_rrc_reconfig.decode_nr_meas_config) or on the firmware-direct
    # RRC-RECONF channel (via decode_nr_meas_config_direct). 3GPP TS 38.331
    # §6.2.2. #N implemented the radioBearerConfig structural skip and the
    # RRC-RECONF bare-SEQUENCE framing, so this now populates on the real corpus
    # (validated field-for-field against pycrate: DL-DCCH 124/124, RRC-RECONF
    # 23/23). meas_objects holds MeasObjectNR entries; meas_eutra_objects holds
    # inter-RAT MeasObjectEUTRA; meas_s_measure_ssb / _csi are the SSB/CSI-RSRP
    # thresholds.
    meas_objects: list[Any] = field(default_factory=list)
    meas_eutra_objects: list[Any] = field(default_factory=list)
    meas_s_measure_ssb: Optional[int] = None
    meas_s_measure_csi: Optional[int] = None

    @property
    def channel_type(self) -> int:
        """Deprecated alias for ``rrc_rel_min`` (byte[5]).

        Prior to #N this parser exposed byte[5] as ``channel_type`` and
        misinterpreted it as the channel discriminator. byte[5] is actually
        ``rrc_rel_min`` per SCAT's NR RRC OTA parser. New consumers should
        read ``rrc_rel_min`` (raw byte) or ``channel_name`` (resolved
        channel-class label) instead. Scheduled for removal once downstream
        callers have migrated.
        """
        return self.rrc_rel_min

    def to_dict(self) -> dict[str, Any]:
        d = {
            'type': 'Diag0xB821',
            'log_time': self.log_time,
            'version': self.version,
            'rrc_release': self.rrc_release,
            'rrc_rel_min': self.rrc_rel_min,
            # Deprecated alias for one release (#N). Same value as
            # rrc_rel_min; will be removed once downstream consumers migrate.
            'channel_type': self.rrc_rel_min,
            'bearer_id': self.bearer_id,
            'pci': self.pci,
            'earfcn': self.arfcn,
            'arfcn': self.arfcn,
            'sfn': self.sfn,
            'slot': self.slot,
            'sfn_subfn_raw': self.sfn_subfn_raw,
            'pdu_id': self.pdu_id,
            'sib_mask': self.sib_mask,
            'msg_length': self.msg_length,
            'msg_bytes': self.msg_data.hex(),
        }
        if self.cell_global_id is not None:
            d['cell_global_id'] = self.cell_global_id
        if self.ncgi_nci is not None:
            d['ncgi_mcc'] = self.ncgi_mcc
            d['ncgi_mnc'] = self.ncgi_mnc
            d['ncgi_nci'] = self.ncgi_nci
            d['ncgi_nci_hex'] = f"{self.ncgi_nci:09X}"
        if self.channel_name:
            d['channel_name'] = self.channel_name
        if self.msg_class_index is not None:
            d['msg_class_index'] = self.msg_class_index
        if self.msg_class_name:
            d['msg_class_name'] = self.msg_class_name
        if self.sib1_tac is not None:
            d['sib1_mcc'] = self.sib1_mcc
            d['sib1_mnc'] = self.sib1_mnc
            d['sib1_tac'] = self.sib1_tac
            d['sib1_cell_id'] = self.sib1_cell_id
        # SI-container walk + SIB2 params + SIB9 network time (#N/#N).
        if self.si_sib_count is not None:
            d['si_sib_count'] = self.si_sib_count
            d['si_sib_tags'] = self.si_sib_tags
        if self.sib2_params is not None:
            d['sib2_params'] = self.sib2_params.to_dict()
        if self.sib4_params is not None:
            d['sib4_params'] = self.sib4_params.to_dict()
        if self.sib5_params is not None:
            d['sib5_params'] = self.sib5_params.to_dict()
        if self.sib9_time_info_utc is not None:
            d['sib9_time_info_utc'] = self.sib9_time_info_utc
            if self.sib9_utc_iso:
                d['sib9_utc_iso'] = self.sib9_utc_iso
            if self.sib9_leap_seconds is not None:
                d['sib9_leap_seconds'] = self.sib9_leap_seconds
            if self.sib9_dst is not None:
                d['sib9_dst'] = self.sib9_dst
            if self.sib9_local_time_offset is not None:
                d['sib9_local_time_offset'] = self.sib9_local_time_offset
        if self.mib_scs_common:
            d['mib_scs_common'] = self.mib_scs_common
            d['mib_ssb_subcarrier_offset'] = self.mib_ssb_subcarrier_offset
            d['mib_dmrs_typeA_position'] = self.mib_dmrs_typeA_position
            d['mib_coreset0'] = self.mib_coreset0
            d['mib_searchspace0'] = self.mib_searchspace0
            d['mib_cell_barred'] = self.mib_cell_barred
            d['mib_intra_freq_reselection'] = self.mib_intra_freq_reselection
            d['mib_sfn_msb'] = self.mib_sfn_msb
        if self.smc_ciphering_algorithm is not None:
            d['smc_rrc_transaction_id'] = self.smc_rrc_transaction_id
            d['smc_ciphering_algorithm'] = self.smc_ciphering_algorithm
            d['smc_ciphering_algorithm_name'] = self.smc_ciphering_algorithm_name
            d['smc_integrity_prot_algorithm'] = self.smc_integrity_prot_algorithm
            d['smc_integrity_prot_algorithm_name'] = (
                self.smc_integrity_prot_algorithm_name)
        # NR DL-CCCH message (#N): keyed on dl_ccch_message_type being set.
        if self.dl_ccch_message_type:
            d['dl_ccch_message_type'] = self.dl_ccch_message_type
            if self.dl_ccch_rrc_transaction_identifier is not None:
                d['dl_ccch_rrc_transaction_identifier'] = (
                    self.dl_ccch_rrc_transaction_identifier)
            if self.dl_ccch_wait_time is not None:
                d['dl_ccch_wait_time'] = self.dl_ccch_wait_time
        # NR MeasurementReport (#N) — keyed on meas_report_id being set.
        if self.meas_report_id is not None:
            d['meas_report_id'] = self.meas_report_id
            if self.meas_report_serving_rsrp is not None:
                d['meas_report_serving_rsrp'] = self.meas_report_serving_rsrp
            if self.meas_report_serving_rsrq is not None:
                d['meas_report_serving_rsrq'] = self.meas_report_serving_rsrq
            if self.meas_report_serving_sinr is not None:
                d['meas_report_serving_sinr'] = self.meas_report_serving_sinr
            d['meas_report_neighbors'] = [
                c.to_dict() for c in self.meas_report_neighbors
            ]
        # NR measConfig (#N) — emit only when meas objects were extracted.
        if self.meas_objects:
            d['meas_objects'] = [m.to_dict() for m in self.meas_objects]
            if self.meas_eutra_objects:
                d['meas_eutra_objects'] = [
                    m.to_dict() for m in self.meas_eutra_objects
                ]
            if self.meas_s_measure_ssb is not None:
                d['meas_s_measure_ssb'] = self.meas_s_measure_ssb
            if self.meas_s_measure_csi is not None:
                d['meas_s_measure_csi'] = self.meas_s_measure_csi
        return d


def _decode_outer_choice(
    channel_name: str, msg_data: bytes,
) -> tuple[Optional[int], str]:
    """Decode the outer ASN.1 CHOICE + c1 index from msg_data.

    The outer envelope on every RRC channel is::

        <Channel>-Message ::= SEQUENCE { message <Channel>-MessageType }
        <Channel>-MessageType ::= CHOICE { c1 CHOICE { ... }, messageClassExtension }

    UPER encodes the outer CHOICE as 1 bit (c1 vs extension). When that bit
    is 0 (c1 path), the next ``width`` bits encode the c1 alternative — width
    is channel-specific per TS 38.331. BCCH-BCH is the special case: the
    outer CHOICE has only ``mib`` and ``messageClassExtension``, with no
    inner c1 wrapper.

    Returns ``(msg_class_index, msg_class_name)``. ``msg_class_index`` is
    None when the channel has no c1 (BCCH-BCH), msg_data is empty, or the
    outer CHOICE selects messageClassExtension. ``msg_class_name`` is empty
    in those cases except BCCH-BCH outer=0 which returns ("", "mib").
    """
    if not msg_data:
        return None, ""

    if channel_name == "BCCH-BCH":
        # Outer CHOICE only — no inner c1.
        outer = (msg_data[0] >> 7) & 1
        if outer == 0:
            return None, "mib"
        return None, ""

    width = _C1_CHOICE_BITS.get(channel_name)
    if width is None:
        return None, ""

    b = msg_data[0]
    outer = (b >> 7) & 1
    if outer != 0:
        # messageClassExtension path — alternative is not a c1 index.
        return None, ""
    c1_index = (b >> (7 - width)) & ((1 << width) - 1)
    name = _MSG_CLASS_NAMES.get((channel_name, c1_index), "")
    return c1_index, name


# ── Ground-truth recipe (#N) — WiGLE-direct (identity) ─────────────────────
# Authored <redacted-ref> 2026-06-11 (wigle-tagged batch, tracker #N).
# 0xB821 is the NR5G RRC OTA message log — wigle:direct because its decoded
# header (and SIB1, when the OTA message IS a SIB1 broadcast) carries the full
# WiGLE cell-identity set: PCI, NR-ARFCN, NCGI (cell_global_id), and PLMN+TAC+
# cellID from the SIB1 ASN.1. Target = RM520N-GL (SDX62), which emits version
# 0x11 (=17, Rel-16) in the corpus (offset-0 walk this session: 1582 v0x11
# records; v17 is the only RM520N-GL version with the NCGI cell_global_id field).
# cond:nr5g — drive an NR5G-SA attach so RRC OTA fires; SIB1-bearing records
# appear during cell (re)selection / connection setup.

@register(LOG_NR5G_RRC_OTA_MSG, domain="rrc",
    name="0xB821",
    description="NR5G RRC Over-The-Air message with ASN.1 PER-encoded content",
    version=18,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v9 RE'd from SDX55 RM500Q DLF (cross-ref AT+QENG serving cell). "
        "v12/v14/v17 RE'd from 1,544-record corpus walk across EM9190 / "
        "RM500Q / RM520N-GL - see #N follow-up. Layout verified at 100%. "
        "v7 added from QCAT-decoded ground truth (UlDl-90-9-1, RRC 15.4.1, "
        "4 records) - same layout as v9; byte[5] (rrc_rel_min) is constant "
        "0x41 on v7. v26 added from RG650V SDX72 donor capture (#N, 7 "
        "records); layout matches v17 except for 4 zero bytes inserted "
        "between msg_length and msg_data, header_size grows 31→35. "
        "v6 (#N): re-based the header dispatch on SCAT's pkt_ver-keyed "
        "rrc_type_map and pdu_id at version-keyed offset (byte[17] on "
        "v7/v9, byte[16] on v12/v14, byte[24] on v17+). The pre-#N "
        "parser treated byte[5] as channel_type, which is actually "
        "rrc_rel_min - a release-version byte whose value coincidentally "
        "correlated with channel within firmware builds. Audit #N "
        "confirmed the byte[24] reading across three independent v17 "
        "fixtures. byte[5] is preserved as rrc_rel_min (and as the "
        "deprecated ``channel_type`` alias for one release). pdu_id is the "
        "authoritative discriminator. SIB1 (channel_name=BCCH-DL-SCH) auto-"
        "decoded via UPER (#N). DL-DCCH / DL-CCCH / BCCH-DL-SCH / PCCH "
        "/ UL-* c1 indices resolve to 38.331 message class names via "
        "_MSG_CLASS_NAMES (validated against pycrate). NR MIB decoder "
        "lives in diaggrok.parsers.nr5g_rrc_mib.decode_nr_mib - not auto-"
        "dispatched here because v7 BCCH-BCH discriminator is in the DLF "
        "outer header. Body ASN.1 full-decode work continues per #N. "
        "v8 (#N): decode the v17+ cell_global_id NCGI into ncgi_mcc / "
        "ncgi_mnc / ncgi_nci (PLMN-BCD high 24 bits + 36-bit NCI). Validated "
        "vs the SCAT/QSCAN black-box oracle on RM520N-GL R03A04: camped n5 "
        "Verizon 311/480 NCI 0x087EAC028. Corrected the prior docstring that "
        "called the high bits an opaque constant marker. "
        "v9 (#N): added version 0x17 (23, SDX72 Foxconn T99W640) - was "
        "silently dropped (absent from _HEADER_SIZE). Shares the v26 NCGI-"
        "inserted 35B header (confirmed 86/86 corpus records by "
        "header_size + msg_length == payload_len; arfcn 521310 / pci 596 / "
        "NCGI 0x01300621 cross-anchor to the HW-verified 0xB823 n41 cell). "
        "Channel map is the 0x14/0x17/0x18 MCCH-variant group (MCCH@5, "
        "PCCH@6) WITHOUT the v26 RRC-RECONF shift; RRC-RECONF position "
        "uncaptured for this group so omitted (empty channel_name). "
        "v13 (#N, <redacted-ref> 2026-06-28): auto-dispatch the canonical "
        "nr5g_rrc_mib.decode_nr_mib on BCCH-BCH frames whose in-payload outer "
        "CHOICE resolves to mib - surfacing mib_scs_common / mib_coreset0 / "
        "mib_searchspace0 / mib_cell_barred / mib_intra_freq_reselection / "
        "mib_ssb_subcarrier_offset / mib_dmrs_typeA_position / mib_sfn_msb. "
        "(Previously the decoder was only reachable directly because v7's "
        "MIB discriminator sits in the DLF outer header; on v17+ the payload "
        "carries its own outer CHOICE, making in-band dispatch safe.) "
        "Validated on RM520N-GL R03A04 (20260628T1556Z nr5g-ml1): same-cell "
        "invariance on the T-Mobile n41 serving cell PCI 260 (4 MIBs, identical "
        "scs30or120 / CORESET#0 12 / SearchSpace#0 4 / notBarred, only SFN "
        "varying) and the physically-correct 30 kHz SSB SCS for n41 (the "
        "no-CHOICE-bit alignment alternative mis-decodes it as 15 kHz, pinning "
        "the leading CHOICE bit). "
        "v14 (#N/#N, <redacted-ref> 2026-06-28): auto-dispatch the DL-DCCH "
        "securityModeCommand body via nr5g_rrc_smc.decode_nr_security_mode_command "
        "- surfacing smc_ciphering_algorithm / smc_integrity_prot_algorithm "
        "(+ names) and smc_rrc_transaction_id. Like the MIB it is a smallest-"
        "fully-defined message (21 bits, no per-version drift), so one offset-"
        "stable decoder covers every wire version. Validated field-for-field "
        "against the stock-tshark nr-rrc dissector of the diaggrok NR Exported-"
        "PDU pcap (#N) on RM520N-GL R03A04 T-Mobile NR5G-SA (tmo_nr5gsa): "
        "msg_data '200910' → nea2 (2) / nia2 (2), matching tshark exactly. "
        "v15 (#N/#N/#N): walk the BCCH-DL-SCH systemInformation "
        "(c1=0) container via nr5g_rrc_si.decode_nr_si - si_sib_count / "
        "si_sib_tags tag enumeration, SIB2 serving-cell reselection "
        "extraction (sib2_params, nr5g_rrc_sib_decode.decode_sib2), and SIB9 "
        "timeInfo extraction (sib9_time_info_utc "
        "/ sib9_utc_iso / sib9_leap_seconds / sib9_dst / "
        "sib9_local_time_offset, nr5g_rrc_sib9.decode_sib9_body). "
        "timeInfoUTC is 10 ms units since 1900-01-01 UTC per TS 38.331. "
        "Validated field-for-field against the stock tshark nr-rrc "
        "dissector on ALL 225 distinct corpus SI messages (416 records / "
        "78 captures / 6 chipsets / pkt_ver 9,12,17), and SIB9 UTC "
        "wall-clock-validated against DIAG ts64 (145/183 within <=38 s; "
        "all 38 outliers are unset-modem-clock captures whose filename "
        "timestamps corroborate SIB9 to minutes). Corpus carries exactly "
        "two SI layouts: sib2,sib4,sib5 and sib2,sib4,sib5,sib9. Header "
        "sib_mask bit-k=SIBk confirmed for masks 0x34/0x234; the 0x200 "
        "variant marks otherwise-identical sib2,4,5,9 messages (flag "
        "semantics unresolved). NOTE: tshark ground truth also shows "
        "timeInfoUTC ~3.99e11 = 1900-epoch 10 ms units - the GPS-1980-"
        "seconds reading used by lte_rrc_sib16.py would put these in year "
        "~14600; LTE SIB16 semantics flagged for re-validation on #N. "
        "v16 (#N): promote the sib4/sib5 structural skips to field "
        "extraction - sib4_params (NrSib4: per-carrier dl_carrier_freq NR "
        "ARFCN, freq_band_list, q_rxlevmin, t_reselection_nr, threshX-High/"
        "LowP, p_max, cellReselectionPriority/subPriority, and any "
        "interFreqNeighCellList PCIs) and sib5_params (NrSib5: per-carrier "
        "carrier_freq EUTRA EARFCN, eutra_bands, q_rxlevmin/q_qualmin/"
        "p_max_eutra, threshX-High/Low, priority, and any eutra-"
        "FreqNeighCellList PCIs, plus t_reselection_eutra). The reads are "
        "the same bit-exact walk as v15's skips (SIB9 time still lands), "
        "now capturing values instead of discarding them; validated field-"
        "for-field against the stock tshark nr-rrc dissector on all 225 "
        "distinct corpus SI messages. "
        "v17 (#N): ground-truth recipe FieldGrounds for the four SIB9 "
        "network-time fields (sib9_time_info_utc/sib9_utc_iso, "
        "sib9_local_time_offset, sib9_dst, sib9_leap_seconds) on the v0x11 "
        "RM520N-GL recipe, all status=verified. RM520N-GL SIB9 re-walk: 40 "
        "SIB9-bearing records across 4 R03A03 wardrive sessions, 100% "
        "extraction, all [sib2,sib4,sib5,sib9]. Two independent oracles: "
        "(1) exact field-set equality vs the stock tshark nr-rrc dissector "
        "(timeInfoUTC/dst/leapSeconds/localTimeOffset, 16/16 on the "
        "2026-06-03_144212 capture); (2) the derived UTC matches the "
        "independent wardrive host-clock session-start timestamp to the "
        "minute in all 4 sessions - pinning the 10 ms-since-1900 epoch over "
        "the GPS-1980 reading. T-Mobile n41 broadcasts a constant "
        "(dst=1, leapSeconds=0, localTimeOffset=-24 = -6 h MDT). No parse-"
        "logic change; recipe metadata + docs only. "
        "v18 (#N, <redacted-ref> 2026-07-09): auto-dispatch the DL-CCCH body via "
        "nr5g_rrc_dlccch.decode_nr_dl_ccch, the last un-decoded DL channel in "
        "the #N MIB/DL-CCCH/DL-DCCH scope. Surfaces dl_ccch_message_type "
        "('rrcSetup'|'rrcReject'), dl_ccch_rrc_transaction_identifier (rrcSetup "
        "leading scalar), and dl_ccch_wait_time (rrcReject RejectWaitTime "
        "seconds). rrcSetup's RadioBearerConfig + masterCellGroup CellGroupConfig "
        "are heavy structures left intentionally structural (outside the "
        "identity/reselection scope). The <redacted-ref> corpus re-gate promoted DL-CCCH "
        "from the 3-record curiosity the issue prose described to 97 records / 34 "
        "captures / 3 versions (v9/v17/v23), all rrcSetup, tid=0 (rrcReject is a "
        "congestion/barring message, zero corpus). Validated field-for-field "
        "against the stock tshark nr-rrc dissector on 24 real rrcSetup records "
        "(RM520N-GL SDX62 v17, Compal RXM-G1 v9, Foxconn T99W640 SDX72 v23: 3 "
        "chipsets, 2 SoC generations; 24/24 c1=rrcSetup / tid=0 / 0 malformed) "
        "and on synthetic rrcReject vectors (waitTime 1s/10s/16s + absent, "
        "tshark-confirmed). pycrate was NOT usable as the oracle here: it "
        "mis-sizes the real masterCellGroup CellGroupConfig open-type ('length "
        "determinant too long'), a body region past the leading scalar this "
        "decoder reads."
    ),
    source_url="https://github.com/lukejenkins",
    issues=(),
    primary_issue=None,
    fields_identified=38,
    fields_parsed=38,
    field_invariants={
        # Validated against the in-repo corpus plus 1,544 DLF records / 23
        # captures / 4 chipsets (corpus walk 2026-05-07, #N) plus 4
        # QCAT-decoded v7 records (UlDl-90-9-1) plus 7 RG650V SDX72 v26
        # records (#N).
        # version is the u32-LE discriminator used to pick header layout.
        # rrc_release is 15 (Rel-15) on v7/v9/v12, 16 (Rel-16) on v14/v17,
        # 17 (Rel-17) on v26. rrc_rel_min varies with firmware and is not
        # an enum — no invariant. pdu_id is not an enum either (the map
        # itself is the validation surface; an unmapped pdu_id surfaces as
        # an empty channel_name).
        "version": {"enum": [7, 9, 12, 14, 17, 23, 26]},
        "rrc_release": {"enum": [15, 16, 17]},
    },
    wigle_direct=True,
    wigle_roles=("identity", "rat-context"),
    # Ground-truth recipe (#N): WiGLE-direct identity validation for v0x11
    # (RM520N-GL SDX62), hw_run_performed=True. Identity fields (pci/arfcn/
    # cell_global_id/sib1_*) verified via <redacted-ref> (2026-06-26..28); SIB9
    # network-time fields verified via tshark-equality + host-clock (#N).
)
def parse_0xb821(log_time: int, data: bytes) -> Diag0xB821 | None:
    """Parse 0xB821 — NR5G RRC OTA Message.

    Extracts the RRC message header (PCI, NR-ARFCN, SFN/slot, pdu_id) and
    the raw ASN.1 PER-encoded message body. Bodies are decoded inline per
    channel via from-scratch UPER sibling decoders (3GPP TS 38.331): SIB1 +
    the systemInformation SI container (SIB2/4/5/9) on BCCH-DL-SCH, MIB on
    BCCH-BCH, securityModeCommand + rrcReconfiguration measConfig on DL-DCCH,
    rrcSetup / rrcReject on DL-CCCH, and MeasurementReport on UL-DCCH. Channels
    / message classes without a body decoder still resolve their
    channel_name + msg_class_name and hand msg_data back raw (#N).

    Supports versions 7, 9, 12, 14, 17, 23, 26. Other versions return None.
    Header dispatch is keyed on SCAT's pkt_ver-aware rrc_type_map and the
    pdu_id at a version-keyed offset (#N / audit #N). byte[5] is
    ``rrc_rel_min`` (release minor) — the pre-#N parser read it as
    ``channel_type`` and that interpretation is preserved only as a
    deprecated alias on the dataclass.
    """
    if len(data) < 4:
        return None

    version = unpack_from('<I', data, 0)[0]
    header_size = _HEADER_SIZE.get(version)
    if header_size is None or len(data) < header_size:
        return None

    rrc_release = data[4]
    rrc_rel_min = data[5]
    bearer_id = data[6]
    pci = unpack_from('<H', data, 7)[0]

    # v17+ insert an 8-byte cell_global_id (NCGI) between bearer_id and arfcn.
    # The lower 32 bits vary per cell; the upper 32 bits are a fixed
    # 0x01300621 marker across the entire observed v17+v26 corpus.
    if version in (17, 23, 26):
        cell_global_id = unpack_from('<Q', data, 9)[0]
        arfcn_offset = 17
    else:
        cell_global_id = None
        arfcn_offset = 9

    ncgi = decode_ncgi(cell_global_id)

    arfcn = unpack_from('<I', data, arfcn_offset)[0]

    # sfn_subfn: the field is 4 bytes on v7/v9 (u32) and 3 bytes on v12/v14/v17+
    # (u24). The low 16 bits give sfn<<4|slot (validated vs 1,544 corpus records).
    # The upper byte(s) are NOT reserved (#N corrected the prior claim) — they
    # carry live, varying data (non-zero in 6/12 fixtures; SCAT derives
    # subframe/slot from them), so the full-width value is read and exposed as
    # sfn_subfn_raw rather than discarded. Width = pdu_id_offset - sfn_offset.
    sfn_off = _SFN_SUBFN_OFFSET[version]
    sfn_width = _PDU_ID_OFFSET[version] - sfn_off      # 4 on v7/v9, 3 elsewhere
    sfn_subfn_raw = int.from_bytes(data[sfn_off:sfn_off + sfn_width], 'little')
    sfn_slot = sfn_subfn_raw & 0xFFFF
    sfn = sfn_slot >> 4
    slot = sfn_slot & 0xF

    pdu_id = data[_PDU_ID_OFFSET[version]]
    sib_mask = unpack_from('<I', data, _SIB_MASK_OFFSET[version])[0]
    msg_length = unpack_from('<H', data, _MSG_LEN_OFFSET[version])[0]

    msg_data = bytes()
    if msg_length > 0 and len(data) >= header_size + msg_length:
        msg_data = data[header_size:header_size + msg_length]

    channel_name = pkt_ver_to_channel_name(version, pdu_id)
    msg_class_index, msg_class_name = _decode_outer_choice(channel_name, msg_data)

    result = Diag0xB821(
        log_time=log_time,
        version=version,
        rrc_release=rrc_release,
        rrc_rel_min=rrc_rel_min,
        bearer_id=bearer_id,
        pci=pci,
        arfcn=arfcn,
        sfn=sfn,
        slot=slot,
        sfn_subfn_raw=sfn_subfn_raw,
        pdu_id=pdu_id,
        sib_mask=sib_mask,
        msg_length=msg_length,
        msg_data=msg_data,
        cell_global_id=cell_global_id,
        ncgi_mcc=ncgi[0] if ncgi else "",
        ncgi_mnc=ncgi[1] if ncgi else "",
        ncgi_nci=ncgi[2] if ncgi else None,
        channel_name=channel_name,
        msg_class_index=msg_class_index,
        msg_class_name=msg_class_name,
    )

    # Auto-decode NR SIB1 from BCCH-DL-SCH frames using the from-scratch
    # UPER decoder (3GPP TS 38.331). The pycrate path was removed in #N
    # to keep diaggrok Apache-2.0-clean. SIB1 dispatch now keys on the resolved
    # channel_name (#N) — previously keyed on byte[5]==0x90, which fired
    # incorrectly on PCCH records that happened to share that rrc_rel_min
    # value.
    if channel_name == "BCCH-DL-SCH" and msg_data:
        sib1 = decode_nr_sib1_uper(msg_data)
        if sib1 is not None:
            result.sib1_mcc = sib1.mcc
            result.sib1_mnc = sib1.mnc
            result.sib1_tac = sib1.tac
            result.sib1_cell_id = sib1.cell_id

    # Auto-decode the systemInformation (c1=0) SI container (#N): walk
    # the sib-TypeAndInfo list — extracting SIB2 serving-cell reselection
    # parameters and the SIB9 timeInfo (NR network time, #N), with
    # structural skips over sib4/sib5 bodies (nr5g_rrc_sib_decode). Same
    # in-band dispatch signal as the MIB/SMC paths — msg_class_name comes
    # from the payload's own outer CHOICE. Validated field-for-field
    # against the stock tshark nr-rrc dissector on all 225 distinct corpus
    # SI messages (#N gate, 2026-07-02).
    if (channel_name == "BCCH-DL-SCH"
            and msg_class_name == "systemInformation" and msg_data):
        si = decode_nr_si(log_time, msg_data)
        if si is not None:
            result.si_sib_count = si.sib_count
            result.si_sib_tags = si.sib_tags
            result.sib2_params = si.sib2
            result.sib4_params = si.sib4
            result.sib5_params = si.sib5
            if si.sib9 is not None:
                result.sib9_time_info_utc = si.sib9.time_info_utc
                result.sib9_utc_iso = (
                    si.sib9.utc_datetime.isoformat()
                    if si.sib9.utc_datetime is not None else "")
                result.sib9_leap_seconds = si.sib9.leap_seconds
                result.sib9_dst = si.sib9.dst
                result.sib9_local_time_offset = si.sib9.local_time_offset

    # Auto-decode the NR MIB from BCCH-BCH frames whose outer CHOICE selects
    # mib. The canonical decoder lives in nr5g_rrc_mib (#N-era); it was
    # previously only reachable directly because v7's MIB-vs-RRC_RECONFIG
    # discriminator sits in the DLF outer header, invisible inside the
    # payload. On v17+ the payload's own outer CHOICE *is* decodable, so
    # _decode_outer_choice resolving msg_class_name=='mib' is an in-band,
    # self-consistent dispatch signal — auto-decode is safe here (#N).
    if channel_name == "BCCH-BCH" and msg_class_name == "mib" and msg_data:
        mib = decode_nr_mib(log_time, msg_data)
        if mib is not None:
            result.mib_scs_common = mib.sub_carrier_spacing_common_name
            result.mib_ssb_subcarrier_offset = mib.ssb_subcarrier_offset
            result.mib_dmrs_typeA_position = mib.dmrs_type_a_position_name
            result.mib_coreset0 = mib.control_resource_set_zero
            result.mib_searchspace0 = mib.search_space_zero
            result.mib_cell_barred = (
                "notBarred" if mib.cell_not_barred else "barred"
            )
            result.mib_intra_freq_reselection = (
                "allowed" if mib.intra_freq_reselection_allowed else "notAllowed"
            )
            result.mib_sfn_msb = mib.system_frame_number

    # Auto-decode the DL-DCCH SecurityModeCommand body (AS-security algorithm
    # pair) when the c1 index resolves to securityModeCommand. Same in-band,
    # self-consistent dispatch signal as the MIB: msg_class_name comes from
    # the payload's own outer CHOICE, so there is no out-of-band ambiguity.
    # securityModeCommand is offset-stable across wire versions (smallest-
    # fully-defined message, no per-version drift) — see nr5g_rrc_smc (#N).
    if (channel_name == "DL-DCCH" and msg_class_name == "securityModeCommand"
            and msg_data):
        smc = decode_nr_security_mode_command(log_time, msg_data)
        if smc is not None:
            result.smc_rrc_transaction_id = smc.rrc_transaction_identifier
            result.smc_ciphering_algorithm = smc.ciphering_algorithm
            result.smc_ciphering_algorithm_name = smc.ciphering_algorithm_name
            result.smc_integrity_prot_algorithm = smc.integrity_prot_algorithm
            result.smc_integrity_prot_algorithm_name = (
                smc.integrity_prot_algorithm_name or "")

    # Auto-decode the DL-CCCH message (rrcSetup / rrcReject): the RRC
    # connection-establishment messages sent before an SRB1/DCCH exists (#N).
    # Same in-band dispatch signal as the MIB/SMC paths: the c1 index that
    # _decode_outer_choice resolved from the payload's own outer CHOICE names
    # the message class, so there is no out-of-band ambiguity. The decoder
    # extracts the clean leading scalars (rrcSetup.rrc-TransactionIdentifier,
    # rrcReject.waitTime); the heavy RadioBearerConfig / masterCellGroup
    # CellGroupConfig in rrcSetup is intentionally left structural. Validated
    # field-for-field against the stock tshark nr-rrc dissector on 24 real
    # rrcSetup records (RM520N-GL SDX62 v17, RXM-G1 v9, T99W640 SDX72 v23) and
    # on synthetic rrcReject vectors (rrcReject has zero corpus records).
    if channel_name == "DL-CCCH" and msg_data:
        dl_ccch = decode_nr_dl_ccch(log_time, msg_data)
        if dl_ccch is not None:
            result.dl_ccch_message_type = dl_ccch.message_type
            result.dl_ccch_rrc_transaction_identifier = (
                dl_ccch.rrc_transaction_identifier)
            result.dl_ccch_wait_time = dl_ccch.wait_time

    # Auto-decode the UL-DCCH MeasurementReport (serving + neighbor NR cell
    # measurements) when the c1 index resolves to measurementReport. Same
    # in-band dispatch signal as the MIB/SMC paths: msg_class_name comes from
    # the payload's own outer CHOICE, so there is no out-of-band ambiguity. The
    # decoder self-gates on the full UL-DCCH-Message outer (#N). 63/188
    # UL-DCCH records across the sampled corpus carry a MeasurementReport.
    if (channel_name == "UL-DCCH" and msg_class_name == "measurementReport"
            and msg_data):
        mr = decode_nr_measurement_report(log_time, msg_data)
        if mr is not None:
            result.meas_report_id = mr.meas_id
            result.meas_report_serving_rsrp = mr.serving_rsrp
            result.meas_report_serving_rsrq = mr.serving_rsrq
            result.meas_report_serving_sinr = mr.serving_sinr
            result.meas_report_neighbors = mr.neighbor_cells

    # Auto-decode the RRCReconfiguration measConfig (NR measurement objects:
    # SSB NR-ARFCNs, subcarrier spacing, neighbor PCIs; inter-RAT EUTRA EARFCNs)
    # from two framings (#N wiring; #N decoder + RRC-RECONF path):
    #   * DL-DCCH channel, c1 == rrcReconfiguration — payload begins with the
    #     DL-DCCH-Message outer CHOICE → decode_nr_meas_config.
    #   * RRC-RECONF firmware-direct channel — the DLF outer header already named
    #     the message, so msg_data starts at the bare RRCReconfiguration SEQUENCE
    #     (no DL-DCCH-Message wrapper) → decode_nr_meas_config_direct.
    # #N closed both decoder gaps (radioBearerConfig structural skip; the
    # RRC-RECONF bare-SEQUENCE entry), validated field-for-field against pycrate
    # on the real 0xB821 corpus (DL-DCCH 124/124, RRC-RECONF 23/23).
    if msg_data and (
        (channel_name == "DL-DCCH" and msg_class_name == "rrcReconfiguration")
        or channel_name == "RRC-RECONF"
    ):
        if channel_name == "RRC-RECONF":
            mc = decode_nr_meas_config_direct(log_time, msg_data)
        else:
            mc = decode_nr_meas_config(log_time, msg_data)
        if mc is not None and (mc.nr_objects or mc.eutra_objects):
            result.meas_objects = mc.nr_objects
            result.meas_eutra_objects = mc.eutra_objects
            result.meas_s_measure_ssb = mc.s_measure_ssb
            result.meas_s_measure_csi = mc.s_measure_csi

    return result
