"""LOG_GNSS_CLOCK_REPORT (0x1478) parser.

Split out of the legacy ``gnss_gps.py`` cluster file per #N tier-2
batch. Companion log codes 0x1477 (LOG_GNSS_GPS_MEASUREMENT_REPORT) and
0x147B (LOG_GNSS_CD_DB_REPORT) moved to ``diag_0x1477.py`` and
``diag_0x147b.py`` respectively.

Historical note: 0x1478 was previously mis-named "GPS RF Status" in this
codebase. An external MIT reference (clean-room safe) enumerates it as
LOG_GNSS_CLOCK_REPORT; the real "RF hardware status" log code is 0x147E
(LOG_GNSS_PRX_RF_HW_STATUS_REPORT). The backward-compat alias
``GpsRfStatus`` lives in ``apps/diaggpsd/gnss_packets.py``.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_GNSS_CLOCK_REPORT_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        LOG_GAN_HANDIN_COMMAND
            source: qxdm_3_12_714_2017_diag_log_codes

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.codes import LOG_GNSS_CLOCK_REPORT
from diaggrok.registry import register


@dataclass
class Diag0x1478:
    """LOG_GNSS_CLOCK_REPORT (0x1478).

    Multi-constellation GNSS clock report emitted at 1 Hz. 13-byte header
    RE'd 2026-04-11 (#N) against EG18-NA and FN980m captures; body region
    is preserved as ``raw`` for future work.

    ## Header layout (13 B, validated 2026-04-11)

        byte 0:     u8   version        (3 on SDX20 V2, 4 on SDX55)
        byte 1..2:  u16  flags          0x01ff on every observed record —
                                        plausibly a GNSS constellation /
                                        signal enable mask (9 low bits set)
        byte 3..6:  u32  f_count        frame counter, ~1 Hz increment
        byte 7..8:  u16  gps_week       validated: matches the capture's
                                        actual GPS week (2413 during
                                        the 2026-04-11 captures)
        byte 9..12: u32  gps_ms         GPS time of week in ms, matches
                                        the clock in 0x1477/0x1480/0x147B
                                        on the same epoch

    ## Size variants
    - 156 B on MDM9207 (version 2, EG25-G OCPU 30.201)
    - 174 B on SDX20 V2 (version 3, EG18-NA / LM960)
    - 221 B on SDX55 (version 4, FN980m / RM500Q)

    The body (bytes 13..end) contains per-constellation clock state —
    time bias, frequency bias, drift uncertainty, and similar fields —
    not yet fully RE'd. Tracked in #N.

    ## #N detection capability — flags field as passive validator

    The ``flags`` u16 at bytes 1..2 is a passive validator for #N-class
    GNSS configuration drift, complementing the ``constellations`` field
    of 0x147E. Observed signatures:

      - EG25-G OCPU 30.201, indoor:        flags=0x0009 (~2 bits, GPS only)
      - EG18-NA pre-#N-fix:              flags=0x018f (mixed)
      - EG18-NA post-#N-fix v2:          flags=0x01ff (all 9 bits set)
      - FN980m SDX55, antenna outdoors:    flags=0x01ff

    The 0x70 difference between EG18-NA pre-fix (0x018f) and post-fix
    (0x01ff) correlates exactly with the GPS/BDS → GPS/GLO/BDS/GAL
    constellation set change in 0x147E's ``constellations`` field —
    same drift, two log codes confirm it. If a future capture reports
    flags below 0x01ff on a unit that should have all constellations
    enabled, the modem isn't actually tracking what its config claims.

    The cross-modem regression test class
    ``test_gnss_gps.py::TestGnssClockReportCrossModem`` locks these
    signatures in.
    """
    log_time: int
    version: int
    flags: int
    f_count: int
    gps_week: int
    gps_ms: int
    raw: bytes

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1478',
            'log_time': self.log_time,
            'version': self.version,
            'flags': self.flags,
            'f_count': self.f_count,
            'gps_week': self.gps_week,
            'gps_ms': self.gps_ms,
            'payload_size': len(self.raw),
        }


_VERSION_TO_SIZE = {0x02: 156, 0x03: 174, 0x04: 221}


# Ground-truth recipe (#N). Authored OFFLINE (hw_run_performed=False) — every
# field is a hypothesis until a hardware run on the SIM7600NA confirms it.
# Target: SIMCom SIM7600NA-H (MDM9207), the v=0x02 / 156B emitter. The decoded
# 13-byte header carries a GPS time (gps_week + gps_ms) plus a free-running
# frame counter (f_count) and a status word (flags). The GPS-time pair is the
# cleanest anchor candidate: under an open-sky fix it should equal the GPS time
# derivable from the modem's reported UTC. gps_week=0xFFFF / gps_ms=0 is the
# no-fix sentinel observed in the offline corpus peek — this recipe is only
# meaningful under cond:sky-fix.

@register(LOG_GNSS_CLOCK_REPORT, domain="gnss",
    name="0x1478",
    description="Multi-constellation GNSS clock state; 13-byte header decoded across 3 versions (v=0x02/156B, v=0x03/174B, v=0x04/221B); body preserved as raw for ongoing RE (#N)",
    version=6,
    # v5 (#N, 2026-06-11): sibling recipe (#N) for RM520N-GL @ RM520NGLAAR03A03M4G (SDX62 v=0x04) — gps_week=2422/gps_ms VERIFIED as GPS timestamp vs QGPSLOC UTC (HW <redacted-ref> 5174)
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail="EG18-NA SDX20 V2 + FN980m SDX55 DLF capture analysis (2026-04-11) + 53,723-record corpus walk (#N 2026-05-08); code name cross-checked against an external MIT reference that does not decode the body",
    source_url="",
    # 2026-05-08 corpus walk over 53,723 records / 196 captures (#N):
    #   v=0x04 / 221B: 24,654 records (45.9%)
    #   v=0x03 / 174B: 19,128 records (35.6%)
    #   v=0x02 / 156B:  9,941 records (18.5%)
    # Size is strictly version-correlated. Byte 1 = 0xff on 79.1% of corpus
    # and byte 2 has 3 dominant values (0x01=68.6%, 0x00=16.7%, 0x07=14.7%) —
    # the "flags=0x01ff" claim from the 2026-04-11 RE is the dominant case
    # but not invariant. Byte 3 (low byte of f_count) shows uniform
    # 256-value distribution as expected for a counter.
    field_invariants={"version": {"enum": [0x02, 0x03, 0x04]}},
    # fields_parsed/fields_identified intentionally unset: the dataclass
    # preserves the body region (bytes 13..end) as ``raw`` for ongoing
    # body-RE work, so any equal-value declaration would trip
    # test_no_fraudulent_completeness_claims. The unset state honestly
    # signals "header parsed, body unknown" to the parser inventory and
    # the diag-decode audit template. Re-declare 5/5 only after the body
    # is RE'd or the ``raw`` field is removed from Diag0x1478. (#N)
    # v6 (2026-06-27, #N cadence-sweep): tagged timebase_roles=
    # ("absolute-time", "ts-anchor") — the sibling LOG_GNSS_CLOCK_REPORT to the
    # already-tagged 0x147B, sharing the gps_week(u16@7)+gps_ms(u32@9) header.
    # Per-code, cross-chipset evidence (memory-safe single-capture sequential
    # decode + linear-fit, the #N method):
    #   * absolute-time — the header's gps_week + gps_ms are a real GPS week /
    #     time-of-week (HW-VERIFIED in _GROUND_TRUTH_0x1478 vs QGPSLOC). Decoded
    #     GPS time matches the capture's own wall-clock within ~1 min on TWO
    #     chipset generations:
    #       RM500Q-AE SDX55 v=0x04 (2026-06-12_213517 wardrive) — 658 fix recs,
    #         GPS->UTC 21:35:38 vs cap dir 21:35:17, monotonic, gps_week 2422.
    #       LM960 SDX20 v=0x03 (2026-06-09_144955 wardrive) — 1246 fix recs,
    #         GPS->UTC 14:50:31 vs cap dir 14:49:55, monotonic, gps_week 2422.
    #     gps_week=0xFFFF is the no-fix sentinel (same as 0x147B / 0x1478's own
    #     ground-truth peek) — the field is filled only on a valid fix.
    #   * ts-anchor — pairing each record's DIAG ts64 (log_time) with its header
    #     absolute GPS time is a clean linear map ts64 -> GPS wall-clock:
    #       SDX55: R²=1.0, slope 52428.63 ts64/ms, residual RMS 0.1 ms (n=658)
    #       SDX20: R²=1.0, slope 52429.20 ts64/ms, residual RMS 2.3 ms (n=1246)
    #     The slope is a chipset-invariant ~52428.8 ts64-units/ms == the known
    #     ts64 rate (cf. 0x1755 metronome / 0x147B ts-anchor). The residual is an
    #     ORDER OF MAGNITUDE tighter than 0x147B's ~70 ms — because this IS the
    #     GNSS clock report, its time-of-week is stamped off the same counter
    #     that drives ts64. Best ts-anchor exemplar in the corpus so far. Header
    #     decode unchanged; this is a metadata/capability tag only.
    timebase_roles=("absolute-time", "ts-anchor"),
)
def parse_0x1478(log_time: int, data: bytes) -> Diag0x1478 | None:
    """Parse a LOG_GNSS_CLOCK_REPORT (0x1478) log payload.

    Decodes the 13-byte header (version, flags, f_count, gps_week, gps_ms).
    Preserves the full payload as ``raw`` for downstream RE of the body
    region (bytes 13..end) which contains per-constellation clock state.

    Three version variants seen in corpus (size strictly version-correlated):
    - v=0x02 / 156-byte record — earliest variant (MDM9207, EG25-G)
    - v=0x03 / 174-byte record — SDX20 V2 (EG18-NA, LM960)
    - v=0x04 / 221-byte record — SDX55 (FN980m, RM500Q) and SDX62

    The ``flags`` u16 is `0x01ff` on the dominant subset (~69%) but cycles
    through `0x00ff` (~17%) and `0x07ff` (~15%) per the 2026-05-08 corpus
    walk — likely a constellation/signal enable mask whose low byte (byte 2)
    tracks enabled satellite systems.

    Layer-1 invariant: rejects (returns None on) any record whose
    (version, len) pair is outside the corpus-validated set above.
    A v=2 record at 174 bytes would silently mis-parse otherwise —
    that's the "same K bytes, new layout" trap (size-invariance does
    not imply format-invariance; a future firmware could ship v=5 at
    156 bytes with a different struct, and we want a visible parse-rate
    drop, not garbage output).
    """
    if len(data) < 13:
        return None
    # Explicit Layer-1 version gate (#N audit-visibility form). The
    # subsequent `_VERSION_TO_SIZE.get(version)` check is the semantic
    # gate; this explicit `not in` form makes the audit regex see it.
    if data[0] not in (0x02, 0x03, 0x04):
        return None
    version = data[0]
    expected_size = _VERSION_TO_SIZE.get(version)
    if expected_size is None or len(data) != expected_size:
        return None
    return Diag0x1478(
        log_time=log_time,
        version=version,
        flags=unpack_from('<H', data, 1)[0],
        f_count=unpack_from('<I', data, 3)[0],
        gps_week=unpack_from('<H', data, 7)[0],
        gps_ms=unpack_from('<I', data, 9)[0],
        raw=data,
    )
