"""0x14FD — split from gnss_nav_db.py per #N tier-3.

See module body for the per-code RE history and field map.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: RESERVED
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


# ---------------------------------------------------------------------------
# 0x14FD — two known size variants (218B / 391B), header-only
# ---------------------------------------------------------------------------
# Cross-corpus structural decomposition (RTCM-revisit <redacted-ref> 2026-04-27,
# 30,869 records / 137 captures; refreshed by the <redacted-ref> NEW-DATA re-check
# 2026-07-12, 62,494 records / 288 captures - see #N):
#
#   218B variant: byte0=0x08, byte3=0x00 (both constant). Seen on the older
#     SDX20 / MDM9x07 / MDM9x30 era parts: Quectel EG18-NA / EP06-A / EG12-GT
#     / EG25-G / EG95-NA, Sierra MC7455 / EM7455, SIMCom SIM7600NA, Telit LM960.
#   391B variant: byte0=0x0a, byte2=0x36, byte3=0x01 (all constant). Emitted on
#     the 5G-NR SDX silicon (SDX55/SDX62). The 2026-07-12 re-check grew this
#     from 2 chipsets (Telit FN980, Inseego M2000) to ~8: +Quectel RM500Q,
#     +Quectel RM520N-GL, +Sierra EM9291, +SIMCom SIM8202G-M2, +Foxconn
#     T99W175, +Wistron LV55. (size|byte0) stays a perfect 1:1 across all
#     62,494 records: 218|0x08 (33,711) and 391|0x0a (28,783).
#
# Byte 1 is NOT a counter despite prior naming — it takes 4 distinct values
# across the corpus (0x05 88.7%, 0x02 11.0%, 0x01 / 0x03 trace) and shows
# intra-capture variance in 75 captures, so it is an RF/state-dependent
# discriminator.

@dataclass
class Diag0x14FD:
    """GNSS data report (0x14FD) — 218B or 391B variant, header-only.

    Fields below cover the 4-byte header; the payload body remains opaque
    in ``body_raw``. Field meaning still pending decode; values listed are
    empirical corpus distributions, not type guarantees.
    """
    log_time: int
    version: int       # byte 0 — 0x08 on 218B variant, 0x0a on 391B variant
    state: int         # byte 1 — RF/state-dependent: 0x05/0x02/0x01/0x03 observed
    byte2: int         # byte 2 — chipset/variant correlated; 0x36 const on 391B
    byte3: int         # byte 3 — 0x00 on 218B variant, 0x01 on 391B variant
    payload_size: int
    body_raw: bytes

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x14FD',
            'log_time': self.log_time,
            'version': self.version,
            'state': self.state,
            'byte2': self.byte2,
            'byte3': self.byte3,
            'payload_size': self.payload_size,
        }


# --- Ground-truth recipe (#N) -------------------------------------------
# Authored offline (<redacted-ref>) for Sierra EM9291 (SWIX65C_02.17.08.00, SDX65)
# — the largest zero-recipe corpus modem. EM9291 emits the 391B / v=0x0a variant
# (confirmed from real records: byte0=0x0a, len=391 — newly observed; the
# docstring previously listed only Telit FN980 / Inseego M2000 as 391B emitters).
# Header-only parser: body opaque in body_raw, so the only RF-state-bearing field
# is `state` (byte 1). hw_run_performed=False — hypothesis only.

@register(
    0x14FD, domain="gnss",
    name="0x14FD",
    description="GNSS data report (0x14FD) — 218B / 391B variants, header-only",
    version=1,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail="Clean-room RE from FN980m SDX55 + EG18-NA SDX20 V2",
    source_url="",
    issues=(),
    primary_issue=None,
    # Completeness metadata (#N / #N 2026-05-22 closure-rigor pass): the
    # 4 header fields (version, state, byte2, byte3) are both identified in
    # the docstring and exposed via to_dict(). The 214B (218B variant) /
    # 387B (391B variant) body remains opaque in body_raw — NOT counted in
    # the denominator, so 4/4 means "everything identified is parsed", not
    # "100% of bytes decoded" (a documented inventory caveat).
    fields_identified=4,
    fields_parsed=4,
    field_invariants={
        "version": {"enum": [0x08, 0x0a]},
        "payload_size": {"enum": [218, 391]},
        "byte3": {"enum": [0x00, 0x01]},
    },
)
def parse_0x14fd(log_time: int, data: bytes) -> Diag0x14FD | None:
    if len(data) < 4:
        return None
    # Layer-1 enforcement of field_invariants version=[0x08, 0x0a] (#N).
    # Corpus (#N, 30,869 records / 137 captures): v=0x08 @ 218B (SDX20/
    # MDM9x07/MDM9x30 era), v=0x0a @ 391B (SDX55 era). Clean 1:1 (version,
    # payload_size) mapping cross-validated against (byte2, byte3) constants.
    if data[0] not in (0x08, 0x0a):
        return None
    return Diag0x14FD(
        log_time=log_time,
        version=data[0],
        state=data[1],
        byte2=data[2],
        byte3=data[3],
        payload_size=len(data),
        body_raw=data[4:],
    )


