"""0x1455 — GNSS epoch counter (7B fixed, all bytes named).

Cross-chipset RE corpus (2026-04-21): 4204 records across 14 chipset+firmware
pairs — EG18-NA (SDX20 V2), EP06A (MDM9x07), EM7511 (MDM9650), FN980m (SDX55),
LM960 32.01.110/120/140/150 + LM960A18 (SDX20).

Field map:
  [0]    u8    version          = 0x00 (CONSTANT 4204/4204)
  [1:5]  u32LE sequence         cumulative count of successful GNSS position
                                  fixes (F3-grounded, see below). +1 per record;
                                  cumulative across sessions (NOT per-capture-
                                  scoped: an EG18-NA capture opened mid-count at
                                  seq=233/299). The "occasional skip gaps" noted
                                  originally are an LM960-specific artifact; the
                                  EG18-NA showed strict +1 steps. u32 not u8
                                  (corrected from the prior stub; observed up to
                                  ~2800 in long captures).
  [5]    u8    flags            = 0x02 (CONSTANT 4204/4204)
  [6]    u8    reserved_6       = 0x00 (CONSTANT 4204/4204)

All 7 bytes named; no body_raw region; fully decoded across 14 chipsets.

F3 semantic grounding (2026-07-13, #N, offline oracle): `sequence` was
confirmed to be the cumulative successful-fix count by aligning 0x1455 records
against the firmware's own fix-report F3 debug prints (`ale_proc.c` "NF: PFR,
Report FIX to SM" / `lm_mgp.c` "=LM TASK= Received FIX REPORT from MGP") on two
GUID-matched-qdb EG18-NA captures (guid f1007b36). Each 0x1455 record trails a
fix-report F3 event by a near-constant ~0.37M ticks (<1% of the ~52M-tick inter-
fix interval), and `sequence` increments in exact 1:1 lockstep with those events
(253 records / 250 fix events across 2 captures; per-record delta == 1
throughout). This validates the vendor name LOG_CGPS_DIAG_SUCCESSFUL_FIX_COUNT_C
without hardware, independent of the AT$GPSACP HW recipe (which remains blocked
on #N/#N).

Split from `gnss_demod.py` per #N tier-2 batch 12.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_CGPS_DIAG_SUCCESSFUL_FIX_COUNT_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        LOG_GPS_TM_ON_DEMAND_DONE
            source: qxdm_3_12_714_2017_diag_log_codes

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register

LOG_GNSS_COUNTER_1455 = 0x1455


# Ground-truth capture recipe (#N / #N — <redacted-ref> 2026-06-07). ONE recipe:
# v=0x00 on the Telit LM960A18 (SDX20), the modem this code is corpus-attested
# on (33 LM960 captures; the parser RE corpus explicitly lists LM960
# 32.01.110/120/140/150 + LM960A18). Authored OFFLINE, hw_run_performed=False — a later
# hardware run flips it.
#
# 0x1455 is a COUNTER-CORRELATION recipe, not a value-equality one. Vendor name
# (LOG_CGPS_DIAG_SUCCESSFUL_FIX_COUNT_C, qualcomm_diag_log_codes_h /
# vendor_official) says `sequence` is a running count of successful GNSS fixes.
# No AT command returns this internal counter directly, so it can't be read off
# a single reply; instead its INCREMENTS are grounded against observed
# successful-fix events. Hold a sky-view fix (cond=sky-fix) and poll AT$GPSACP
# at a fixed cadence in lockstep with the DIAG stream: each successful-fix
# transition in $GPSACP (<fix> field 6 → 2/3) should coincide with a +1 step in
# `sequence` (occasional skip gaps were observed on the LM960 — so the
# hypothesis is monotonic correspondence of fix events to counter steps, not
# strict 1:1). version/flags/reserved_6 are structural constants (0x00/0x02/
# 0x00), not physical quantities, and are intentionally not grounded.
#
# NOT YET VALIDATED. The bench LM960 (e3296e3) can't validate it now: the DIAG
# port fails the diaggulp log-mask handshake (#N/#N), so no 0x1455 stream
# is capturable yet.

@dataclass
class Diag0x1455:
    """GNSS epoch counter (0x1455) — 7B fixed, all bytes named (#N)."""
    log_time: int
    version: int         # [0] = 0x00 CONSTANT
    sequence: int        # [1:5] u32 LE — monotonic epoch counter
    flags: int           # [5]   = 0x02 CONSTANT
    reserved_6: int      # [6]   = 0x00 CONSTANT
    payload_size: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1455',
            'log_time': self.log_time,
            'version': self.version,
            'sequence': self.sequence,
            'flags': self.flags,
            'reserved_6': self.reserved_6,
            'payload_size': self.payload_size,
        }


@register(
    LOG_GNSS_COUNTER_1455, domain="gnss",
    name="0x1455",
    description="GNSS epoch counter (0x1455) — 7B fixed, all bytes named",
    version=2,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Cross-chipset RE (2026-04-21, #N): 4204 records across 14 "
        "chipset+firmware pairs — EG18-NA SDX20 V2, EP06A MDM9x07, EM7511 "
        "MDM9650, FN980m SDX55, LM960 32.01.110/120/140/150 + LM960A18 "
        "SDX20. Every byte named: version/sequence(u32 LE)/flags/reserved. "
        "Prior stub read sequence as u8 which wraps at 256; corrected to "
        "u32 LE at [1:5] (observed up to ~2800 in long captures)."
    ),
    source_url="",
    issues=(),
    fields_identified=5,
    fields_parsed=5,
    # Layer-2 invariants from 2026-04-21 RE corpus (4204/4204 records across
    # 14 chipset+firmware pairs). version/flags/reserved_6 are corpus-wide
    # constants on every observed record; payload_size is strictly 7B (the
    # parser already rejects len != 7 at Layer 1). Declaring here per #N
    # adoption sweep so future drift (new chipset emits version=0x01, or a
    # 7B foreign payload routes here) surfaces via the Layer-2 violation
    # pipeline rather than getting silently re-decoded.
    field_invariants={
        "version": {"enum": [0x00]},
        "flags": {"enum": [0x02]},
        "reserved_6": {"enum": [0x00]},
        "payload_size": {"enum": [7]},
    },
)
def parse_0x1455(log_time: int, data: bytes) -> Diag0x1455 | None:
    if len(data) != 7:
        return None
    if data[0] != 0x00:
        return None
    return Diag0x1455(
        log_time=log_time,
        version=data[0],
        sequence=unpack_from('<I', data, 1)[0],
        flags=data[5],
        reserved_6=data[6],
        payload_size=len(data),
    )
