"""LTE ML1 Connected-Mode Neighbor Cell Measurement parser (0xB195).

0xB195 -- LTE ML1 Connected-Mode Neighbor Cell Measurement Request/Response
    Per-cell connected-mode neighbor cell measurements while the UE is in
    RRC_CONNECTED. Emitted during the L1 measurement gap so the UE can
    measure neighbor cells without losing the serving link.

    The connected-mode variant is the primary source for handover-quality
    neighbor data during active data sessions — complements 0xB192 (idle
    mode) and 0xB193 (serving cell).

Payload structure (version 1, MDM9207 / SDX-class subpacket variant
v3 request + v4 response, 100 bytes total):

    [0]      u8   version (1)
    [1]      u8   num_subpackets (2)
    [2:4]    u16  measurement counter / SFN

    Subpacket 0 (id=30, ver=3, size=32) -- Request/Config:
        [0:4]    u32  EARFCN (low 18 bits)
        [4:8]    u32  config flags / cell count hint
        [8:12]   u32  serving PCI bitfield
        [12:16]  u32  scheduling/timing
        [16:20]  u32  rotation timing
        [20:24]  u32  rotation timing (mirror)
        [24:28]  u32  reserved (zeros)

    Subpacket 1 (id=31, ver=4, size=64) -- Response/Measurement:
        [0:4]    u32  EARFCN (low 18 bits)
        [4:6]    u16  num_cells
        [6:8]    u16  reserved

        Per-cell record (52 bytes each — same layout as 0xB192):
            [0:2]    u16  PCI
            [4:8]    u32  timing field 1
            [8:12]   u32  timing field 2 (TX/RX delta)
            [12:16]  u32  timing field 1 mirror (Rx pair)
            [24:26]  u16  RSRP raw (RSRP_dBm = -raw / 10.0)
            [36:38]  u16  RSRQ Rx0 raw (dB = (raw-60)/2.0)
            [38:40]  u16  RSRQ Rx1 raw (dB = (raw-60)/2.0)

Reverse-engineered from EG25-G OCPU 30.201 DLF capture
(<redacted-pii>,
46 records, all 100 bytes, all single-cell on EARFCN 5035 / PCI 404).

The per-cell record layout is byte-compatible with 0xB192's per-cell
record at the PCI/RSRP/RSRQ field offsets, so this parser shares the
extraction primitives with the idle-mode neighbor parser.

**v40 variant (LV55 SDX55):** the LV55 (Qualcomm SDX55) capture
(<redacted-pii>, 10
records, sizes 168/236) uses subpacket version **40** where the
num_cells field at offset 4 contains a different value. The parser
now computes cell count from body size when num_cells_raw > 32.
Cell record layout (PCI/RSRP/RSRQ offsets) is the same as v4.

Reference: GitHub issue #N

Techplayon QXDM field reference (sources/web/2026-04-07_techplayon_qxdm-log-packets.wacz),
canonical names per docs/qualcomm/techplayon-field-validation.md (#N Track 1)
+ docs/qualcomm/techplayon-cross-refs.md (#N Track 2):
    0xB195 — LTE ML1 Connected Neighbor Meas Request/Response
        Request: earfcn, serving_cell_index, measurement_gap_period_ms,
            measurement_gap_mask, neighbor_pci, cyclic_prefix_type,
            frame_boundary_offset, cir_timing_adjustment_samples
        Response: rsrp_rx0_dbm, rsrp_rx1_dbm, rsrp_combined_dbm,
            rsrq_rx0_db, rsrq_rx1_db, rsrq_instantaneous_db,
            rssi_rx0_dbm, rssi_rx1_dbm

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_LTE_ML1_CONNECTED_MODE_NEIGHBOR_MEAS_REQ_RESP
        source: qxdm_3_12_714_2017_diag_log_codes (authority: community)
    aliases:
        LOG_LTE_ML1_CONNECTED_NEIGHBOR_MEAS_REQUEST_RESPONSE
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass, field
from struct import unpack_from
from typing import Any

from diaggrok.codes import LOG_LTE_ML1_CONNECTED_NEIGHBOR_MEAS
from diaggrok.registry import register


_REQUEST_SP_ID = 30
_RESPONSE_SP_ID = 31
_RESPONSE_SP_VERSION = 4
_CELL_RECORD_SIZE = 52
_CARRIER_HEADER_SIZE = 8


@dataclass
class LteMl1ConnectedNeighborEntry:
    """A single connected-mode neighbor cell measurement."""
    pci: int
    earfcn: int
    rsrp: float       # dBm (combined Rx)
    rsrq_rx0: float   # dB
    rsrq_rx1: float   # dB

    def to_dict(self) -> dict[str, Any]:
        return {
            'pci': self.pci,
            'earfcn': self.earfcn,
            'rsrp': self.rsrp,
            'rsrq_rx0': self.rsrq_rx0,
            'rsrq_rx1': self.rsrq_rx1,
        }


@dataclass
class Diag0xB195:
    """LTE ML1 Connected-Mode Neighbor Cell Measurement (0xB195)."""
    log_time: int
    version: int
    earfcn: int
    num_cells: int
    entries: list[LteMl1ConnectedNeighborEntry] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0xB195',
            'log_time': self.log_time,
            'version': self.version,
            'earfcn': self.earfcn,
            'num_cells': self.num_cells,
            'entries': [e.to_dict() for e in self.entries],
        }


# Ground-truth recipe (#N) — EC25/EG25 family (MDM9607) LTE connected-mode
# neighbor measurement. 0xB195 is the cleanest EC25 LTE target: every decoded
# per-cell field maps 1:1 to a Quectel AT+QENG="neighbourcell" column. RSRP/RSRQ
# raw→engineering conversions are applied IN the parser, so the validator
# compares decoded dBm/dB directly. cond="connected": the connected-mode
# neighbor log only fires while the UE is RRC_CONNECTED (active data session),
# so the capture must drive a sustained download while polling QENG.

@register(LOG_LTE_ML1_CONNECTED_NEIGHBOR_MEAS,
    name="0xB195",
    description="Connected-mode neighbor PCI, EARFCN, RSRP, RSRQ from 0xB195 sp31v4/v40 — all variants",
    version=6,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v1: EG25-G OCPU 30.201 DLF capture (46 records, 100B single-cell). "
        "v2 (2026-05-08, #N): corpus walk (9 captures, 202 records) "
        "validated outer version=0x01 invariant across 100% of records, "
        "and catalogued the size progression: 100B (1 cell, 35%), "
        "168B (2 cells, 29%), 236B (3 cells, 22%), 304B (4 cells, 11%), "
        "372B (5 cells, 2%) — +68B increment per added cell. The parser "
        "computes num_cells from body size on the v40 SP variant; entry "
        "decode (PCI/EARFCN/RSRP/RSRQ Rx0/Rx1) is byte-compatible with "
        "the v4 layout and validates across the full size range."
    ),
    source_url="",
    issues=(),
    primary_issue=None,
    # Header fields: outer version, earfcn, num_cells (3) + per-cell:
    # pci, earfcn, rsrp, rsrq_rx0, rsrq_rx1 (5) — total 8.
    fields_identified=8, fields_parsed=8,
    field_invariants={
        "version": {"enum": [0x01]},
    },
    wigle_direct=True,
    wigle_roles=("signal", "pci-earfcn-bridge", "rat-context"),
)
def parse_0xb195(
    log_time: int, data: bytes
) -> Diag0xB195 | None:
    """Parse 0xB195 -- LTE ML1 Connected-Mode Neighbor Cell Measurement.

    Walks subpackets to find the response subpacket (id=31, ver=4),
    extracts per-cell PCI, EARFCN, RSRP, and RSRQ Rx0/Rx1.

    Returns ``None`` for malformed payloads or for the v40 LV55 variant
    (which uses a different layout and is not yet RE'd).
    """
    if len(data) < 8:
        return None

    version = data[0]
    if version != 1:
        return None
    num_subpackets = data[1]
    if num_subpackets < 1:
        return None

    # Walk subpackets to find the response subpacket (id=31)
    offset = 4  # skip outer header (version + num_sp + counter)

    for _ in range(num_subpackets):
        if offset + 4 > len(data):
            return None

        sp_id = data[offset]
        sp_ver = data[offset + 1]
        sp_size = unpack_from('<H', data, offset + 2)[0]

        if sp_size < 4 or offset + sp_size > len(data):
            return None

        if sp_id == _RESPONSE_SP_ID:
            sp_data = data[offset + 4:offset + sp_size]
            return _parse_response_subpacket(log_time, version, sp_data, sp_ver)

        offset += sp_size

    return None


def _parse_response_subpacket(
    log_time: int, version: int, sp: bytes, sp_ver: int = 4
) -> Diag0xB195 | None:
    """Parse the response subpacket data (id=31).

    Handles both v4 (MDM9207/EG25-G) and v40 (SDX20/LV55) variants.
    The cell record layout at PCI/RSRP/RSRQ offsets is the same across
    versions — only the num_cells field location differs.
    """
    if len(sp) < _CARRIER_HEADER_SIZE:
        return None

    earfcn_raw = unpack_from('<I', sp, 0)[0]
    earfcn = earfcn_raw & 0x3FFFF
    num_cells_raw = unpack_from('<H', sp, 4)[0]

    if earfcn > 262143:
        return None

    # For v40 (SDX20/LV55), the num_cells field at offset 4 contains
    # a different value. Compute num_cells from body size instead.
    if num_cells_raw > 32:
        body_size = len(sp) - _CARRIER_HEADER_SIZE
        num_cells = body_size // _CELL_RECORD_SIZE
    else:
        num_cells = num_cells_raw

    entries: list[LteMl1ConnectedNeighborEntry] = []

    for i in range(num_cells):
        cell_offset = _CARRIER_HEADER_SIZE + i * _CELL_RECORD_SIZE
        if cell_offset + _CELL_RECORD_SIZE > len(sp):
            break

        pci = unpack_from('<H', sp, cell_offset)[0]
        if pci > 503:
            continue

        # RSRP: u16 at cell offset 24, scaled as -raw/10.0 dBm
        rsrp_raw = unpack_from('<H', sp, cell_offset + 24)[0]
        rsrp = -rsrp_raw / 10.0
        if not (-140.0 <= rsrp <= -30.0):
            continue

        # RSRQ Rx0/Rx1: u16 at cell offsets 36/38, scaled as (raw-60)/2.0 dB
        rsrq_rx0_raw = unpack_from('<H', sp, cell_offset + 36)[0]
        rsrq_rx1_raw = unpack_from('<H', sp, cell_offset + 38)[0]
        rsrq_rx0 = (rsrq_rx0_raw - 60) / 2.0
        rsrq_rx1 = (rsrq_rx1_raw - 60) / 2.0
        # RSRQ valid range -34..+2.5 dB per 3GPP TS 36.133 §9.1.7
        if not (-34.0 <= rsrq_rx0 <= 2.5):
            continue
        if not (-34.0 <= rsrq_rx1 <= 2.5):
            continue

        entries.append(LteMl1ConnectedNeighborEntry(
            pci=pci, earfcn=earfcn,
            rsrp=round(rsrp, 1),
            rsrq_rx0=round(rsrq_rx0, 1),
            rsrq_rx1=round(rsrq_rx1, 1),
        ))

    return Diag0xB195(
        log_time=log_time,
        version=version,
        earfcn=earfcn,
        num_cells=num_cells,
        entries=entries,
    )
