"""0x1D23 — LOG_GNSS_POWER_PROFILING_REPORT_C (structural stub, #N).

**Canonical name** per the zukgit blog (`Qcom_GPS_ModemLog_排查分析`,
2024-10-31, linked in #N 2026-04-30 comment):

  ``LOG_GNSS_POWER_PROFILING_REPORT_C``

Despite the issue title saying "NR5G ML1" (a code-range heuristic guess),
the canonical name places this code firmly in the **GNSS subsystem** —
specifically GNSS power profiling, fired around radio-on/off transitions.
This is consistent with the edge-trigger signature observed in the
2026-04-22 RM520N wardrive analysis: single firing immediately after a
6-record 0x18AE (LTE RRC CA-combos) burst, suggesting it lands when
GNSS power state evaluates a reconfig boundary.

Corpus snapshot (2026-05-23, 1 capture, 1 record, walked via
`tools/parser_corpus_summary.py --code 0x1D23 --offsets 0,1,2,3,4`):
  - Single 54-byte record from
    `<redacted-pii>`
  - Modem: RM520N-GL (SDX62), firmware RM520NGLAAR03A03M4G_A0.303.A0.303
  - Version (+0) = 0x04, bytes +1..+4 = 0x00, 0x00, 0x00, 0x00

Structural layout (per the 2026-04-22 analysis in #N):
  [0]       u8     version = 4
  [0x00..0x1B] 28B  "context block" — densely-packed nested enum/index
                    tuple (small integers, 0x01..0x04 + 0x00 separators);
                    individual field semantics unknown
  [0x1C..0x33] 24B "trailer" — three u32 counters/ticks + zero gap +
                    flag byte + 2 B; two u32s at 0x28 / 0x30 have the
                    form 0x??00_0000 (likely monotonic counters)
  Total 54 B

Per the project's burned-in `size invariance ≠ format invariance` rule
AND the user closure-rigor directive ("knowing the STRUCTURE of a
message does NOT qualify it for closure — we must know WHAT data is
in the message"): this parser is a **hardening-only stub**. The
54-byte fixed size + v=4 invariant from a single-record corpus is too
thin to claim cross-firmware format stability — declaring
`field_invariants={"version": {"enum": [4]}, "payload_size": {"enum":
[54]}}` makes the layer-2 check reject future v≠4 / size≠54 records
rather than silently mis-parse them under the v=4 assumption.

**Issue #N stays open.** Closure requires:
  - More samples (N=1 is hypothesis-only — see <redacted-ref> small-N rule)
  - Cross-modem / cross-firmware confirmation (currently RM520N-only)
  - Field-level decoding of the 28-B context block + 24-B trailer
    using the LOG_GNSS_POWER_PROFILING_REPORT_C semantic (Qualcomm
    spec or AT-correlation with QGPS/QGPSGNMEA on the firing
    timestamp)

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: RESERVED
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


@dataclass
class Diag0x1D23:
    """0x1D23 — LOG_GNSS_POWER_PROFILING_REPORT_C structural stub (#N)."""
    log_time: int
    version: int
    context_block: bytes        # 28 B at [0..0x1B] — densely-packed enum/index
    trailer_u32_a: int          # u32LE at 0x1C
    trailer_u32_b: int          # u32LE at 0x20
    trailer_u32_c: int          # u32LE at 0x24
    counter_u32_a: int          # u32LE at 0x28 (monotonic-counter hypothesis)
    counter_u32_b: int          # u32LE at 0x30 (monotonic-counter hypothesis)
    trailer_tail: bytes         # 2 B at [0x34..0x36]
    payload_size: int
    body_raw: bytes

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": "Diag0x1D23",
            "log_time": self.log_time,
            "version": self.version,
            "context_block_hex": self.context_block.hex(),
            "trailer_u32_a": self.trailer_u32_a,
            "trailer_u32_b": self.trailer_u32_b,
            "trailer_u32_c": self.trailer_u32_c,
            "counter_u32_a": self.counter_u32_a,
            "counter_u32_b": self.counter_u32_b,
            "trailer_tail_hex": self.trailer_tail.hex(),
            "payload_size": self.payload_size,
            "body_raw": self.body_raw,
        }


@register(
    0x1D23,
    name="0x1D23",
    description="LOG_GNSS_POWER_PROFILING_REPORT_C (0x1D23) — GNSS structural stub (#N)",
    version=1,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail="Canonical name LOG_GNSS_POWER_PROFILING_REPORT_C per zukgit blog (2024-10-31, linked in #N). Structural layout from the 2026-04-22 <redacted-pii> single-record analysis (54 B = 28 B context + 24 B trailer + 2 B tail). N=1 — hardening only, NOT closure.",
    source_url="",
    issues=(),
    fields_identified=8,
    fields_parsed=8,
    field_invariants={
        "version": {"enum": [4]},
        "payload_size": {"enum": [54]},
    },
)
def parse_0x1d23(log_time: int, data: bytes) -> Diag0x1D23 | None:
    if len(data) != 54:
        return None
    if data[0] != 0x04:
        return None
    trailer_u32_a, trailer_u32_b, trailer_u32_c = unpack_from('<3I', data, 0x1C)
    counter_u32_a = unpack_from('<I', data, 0x28)[0]
    counter_u32_b = unpack_from('<I', data, 0x30)[0]
    return Diag0x1D23(
        log_time=log_time,
        version=data[0],
        context_block=bytes(data[0:0x1C]),
        trailer_u32_a=trailer_u32_a,
        trailer_u32_b=trailer_u32_b,
        trailer_u32_c=trailer_u32_c,
        counter_u32_a=counter_u32_a,
        counter_u32_b=counter_u32_b,
        trailer_tail=bytes(data[0x34:0x36]),
        payload_size=len(data),
        body_raw=bytes(data[1:]),
    )
