"""0x1490 — GNSS state/event report (14B fixed, all bytes named).

Cross-chipset RE corpus (2026-04-21): 8342 records across 14 chipset+firmware
pairs — EG18-NA (SDX20 V2), EP06A (MDM9x07), EM7511 (MDM9650), FN980m (SDX55),
LM960 32.01.110/120/140/150 + LM960A18 (SDX20).

Field map:
  [0]    u8    version          = 0x00 (CONSTANT 8342/8342)
  [1]    u8    state_byte       ∈ {0xA3 (8310), 0x59 (32)} — 2-state machine:
                                   0xA3 = steady-state (post-init)
                                   0x59 = boot/reset event (32/8342 records,
                                          exclusively on cold-reset post or
                                          reboot-v2 post captures)
  [2]    u8    sub_state        ∈ {0x0D (8310), 0x1B (32)} — locked to
                                   state_byte (A3↔0D, 59↔1B, 32/32 boot-state
                                   records co-occur with sub_state=0x1B).
  [3:5]  u16LE reserved_3_4     = 0 (CONSTANT 8342/8342)
  [5]    u8    status           ∈ {0x07 (4184), 0x01 (4099), 0x1D (32),
                                   0x00 (15), 0x09 (7), 0x08 (5)} —
                                   6-value status enum. 0x1D correlates 1:1
                                   with boot-state (byte[1]=0x59).
                                   0x01/0x07 are the two steady-state values
                                   (49%/50% distribution) — likely a bistable
                                   "fix/no-fix" toggle on 1Hz cadence.
  [6]    u8    event_flag       ∈ {0x00 (8327), 0x0C (9), 0x09 (6)} —
                                   secondary event flag; non-zero iff
                                   status ∈ {0, 8, 9} (transition records).
  [7:14] 7B    reserved_7_13    = 0 (CONSTANT 8342/8342)

All 14 bytes named; no body_raw region; fully decoded across 14 chipsets.

Split from `gnss_demod.py` per #N tier-2 batch 12.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_GNSS_PDSM_PD_EVENT_CALLBACK_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        LOG_GAN_WAKEUP_REQUEST
            source: qxdm_3_12_714_2017_diag_log_codes

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register

LOG_GNSS_STATE_1490 = 0x1490

# Status-byte enum mapping — empirical semantics from edge-case analysis.
GNSS_STATE_1490_STATUS: dict[int, str] = {
    0x00: 'transition',          # correlated with event_flag=9
    0x01: 'steady_01',           # steady-state value A
    0x07: 'steady_07',           # steady-state value B (near-equal counts)
    0x08: 'transition_08',       # rare, correlated with event_flag
    0x09: 'transition_09',       # rare, correlated with event_flag
    0x1D: 'boot_event',          # exclusive with state_byte=0x59/sub_state=0x1B
}

GNSS_STATE_1490_STATE_NAMES: dict[int, str] = {
    0xA3: 'steady',
    0x59: 'boot',
}


@dataclass
class Diag0x1490:
    """GNSS state/event report (0x1490) — 14B fixed, all bytes named (#N)."""
    log_time: int
    version: int             # [0] = 0x00 CONSTANT
    state_byte: int          # [1] ∈ {0xA3, 0x59}
    state_name: str          # derived
    sub_state: int           # [2] ∈ {0x0D, 0x1B}, locked to state_byte
    reserved_3_4: int        # [3:5] u16 LE = 0 CONSTANT
    status: int              # [5] 6-value enum
    status_name: str         # derived
    event_flag: int          # [6] secondary event flag
    reserved_7_13: bytes     # [7:14] 7B = 0 CONSTANT
    payload_size: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1490',
            'log_time': self.log_time,
            'version': self.version,
            'state_byte': self.state_byte,
            'state_name': self.state_name,
            'sub_state': self.sub_state,
            'reserved_3_4': self.reserved_3_4,
            'status': self.status,
            'status_name': self.status_name,
            'event_flag': self.event_flag,
            'payload_size': self.payload_size,
        }


# Ground-truth recipe (#N) — EC25/EG25 family (MDM9607). Vendor-official name
# LOG_GNSS_PDSM_PD_EVENT_CALLBACK_C confirms this is a GNSS position-determination
# (PDSM) event callback, NOT a measurement record: its decoded bytes are STATE/
# STATUS/EVENT flags, none of which any AT command returns as a literal value.
# Per the counter/state-flag honesty rule these ground by CORRELATION — the flag
# must co-vary with an observable GNSS engine state, not equal an AT reply.
# cond="sky-fix": run outdoors / with sky view so the engine transitions through
# no-fix → acquiring → fix, exercising the state bytes.

@register(
    LOG_GNSS_STATE_1490, domain="gnss",
    name="0x1490",
    description="GNSS state/event report (0x1490) — 14B fixed, all bytes named",
    version=4,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Cross-chipset RE (2026-04-21, #N): 8342 records across 14 "
        "chipset+firmware pairs — EG18-NA SDX20 V2, EP06A MDM9x07, EM7511 "
        "MDM9650, FN980m SDX55, LM960 32.01.110/120/140/150 + LM960A18 "
        "SDX20. Every byte named: version/state/sub_state/reserved_3_4/"
        "status/event_flag/reserved_7_13. state_byte is 2-state (0xA3 "
        "steady, 0x59 boot); sub_state locked to state. status is 6-value "
        "enum; event_flag non-zero on transition records only. "
        "v3 (2026-05-11, #N audit follow-up — Wave 3 G1): added byte-0 "
        "version-byte hard gate (version == 0x00 across 50,510 records / "
        "27+ captures / 15 chipsets) before state_byte = data[1]. The audit "
        "flagged 'state_byte = data[1] first' — byte 0 was being assigned "
        "to `version` but never validated. field_invariants on version + "
        "reserved_3_4 were already declared in v2 (#N follow-up); this "
        "promotes the version invariant to a hard parser-body gate."
    ),
    source_url="",
    issues=(),
    fields_identified=9,
    fields_parsed=9,
    field_invariants={
        # Validated against 50,510 records / 27+ captures / 15 chipsets
        # (corpus reprocessing 2026-05-07, #N follow-up). version and
        # reserved_3_4 are 100% invariant across the entire corpus. Soft
        # enums (state_byte, sub_state, status, event_flag) have rare
        # single-record outliers in pre-reset / corrupted captures and
        # are documented in the field-map comment instead of declared
        # here — the parser falls back to f'unknown_{:#04x}' for them.
        "version": {"enum": [0]},
        "reserved_3_4": {"enum": [0]},
        # v3 (#N audit follow-up): payload size is corpus-constant.
        "payload_size": {"enum": [14]},
    },
)
def parse_0x1490(log_time: int, data: bytes) -> Diag0x1490 | None:
    if len(data) != 14:
        return None
    # v3 (#N audit follow-up): hard gate on version byte before reading
    # state_byte at data[1]. Audit flagged 'state_byte = data[1] first' —
    # the previous version assigned data[0] to `version` in the return
    # tuple but never validated it. Corpus: 50,510 records / 15 chipsets
    # all have version == 0x00.
    if data[0] != 0x00:
        return None
    state_byte = data[1]
    status = data[5]
    return Diag0x1490(
        log_time=log_time,
        version=data[0],
        state_byte=state_byte,
        state_name=GNSS_STATE_1490_STATE_NAMES.get(state_byte, f'unknown_{state_byte:#04x}'),
        sub_state=data[2],
        reserved_3_4=unpack_from('<H', data, 3)[0],
        status=status,
        status_name=GNSS_STATE_1490_STATUS.get(status, f'unknown_{status:#04x}'),
        event_flag=data[6],
        reserved_7_13=bytes(data[7:14]),
        payload_size=len(data),
    )
