"""0x7160 — LOG_UMTS_NAS_PPLMN_LIST, cross-chipset preferred-PLMN-list dump (#N).

⚠️ SEMANTIC CORRECTION (v4, 2026-07-17, F3-grounded). Earlier revisions of
this parser (v1–v3) framed 0x7160 as a "GNSS-engine-start cluster sibling"
(alongside 0x7153/0x7154/0x7155/0x7156) and dismissed the names-block
canonical `LOG_UMTS_NAS_PPLMN_LIST` as a "community mis-attribution". **That
framing was wrong and is scrubbed.** Three independent lines of evidence, the
last one an F3 ground-truth oracle no prior session had consulted, place this
code firmly in the **UMTS/NAS registration (PLMN-selection)** subsystem:

1. **Canonical-name family.** The whole contiguous 0x715x–0x716x block in
   `DIAG_LOG_INDEX.yaml` is one UMTS-NAS PLMN-list family (equipment_id 7, two
   agreeing community sources): 0x7153 HPLMN_SEARCH_TIMER_START, 0x7154
   HPLMN_SEARCH_TIMER_EXPIRE, 0x7155 HPLMN_SEARCH_START, 0x7156
   HPLMN_SEARCH_END, **0x7160 PPLMN_LIST**, 0x7161 LTE_CELL_LIST. The prior
   "GNSS cluster" was the *same* set of codes read under the wrong subsystem.

2. **Emission context (no GNSS engine involved).** On the Wistron LV55 — a
   Verizon 5G CPE with no GNSS use case — 0x7160 fires in every NAS/PLMN
   scenario and no GNSS scenario: `08_manual_plmn_scan`, `07_cops_dereg_cycle`,
   `03_lte_airplane_cycle`, `04_sim_power_cycle`, `12_psm_edrx_cycle`, PDP and
   reject cycles. The original LM960 "fires only on GNSS scenarios" reading was
   a boot-time confound — a full reboot triggers a NAS PLMN re-search, and the
   GNSS antenna happened to be attached.

3. **F3 ground truth (the decisive oracle).** In the co-temporal F3 window of a
   0x7160 emission (RM520N-GL cops capture `<redacted-pii>`), the
   firmware's own prints are entirely NAS/PLMN, zero GNSS:
     - `reg_mode.c:2264` dumps a PLMN table — MCC-MNC / RAT / HPLMN / priority /
       EARFCN rows (`310-260 LTE HPLMN`, `311-480 NR5G`, `310-410 NR5G`, ...).
     - `reg_mode.c:7291  reg_mode_update_available_plmn_list`.
     - `mmgsdicache.c` SIM-EF cache reads.

## Structure (unchanged decode; re-interpreted)

The header decode is unchanged from v3 — only the *meaning* is corrected:

  byte[0]    = version      0x01 (SDX20) | 0x02 (SDX55+)     — Layer-1 gate
  byte[1]    = sub_flag     corpus-invariant 0x01
  bytes[2:4] = entry_count  LE u16 — number of POPULATED PLMN entries
                            (obs {70, 100}, intra-capture variance)
  bytes[4:]  = PLMN table   fixed 100-slot table (v2: 100×90 B = 9000 B;
                            v1: 100×80 B = 8000 B). See body note below.

## PLMN-table body (the correctly-framed open T1 lead)

The 9004 B (v2) / 8004 B (v1) envelope is size-invariant regardless of
`entry_count`, i.e. the body is a **fixed-capacity table**, not an
`entry_count`-length array — which is why the old "entry_count × 90 B stride"
test failed (the table is always 100 slots; entry_count counts the populated
ones). Direct inspection of a v2 record confirms the PLMN-list shape:

  - each 90 B slot begins with a 3-byte **BCD PLMN id** (`13 01 94` =
    MCC 310 …; `25 f0 50` = MCC 520 …),
  - unused slots past the populated region are the 3GPP `ff ff ff` "no PLMN"
    sentinel (slots 4+ in the observed record),
  - `entry_count` (=100 here) = populated-slot count.

The per-slot layout beyond the PLMN-id prefix (AcT bitmask, priority, domain,
EARFCN — the fields `reg_mode.c:2264` prints) is not yet fully mapped and stays
`body_raw`. It is now correctly groundable via **AT+CPOL** (reads the preferred
PLMN list w/ AcT) and **AT+COPS=?** (available-PLMN scan) — NOT the GNSS
`AT+QGPS*` levers the old recipes used.

## "Size invariance ≠ format invariance" hedge

Per `core-memories.md`: a future SDX65/SDX72 firmware can ship version 0x03 in
the same 8004/9004-byte envelope under a new struct layout. This parser
declares `field_invariants={"version": {"enum": [1, 2]}}` so a record with
`byte[0] not in {1, 2}` returns None and surfaces as a no-parser miss instead
of being silently mis-decoded. The (size, version) tuple is likewise enforced.

## Next steps (tracked on #N)

- Decode the per-slot PLMN entry: BCD PLMN-id (confirmed) + AcT/priority/domain/
  EARFCN. Ground against a co-captured `AT+CPOL` / `AT+COPS=?` readback and the
  co-temporal `reg_mode.c:2264` F3 table (both now identified as the oracles).
- Promote to T1 once the per-slot fields are named + grounded.
- Sibling cluster codes 0x7153/0x7154/0x7155/0x7156 (#N–#N) carry the SAME
  stale "GNSS-lifecycle" framing and need the same NAS-PLMN correction.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_UMTS_NAS_PPLMN_LIST
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


_LOG_CODE = 0x7160

# Cross-chipset (size, version) tuples observed across the corpus
# as of 2026-05-20 (#N).  Layer-1 gate; mismatched tuples return
# None.  Layer-2 invariant on the version enum below catches any
# silent drift if the gate is ever bypassed.
_VERSION_SDX20 = 0x01
_VERSION_SDX55_PLUS = 0x02
_SIZE_V1 = 8004
_SIZE_V2 = 9004
_OBSERVED_VERSIONS: tuple[int, ...] = (_VERSION_SDX20, _VERSION_SDX55_PLUS)
_VERSION_TO_SIZE = {
    _VERSION_SDX20: _SIZE_V1,
    _VERSION_SDX55_PLUS: _SIZE_V2,
}

# Header constants stable across all modems / both versions.
# byte[1] = sub-flag (role TBD, corpus-invariant 0x01).
_EXPECTED_SUB_FLAG = 0x01
# bytes[2:4] = entry_count (LE u16) — number of POPULATED PLMN entries.
# NOT a constant — 2026-06-26 re-walk (N=514) shows it is DYNAMIC:
# observed {70, 100} with *intra-capture* variance (one survey capture
# emits both 0x46 and 0x64). The body is a fixed-capacity 100-slot PLMN
# table regardless; entry_count counts the populated slots. The only
# invariant is the high byte (data[3]) == 0x00 (entry_count <= 255).
_ENTRY_COUNT_HI_INVARIANT = 0x00  # data[3] — corpus-wide 0x00 (N=514)
_ENTRY_COUNT_MAX = 0xFF           # high-byte-zero => value fits in a byte


@dataclass
class Diag0x7160:
    """0x7160 — LOG_UMTS_NAS_PPLMN_LIST preferred-PLMN-list header (#N)."""
    log_time: int
    version: int            # byte[0] — 0x01 (SDX20) | 0x02 (SDX55+)
    sub_flag: int           # byte[1] — corpus-invariant 0x01
    entry_count: int        # bytes[2:4] LE u16 — populated PLMN entries (obs {70,100})
    payload_size: int
    body_raw: bytes         # bytes[4:] — fixed 100-slot PLMN table (per-slot decode TBD)

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": "Diag0x7160",
            "log_time": self.log_time,
            "version": self.version,
            "sub_flag": self.sub_flag,
            "entry_count": self.entry_count,
            "payload_size": self.payload_size,
        }


# Ground-truth recipes (#N): per-(modem, version) TOMLs under
# ground_truth/0x7160/. Both were re-authored in v4 (2026-07-17) to the
# corrected NAS-PLMN framing — validating via AT+CPOL / AT+COPS=? that a
# 0x7160 record's PLMN table matches the modem's preferred/available PLMN
# list, NOT the old GNSS-engine-start trigger correlation (scrubbed).

@register(
    _LOG_CODE, domain="nas",
    name="0x7160",
    description=(
        "LOG_UMTS_NAS_PPLMN_LIST — preferred-PLMN-list dump, header-only "
        "decode (#N). Chipset-keyed (size, version) split: 8004 B / v=1 "
        "on SDX20 (LM960, MC7411, EM7565), 9004 B / v=2 on SDX55+ (FN980m, "
        "RM520N-GL). Header: version, sub_flag=0x01, entry_count (populated "
        "PLMN entries, DYNAMIC u16, obs {70,100}). Body is a fixed 100-slot "
        "PLMN table (v2 90 B/slot, v1 80 B/slot), per-slot decode NOT yet "
        "landed (BCD PLMN-id prefix + 0xFFFFFF-sentinel padding confirmed). "
        "F3-grounded to NAS reg_mode PLMN-list (v4, #N)."
    ),
    version=4,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room header RE across 4-modem / 3-vendor / 2-chipset "
        "corpus extracted 2026-05-20: LM960A18 SDX20 32.01.1X0, "
        "MC7411 SDX20 SWI9X50C_01.14.22.00, FN980m SDX55 M0H.030282 "
        "(AT&T profile 10), RM520N-GL SDX62 RM520NGLAAR03A03M4G. "
        "Clean chipset-keyed (size, version) split — same pattern as "
        "0x1C6E (#N) and 0x1636. Per-slot PLMN-entry layout not yet "
        "fully RE'd. "
        "v4 (2026-07-17, #N): SEMANTIC CORRECTION — the v1-v3 "
        "'GNSS-engine-start cluster' framing was refuted by F3 ground "
        "truth (reg_mode.c:2264 PLMN table + reg_mode_update_available_"
        "plmn_list co-temporal with the emission; zero GNSS F3), by the "
        "0x715x-0x716x canonical UMTS-NAS-PLMN name family, and by LV55 "
        "emission context (fires on manual_plmn_scan / cops_dereg / "
        "airplane / sim-cycle, not GNSS). domain gnss->nas; both "
        "GroundTruth recipes re-authored to AT+CPOL / AT+COPS grounding."
    ),
    source_url=(
        "F3 ground truth: reg_mode.c:2264 / reg_mode.c:7291 co-temporal "
        "with 0x7160 in RM520N-GL cops-f3 capture 20260626T225840Z (#N)"
    ),
    issues=(),
    fields_parsed=4,        # version + sub_flag + entry_count + payload_size
    fields_identified=4,
    # Layer-2 invariant — catches a future v3 firmware that ships
    # the same 8004 or 9004 byte envelope under a new struct layout.
    # See `core-memories.md` ("size invariance ≠ format invariance").
    field_invariants={
        "version": {"enum": list(_OBSERVED_VERSIONS)},
        "sub_flag": {"enum": [_EXPECTED_SUB_FLAG]},
        # entry_count is DYNAMIC (obs {70,100}, intra-capture variance) —
        # only the high-byte-zero structural bound is corpus-invariant.
        "entry_count": {"range": (0, _ENTRY_COUNT_MAX)},
    },
)
def parse_0x7160(log_time: int, data: bytes) -> Diag0x7160 | None:
    """Parse the 4-byte header of a 0x7160 (PPLMN-list) record.

    Returns None if:
      - payload length is not 8004 (v1) or 9004 (v2)
      - byte[0] (version) is not in {0x01, 0x02}
      - (version, len(data)) tuple does not match the observed split
        (v1 must be 8004 B; v2 must be 9004 B)
      - byte[1] (sub_flag) is not 0x01
      - byte[3] (entry_count high byte) is not 0x00 (entry_count > 255)

    Each of these guards rejects rather than silently mis-decoding a
    record that drifts from the observed corpus.  When a future capture
    surfaces a record this parser rejects, the no-parser miss is the
    signal that the corpus invariants need re-validation against the
    new chipset/firmware family.
    """
    if len(data) < 4:
        return None

    version = data[0]
    if version not in _OBSERVED_VERSIONS:
        return None
    if len(data) != _VERSION_TO_SIZE[version]:
        return None

    sub_flag = data[1]
    if sub_flag != _EXPECTED_SUB_FLAG:
        return None

    # entry_count is a DYNAMIC u16 count (obs {70, 100}, intra-capture
    # variance) of POPULATED PLMN entries — do NOT gate on a specific
    # value (the prior `!= 100` gate silently dropped 97/514 records,
    # incl. all 69 RM520N-GL survey records). The only structural reject
    # is the corpus-wide high-byte-zero invariant (data[3] == 0x00).
    if data[3] != _ENTRY_COUNT_HI_INVARIANT:
        return None
    entry_count = unpack_from("<H", data, 2)[0]

    return Diag0x7160(
        log_time=log_time,
        version=version,
        sub_flag=sub_flag,
        entry_count=entry_count,
        payload_size=len(data),
        body_raw=data,
    )
