"""0x1D2E — LOG_1D2E (Qualcomm GNSS/config cell-array record) (#N).

Split from gnss_nav_db.py per #N tier-3.

**Variable-length structure (revised 2026-06-02, #N).** The original
RE modelled this as a fixed 123-byte record because the only corpus at
the time was 8 RM520N-GL records that all carried a single data cell.
The 2026-05 corpus rebuild added a Sierra EM9291 (SWIX65C/SDX65) edge-
case suite that emits the same log code at **five payload sizes**
following a clean ``86 + 37·N`` ladder. Structural RE across both modems
(`tools/diag_struct_aggregate.py` + raw-record inspection) shows the
record is a **49-byte header followed by an array of 37-byte cells**, not
a fixed record:

    payload_size = 86 + 37 * n_counters
                 = 49 + 37 * (n_counters + 1)

i.e. ``n_counters`` "counter" cells plus exactly one "trailer" cell.

The cell count is encoded **three** redundant ways that all agree — a
strong cross-validation of the model:

  * ``data[48]``  = ``n_counters``                (the length prefix)
  * ``data[11]``  = ``n_counters - 1``            (redundant length field)
  * trailer cell ``[+1]`` = ``2**n_counters - 1`` (presence bitmask:
                                                   01, 03, 07, 0f for N=1..4)

Observed size ladder (clean family, ``(size-86) % 37 == 0``):

    size  n_counters  n_cells  modems
    ----  ----------  -------  ------------------------------
     123       1          2     RM520N-GL (SDX62), EM9291 (SDX65)
     160       2          3     EM9291
     197       3          4     EM9291
     234       4          5     EM9291

A separate RM520N-GL ``v=0x01`` **anomaly family** at sizes
{196, 233, 269, 270, 307} does **not** fit the 37-byte cell stride
(``(size-86) % 37`` is 35 or 36, not 0). The 2026-06 corpus rebuild shows
it is *not* rare — 233B alone is 1,635 records (2026-06-07 correlation
captures) and 269B is 598. Its header breaks the redundant-length contract
(``data[11] != data[48] - 1``) and carries a different magic (``0x3933``
vs RM520's ``0x8737``), so it is a genuinely distinct layout, not a clean
record off-by-a-byte. Left for future RE; rejected here (documented, not
silently size-gated as the pre-2026-06 ``n != 123`` guard did).

A NEW chipset family also appeared in 2026-06: **T99W640 / SDX72** emits
0x1D2E at 157B with ``version`` bumped to ``0x02`` (subversion still 0x01)
and a different header/tag geometry (80 records across three surveys). The
``version`` layer-2 enum ``[0x01]`` correctly rejects it — decoding the
``v=0x02`` SDX72 layout is separate new scope.

Layout (little-endian):

  Header — 49 B, ``data[0:49]``
    [0]        u8      version          = 0x01
    [1]        u8      subversion       = 0x01
    [2..11]    10 B    reserved (zero)
    [11]       u8      n_counters_m1    = n_counters - 1  (redundant length)
    [12..18]   6 B     reserved (zero)
    [18..23]   5 B     tag1             = FF FF 00 <0x06 RM520 | 0x08 Sierra> 00
    [23..28]   5 B     tag2             = (same shape as tag1)
    [28..30]   u16LE   field_pre        = 0x0000
    [30..32]   u16LE   magic            modem-specific: 0x8737 RM520, 0x04B7 Sierra
    [32]       u8      field_32         modem-specific: 0x0A RM520, 0x0C Sierra
    [33..38]   5 B     reserved (zero)
    [38]       u8      marker_0d        = 0x0D (13)
    [39]       u8      marker_0f        = 0x0F (15)
    [40]       u8      reserved (zero)
    [41]       u8      = 0x80
    [42..45]   modem-specific (RM520: 0x80 at 43 too; Sierra: zero)
    [45]       u8      = 0x80
    [46..48]   reserved (zero)
    [48]       u8      n_counters       (the length prefix)

  Counter cell — 37 B, ``data[49 + 37*k : 49 + 37*(k+1)]`` for k in 0..N-1
    [+0]       u8      index            = k (0-based)
    [+1..11]   modem-specific reserved/flags
    [+11..13]  u16LE   value            the per-cell datum (RM520 cell-0
                                        observed 0x300 / 0x310 / 0x3D0)
    [+13..37]  modem-specific trailer (typically `01` at +20, `0xFF` at +28)

  Trailer cell — 37 B, ``data[49 + 37*N : 86 + 37*N]`` (always present)
    [+0]       u8      = 0x01
    [+1]       u8      mask             = 2**n_counters - 1
    [+5]       u8      = 0x04
    [+8]       u8      = 0x0C
    [+12..14]          = 01 02
    [+33]      u8      checksum-like    (varies: 0x83, 0xA8, 0xBF, ...)

Counter-cell internals beyond ``index`` and ``value`` vary by modem and
firmware, so they are exposed as raw bytes rather than decoded into named
fields — see ``CounterCell.raw`` and ``Diag0x1D2E.trailer_raw``.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: RESERVED
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register

_HEADER_LEN = 49
_CELL_LEN = 37
_MIN_LEN = _HEADER_LEN + _CELL_LEN  # 86 — one counter would make 123; a
#   record always has >=1 counter + 1 trailer, so the smallest valid record
#   is 86 + 37 = 123. _MIN_LEN gates the "header + trailer-only" floor.


@dataclass
class CounterCell:
    """One 37-byte counter cell of a 0x1D2E record."""
    index: int       # cell [+0] — 0-based position
    value: int       # u16LE @ cell [+11] — the per-cell datum
    raw: bytes       # full 37-byte cell

    def to_dict(self) -> dict[str, Any]:
        return {'index': self.index, 'value': self.value, 'raw': self.raw.hex()}


@dataclass
class Diag0x1D2E:
    """LOG_1D2E (0x1D2E) — Qualcomm GNSS/config cell-array record (#N)."""
    log_time: int
    version: int
    subversion: int
    n_counters: int            # data[48] — the length prefix
    tag1: bytes
    tag2: bytes
    field_pre: int
    magic: int                 # modem-specific (0x8737 RM520, 0x04B7 Sierra)
    field_32: int              # modem-specific
    counters: list[CounterCell]
    trailer_mask: int          # trailer [+1] == 2**n_counters - 1
    trailer_raw: bytes
    n_cells: int               # n_counters + 1
    payload_size: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1D2E',
            'log_time': self.log_time,
            'version': self.version,
            'subversion': self.subversion,
            'n_counters': self.n_counters,
            'tag1': self.tag1.hex(),
            'tag2': self.tag2.hex(),
            'field_pre': self.field_pre,
            'magic': self.magic,
            'field_32': self.field_32,
            'counters': [c.to_dict() for c in self.counters],
            'trailer_mask': self.trailer_mask,
            'trailer_raw': self.trailer_raw.hex(),
            'n_cells': self.n_cells,
            'payload_size': self.payload_size,
        }


@register(
    0x1D2E,
    name="0x1D2E",
    description="LOG_1D2E (0x1D2E) — GNSS/config cell-array record, 49-B header + N×37-B cells (#N)",
    version=2,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room RE from RM520N-GL SDX62 (2026-04-14) + Sierra EM9291 SDX65 "
        "edge-case suite (2026-05-27). Variable length 86+37*N; cell count at "
        "data[48], cross-checked by data[11] and the trailer presence bitmask (#N)"
    ),
    source_url="",
    field_invariants={
        "version": {"enum": [0x01]},
        "subversion": {"enum": [0x01]},
        # payload_size = 86 + 37*n_counters; observed clean family below.
        "payload_size": {"enum": [123, 160, 197, 234, 271]},
        "n_cells": {"min": 2},
    },
)
def parse_0x1d2e(log_time: int, data: bytes) -> Diag0x1D2E | None:
    n = len(data)
    # Clean cell-array family only: 86 + 37*N, N >= 1 (i.e. n >= 123).
    if n < _MIN_LEN + _CELL_LEN or (n - _MIN_LEN) % _CELL_LEN != 0:
        return None
    if data[0] != 0x01 or data[1] != 0x01:
        return None
    # tag skeleton FF FF 00 ?? 00 — 4th byte is modem-specific (0x06 / 0x08).
    if data[18] != 0xFF or data[19] != 0xFF or data[22] != 0x00:
        return None
    if data[23] != 0xFF or data[24] != 0xFF or data[27] != 0x00:
        return None
    if data[38] != 0x0D or data[39] != 0x0F:
        return None

    n_counters = data[48]
    # Size must agree with the length prefix, and the redundant data[11]
    # field must equal n_counters - 1. Both are part of the structural
    # contract; a mismatch means this isn't a clean cell-array record.
    if (n - _MIN_LEN) // _CELL_LEN != n_counters:
        return None
    if data[11] != n_counters - 1:
        return None

    counters: list[CounterCell] = []
    for k in range(n_counters):
        off = _HEADER_LEN + k * _CELL_LEN
        cell = bytes(data[off:off + _CELL_LEN])
        counters.append(CounterCell(
            index=cell[0],
            value=unpack_from('<H', cell, 11)[0],
            raw=cell,
        ))

    trailer_off = _HEADER_LEN + n_counters * _CELL_LEN
    trailer = bytes(data[trailer_off:trailer_off + _CELL_LEN])

    return Diag0x1D2E(
        log_time=log_time,
        version=data[0],
        subversion=data[1],
        n_counters=n_counters,
        tag1=bytes(data[18:23]),
        tag2=bytes(data[23:28]),
        field_pre=unpack_from('<H', data, 28)[0],
        magic=unpack_from('<H', data, 30)[0],
        field_32=data[32],
        counters=counters,
        trailer_mask=trailer[1] if len(trailer) > 1 else 0,
        trailer_raw=trailer,
        n_cells=n_counters + 1,
        payload_size=n,
    )
