"""0x1885 — GNSS measurement/status (variable size: 35/36/40/42/44/47/51/54B) (#N).

Split from gnss_nav_db.py per #N tier-3.

Promoted from _simple_parser stub to dedicated parser (2026-04-21).

Corpus history:
  v1 (2026-04-21):  89 records, 3 chipsets (lm960 SDX20, fn980 SDX55, eg18na).
  v2 (2026-04-21n): +42 records, +mc7455 (MDM9230) as 4th chipset.
  v3 (2026-04-21n): sz=47 structured-tail decode (bit-exact echo claim — see v4 falsification).
  v4 (2026-04-27, /rtcm-revisit <redacted-ref>): +RM500Q (SDX55), +EM9190, +EG12-GT
      chipsets; new sz=35 + sz=42 size variants; new sz=36 Mode C status code;
      FALSIFIED v3 "bit-exact echo" claim — see "sz=47 tail" notes below.

Shared 10-byte header (invariant across 87+ records sampled in v4 corpus):
  [0]    u8 version = 0x01
  [1]    u8 reserved_1 = 0x00
  [2:4]  u16 LE counter_like (varies; 17-20 uniq per size)
  [4]    u8 aux_4 (small enum per size)
  [5:10] 5 bytes reserved_a = 0x0000000000 (all zero 87/87)

Size-variant tag at [10:14]: 4 bytes whose layout differs per size:
  sz=35: [10]=0x01 [11]=0x00 [12]=varies [13]∈{0,1} (rm500q SDX55-only so far)
  sz=36: [10]=0x01 [11]=0x00 [12]=varies [13]∈{0,1} [14:16]=0x0000
  sz=40: [10]=0x00 [11]=0x0a [12]=0x02 [13]∈{0,1} [14:16]=0x0000
  sz=42: [10]=0x00 [11]=0x00 [12]=0xff [13]=0x00 (rm500q + eg18na so far)
  sz=44: [10]=0x00 [11]=0x02 [12]=0x02 [13]∈{1,2} [14:16]=0x0000
  sz=47: [10]=0x00 [11]∈{0,14} [12]=0x02 [13]=0x01 [14:16]=0x0000
  sz=51: [10]=0x02 [11]=0x01 [12]=0x02 [13]=0x00 [14:16]=0x0000
  sz=54: [10]=0x00 [11]=0x04 [12]∈{0x01,0xff} [13]∈{0,1,2} [14:16]=0x0000
         (2026-05-30 <redacted-ref> walk: 163 records / 17 captures; new
          variant-tag low byte [11]=0x04; introduces Sierra EM9291
          (SDX65, SWIX65C) as an 8th chipset for this code. Header +
          variant_tag + reserved_a all conform to the shared model;
          promoted from `other_54` to a named `sz54` family.)

sz=47 tail (v3 claim falsified by v4 /rtcm-revisit):
  Bytes [31:35] = 0xffffffff (sentinel "invalid_reference_ms"): 3/3 records ✓
  Bytes [35:39] u32 LE = 2 (subtype_tag): 3/3 records ✓
  Bytes [14:31] = 17B all-zero (mid-reserved): 3/3 records ✓
  Bytes [43:47] = 4B all-zero (trailing reserved): 3/3 records ✓
  Bytes [39:43] u32 LE — v3 claimed "bit-exact echo of header [2:6]". v4
    /rtcm-revisit corpus walk found 1/3 records match (the v3 lm960
    wardriving fixture), 2/3 records show delta = +1 (header counter is
    EXACTLY 1 greater than tail counter). This rules out an integrity
    echo and points at a `prev_counter_ref` / `measurement_ref_counter`
    field — the tail counter is the previous measurement epoch's counter,
    equal to header counter only when consecutive epochs share a counter
    bump. Field is exposed both as the raw u32 (sz47_prev_counter_ref)
    and as a "matches header" bool (sz47_counter_echo_ok) for backward
    compatibility; downstream consumers should prefer the u32 value and
    compute their own delta.

sz=36 tail enum (v4 expanded the v3 bimodal model):
  Bytes [30:36] have a (now) tri-modal 6-byte tail structure:
    Mode A (success):     [30]=sub_seq u8 ∈ {0,1,...,12,...}, [31]=0x02,
                          [32:36]=0x00000000
    Mode B (error -13):   [30:32]=0x0000, [32:36]=0xfffffff3
                          (i32 LE = -13; plausible GPS "not available")
    Mode C (rm500q -1):   [30:32]=0xffff (i16 LE = -1), [32:36]=0x00000000
                          (chipset-specific, observed only on rm500q SDX55
                          in v4 corpus walk; plausible "no measurement
                          available" with a different sentinel encoding)
  Treat [30:36] as a 6-byte (sub_seq + status_code) tagged-union region.

This parser extracts the 10-byte header, the 4-byte variant_tag, the
size_family classification, and (for sz=47 only) the structured-tail
fields. The extension region [14:] is still exposed raw for per-size
downstream RE work.

Closure is blocked on:
  * Per-byte decode of sz=35/40/42/44/51 extension regions (multi-record,
    multi-chipset RE work; sz=42 still narrow on chipset spread)
  * Mode A/B/C status code semantics (correlate [30:32]/[32:36] against
    AT/NMEA fix-quality state at the same timestamp — needs paired-AT
    captures of GNSS startup/restart scenarios)

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_EVENT_MTP_FORMAT_STORE_STARTED
        source: qxdm_3_12_714_2017_diag_log_codes (authority: community)
    aliases:
        RESERVED
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


# Ground-truth recipe (#N). Authored offline (session <redacted-ref>) — NOT
# hardware-verified. SIM8202G-M2 (SIMCom SDX55) recommended target. This
# recipe operationalizes the closure-blocked item named in the module
# docstring above: "Mode A/B/C status code semantics (correlate [30:32]/
# [32:36] against AT/NMEA fix-quality state at the same timestamp — needs
# paired-AT captures of GNSS startup/restart scenarios)". Names-block
# honesty: the community QXDM name (LOG_EVENT_MTP_FORMAT_STORE_STARTED /
# RESERVED) is bogus index noise; the observation (GNSS measurement/status,
# gnss_nav_db cluster, sz=36 Mode B = -13 "GPS not available") is the real
# subsystem. version=0x01 is a corpus-wide invariant for this code.

@dataclass
class Diag0x1885:
    """GNSS measurement/status (0x1885) — variable size (35/36/40/42/44/47/51/54B).

    10-byte shared header + size-variant dispatch tag + extension region.
    See module docstring above for field semantics and corpus evidence.
    """
    log_time: int
    version: int          # [0] = 0x01 (constant 89/89)
    reserved_1: int       # [1] = 0x00 (constant 89/89)
    counter_like: int     # [2:4] u16 LE
    aux_4: int            # [4] small enum
    reserved_a: bytes     # [5:10] 5B all-zero 89/89
    variant_tag: int      # [10:14] u32 LE — encodes size-variant family
    size_family: str      # derived: sz35/sz36/sz40/sz42/sz44/sz47/sz51 / other_<n>
    extension: bytes      # [14:] size-variant specific payload (pending RE)
    # sz=47-only structured-tail fields. Set to None on every other size
    # variant so downstream consumers can dispatch cleanly.
    sz47_sentinel_ref_ms: int | None     # sz=47 [31:35] — 0xffffffff "invalid"
    sz47_subtype_tag: int | None         # sz=47 [35:39] u32 LE = 2 (constant)
    # v4: prev_counter_ref is the raw u32 LE at [39:43]. v3 framed this as a
    # bit-exact echo of header [2:6]; v4 /rtcm-revisit (#N) found Δ=+1 on
    # 2/3 corpus records, so it's actually a "previous measurement epoch
    # counter" reference, not an integrity echo. The bool stays for
    # backward compatibility.
    sz47_prev_counter_ref: int | None    # sz=47 [39:43] u32 LE — header[2:6] - {0,1}
    sz47_counter_echo_ok: bool | None    # sz=47 [39:43] == header [2:6] (deprecated; use sz47_prev_counter_ref)
    payload_size: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1885',
            'log_time': self.log_time,
            'version': self.version,
            'reserved_1': self.reserved_1,
            'counter_like': self.counter_like,
            'aux_4': self.aux_4,
            'reserved_a_all_zero': self.reserved_a == b'\x00' * 5,
            'variant_tag': self.variant_tag,
            'size_family': self.size_family,
            'extension_bytes': len(self.extension),
            'sz47_sentinel_ref_ms': self.sz47_sentinel_ref_ms,
            'sz47_subtype_tag': self.sz47_subtype_tag,
            'sz47_prev_counter_ref': self.sz47_prev_counter_ref,
            'sz47_counter_echo_ok': self.sz47_counter_echo_ok,
            'payload_size': self.payload_size,
        }


_GNSS_1885_SIZE_FAMILY = {35: 'sz35', 36: 'sz36', 40: 'sz40', 42: 'sz42',
                          44: 'sz44', 47: 'sz47', 51: 'sz51', 54: 'sz54'}


@register(
    0x1885, domain="gnss",
    name="0x1885",
    description="GNSS measurement/status (0x1885) — variable size (35/36/40/42/44/47/51B) shared header + sz=47 structured tail",
    version=6,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room RE across 87+ records and 7 chipsets (lm960 SDX20, "
        "fn980 SDX55, eg18na, mc7455 MDM9230, em9190, rm500q SDX55, EG12-GT). "
        "10-byte shared header fully named; 7 size variants (35/36/40/42/44/47/51B) "
        "dispatch via variant_tag at [10:14]. "
        "v3 (2026-04-21n): sz=47 structured-tail decode — 0xffffffff sentinel "
        "at [31:35], u32 subtype_tag at [35:39], and bytes [39:43] proposed as "
        "bit-exact echo of header [2:6]. "
        "v4 (2026-04-27 /rtcm-revisit #N <redacted-ref>): added rm500q + em9190 + "
        "EG12-GT chipsets; promoted sz=35 and sz=42 from `other` to named families; "
        "added sz=36 Mode C (rm500q [30:32]=0xffff status code). FALSIFIED v3 "
        "echo claim — 2/3 sz=47 corpus records show [39:43] = header[2:6]−1, so "
        "the field is a `prev_counter_ref` (previous measurement epoch counter), "
        "not an integrity echo. Both `sz47_prev_counter_ref` (u32) and "
        "`sz47_counter_echo_ok` (bool, deprecated) are exposed. "
        "v5 (2026-05-11, #N audit follow-up — Wave 3 G2): added byte-0 "
        "version + byte-1 reserved-zero gate at top of parser body BEFORE "
        "reading sz=47 tail fields at offsets 31/35/39. Audit flagged "
        "'sz47_ref = u32@31 first' as the silent-mis-parse hazard. Corpus "
        "walk (654 records / 34 captures / 7 chipsets): version == 0x01 and "
        "reserved_1 == 0x00 are corpus-wide invariants. Promoted version + "
        "reserved_1 to layer-2 field_invariants. "
        "v6 (2026-05-30 <redacted-ref> #N size-segmented invariance walk): named "
        "the sz=54 family (163 records / 17 captures), previously falling to "
        "`other_54`. sz=54 conforms to the shared 10B header + variant_tag "
        "model ([11]=0x04 low byte) and introduces Sierra EM9291 (SDX62) as "
        "an 8th chipset. version/reserved_1 invariants hold for sz=54."
    ),
    source_url="",
    issues=(),
    # Honest partial: 10-byte shared header + variant_tag + size_family +
    # extension metadata + 4 sz=47-specific fields are all named (13 fields);
    # sz=47 extension is now almost-fully accounted for, but sz=35/36/40/42/44/51
    # extension regions are still opaque pending expanded captures and Mode A/B/C
    # status code RE.
    fields_identified=13,
    fields_parsed=12,
    field_invariants={
        # v5 (#N audit follow-up): version + reserved_1 are corpus-wide
        # invariants across 654 records / 7 chipsets. The parser already
        # tolerates variable size_family in {35,36,40,42,44,47,51} so size
        # is NOT pinned here; only the byte-0 and byte-1 magic constants.
        "version": {"enum": [0x01]},
        "reserved_1": {"enum": [0x00]},
    },
)
def parse_0x1885(log_time: int, data: bytes) -> Diag0x1885 | None:
    if len(data) < 14:
        return None
    # v5 (#N audit follow-up): byte-0 version + byte-1 reserved-zero
    # gate BEFORE any other byte read. Audit flagged `sz47_ref = u32@31
    # first` as the silent-mis-parse hazard — the sz=47 branch read
    # bytes [31:43] before validating byte 0. Corpus (654 records, 7
    # chipsets): version == 0x01 and reserved_1 == 0x00 are corpus-wide
    # invariants.
    if data[0] != 0x01 or data[1] != 0x00:
        return None
    sz47_ref = None
    sz47_subtype = None
    sz47_prev_counter = None
    sz47_echo_ok = None
    if len(data) == 47:
        sz47_ref = unpack_from('<I', data, 31)[0]
        sz47_subtype = unpack_from('<I', data, 35)[0]
        sz47_prev_counter = unpack_from('<I', data, 39)[0]
        sz47_echo_ok = data[39:43] == data[2:6]
    return Diag0x1885(
        log_time=log_time,
        version=data[0],
        reserved_1=data[1],
        counter_like=unpack_from('<H', data, 2)[0],
        aux_4=data[4],
        reserved_a=bytes(data[5:10]),
        variant_tag=unpack_from('<I', data, 10)[0],
        size_family=_GNSS_1885_SIZE_FAMILY.get(len(data), f'other_{len(data)}'),
        extension=bytes(data[14:]),
        sz47_sentinel_ref_ms=sz47_ref,
        sz47_subtype_tag=sz47_subtype,
        sz47_prev_counter_ref=sz47_prev_counter,
        sz47_counter_echo_ok=sz47_echo_ok,
        payload_size=len(data),
    )
