"""0x1634 — GNSS per-SV range measurement (31B fixed) (#N).

Split from gnss_nav_db.py per #N tier-3.

Promoted from lte_misc.py stub (2026-04-21).

Corpus: 39,996 records / 31B fixed / 12 chipset+firmware pairs:
  v=1: MDM9x07, MDM9650, SDX20, SDX20 V2 chipsets (7720 records)
  v=2: SDX55, SDX65 chipsets (fn980m + rm500q) (32276 records)

Full-byte decode (every one of 31 bytes named — no body_raw):
  [0]    u8  version         ∈ {1, 2}  (old vs SDX55+ layouts)
  [1:3]  u16 LE counter_ms   monotonic-increasing within capture; wraps
                             every ~65s; delta ~= 1000 per record →
                             1 ms per LSB, 1 Hz emission cadence.
  [3]    u8  aux_counter     small rolling counter, 47 uniq values 0..250
  [4]    u8  flag_4          ∈ {0, 1}
  [5]    u8  constellation   0=GPS, 1=GLONASS, 2=BDS, 3=GAL  (validated
                             by cross-table: values 0-3 combine with
                             `signal_type` in per-constellation patterns,
                             consistent with QCA GNSS constellation IDs).
                             NOTE (2026-05-30 #N, 878,250-record walk —
                             22x corpus growth since promotion): a 5th value
                             **0x04 (42,198 records, 4.8%)** is now present
                             and currently maps to UNKNOWN_4. In QCA
                             0-indexed GNSS enums following GPS/GLO/BDS/GAL,
                             value 4 is most likely QZSS or NavIC — NOT yet
                             confirmed (needs SV-ID-range / signal_type
                             cross-check), so left UNKNOWN_4 per the
                             declare-what-you-confirmed rule. constellation
                             is intentionally NOT a closed-enum invariant,
                             so value 4 parses cleanly (no parse-rate loss).
  [6]    u8  flags_6         ∈ {0..7}
  [7:11] i32 LE meas_a       signed; range ~±4M; sign byte at [10] matches
                             i32 sign bit on 5000/5000 spot-check records.
  [11:15] i32 LE meas_b      signed; effective range ~±32K; high two
                             bytes are sign extension.  Observed ±ratio
                             pairs with meas_a (e.g. (+51150, -819) and
                             (-51150, +819)) — likely two unit conversions
                             of the same physical quantity.
  [15]   u8  signal_type     ∈ {1, 2, 3}  (L1/L2/L5-style band tag)
  [16]   u8  flag_16         ∈ {0, 1, 2}
  [17]   u8  sub_idx         ∈ {2, 3, 4, 9} in v1; =4 in v2
  [18]   u8  sv_slot         ∈ {1..5}
  [19]   u8  reserved_19     = 0 (constant 39996/39996)
  [20]   u8  param_20        ∈ {2, 4, 8}
  [21]   u8  param_21        enum, 6 values
  [22]   u8  param_22        enum, 6 values
  [23]   u8  cno_dbhz        ∈ {36, 38, 46} → plausibly C/N0 dB-Hz value
  [24]   u8  reserved_24     = 0 (constant 39996/39996)
  [25:27] u16 LE metric_25   16 uniq 53..310
  [27:31] i32 LE ext_meas    v2-active (range ~±1.8M, 16403 uniq values);
                             v1 mostly zero (6960/7720 records are 0) but
                             non-zero values populate the same i32 field
                             in the remaining 760 v1 records.

Two invariants enforced via named reserved fields (39996/39996 obs):
  - [19] == 0
  - [24] == 0

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_LTE_REG_OUTGOING_MSG
        source: qxdm_3_12_714_2017_diag_log_codes (authority: community)
    aliases:
        RESERVED
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register

# --- Ground-truth recipe (#N) ------------------------------------------
# 0x1634 is per-SV GNSS range data straight off the measurement engine.
# Two field classes ground very differently and the recipe is explicit
# about which is which (honesty discipline): (1) constellation + cno_dbhz
# map cleanly onto NMEA GSV (talker ID + per-SV C/N0), so those validate by
# near-direct equality; (2) meas_a / meas_b are raw signed range words
# (pseudorange / Doppler-style, observed as ±ratio pairs = two unit
# conversions of the same quantity) for which NMEA exposes NOTHING — there
# is no AT command that returns a pseudorange. Those are flagged as
# no-AT-source hypotheses rather than mapped to a command that doesn't
# carry the quantity. v=0x02 is the SDX55/SDX62/SDX65 layout; RM520N-GL
# (SDX62) is the recommended target.

@dataclass
class Diag0x1634:
    """GNSS per-SV range measurement (0x1634) — 31B fixed.

    See module docstring above the `parse_0x1634` register for
    field semantics, corpus evidence, and closure decisions.
    """
    log_time: int
    version: int
    counter_ms: int          # [1:3] u16 LE 1-ms-tick counter
    # Back-compat aliases kept because the prior stub exposed `counter_hi`
    # and `counter_lo` as raw bytes; downstream code may still reference
    # them.  They are derived from counter_ms (low / high bytes).
    counter_hi: int          # [1] low byte of counter_ms (misnamed in stub)
    counter_lo: int          # [2] high byte of counter_ms (misnamed in stub)
    aux_counter: int         # [3]
    flag_4: int              # [4]
    constellation: int       # [5] 0/1/2/3
    flags_6: int             # [6]
    meas_a: int              # [7:11] i32 LE
    meas_b: int              # [11:15] i32 LE
    signal_type: int         # [15]
    flag_16: int             # [16]
    sub_idx: int             # [17]
    sv_slot: int             # [18]
    reserved_19: int         # [19] = 0
    param_20: int            # [20]
    param_21: int            # [21]
    param_22: int            # [22]
    cno_dbhz: int            # [23]
    reserved_24: int         # [24] = 0
    metric_25: int           # [25:27] u16 LE
    ext_meas: int            # [27:31] i32 LE
    payload_size: int

    @property
    def constellation_name(self) -> str:
        return {0: 'GPS', 1: 'GLONASS', 2: 'BDS', 3: 'GAL'}.get(
            self.constellation, f'UNKNOWN_{self.constellation}'
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1634',
            'log_time': self.log_time,
            'version': self.version,
            'counter_ms': self.counter_ms,
            'aux_counter': self.aux_counter,
            'flag_4': self.flag_4,
            'constellation': self.constellation,
            'constellation_name': self.constellation_name,
            'flags_6': self.flags_6,
            'meas_a': self.meas_a,
            'meas_b': self.meas_b,
            'signal_type': self.signal_type,
            'flag_16': self.flag_16,
            'sub_idx': self.sub_idx,
            'sv_slot': self.sv_slot,
            'param_20': self.param_20,
            'param_21': self.param_21,
            'param_22': self.param_22,
            'cno_dbhz': self.cno_dbhz,
            'metric_25': self.metric_25,
            'ext_meas': self.ext_meas,
            'payload_size': self.payload_size,
        }


@register(
    0x1634,
    name="0x1634",
    description="GNSS per-SV range measurement (0x1634) — 31B fixed, fully decoded",
    version=4,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room RE from 39,996-record cross-chipset corpus (2026-04-21): "
        "EG12-GT, eg18na SDX20 V2, eg25g MDM9207, em7511 MDM9650, ep06a MDM9x07, "
        "fn980 SDX55, lm960 SDX20 (32.01.110..150 + LM960A18), rm500q SDX65. "
        "v1 (7720 records, old chipsets) and v2 (32276 records, SDX55/SDX65) share "
        "the same layout; v2 activates the [27:31] extension field. "
        "Every byte named; body_raw eliminated. "
        "v3 (2026-05-11, #N audit follow-up — Wave 3 G2): added byte-0 "
        "version-enum gate at top of parser body BEFORE reading counter_ms "
        "at offset 1. Audit flagged 'counter_ms = u16@1 first' as the silent-"
        "mis-parse hazard. Corpus walk (681,462 records / 159 captures / 15 "
        "modem variants): version takes exactly two values — 0x01 (54,119 "
        "records, 7.9%, MDM9x07 / SDX20 / MDM9207 / MDM9650 family) and "
        "0x02 (627,343 records, 92.1%, SDX55 / SDX62 / SDX65 family). "
        "Promoted version to layer-2 field_invariants enum."
    ),
    source_url="",
    issues=(),
    # 31/31 bytes named across 39996-record corpus. Fields counted:
    # version, counter_ms, aux_counter, flag_4, constellation (+derived name),
    # flags_6, meas_a, meas_b, signal_type, flag_16, sub_idx, sv_slot,
    # reserved_19 (invariant=0), param_20, param_21, param_22, cno_dbhz,
    # reserved_24 (invariant=0), metric_25, ext_meas, payload_size = 22.
    fields_identified=22,
    fields_parsed=22,
    field_invariants={
        # v3 (#N audit follow-up): version is a closed 2-element enum
        # across 681,462 records (15 modem variants). v1 = MDM9x07/SDX20/
        # MDM9207/MDM9650 generation; v2 = SDX55/SDX62/SDX65 generation.
        "version": {"enum": [0x01, 0x02]},
        "payload_size": {"enum": [31]},
    },
)
def parse_0x1634(log_time: int, data: bytes) -> Diag0x1634 | None:
    if len(data) != 31:
        return None
    # v3 (#N audit follow-up): byte-0 version-enum gate BEFORE reading
    # counter_ms at offset 1. Audit flagged `counter_ms = u16@1 first` as
    # the silent-mis-parse hazard. Corpus (681,462 records, 15 modem
    # variants): version ∈ {0x01, 0x02}.
    if data[0] not in (0x01, 0x02):
        return None
    counter_ms = unpack_from('<H', data, 1)[0]
    return Diag0x1634(
        log_time=log_time,
        version=data[0],
        counter_ms=counter_ms,
        counter_hi=data[1],
        counter_lo=data[2],
        aux_counter=data[3],
        flag_4=data[4],
        constellation=data[5],
        flags_6=data[6],
        meas_a=unpack_from('<i', data, 7)[0],
        meas_b=unpack_from('<i', data, 11)[0],
        signal_type=data[15],
        flag_16=data[16],
        sub_idx=data[17],
        sv_slot=data[18],
        reserved_19=data[19],
        param_20=data[20],
        param_21=data[21],
        param_22=data[22],
        cno_dbhz=data[23],
        reserved_24=data[24],
        metric_25=unpack_from('<H', data, 25)[0],
        ext_meas=unpack_from('<i', data, 27)[0],
        payload_size=len(data),
    )
