"""0x1859 — GNSS XTRA assistance server URL event (#N).

Split from gnss_nav_db.py per #N tier-3.

Observed once in the MC7455 (MDM9x30) GNSS live capture at a singular
moment — this event fires when the modem loads its XTRA assistance
configuration. Code not observed on any other chipset in the corpus
(Sierra MC7455-family only; later Qualcomm chipsets likely use the
Loc2 `izat` daemon event stream rather than this log code).

v2 (2026-05-11, #N audit follow-up):
  The prior parser's first data access was `_decode_pascal_strings(data, 16)`
  — the u32LE version field at bytes [0:4] was read only at the tail of
  the function, so a future MC7455-family firmware revision shipping a
  different layout in the same 104-byte envelope under a different
  version-byte value would have decoded plausibly with v1 field offsets
  (the audit's "silent-mis-parse hazard"). Promoted to layer-1 hard
  rejection on byte 0 + full u32LE version-field equality; added layer-2
  `field_invariants={"version": {"enum": [1]}}` on @register.
  Corpus evidence: byte 0 == 0x01 (u32LE version == 1) across all
  records of 0x1859 in the repo corpus (MC7455-exclusive per the
  2026-04-23 + 2026-05-01 corpus walks; 1 capture / 1 chipset).

Payload fully decoded (104 B fixed):

    [0:4]    u32LE  version (observed: 1)
    [4]      u8     record_marker (observed: 0x41 = 65 = 'XTRA_LOAD'?)
    [5:8]   3B      magic_pre `00 01 00` (same 3B appears again after URL)
    [8:12]  u32LE   flag_8 (observed: 256 = 0x00000100 — likely 'address_count'
                           or 'mode' enum; low byte is 0x00 and
                           second byte is 0x01)
    [12:16] u32LE   reserved_12 (always 0)
    [16]    u8      host_part_1_len (= 9)
    [17..25]       "xtrapath1"
    [26]    u8      host_part_2_len (= 9)
    [27..35]       "izatcloud"
    [36]    u8      host_part_3_len (= 3)
    [37..39]       "net"
    [40]    u8      host_terminator (= 0)
    [41..43] 3B     magic_post `00 01 00` (matches [5:8])
    [44:48] u32LE   entry_count (observed: 1 — likely the count of
                           resolved IPs or URL alternates following;
                           trailer padding accommodates up to 14
                           additional fields but none populated here)
    [48..104]       zero padding (56 B — reserved for additional IP/URL
                           records when entry_count > 1)

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_EVENTS_DS_GSM_MESSAGE_RECEIVED
        source: qxdm_3_12_714_2017_diag_log_codes (authority: community)
    aliases:
        LOG_EVENTS_GSM_DS_MESSAGE_RECEIVED
            source: qxdm_3_12_714_2017_diag_log_codes
        LOG_DS_FIRST_REORIG_IP_PACKET_HEADER
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


@dataclass
class Diag0x1859:
    """GNSS XTRA assistance server URL event (0x1859) — MC7455 (#N).

    Every one of the 104 bytes in the payload is named. ``magic_pre`` /
    ``magic_post`` carry the 3-byte `00 01 00` constant that brackets
    the flag block. ``trailer_zero_bytes`` counts the zero padding so
    a test can assert the full 48..104 reserved region is untouched.
    """
    log_time: int
    version: int
    record_marker: int
    magic_pre: bytes           # [5:8] — always b'\\x00\\x01\\x00'
    flag_8: int                # [8:12] u32LE
    reserved_12: int           # [12:16] u32LE (always 0)
    host_parts: list[str]
    host_terminator: int       # post-hostname NUL byte
    magic_post: bytes          # 3-B constant repeating magic_pre
    entry_count: int           # u32LE — "follow-up entry count" (1 observed)
    trailer_zero_bytes: int    # count of zero bytes in the 56-B trailer
    xtra_host: str             # joined host_parts
    payload_size: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1859',
            'log_time': self.log_time,
            'version': self.version,
            'record_marker': self.record_marker,
            'magic_pre': self.magic_pre.hex(),
            'flag_8': self.flag_8,
            'reserved_12': self.reserved_12,
            'host_parts': list(self.host_parts),
            'host_terminator': self.host_terminator,
            'magic_post': self.magic_post.hex(),
            'entry_count': self.entry_count,
            'trailer_zero_bytes': self.trailer_zero_bytes,
            'xtra_host': self.xtra_host,
            'payload_size': self.payload_size,
        }


def _decode_pascal_strings(data: bytes, start: int, max_parts: int = 8) -> list[str]:
    """Read length-prefixed ASCII strings until we hit a zero-length or run out."""
    parts: list[str] = []
    off = start
    while off < len(data) and len(parts) < max_parts:
        n = data[off]
        if n == 0 or off + 1 + n > len(data):
            break
        segment = data[off + 1:off + 1 + n]
        try:
            decoded = segment.decode('ascii')
        except UnicodeDecodeError:
            break
        if not all(32 <= c < 127 for c in segment):
            break
        parts.append(decoded)
        off += 1 + n
    return parts


# v2 (#N audit follow-up): byte 0 / u32LE version-field constant.
# Observed value across the entire 0x1859 corpus is 1 (MC7455-exclusive,
# 1 capture / 1 chipset). Encoded as the u32LE at [0:4]; the high three
# bytes are zero in every observed record.
_GNSS_1859_EXPECTED_VERSION = 0x01


@register(
    0x1859,
    name="0x1859",
    description="GNSS XTRA assistance server URL event (0x1859) — MC7455 (#N)",
    version=2,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room RE from MC7455 GNSS live capture 2026-04-12 (#N) — "
        "Pascal-string hostname decode. v2 (2026-05-11, #N audit "
        "follow-up): promoted u32LE version field at [0:4] to layer-1 "
        "first-access hard gate + layer-2 field_invariants enum [1]. "
        "Prior version read byte 0 only at the very end of the function, "
        "exposing the silent-mis-parse hazard the audit named."
    ),
    source_url="",
    issues=(),
    primary_issue=None,
    field_invariants={
        "version": {"enum": [_GNSS_1859_EXPECTED_VERSION]},
    },
    # ASCII audit (#N slice 6): this code carries ASCII in two distinct
    # variants. (a) The v1 MC7455 GNSS variant this parser decodes embeds the
    # XTRA assistance server hostname (`xtrapath1.izatcloud.net`,
    # `time.xtracloud.net`) — a config-token. (b) A *second* variant, matching
    # the canonical name LOG_DS_FIRST_REORIG_IP_PACKET_HEADER, logs the first
    # re-originated IP packet header — observed on the registered T-Mobile
    # survey 2026-05-29T0107Z as a full SIP REGISTER message whose `From:`
    # header carries the subscriber IMS identity (IMSI-derived SIP URI) =>
    # identifier (PII). That variant's first 4 bytes are SIP ASCII (`REGI`),
    # so the v1 version-gate above rejects it (it returns None, not a
    # mis-parse) — the ascii_kinds tag stands on the empirical ASCII carriage,
    # independent of which variant the parser currently decodes.
    ascii_kinds=("config-token", "identifier"),
)
def parse_0x1859(log_time: int, data: bytes) -> Diag0x1859 | None:
    if len(data) < 16:
        return None
    # v2 (#N): version-byte gate is the FIRST data access. The full
    # u32LE field at [0:4] must equal 1 across the entire observed corpus;
    # any deviation (low byte or high-byte drift) is rejected outright so
    # firmware-format drift surfaces as a no-parser miss rather than a
    # plausible-looking but wrong decomposition.
    version = unpack_from('<I', data, 0)[0]
    if version != _GNSS_1859_EXPECTED_VERSION:
        return None
    parts = _decode_pascal_strings(data, 16)
    # Walk the host_parts to find where the trailer begins. Each part
    # costs (1 + len) bytes. If no parts parsed, skip directly.
    trailer_off = 16 + sum(1 + len(part) for part in parts)
    host_terminator = data[trailer_off] if trailer_off < len(data) else 0
    magic_post_off = trailer_off + 1
    magic_post = bytes(data[magic_post_off:magic_post_off + 3]) if magic_post_off + 3 <= len(data) else b''
    entry_count_off = magic_post_off + 3
    entry_count = 0
    if entry_count_off + 4 <= len(data):
        entry_count = unpack_from('<I', data, entry_count_off)[0]
    # Count zero bytes in the 56-byte tail (trailer structure is fixed 8 B
    # [terminator + magic_post + entry_count], so the zero-padding region
    # begins 8 B after trailer_off).
    zero_region_off = trailer_off + 8
    trailer_zero_bytes = sum(1 for b in data[zero_region_off:] if b == 0)
    return Diag0x1859(
        log_time=log_time,
        version=version,
        record_marker=data[4],
        magic_pre=bytes(data[5:8]),
        flag_8=unpack_from('<I', data, 8)[0],
        reserved_12=unpack_from('<I', data, 12)[0] if len(data) >= 16 else 0,
        host_parts=parts,
        host_terminator=host_terminator,
        magic_post=magic_post,
        entry_count=entry_count,
        trailer_zero_bytes=trailer_zero_bytes,
        xtra_host='.'.join(parts) if parts else '',
        payload_size=len(data),
    )
