"""0x4179 -- LTE intra-freq neighbor cell measurement (6-cell sorted list).

Co-emitted carrier for 0x187B's `num_cells=1` neighbor-measurement
announcement (see #N / #N). The body carries two aligned 6-element
u32 LE arrays at the **tail** of every record, independent of total
payload size:

    arrayA[6] @ [sz-48 : sz-24]  -- EARFCN-shaped, byte3=0, byte2 in {0..4}
    arrayB[6] @ [sz-24 : sz]     -- measurement quanta, effectively u16 LE
                                    (byte3=byte2=0), descending-sorted with
                                    trailing zero-fill for unmeasured slots

v=0x05 (LM960 SDX20, ECx/EGx legacy): base size 99B; header 51B.
v=0x08 (FN980m SDX55, RM5xx, SIM8202G-M2): base size 77B; header 29B.

Larger payload sizes (LM960: 147/170/241/.../1448B; FN980m: 125/140/...B)
carry additional measurement groups (per intra-freq carrier layer) between
the fixed header and the tail arrays. The base+48 case (147B v=0x05, 125B
v=0x08) carries a single prior-window Block48 (see v=3 note below). The
strictly-larger sizes carry a *stacked-preamble multi-layer* layout where
each of N layers contributes one 11-byte preamble plus one
``Block48 + trailer`` pair (see v=4 note below).

**v=3 addition (#N <redacted-ref> follow-up).** For ``payload_size ==
base + 48`` records (LM960 147B, FN980m 125B), the bytes preceding the
tail block are themselves a structurally-valid Block48 -- a *prior*
measurement window for the same 6 cells. Gated by the same invariants
the tail satisfies (arrayB non-strictly descending; arrayA byte-3==0
and byte-2 in {0..4} on populated slots). On gate-pass the parser
populates the ``prev_*`` fields; ``middle_raw`` is still preserved
verbatim so downstream consumers can re-derive the raw bytes. Gate-
fail (e.g. a 147B record whose middle block doesn't satisfy the
invariants) leaves the ``prev_*`` fields as None / empty without
disturbing the canonical tail-array decode. Evidence: 139/139 records
in the wardriving corpus (79 LM960 147B v=0x05 + 60 FN980m 125B
v=0x08) satisfied both gates; the two blocks per record carry
*different* per-cell values (different averaging windows / adjacent
subframes -- semantics not yet pinned). Other oversized sizes (170B,
241B, 1448B; FN980m 140B etc.) do NOT satisfy ``body % 48 == 0`` and
remain structural-passthrough pending follow-up RE.

**v=4 addition (#N <redacted-ref> follow-up).** Strictly-oversized
records (``sz > base + 48`` AND ``(sz - base) % stride == 0``) are
decoded as a stacked-preamble multi-layer record. For
``N = (sz - base) // stride`` layers, the layout is::

    header[header_size]                       # base header bytes
    N * preamble[preamble_size]               # stacked per-carrier tags
    N * (Block48 + trailer[trailer_size])     # per-carrier measurements
    tail Block48                              # already decoded above

Per-version params: v=0x05 stride 71 (preamble 11, trailer 12);
v=0x08 stride 63 (preamble 11, trailer 4). Each Block48 is gated by
the same invariants the tail satisfies. Atomically: if every Block48
passes the gate, the per-layer records are exposed via the ``blocks``
list. If *any* block fails, ``blocks`` is left ``[]`` -- a future-
firmware layout drift surfaces as "no extra fields" instead of a
half-populated structure. Evidence: 224/224 v=0x05 (19 sizes,
170B..1448B) + 80/80 v=0x08 (13 sizes, 140B..1274B) on the
2026-05-26 corpus walk.

Strict invariant: ``version in {0x05, 0x08}``. Per the size-vs-format-
invariance trap, a future firmware could ship a new layout under v=0x09
or v=0x06 in the SAME base byte count; layer-2 invariant rejection makes
that regression visible (parse-rate drop on fresh capture) rather than
silently mis-parsing as v=0x05/0x08.

**v=9 addition (#N 2026-06-26, #N RM520N-GL sibling-port sweep).** The
last previously-unnamed v=0x08 prefix bytes are named structural constants on
the RM520N-GL (SDX62) corpus (28/28 records): ``sub_format`` @[1]=0x01,
``format_const_raw`` @[5:8]=``00 02 00`` (u24-LE 512), ``prefix_tag``
@[14]=0x01; and the 4-byte per-block trailer @[+48:+52] is all-zero (75/75
blocks, ``block_trailers_zeroed``). This lifts the decode from 100% byte
*coverage* to 100% byte *naming* — every v=0x08 byte is now a named varying
field OR a named constant. ``prefix_const_ok`` is a SOFT drift witness (records
presence, never rejects — same convention as the preamble ``marker_ok``), so a
future-firmware format drift in the same byte count surfaces as the witness
going False. Re-validated 28/28 across the full current RM520N-GL corpus
(4 captures incl. the new 2026-06-25 wardrive, sizes 77..1274B / B up to 20).

Co-emission timing with 0x187B: median lag +101,376us (~99ms),
80.5% pair rate across the cross-vendor corpus (62/77 0x187B
``num_cells=1`` events in #N's 2026-05-24 walk).

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_WCDMA_PN_SEARCH_EDITION_2
        source: qxdm_3_12_714_2017_diag_log_codes (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).

Note: the QXDM 3.12 name "LOG_WCDMA_PN_SEARCH_EDITION_2" is a misleading
legacy alias -- the corpus emissions are clearly LTE-context (paired
with 0x187B LTE ML1 Neighbor Cell, on LTE-only modems). Qualcomm
appears to have reassigned the code ID; treat the WCDMA name as
historical, not authoritative.
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register

_SUPPORTED_VERSIONS = frozenset({0x05, 0x08})
_BASE_SIZE_FOR_VERSION = {0x05: 99, 0x08: 77}
_CELL_SLOTS = 6
_ARRAY_BYTES = _CELL_SLOTS * 4  # 24
_TAIL_BYTES = 2 * _ARRAY_BYTES   # 48
_PREAMBLE_SIZE = 11

# --- Full record layout spec, per version (#N structural RE 2026-06-26) --
#
# A v=4 multi-block 0x4179 record is, byte-for-byte::
#
#     prefix [prefix_size]                         # fixed front matter
#     B × preamble [11]                            # one per measurement block
#     gap [gap_size]                               # constant 0x00 fill
#     (B-1) × (Block48[48] + trailer[trailer_size])# non-tail measurement layers
#     tail Block48 [48]                            # the canonical "current" window
#
# where ``B`` = block_count = the number of 6-cell measurement blocks. The
# whole record obeys ``sz == prefix_size + gap_size + 48 + 11*B +
# (B-1)*(48+trailer_size)`` which collapses to ``sz == c0 + stride*B`` with
# ``stride = 11 + 48 + trailer_size`` and ``c0 = prefix_size + gap_size``.
# Empirically (31 RM520N-GL v=0x08 records + 209 LM960 v=0x05 records,
# 2026-06-26): v=0x08 ``sz = 14 + 63*B``; v=0x05 ``sz = 28 + 71*B``.
#
# ``block_count`` is *also stated in the prefix* (v=0x08 @ byte 12, v=0x05 @
# byte 26), giving an independent count-mirror invariant against the size
# arithmetic — a drift guard the prior size-only parser lacked.
#
# Each 11-byte preamble decomposes as::
#
#     marker [3]  = 23 00 00                  (literal, present in every block)
#     value  [4]  = per-block u32 LE          (unique-per-block, counter/ts-shaped)
#     const  [3]  = c0 00 04                   (literal)
#     delim  [1]  = 01 for every block EXCEPT the last (tail) block, which = 00
#                   -> a self-describing "final block" terminator that
#                      independently corroborates block_count.
#
# IMPORTANT (the #N preamble-alignment fix): preambles start at
# ``prefix_size`` (15 on v=0x08, 29 on v=0x05) and are *contiguous* — NOT at
# the old ``header_size`` (29 / 51) the prior parser used, which absorbed the
# first preamble into ``header_raw`` and left the per-block ``preamble_raw``
# off by one layer. The Block48 measurement offsets are UNCHANGED by this fix
# (``prefix_size + 11*B + gap_size == header_size + 11*(B-1)``), so the
# 224/224 + 80/80-validated arrayA/arrayB decode is preserved exactly.
#
# Fields: prefix_size, blkcount_off, gap_size, trailer_size, stride, c0, base.
_LAYOUT = {
    0x05: dict(prefix=29, blkcount_off=26, gap=11, trailer=12, stride=71, c0=28, base=99),
    0x08: dict(prefix=15, blkcount_off=12, gap=3,  trailer=4,  stride=63, c0=14, base=77),
}

# Preamble literals (used as soft structural witnesses, not hard gates — a
# future firmware could shift them; we record presence rather than reject).
_PRE_MARKER = b"\x23\x00\x00"
_PRE_CONST = b"\xc0\x00\x04"

# Back-compat: (preamble_size, trailer_size, stride) tuple some call sites /
# tests referenced. Derived from _LAYOUT.
_MULTI_LAYER_PARAMS = {
    v: (_PREAMBLE_SIZE, L["trailer"], L["stride"]) for v, L in _LAYOUT.items()
}


@dataclass
class Diag4179Block:
    """One per-carrier measurement layer from a multi-block 0x4179 record.

    Each block contains an 11-byte ``preamble_raw`` followed by a Block48
    (arrayA[6×u32] EARFCN-shaped + arrayB[6×u32] measurement quanta) and
    a chipset-dependent trailer (12B on v=0x05, 4B on v=0x08).

    **Preamble structure (#N RE 2026-05-28).** The earlier "``c0 00 04``
    triple = per-carrier EARFCN-band tag" hypothesis is **DISPROVEN.** A
    cross-vendor corpus walk (1,145 LM960 v=0x05 + 33 FN980m v=0x08
    marker-bearing preambles) shows the 11-byte preamble is three fixed
    components in a version-specific rotation::

        marker = 23 00 00            (3-byte literal)
        const  = c0 00 04 01         (4-byte literal; [+3] is 0x01, rarely 0x00)
        value  = 4 variable bytes    (the only per-block-varying field)

        v=0x05 order:  [marker][value][const]   (const at preamble offset 7)
        v=0x08 order:  [value][const][marker]   (const at preamble offset 4)

    ``c0 00 04 (01)`` is therefore a **100%-invariant structural constant**,
    not a per-carrier discriminator — it is present identically in every
    marker-bearing block on both chipsets, so it cannot identify a carrier.
    The real per-block field is ``value``: unique per block (1145/1145 +
    33/33 distinct), high-entropy, **uncorrelated** with the block's
    arrayA[0] EARFCN (Pearson r ≈ −0.03 / +0.22) or arrayB[0] measurement
    (r ≈ 0), with a reserved nibble at bits 16-19. That signature
    fingerprints a **per-layer timestamp / sequence counter**, not a band
    or carrier identifier. Semantic units await AT-correlated capture.

    ✅ **Alignment caveat RESOLVED (v=8, #N 2026-06-26).** The prior
    off-by-one was confirmed and fixed: preambles are contiguous from
    ``prefix_size`` (15 on v=0x08, 29 on v=0x05), and there are exactly
    ``B = block_count`` of them (one per measurement block, including the
    tail block — the prior code extracted only ``N = B-1`` starting at the
    wrong ``header_size`` offset, absorbing the first preamble into
    ``header_raw``). Verified on 31 RM520N-GL v=0x08 + cross-modem corpus:
    every preamble now carries the ``23 00 00`` marker (``marker_ok``), the
    final block's delim byte is 0 and all others 1 (``is_final``), and
    ``block_count`` matches the size law (``block_count_mirror_ok``). The
    *measurement* decode (arrayA/arrayB Block48 offsets) is byte-for-byte
    unchanged — only the preamble↔block association was corrected.

    Decoded fields mirror the tail-block convention: ``earfcn_or_freq``
    and ``measurement_raw`` are slot-aligned with ``None`` where
    arrayB == 0 (unmeasured slot).
    """
    preamble_raw: bytes
    array_a_raw: list[int]
    array_b_raw: list[int]
    trailer_raw: bytes
    earfcn_or_freq: list[int | None]
    measurement_raw: list[int | None]
    measured_cell_count: int
    # Decoded preamble sub-fields (#N 2026-06-26). preamble_value is the
    # only per-block-varying field (u32 LE, counter/timestamp-shaped);
    # preamble_marker_ok / preamble_const_ok record whether the 23 00 00 /
    # c0 00 04 literals were present (structural witnesses). preamble_is_final
    # is the delim byte == 0 (set only on the tail block's preamble).
    preamble_value: int = 0
    preamble_marker_ok: bool = False
    preamble_const_ok: bool = False
    preamble_is_final: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "preamble_raw": self.preamble_raw,
            "array_a_raw": self.array_a_raw,
            "array_b_raw": self.array_b_raw,
            "trailer_raw": self.trailer_raw,
            "earfcn_or_freq": self.earfcn_or_freq,
            "measurement_raw": self.measurement_raw,
            "measured_cell_count": self.measured_cell_count,
            "preamble_value": self.preamble_value,
            "preamble_marker_ok": self.preamble_marker_ok,
            "preamble_const_ok": self.preamble_const_ok,
            "preamble_is_final": self.preamble_is_final,
        }


@dataclass
class Diag0x4179:
    """0x4179 -- LTE intra-freq neighbor cell measurement record."""
    log_time: int
    version: int
    payload_size: int
    header_size: int
    # Number of 6-cell measurement blocks in this record (= N_layers + 1;
    # the tail block is the last one). Decoded from the prefix block-count
    # byte (v=0x08 @12, v=0x05 @26) AND cross-checked against the size law
    # ``sz == c0 + stride*B`` -- see block_count_mirror_ok. (#N 2026-06-26)
    block_count: int
    block_count_mirror_ok: bool
    # Prefix front-matter, fully sliced (#N 2026-06-26). prefix_raw is the
    # whole prefix (15 B on v=0x08, 29 B on v=0x05); the named fields below
    # are the v=0x08 decode (offsets differ on v=0x05, where only version +
    # block_count are pinned -- the rest stays in prefix_raw). seq_u16 is a
    # per-record counter @[3:5]; camp_context_u32 @[8:12] is stable within a
    # camp/burst (serving-cell / coarse-time candidate, F3-groundable).
    prefix_raw: bytes
    seq_u16: int | None
    camp_context_u32: int | None
    prefix_flag_a: int | None  # data[2] {1,3}
    prefix_flag_b: int | None  # data[13] {0,4}
    # v=9 (#N 2026-06-26, #N): the previously-unnamed v=0x08 prefix bytes
    # are structural CONSTANTS on the RM520N-GL (SDX62) corpus (28/28 records) --
    # naming them lifts the decode from 100% byte coverage to 100% byte NAMING.
    #   sub_format     = data[1]   = 0x01        (fixed format/sub-version byte)
    #   format_const_raw = data[5:8] = 00 02 00  (fixed u24-LE 512 marker+pad)
    #   prefix_tag     = data[14]  = 0x01        (fixed trailing prefix tag)
    # All three are None/empty on v=0x05 (its 29B prefix has a different layout;
    # only version + block_count are pinned there). prefix_const_ok is True iff
    # all three hold their RM520N-GL constant -- a SOFT witness (record presence,
    # not hard reject, matching the preamble marker_ok convention) so a future-
    # firmware format drift in the SAME byte count surfaces as the witness going
    # False rather than a silent mis-parse (size-vs-format invariance, core memory).
    sub_format: int | None
    format_const_raw: bytes
    prefix_tag: int | None
    prefix_const_ok: bool
    # True iff every non-tail block's 4-byte trailer is all-zero (observed
    # 75/75 RM520N-GL blocks). The v=0x08 trailer carries no information on this
    # modem -- this witness records that, and flags a future non-zero trailer.
    block_trailers_zeroed: bool
    # All B decoded preambles (one per block; the last is the tail block's).
    preambles: list[dict[str, Any]]
    # Trailing reserved gap between the preamble region and the first Block48
    # (constant 0x00 fill: 3 B on v=0x08, 11 B on v=0x05).
    gap_raw: bytes
    # Per-slot decoded fields (None when slot is zero-filled / unmeasured).
    # arrayA values: EARFCN-shaped u32 (always populated when slot present).
    # arrayB values: u16 measurement quanta (descending-sorted; 0 -> empty slot).
    earfcn_or_freq: list[int | None]
    measurement_raw: list[int | None]
    measured_cell_count: int
    # Raw arrays as ints, including zeros, for downstream consumers that
    # want the trailing-zero positions preserved.
    array_a_raw: list[int]
    array_b_raw: list[int]
    # Header bytes preserved for traceability; not yet semantically named
    # in full (T1.5 -- partial structural mapping, see module docstring).
    header_raw: bytes
    # Bytes between header and tail arrays in oversized records. Empty
    # for base-size payloads (99B v=0x05, 77B v=0x08). Preserved verbatim
    # even when prev_* fields are populated, so downstream consumers can
    # re-derive the raw evidence.
    middle_raw: bytes
    # Prior-window measurement (Block48 immediately after header on
    # base+48 records). All None / empty when payload is not base+48 or
    # the Block48 gates fail.
    prev_earfcn_or_freq: list[int | None]
    prev_measurement_raw: list[int | None]
    prev_measured_cell_count: int | None
    array_a_prev_raw: list[int]
    array_b_prev_raw: list[int]
    # Multi-layer per-carrier blocks decoded from oversized records
    # (sz > base+48 AND (sz - base) % stride == 0). Empty list when the
    # record is not multi-layer-shaped or any Block48 fails the
    # invariant gate -- consistent with the "no extra fields rather than
    # wrong extra fields" rule (size-vs-format invariance, core memory).
    blocks: list[Diag4179Block]

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": "Diag0x4179",
            "log_time": self.log_time,
            "version": self.version,
            "payload_size": self.payload_size,
            "header_size": self.header_size,
            "block_count": self.block_count,
            "block_count_mirror_ok": self.block_count_mirror_ok,
            "prefix_raw": self.prefix_raw,
            "seq_u16": self.seq_u16,
            "camp_context_u32": self.camp_context_u32,
            "prefix_flag_a": self.prefix_flag_a,
            "prefix_flag_b": self.prefix_flag_b,
            "sub_format": self.sub_format,
            "format_const_raw": self.format_const_raw,
            "prefix_tag": self.prefix_tag,
            "prefix_const_ok": self.prefix_const_ok,
            "block_trailers_zeroed": self.block_trailers_zeroed,
            "preambles": self.preambles,
            "gap_raw": self.gap_raw,
            "earfcn_or_freq": self.earfcn_or_freq,
            "measurement_raw": self.measurement_raw,
            "measured_cell_count": self.measured_cell_count,
            "array_a_raw": self.array_a_raw,
            "array_b_raw": self.array_b_raw,
            "header_raw": self.header_raw,
            "middle_raw": self.middle_raw,
            "prev_earfcn_or_freq": self.prev_earfcn_or_freq,
            "prev_measurement_raw": self.prev_measurement_raw,
            "prev_measured_cell_count": self.prev_measured_cell_count,
            "array_a_prev_raw": self.array_a_prev_raw,
            "array_b_prev_raw": self.array_b_prev_raw,
            "blocks": [b.to_dict() for b in self.blocks],
        }


def _block48_valid(array_a: list[int], array_b: list[int]) -> bool:
    """Return True iff (array_a, array_b) satisfy the Block48 invariants
    the tail arrays exhibit corpus-wide:

    - arrayB non-strictly descending across all 6 slots (trailing-zero-
      fill is naturally descending, so this also covers the "fewer than
      6 measured cells" case).
    - arrayA byte-3 == 0 AND byte-2 in {0..4} on every slot whose
      paired arrayB value is non-zero (i.e. populated cells).

    Both invariants were verified 139/139 on the wardriving corpus's
    base+48 records (#N <redacted-ref>).
    """
    if not all(array_b[i] >= array_b[i + 1] for i in range(5)):
        return False
    for a, b in zip(array_a, array_b):
        if b == 0:
            continue
        if (a >> 24) != 0:
            return False
        if ((a >> 16) & 0xff) > 4:
            return False
    return True


def _decode_preamble(pre: bytes) -> dict[str, Any]:
    """Decode one 11-byte preamble: marker(3) + value(u32 LE) + const(3) +
    delim(1). Returns a dict with the raw bytes, the per-block value, the
    two literal-presence witnesses, and the ``is_final`` delim flag
    (delim == 0 marks the tail block). Tolerant of short/garbage slices
    (returns presence=False rather than raising) so a future-firmware
    layout drift degrades to "literals absent" instead of a parse failure.
    """
    if len(pre) < _PREAMBLE_SIZE:
        return {
            "preamble_raw": bytes(pre),
            "value": 0,
            "marker_ok": False,
            "const_ok": False,
            "is_final": False,
        }
    value = int.from_bytes(pre[3:7], "little")
    return {
        "preamble_raw": bytes(pre),
        "value": value,
        "marker_ok": pre[0:3] == _PRE_MARKER,
        "const_ok": pre[7:10] == _PRE_CONST,
        "is_final": pre[10] == 0,
    }


# --- Ground-truth recipes (#N / #N) ---------------------------------
#
# ⚠️ RECIPE GOAL CORRECTION (#N 2026-06-26). The ORIGINAL recipe goal —
# "arrayA = the neighbour EARFCN; match arrayB to a 6-row neighbour-cell AT
# table (AT+QENG/MONI/LTEINFO RSRP/RSRQ)" — is **the wrong goal** and has been
# INVALIDATED. Two independent reasons:
#
#   1. arrayA = EARFCN is **F3-REFUTED** on three modems (RM500Q-AE + SIM8202G-M2
#      SDX55 same-modem, <redacted-ref> 2026-06-13; LM960 SDX20 same-chipset HW run,
#      <redacted-ref> 2026-06-22): the decoded values have ZERO overlap with the
#      co-captured F3 rflte tune-EARFCN set and mostly fall outside the LTE
#      EARFCN range. Every ``earfcn_or_freq`` FieldGround below is therefore
#      ``status="refuted"`` — it is a CLOSED question, not a live target.
#   2. The "6 neighbour cells, each with its own EARFCN" model is **structurally
#      false** for an intra-freq code: intra-freq neighbours share the single
#      serving EARFCN, yet arrayA holds 6 *distinct* large u32s per block. The
#      v=8 structural RE (2026-06-26) shows the record is ``prefix + B×preamble +
#      gap + B×Block48`` with B measurement *blocks* (not 6 cells with AT-table
#      rows) — so "join arrayB to a 6-row neighbour AT table" was never the right
#      correlation.
#
# CORRECTED live goal (what the RM520N-GL recipe below now drives):
#   (a) confirm the v=8 structural byte-map on live RM520N-GL data
#       (block_count_mirror, preamble markers/delim, 100% byte coverage);
#   (b) ground the NEW structural fields — camp_context_u32 vs AT+QENG
#       "servingcell" (the strongest play: an intra-freq code's serving context
#       is exactly what servingcell reports), block_count + preamble_value vs the
#       measurement cadence;
#   (c) pin arrayB's RAN quantity (RSRP vs RSRQ vs RSSI vs LL1 energy) + raw→dBm
#       scale — the ONE original sub-goal that survives, now correctly framed as
#       a per-block descending-sorted quantum, not a neighbour-AT-table join.
#
# The per-modem sibling recipes (RM500Q-AE / LM960 / RXM-G1 / SIM8202G-M2 /
# FN980m / EM9190) are KEPT, not deleted, because they carry the self-contained
# F3 refutation provenance (#N qdb GUIDs) and per-vendor AT dialect needed to
# ground arrayB; their arrayA=EARFCN field-goal is invalidated (refuted) in
# place. The LM960 recipe additionally holds the only HW-validated v=0x05
# evidence and stays as-is.
#
# 0x4179 is the co-emitted neighbour carrier for 0x187B's num_cells>0
# announcement (#N), so capture both together.

@register(
    0x4179,
    name="0x4179",
    description=(
        "0x4179 -- LTE intra-freq neighbor cell measurement (6-cell sorted "
        "list). Co-emitted carrier for 0x187B num_cells>0 announcements "
        "(#N). Body tail = 6-slot arrayA (per-cell u32; the earlier "
        "'EARFCN-shaped' reading is F3-REFUTED for v=0x08 -- see #N) + "
        "6-slot arrayB (measurement quanta u16, descending-sorted, zero-fill "
        "for unmeasured slots). v=0x05 99B (LM960 SDX20); v=0x08 77B (FN980m "
        "SDX55 / RM5xx / SIM8202G-M2). v=3: base+48 records (LM960 147B, "
        "FN980m 125B) additionally decode a prior-window Block48 from the "
        "bytes immediately after the header into prev_* fields, gated by "
        "the same descending + byte-signature invariants the tail "
        "satisfies. v=4: multi-layer oversized records (LM960 170B/241B/.../1448B, "
        "FN980m 140B/.../1274B) where (sz - base) %% stride == 0 are decoded "
        "as N preambles + N (Block48 + trailer) pairs + tail Block48 into "
        "the per-carrier `blocks` list. Per-version params: v=0x05 stride=71 "
        "(preamble=11, trailer=12); v=0x08 stride=63 (preamble=11, trailer=4). "
        "Each Block48 gated by the same invariants as the tail; on any "
        "block-level gate-fail blocks=[] (no-extra-fields-on-fail). v=5: "
        "preamble structure RE'd (marker+value+const rotation); band-tag "
        "hypothesis disproven (see source_detail). v=6: arrayA=EARFCN "
        "hypothesis F3-REFUTED for v=0x08 (#N) -- arrayA is a per-cell "
        "measurement-shaped u32, not a frequency. v=7: arrayA=EARFCN "
        "hypothesis now ALSO F3-REFUTED for v=0x05 on the LM960 SDX20 (#N, "
        "<redacted-ref> 2026-06-22) -- same-chipset HW run, cross-corroborating "
        "the SDX55/SDX62 refutation. v=8: FULL STRUCTURAL BYTE-MAP (#N "
        "2026-06-26, RM520N-GL target). Record = prefix[prefix_size] + B "
        "preambles[11] + gap[gap_size] + (B-1)(Block48+trailer) + tail "
        "Block48, with sz == c0 + stride*B (v=0x08 14+63B, v=0x05 28+71B). "
        "block_count B is decoded from the prefix (v=0x08 @12, v=0x05 @26) "
        "AND cross-checked against the size law (block_count_mirror_ok). The "
        "preamble alignment bug is FIXED: preambles are contiguous from "
        "prefix_size (15/29), not header_size (29/51) -- B preambles now "
        "decode (was N=B-1, mis-sliced). Preamble delim byte = 01 except the "
        "final (tail) block = 00 (self-describing terminator). New fields: "
        "block_count, prefix_raw, seq_u16, camp_context_u32, prefix_flag_a/b, "
        "preambles[], gap_raw, per-block preamble_value/marker_ok/const_ok/"
        "is_final. 100%% byte coverage verified on 31 RM520N-GL v=0x08 records "
        "(0 unaccounted bytes). arrayA/arrayB measurement decode UNCHANGED "
        "(block offsets do not move). arrayA identity + arrayB RAN-quantity/"
        "scale remain the open semantic work (HW-gated; recipes in ground_truth). "
        "v=9 (#N 2026-06-26, #N sibling-port sweep): the LAST unnamed "
        "v=0x08 prefix bytes are now NAMED constants (sub_format @1=0x01, "
        "format_const_raw @5:8=00 02 00, prefix_tag @14=0x01) plus a "
        "block_trailers_zeroed witness (trailer @[+48:+52]=00 00 00 00, 75/75 "
        "blocks) -- lifting the decode from 100%% byte COVERAGE to 100%% byte "
        "NAMING on the RM520N-GL (every byte = a named varying field OR a named "
        "constant). prefix_const_ok is a soft drift witness (records presence, "
        "never rejects). Re-validated 28/28 across the FULL CURRENT RM520N-GL "
        "corpus incl. the new 2026-06-25 wardrive (size classes up to 1274B / "
        "B=20): 28/28 decode, mirror_ok, on_formula, 100%% byte coverage, every "
        "preamble marker-bearing + final-delim correct, 0 degraded."
    ),
    version=9,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Cross-vendor corpus walk 2026-05-25 over 1315 records / 43 "
        "captures: 200 LM960 99B v=0x05, 96 FN980m 77B v=0x08, plus 23 "
        "SIM8202 / 4 RM500Q / 1 RM520 / 5 EG25G samples confirming version-"
        "to-chipset mapping. Tail-array layout (offsets [-48:-24] arrayA, "
        "[-24:] arrayB) is identical across both versions; header diff "
        "(LM960 51B vs FN980m 29B) accounts for the 22-byte payload-size "
        "delta. Zero-fill monotonicity on arrayB across slots 0->5 "
        "(LM960: 118->121->125->130->133->135 records with high-bytes=0) "
        "confirms descending sort with empty-slot zero padding. "
        "v=3 prev_*-block decode validated 2026-05-25 (<redacted-ref>) "
        "across 139/139 wardriving-corpus base+48 records (79 LM960 147B "
        "v=0x05 + 60 FN980m 125B v=0x08); first-block arrayB descending "
        "and arrayA byte-3==0 / byte-2 in {0..4} held on every sample. "
        "Per-cell values differ between first and tail blocks (e.g. "
        "37460->37472 on arrayA[0], 117->122 on arrayB[0]), indicating "
        "the first block represents a distinct measurement window rather "
        "than a re-emission. v=4 multi-layer block decode validated #N "
        "<redacted-ref> (2026-05-26) across 304/304 oversized records: "
        "224/224 v=0x05 across 19 size buckets (170B..1448B) and 80/80 "
        "v=0x08 across 13 size buckets (140B..1274B). Stacked-preamble "
        "layout (N preambles followed by N Block48+trailer pairs) "
        "decisively outscored the interleaved-preamble alternative for "
        "v=0x05 (224 vs 0); for v=0x08 only the P=11/T=4 widths passed "
        "universally (3 sibling candidates each scored <=4/80). v=5 "
        "(#N RE 2026-05-28): the 11-byte preamble decomposes into "
        "marker(23 00 00) + value(4B) + const(c0 00 04 01) in a version-"
        "specific rotation (v=0x05 marker|value|const, v=0x08 value|const|"
        "marker; rotation 100% on 1,145 v=0x05 + 33 v=0x08 marker-bearing "
        "blocks). This DISPROVES the prior 'c0 00 04 = EARFCN-band tag' "
        "hypothesis -- c0 00 04 01 is a structural constant, and the only "
        "per-block field (value) is unique-per-block, high-entropy and "
        "uncorrelated with arrayA EARFCN / arrayB measurement (timestamp/"
        "counter-shaped, not a carrier id). v=8 (#N 2026-06-26): the "
        "preamble alignment is FIXED (preambles contiguous from prefix_size, "
        "B=block_count of them); the full prefix + gap + per-block trailer "
        "are now sliced, giving 100%% byte coverage on 31 RM520N-GL v=0x08 "
        "records + cross-modem (333 v=0x05 / 57 v=0x08 walk: 0 mirror fails, "
        "0 coverage fails). Measurement decode (arrayA/arrayB) is unaffected. "
        "v=9 (#N 2026-06-26): named the final v=0x08 prefix constants "
        "(sub_format @1, format_const_raw @5:8, prefix_tag @14) + "
        "block_trailers_zeroed; all are RM520N-GL corpus constants (28/28 prefix, "
        "75/75 trailers), giving 100%% byte NAMING. Full-current-corpus re-walk "
        "(4 RM520N-GL captures, 28 records incl. new 2026-06-25 wardrive): "
        "28/28 decode + mirror_ok + on_formula + full byte-coverage, "
        "prefix_const_ok 28/28, block_trailers_zeroed 28/28."
    ),
    source_url="",
    issues=(),
    primary_issue=None,
    fields_identified=23,
    fields_parsed=23,
    wigle_direct=True,
    wigle_roles=("identity", "signal"),
    supported_versions=sorted(_SUPPORTED_VERSIONS),
    field_invariants={
        "version": {"enum": sorted(_SUPPORTED_VERSIONS)},
    },
)
def parse_0x4179(log_time: int, data: bytes) -> Diag0x4179 | None:
    if len(data) < _TAIL_BYTES + 1:
        return None
    version = data[0]
    if version not in _SUPPORTED_VERSIONS:
        return None
    base = _BASE_SIZE_FOR_VERSION[version]
    sz = len(data)
    header_size = base - _TAIL_BYTES  # 51 for v=0x05, 29 for v=0x08
    layout = _LAYOUT[version]
    prefix_size = layout["prefix"]
    gap_size = layout["gap"]
    stride = layout["stride"]
    trailer_size = layout["trailer"]
    c0 = layout["c0"]
    blkcount_off = layout["blkcount_off"]
    # Sanity: any payload below the base size for its version is malformed.
    if sz < base:
        return None
    # arrayA + arrayB always live in the trailing 48 bytes.
    array_a_off = sz - _TAIL_BYTES
    array_b_off = sz - _ARRAY_BYTES
    array_a_raw = list(unpack_from('<6I', data, array_a_off))
    array_b_raw = list(unpack_from('<6I', data, array_b_off))

    earfcn_or_freq: list[int | None] = []
    measurement_raw: list[int | None] = []
    measured_cell_count = 0
    for a, b in zip(array_a_raw, array_b_raw):
        if b == 0:
            # arrayB zero -> unmeasured slot (validated by monotonic
            # zero-count progression across slots 0->5 in the corpus).
            earfcn_or_freq.append(None)
            measurement_raw.append(None)
        else:
            earfcn_or_freq.append(a)
            measurement_raw.append(b)
            measured_cell_count += 1

    header_raw = bytes(data[:header_size])
    middle_raw = bytes(data[header_size:array_a_off])

    # --- block_count + prefix decode (#N 2026-06-26) --------------------
    # On-formula (stacked-preamble) records satisfy sz == c0 + stride*B. The
    # firmware also states B in the prefix (v=0x08 @12, v=0x05 @26); the two
    # must agree -> block_count_mirror_ok. base+48 prev-window records and
    # any off-formula size leave block_count from the prefix byte (mirror
    # N/A -> False) without disturbing the canonical decode.
    on_formula = (sz - c0) % stride == 0 and sz >= c0 + stride
    block_count_from_size = (sz - c0) // stride if on_formula else None
    block_count_from_prefix = data[blkcount_off] if sz > blkcount_off else None
    block_count = (
        block_count_from_size
        if block_count_from_size is not None
        else (block_count_from_prefix if block_count_from_prefix else 1)
    )
    block_count_mirror_ok = (
        block_count_from_size is not None
        and block_count_from_prefix == block_count_from_size
    )

    prefix_raw = bytes(data[:prefix_size])
    seq_u16 = unpack_from('<H', data, 3)[0] if sz >= 5 else None
    # Named prefix fields are the v=0x08 decode; on v=0x05 the offsets differ
    # so only version + block_count are pinned (rest stays in prefix_raw).
    if version == 0x08:
        camp_context_u32: int | None = unpack_from('<I', data, 8)[0] if sz >= 12 else None
        prefix_flag_a: int | None = data[2] if sz > 2 else None
        prefix_flag_b: int | None = data[13] if sz > 13 else None
        # v=9: name the fixed prefix constants (RM520N-GL 28/28). These are the
        # last previously-unnamed prefix bytes; prefix_const_ok is a soft drift
        # witness (records presence, never rejects -- see dataclass docstring).
        sub_format: int | None = data[1] if sz > 1 else None
        format_const_raw = bytes(data[5:8]) if sz >= 8 else b""
        prefix_tag: int | None = data[14] if sz > 14 else None
        prefix_const_ok = (
            sub_format == 0x01
            and format_const_raw == b"\x00\x02\x00"
            and prefix_tag == 0x01
        )
    else:
        camp_context_u32 = None
        prefix_flag_a = None
        prefix_flag_b = None
        sub_format = None
        format_const_raw = b""
        prefix_tag = None
        prefix_const_ok = False

    # All B preambles, at the CORRECTED contiguous offset prefix_size + i*11
    # (the #N alignment fix: was header_size, which absorbed the first
    # preamble into header_raw). Only meaningful for on-formula records; for
    # off-formula / base+48 forms we leave it empty rather than mis-slice.
    preambles: list[dict[str, Any]] = []
    gap_raw = b""
    if on_formula:
        for i in range(block_count):
            off = prefix_size + i * _PREAMBLE_SIZE
            preambles.append(_decode_preamble(data[off:off + _PREAMBLE_SIZE]))
        gap_off = prefix_size + block_count * _PREAMBLE_SIZE
        gap_raw = bytes(data[gap_off:gap_off + gap_size])

    # v=3: try prior-window Block48 on base+48 records. Gate on the same
    # invariants the tail satisfies; gate-fail leaves prev_* unpopulated
    # so the regression mode is "no extra fields" rather than "wrong
    # extra fields" (size-vs-format invariance, core memory).
    prev_earfcn_or_freq: list[int | None] = []
    prev_measurement_raw: list[int | None] = []
    prev_measured_cell_count: int | None = None
    array_a_prev_raw: list[int] = []
    array_b_prev_raw: list[int] = []
    if len(middle_raw) == _TAIL_BYTES:
        cand_a = list(unpack_from('<6I', middle_raw, 0))
        cand_b = list(unpack_from('<6I', middle_raw, _ARRAY_BYTES))
        if _block48_valid(cand_a, cand_b):
            array_a_prev_raw = cand_a
            array_b_prev_raw = cand_b
            prev_measured_cell_count = 0
            for a, b in zip(cand_a, cand_b):
                if b == 0:
                    prev_earfcn_or_freq.append(None)
                    prev_measurement_raw.append(None)
                else:
                    prev_earfcn_or_freq.append(a)
                    prev_measurement_raw.append(b)
                    prev_measured_cell_count += 1

    # v=4: multi-layer per-carrier block decode for sz > base+48 where
    # (sz - base) % stride == 0. Layout per version params is N preambles
    # stacked, then N (Block48 + trailer) pairs, then tail Block48 (already
    # decoded above as arrayA/arrayB). Atomically populate `blocks` only
    # when EVERY Block48 passes the invariant gate; any single gate-fail
    # leaves blocks=[] so a future-firmware layout drift surfaces as
    # "no extra fields" instead of a half-populated structure.
    blocks: list[Diag4179Block] = []
    if sz > base + _TAIL_BYTES and version in _MULTI_LAYER_PARAMS:
        preamble_size, trailer_size, stride = _MULTI_LAYER_PARAMS[version]
        body_delta = sz - base
        if body_delta % stride == 0:
            n_layers = body_delta // stride
            # CORRECTED preamble offset (#N alignment fix): preambles are
            # contiguous from prefix_size, NOT header_size. blocks_region_off
            # is unchanged (header_size + n_layers*11 == prefix_size + 11*B +
            # gap), so the validated Block48 offsets do not move.
            preamble_region_off = prefix_size
            blocks_region_off = header_size + n_layers * preamble_size
            block_stride = _TAIL_BYTES + trailer_size
            candidates: list[Diag4179Block] = []
            all_gates_pass = True
            for i in range(n_layers):
                pre_off = preamble_region_off + i * preamble_size
                blk_off = blocks_region_off + i * block_stride
                a_off = blk_off
                b_off = blk_off + _ARRAY_BYTES
                t_off = blk_off + _TAIL_BYTES
                cand_a = list(unpack_from('<6I', data, a_off))
                cand_b = list(unpack_from('<6I', data, b_off))
                if not _block48_valid(cand_a, cand_b):
                    all_gates_pass = False
                    break
                preamble_bytes = bytes(data[pre_off:pre_off + preamble_size])
                pre_dec = _decode_preamble(preamble_bytes)
                trailer_bytes = bytes(data[t_off:t_off + trailer_size])
                blk_earfcn: list[int | None] = []
                blk_meas: list[int | None] = []
                blk_count = 0
                for a, b in zip(cand_a, cand_b):
                    if b == 0:
                        blk_earfcn.append(None)
                        blk_meas.append(None)
                    else:
                        blk_earfcn.append(a)
                        blk_meas.append(b)
                        blk_count += 1
                candidates.append(Diag4179Block(
                    preamble_raw=preamble_bytes,
                    array_a_raw=cand_a,
                    array_b_raw=cand_b,
                    trailer_raw=trailer_bytes,
                    earfcn_or_freq=blk_earfcn,
                    measurement_raw=blk_meas,
                    measured_cell_count=blk_count,
                    preamble_value=pre_dec["value"],
                    preamble_marker_ok=pre_dec["marker_ok"],
                    preamble_const_ok=pre_dec["const_ok"],
                    preamble_is_final=pre_dec["is_final"],
                ))
            if all_gates_pass:
                blocks = candidates

    # v=9: record-level witness that every non-tail block trailer is all-zero
    # (observed 75/75 RM520N-GL blocks). Vacuously True for base records (B=1,
    # no non-tail blocks); a future non-zero trailer flips it without disturbing
    # the canonical decode.
    block_trailers_zeroed = all(
        all(byte == 0 for byte in blk.trailer_raw) for blk in blocks
    )

    return Diag0x4179(
        log_time=log_time,
        version=version,
        payload_size=sz,
        header_size=header_size,
        block_count=block_count,
        block_count_mirror_ok=block_count_mirror_ok,
        prefix_raw=prefix_raw,
        seq_u16=seq_u16,
        camp_context_u32=camp_context_u32,
        prefix_flag_a=prefix_flag_a,
        prefix_flag_b=prefix_flag_b,
        sub_format=sub_format,
        format_const_raw=format_const_raw,
        prefix_tag=prefix_tag,
        prefix_const_ok=prefix_const_ok,
        block_trailers_zeroed=block_trailers_zeroed,
        preambles=preambles,
        gap_raw=gap_raw,
        earfcn_or_freq=earfcn_or_freq,
        measurement_raw=measurement_raw,
        measured_cell_count=measured_cell_count,
        array_a_raw=array_a_raw,
        array_b_raw=array_b_raw,
        header_raw=header_raw,
        middle_raw=middle_raw,
        prev_earfcn_or_freq=prev_earfcn_or_freq,
        prev_measurement_raw=prev_measurement_raw,
        prev_measured_cell_count=prev_measured_cell_count,
        array_a_prev_raw=array_a_prev_raw,
        array_b_prev_raw=array_b_prev_raw,
        blocks=blocks,
    )
