"""0x147D — split from gnss_nav_db.py per #N tier-3.

See module body for the per-code RE history and field map.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_GNSS_PE_KF_POSITION_REPORT_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        RESERVED
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


# ---------------------------------------------------------------------------
# 0x147D — GNSS Nav DB 147D (companion to 0x147C, #N)
# ---------------------------------------------------------------------------
# Observed on MDM9x07 (EP06A, EG18-NA), SDX20 (LM960) as 3665B fixed, and
# on SDX55 (FN980m) as 4717B fixed (1052B larger). 858 records × 3 captures
# on the 3665B variant, plus 5 records on SDX55.
#
# v1 (2026-04-17) shipped a header-only parser with a bug: the field named
# `sub_counter` was reading byte [5], which is a CONSTANT format-marker byte
# (0x91 across every observed generation), not a counter.  v2 (2026-04-21)
# fixes this and ships the body-structure RE findings from the 3-fixture
# pass.
#
# Cross-chipset constants across 3 QCA generations (eg18na, ep06a, fn980m)
# computed against the first 3665B common region using N=1 record per
# fixture, originally claimed 7 non-zero constant bytes including
# [5]=0x91 and [6]=0x10. v7 (2026-05-01) corpus walk against 883 records
# from 4 splitter-paired LG290P captures (EP06A, EM7511, EG18-NA, FN980)
# falsifies the [5]=0x91 / [6]=0x10 claim: bytes[5:7] is a session/state
# word taking values from a small set (0x1091, 0x1011, 0x0011, 0x0002)
# that varies WITHIN a single capture as well as across captures of the
# same module. The original 7-byte claim landed because each per-chipset
# fixture was N=1 — single records that happened to land on the modal
# value 0x1091. The remaining record-field markers at [17]/[22]/[24]/[30]/
# [36] are body-record tags (see "Body substructure" section below) and
# remain valid as body-internal invariants — they were not falsified by
# the v7 walk.
#
# Header (offsets cross-chipset stable; values where noted):
#     [0]      u8    version                (5 on MDM9x07/SDX20; 6 on SDX55)
#     [1:4]    u24LE scope_id               (per-record, varies)
#     [4]      u8    const 0x00
#     [5:7]    u16LE marker_bytes_5_7       (header-state word; observed
#                                            values: 0x1091 modal, 0x1011,
#                                            0x0011, 0x0002 — NOT a constant)
#     [7]      u8    size_flag              (bitfield — see v6 source_detail:
#                                            bit 4 = SDX55 4717B size class,
#                                            bit 1 = FN980 firmware variant)
#     [8:16]   8B    reserved               (all zero)
#
# Body substructure (starts at offset 16) — per-SV ephemeris table with
# a mixed record-size pattern:
#     19-byte header record at offset 16, layout:
#         [+0]   0x6d / 0x6e   record-start marker (ASCII 'm'/'n')
#         [+1]   0x09          record-type tag (always 0x09 for this head)
#         [+2:6] 4B            ephemeris value  (repeats in the 6B tail record)
#         [+6]   0x08          field marker
#         [+7]   u8 kind       (0x40 / 0x44 — varies)
#         [+8]   0x03          field marker
#         [+9:14] 5B           per-SV data
#         [+14]  0x04          field marker
#         [+15:19] 4B          per-SV data (repeats in the tail record's body)
#     6-byte tail record at offset 35, layout:
#         [+0]   0x6d / 0x6e   same marker as the header record at [+0]
#         [+1]   0x05          record-type tag (always 0x05 for the tail)
#         [+2:6] 4B            ephemeris value  (== 19B record's [+2:6])
#
# The header-record's 4B value at [+2:6] is byte-exact identical to the
# tail-record's 4B value at [+2:6] on every fixture observed — evidence
# that the 19B + 6B pair corresponds to a single SV's observation split
# across two record-type-tag windows (likely L1 vs L2 / primary vs secondary
# band entries).
#
# On SDX55 (4717B variant) this per-SV pattern repeats past offset 41
# (6B tail-record, then another 6B tail-record at 41) giving the extra
# 1052B over MDM9x07's 3665B.  MDM9x07 captures have zeros from offset 41
# to 44 before the next 19B record starts.
#
# Full per-SV field labelling still requires correlating with a known-
# ephemeris baseline — but the 19B + 6B bipartite record structure is
# cross-chipset-stable and documented here for future RE passes.
#
# v3 (2026-04-21n): per-byte variance across fixtures surfaced a second
# structural layer — a 46-byte-stride repeating table starting around
# payload offset 440.  Slot density pattern (across 3665B fixture pairs):
#
#     [ 440:486] slot 0   high variability — populated
#     [ 486:532] slot 1   partial
#     [ 532:578] slot 2   ~0 variability — empty/reserved
#     [ 578:624] slot 3   populated
#     [ 624:670] slot 4   populated
#     ...
#
# Pattern matches a Qualcomm ephemeris cache: a pre-sized per-SV slot
# table where only actively-tracked SVs have populated slots.  Slot
# size 46 bytes fits a standard 40-byte-core ephemeris record plus 6B
# auxiliary header.  Full per-slot field naming still requires an
# ephemeris-baseline cross-check, but the slot-table structure itself
# is locked as an invariant — enough to expose per-slot 46B windows for
# downstream decode.

# Cross-chipset signature markers (empirically stable).
_NAVDB147D_SIG_1091 = 0x1091

# v4 (2026-04-23) per-byte variance analysis on 1482 EM9190 SDX55 records
# (<redacted-pii>) surfaced TWO distinct per-slot
# layouts — both SDX55-specific; MDM9x07 uses different constants at the
# same offsets.
#
# Slot-0 "summary" layout — 5 cross-chipset format markers (SDX55 only).
# (A 6th candidate at [+3] looked constant within a single 1482-record
# EM9190 session at 0x3f, but the fn980m SDX55 fixture has it at 0x3e —
# suggesting it's the sign+exp_hi byte of an f32 that varies by session
# but not by record within a session. Excluded from the validator set.)
#     [+18] = 0x3b   marker byte (combined with +19 forms u16 0xc13b)
#     [+19] = 0xc1   marker byte
#     [+27] = 0xc1   marker byte (same value as +19)
#     [+34] = 0x4f   marker byte / f32 mantissa tail
#     [+35] = 0x41   f32 sign+exp_hi byte of a [2..4) range float
#
# Slot-4..7 "per-SV measurement" layout — 8 shared format zeros +
# 1 non-zero marker (SDX55 only):
#     [+ 1] = 0x00
#     [+ 5..+7] = 0x00 (3 zero bytes)
#     [+ 9] = 0x00
#     [+10] = 0x07   constellation or field-type marker
#     [+12] = 0x00
#     [+45] = 0x00   trailer byte
#
# Slot 1 is populated but appears to carry densely-packed ephemeris-style
# data (uniform-256 byte distribution); structure TBD.  Slots 2-3 and 8+
# are usually empty/zero.
#
# On MDM9x07 fixtures (ep06a, eg18na) the slot-0 offsets hold entirely
# different values (no cross-chipset invariance at these positions),
# indicating the 46-byte-stride layout is an SDX55-family format choice.
# Validators therefore return None on non-SDX55 size classes.

_NAVDB147D_SDX55_SLOT0_CONSTS: dict[int, int] = {
    18: 0x3B, 19: 0xC1, 27: 0xC1, 34: 0x4F, 35: 0x41,
}
_NAVDB147D_SDX55_SLOTC_CONSTS: dict[int, int] = {
    1: 0x00, 5: 0x00, 6: 0x00, 7: 0x00, 9: 0x00, 10: 0x07, 12: 0x00, 45: 0x00,
}
# Slot indices that carry the per-SV "format-C" measurement layout on SDX55.
_NAVDB147D_SDX55_SLOTC_INDICES: tuple[int, ...] = (4, 5, 6, 7)

# v5 (2026-04-23): slot-0 f32 candidate offsets. The two pairs at offsets
# 16 and 32 are locked by the v4 marker constants (exp_hi bytes 0xC1 and
# 0x41 at [+19] and [+35]). The two at offsets 0 and 8 are bounded by
# empirically-observed exp_hi bytes 0x3e/0x3f on the EM9190/fn980m SDX55
# corpus — small positive fractions. Values outside these ranges signal
# a quantizer change or a layout drift.
_NAVDB147D_SDX55_SLOT0_F32_OFFSETS: tuple[int, ...] = (0, 8, 16, 32)


@dataclass
class Diag0x147D:
    """GNSS nav DB 147D (0x147D) — companion to 0x147C, size-variant (#N)."""
    log_time: int
    version: int
    scope_id: int               # u24LE at [1:4] — per-record scope / sequence id
    marker_bytes_5_7: int       # u16LE at [5:7] — header-state word (v7)
    sig_1091_ok: bool           # marker_bytes_5_7 == 0x1091; deprecated — v2
                                # mis-named this a cross-chipset format marker
                                # but bytes[5:7] takes values from a small set
                                # (0x1091, 0x1011, 0x0011, 0x0002) that varies
                                # within and across captures. Kept for v1
                                # consumers; new code should read marker_bytes_5_7.
    size_flag: int              # byte [7] — 0x00 on 3665B / 0x10 on 4717B
    size_class: str             # "mdm9x07_3665" | "sdx55_4717" | "unknown"
    payload_size: int
    body_raw: bytes
    # v3 (2026-04-21n): 46-byte-stride slot table starting at offset 440.
    # Exposed as raw slots so downstream consumers can iterate without
    # re-parsing.  None on unknown sizes.
    body_slot_table_start: int | None
    body_slot_stride: int | None
    body_slots: list[bytes] | None  # list of 46B slices starting at [440:]

    # v4 (2026-04-23): SDX55-family slot-layout validators. None on MDM9x07
    # (the 46-byte-stride constants do not hold on that family).
    slot_0_sdx55_format_ok: bool | None   # slot 0's 6 cross-record constants all present
    slot_c_sdx55_format_count: int | None  # how many of slots 4..7 match format-C

    # v5 (2026-04-23): slot-0 f32 decodes on SDX55. None on MDM9x07.
    # The two pairs at offsets 16 and 32 are locked by v4 marker constants
    # (exp_hi 0xC1 → [-16, -8) range; exp_hi 0x41 → [8, 16) range). The two
    # at offsets 0 and 8 are empirically small positive fractions.
    slot_0_sdx55_f32_at_0: float | None   # ≈ [0.1, 0.5) on SDX55 corpus
    slot_0_sdx55_f32_at_8: float | None   # ≈ [0.1, 0.5)
    slot_0_sdx55_f32_at_16: float | None  # ≈ [-16, -8) via 0xC1 marker
    slot_0_sdx55_f32_at_32: float | None  # ≈ [8, 16) via 0x41 marker

    # Preserved for backward compatibility with v1 consumers (dlf_to_jsonl
    # snapshots, downstream tooling).  Deprecated — prefer scope_id.  Once
    # every consumer is migrated these can be dropped.
    counter_hi: int
    counter_lo: int
    sub_counter: int            # v1 bug: this was always 0x91; kept for compat.

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x147D',
            'log_time': self.log_time,
            'version': self.version,
            'scope_id': self.scope_id,
            'marker_bytes_5_7': self.marker_bytes_5_7,
            'sig_1091_ok': self.sig_1091_ok,
            'size_flag': self.size_flag,
            'size_class': self.size_class,
            'payload_size': self.payload_size,
            'body_slot_table_start': self.body_slot_table_start,
            'body_slot_stride': self.body_slot_stride,
            'body_slots_count': len(self.body_slots) if self.body_slots else 0,
            'slot_0_sdx55_format_ok': self.slot_0_sdx55_format_ok,
            'slot_c_sdx55_format_count': self.slot_c_sdx55_format_count,
            'slot_0_sdx55_f32_at_0': (
                None if self.slot_0_sdx55_f32_at_0 is None
                else round(self.slot_0_sdx55_f32_at_0, 9)
            ),
            'slot_0_sdx55_f32_at_8': (
                None if self.slot_0_sdx55_f32_at_8 is None
                else round(self.slot_0_sdx55_f32_at_8, 9)
            ),
            'slot_0_sdx55_f32_at_16': (
                None if self.slot_0_sdx55_f32_at_16 is None
                else round(self.slot_0_sdx55_f32_at_16, 6)
            ),
            'slot_0_sdx55_f32_at_32': (
                None if self.slot_0_sdx55_f32_at_32 is None
                else round(self.slot_0_sdx55_f32_at_32, 6)
            ),
            # v1-compat fields (deprecated).
            'counter_hi': self.counter_hi,
            'counter_lo': self.counter_lo,
            'sub_counter': self.sub_counter,
        }


def _147d_size_class(n: int) -> str:
    if n == 3185:
        return "mc7455_3185"
    if n == 3665:
        return "mdm9x07_3665"
    if n == 4717:
        return "sdx55_4717"
    return "unknown"


_NAVDB147D_SLOT_TABLE_START = 440
_NAVDB147D_SLOT_STRIDE = 46

# v10 (#N): v=0x08 is the variable-size, 46-byte-stride, cross-chipset
# (SDX55/SDX62) form — the dominant real-world 0x147D shape (13,605 records
# / 36 captures in the #N audit). Structure confirmed this pass on a
# Quectel RM520N-GL SDX62 capture (1,582 records, 8 sizes 1691..2013 B):
#   * Sizes advance in EXACT 46-byte steps; every size == 35 (mod 46).
#   * Within-record byte autocorrelation peaks at lag 46 (0.639) and 92
#     (2x46) — the 46B slot stride is the dominant period.
#   * Adjacent sizes differ by exactly one 46B slot (1691 vs 1737: 1-byte
#     common prefix, diff regions differ by exactly 46B) -> header + N*46B
#     slots + trailer; bumping the size appends one nav-DB entry.
#   * The v=0x05/0x06 header convention carries forward and is verified
#     LOCKED across all 1,582 records: [0]=0x08, [4]=0x00, [6]=0x10,
#     [7]=0x00, [8:16]=0; [5] is the state-word high bit (0x11/0x91, giving
#     marker_bytes_5_7 in {0x1011, 0x1091} — the same small set as v5/6).
# The ABSOLUTE slot-table start offset is NOT uniquely determinable from
# size arithmetic alone (many (header, trailer) splits satisfy the (mod 46)
# == 35 constraint; the universal common trailer is only 36B), and slots
# carry no cross-record locked columns (consistent with all-varying
# ephemeris fields). So this is a STRUCTURAL-recognition landing (same
# conservative posture as v=0x04): the format is recognized + the stride is
# exposed, but body_slots stay raw pending symbolic/ephemeris RE.
_NAVDB147D_V08_VERSION = 0x08
_NAVDB147D_V08_SIZE_MOD = 35   # len(data) % 46 on every observed v=0x08 record
# Carried-forward header anchors (LOCKED on 1,582/1,582 RM520N-GL records).
_NAVDB147D_V08_HEADER_ANCHORS: dict[int, int] = {4: 0x00, 6: 0x10, 7: 0x00}


# --- Ground-truth recipe (#N) — MC7455 / Sierra SWI9X30C, v=0x04 -----------
# Vendor name LOG_GNSS_PE_KF_POSITION_REPORT_C (vendor_official): the Position
# Engine's Kalman-filter position report. On the MC7455 (MDM9x30) this is the
# v=0x04 / 3185B variant (peeked: byte[0]==0x04 on the gnss-live capture). The
# header is decoded structurally; the body carries the KF nav solution
# (lat/lon/alt/velocity) but the 46B slot table does NOT tile cleanly for 3185B,
# so the position payload is exposed raw and is the open RE. The NOTE-worthy
# point (#N): the SDX55-only slot_0_* f32 fields are None on the MC7455 — do
# NOT ground them here; only the v=0x04 header + record-emission are valid anchors.
# Grounding design: capture during a live GNSS fix and correlate the 0x147D v=4
# report cadence + (eventually) the decoded body against AT!GPSLOC? position.
# Authored offline (<redacted-ref>) — hypothesis only, no hardware run yet.

@register(
    0x147D, domain="gnss",
    name="0x147D",
    description="GNSS nav DB 147D — companion to 0x147C, size-variant (#N)",
    version=10,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v1 header-only RE across EP06A + EG18-NA + LM960 + FN980m "
        "(#N, 2026-04-17).  v2 (2026-04-21): dropped duplicate @register; "
        "renamed bogus sub_counter (always 0x91) → sig_1091 cross-chipset "
        "format-marker validator; extracted u24LE scope_id at [1:4] and "
        "size_flag at [7]; documented 19B + 6B bipartite per-SV record "
        "stride hypothesis for body RE.  v3 (2026-04-21n): discovered "
        "second body layer — a 46-byte-stride slot table starting at "
        "offset 440 (ephemeris-cache layout); exposes body_slots for "
        "downstream per-slot decode.  v4 (2026-04-23): per-byte variance "
        "on 1482 EM9190 SDX55 records revealed TWO SDX55-specific slot "
        "layouts — slot-0 summary (6 format markers) and slots 4..7 "
        "per-SV measurement (8 constants); validators added. MDM9x07 "
        "uses a different slot structure — validators return None there. "
        "v5 (2026-04-23): promoted 4 marker-backed slot-0 f32 decodes at "
        "offsets 0/8/16/32 — the pairs at 16 and 32 are locked by the v4 "
        "exp_hi markers 0xC1 and 0x41; the pairs at 0 and 8 are empirically "
        "small positive fractions. None on MDM9x07. "
        "v6 (2026-04-25): validated against 940 FN980 SDX55 records "
        "(firmware 38.03.282-P0H.000700, gnss_comparison_lg290p_2026-04-23 "
        "+ edge_cases_2026-04-24). Findings: (1) size_flag is a BITFIELD "
        "not a chipset enum — observed values on FN980 4717B records are "
        "0x12 (steady state, 911/940), 0x00 (state-transition, 26/940), "
        "and 0x02 (warm-restart transient, 3/940). v2's 'size_flag=0x10 "
        "on 4717B / 0x00 on 3665B' was a single-fixture observation: the "
        "0x10 high bit is 'SDX55 4717B size class' and the 0x02 low bit "
        "is 'FN980 firmware variant'. EM9190 sets only 0x10 (no FN980 "
        "bit); FN980 sets both = 0x12. (2) f32@16 and f32@32 are "
        "session-stable across 940 records with 1e-5 absolute spread — "
        "essentially constants, not range-bounded floats. (3) sig_1091 "
        "is steady-state-only — fails on 35/113 warm-GNSS-restart records "
        "while holding on every steady-state capture; documented as a "
        "transient that can fail during GNSS state transitions. None of "
        "these change the parser's emit shape; they tighten the docstring "
        "claims to match observed corpus behavior. "
        "v7 (2026-05-01, /rtcm-revisit <redacted-ref>): the v6 'sig_1091 "
        "holds on every steady-state capture' claim is FALSIFIED. Cross-"
        "checking 883 records from 4 splitter-paired LG290P captures "
        "(EP06A, EM7511, EG18-NA, FN980) shows bytes[5:7] takes values "
        "from a small set: 0x1091 (modal — EP06A 293/295, EM7511 462/462, "
        "FN980 5/5), 0x1011 (a few records on EP06A & EG18-NA), 0x0011 "
        "(EG18-NA gnss_comparison_lg290p_2026-04-11: 113/121 in pure "
        "steady-state stationary capture), 0x0002 (single record). Both "
        "byte[5] AND byte[6] vary independently within a single capture "
        "session — bytes[5:7] is a header-state word, NOT a format marker. "
        "v2's 'cross-chipset constant' claim was an artifact of N=1-record-"
        "per-chipset fixtures all happening to land on the modal value. "
        "The actually-cross-chipset header invariants are version + size_class "
        "+ scope_id structure + body record-type tags at body[1]/[20] — "
        "those remain valid. Added marker_bytes_5_7 field exposing the "
        "actual u16LE value; sig_1091_ok kept for v1 consumers but "
        "redocumented as deprecated (consumers should read marker_bytes_5_7). "
        "New EG18-NA fixture from the LG290P-paired capture pins the "
        "falsifying invariant going forward. "
        "v8 (2026-05-11, #N audit follow-up — Wave 3 G1): added (size, "
        "version) tuple hard gate at top of parser body before reading "
        "scope_id at bytes [1:4]. Audit flagged 'scope_id = data[1] | … "
        "first' as the silent-mis-parse hazard. Corpus across 5 fixtures: "
        "version is 0x05 on 3665B records and 0x06 on 4717B records — the "
        "two are locked. Added field_invariants on version + payload_size. "
        "v9 (2026-05-28, #N / #N completeness-audit drain): added the "
        "v=0x04 ↔ 3185B variant (Sierra MC7455, MDM9x30 — the chipset rung "
        "BELOW v=0x05/3665B). Established entirely from the 7 MC7455 "
        "SWI9X30C_02.24.03.00 .scan.json sidecars' offset_dist (1,376 "
        "records, no corpus walk) plus a 2-record raw confirmation from "
        "<redacted-pii>. The v=0x04 header is "
        "byte-identical to the v=0x05/0x06 convention: [0]=0x04 (LOCKED "
        "301/301), [1:4] u24LE scope_id (high byte [3] clusters 0x17–0x1b "
        "→ slow per-record counter, observed +1000/record), [4]=0x00 "
        "(LOCKED), [5:7] header-state word (modal 0x1091, also 0x1011 — same "
        "small set as the other generations), [7] size_flag=0x00 (no SDX55 "
        "0x10 / FN980 0x02 bits — correct for the sub-ladder MDM9x30), "
        "[8:16] reserved-zero. Body record tags hold too: body[+1]=0x09 "
        "([17]), [+6]=0x08 ([22]), [+8]=0x03 ([24]), [+14]=0x04 ([30]) all "
        "LOCKED, and the bipartite 19B-rec[+2:6]==6B-tail[+2:6] invariant is "
        "intact (a05d0a05 on the fixture). The record-start marker at [16] "
        "is 0x71 on MC7455 (vs 0x6d/0x6e on later gens) — chipset-specific, "
        "not asserted. The 46-byte slot table at offset 440 does NOT tile "
        "cleanly for 3185B ((3185-440)/46 = 59.67), so body_slots are "
        "exposed raw (as for mdm9x07_3665, whose count is likewise "
        "non-integer) and the SDX55-only slot validators stay None. "
        "Widened field_invariants version→{0x04,0x05,0x06}, "
        "payload_size→{3185,3665,4717}; joint (size,version) gate extended. "
        "Drains the #N audit's v=0x04 miss (1,376 records). "
        "v10 (2026-05-29, #N / #N drain): added the v=0x08 VARIABLE-size "
        "variant — the dominant real-world 0x147D shape (13,605 records / 36 "
        "captures). Confirmed on a Quectel RM520N-GL SDX62 capture (1,582 "
        "records, 8 sizes 1691..2013 B): sizes advance in EXACT 46B steps "
        "(every size == 35 mod 46); within-record byte autocorrelation peaks "
        "at lag 46 (0.639) + 92 (2x46); adjacent sizes differ by exactly one "
        "46B slot (header + N*46B slots + trailer — bumping size appends one "
        "nav-DB entry). The v5/6 header convention carries forward LOCKED "
        "across 1,582/1,582 records: [0]=0x08, [4]=0x00, [6]=0x10, [7]=0x00, "
        "[8:16]=0; [5] is the state-word high bit (0x11/0x91 → "
        "marker_bytes_5_7 in {0x1011,0x1091}). STRUCTURAL landing (v=0x04 "
        "posture): the absolute slot-table start is not uniquely determinable "
        "from size arithmetic (universal common trailer only 36B; many "
        "header/trailer splits satisfy the mod-46 constraint) and slots carry "
        "no cross-record locked columns (all-varying ephemeris fields), so "
        "body_slot_stride=46 is exposed but body_slots stay raw pending "
        "symbolic/ephemeris RE. payload_size dropped from field_invariants "
        "(now version-conditional: fixed for v4/5/6, variable for v8 — the "
        "0x13C7 pattern); the parser joint-gate still enforces the fixed "
        "v4/5/6 sizes and the (mod 46)==35 relationship for v8. Drains the "
        "#N audit's v=0x08 version miss (~15K records)."
    ),
    source_url="",
    issues=(),
    primary_issue=None,
    # 15 named header/metadata fields + v5's 4 slot-0 f32 decodes on SDX55
    # + v7's marker_bytes_5_7. Body still opaque at per-field level for
    # slots 1-N — pending ephemeris-baseline correlation. (#N)
    fields_parsed=20,
    fields_identified=21,
    field_invariants={
        # v10 (#N): version enum widened to include 0x08 (the variable-size
        # SDX55/SDX62 form), draining the #N completeness-audit miss.
        # payload_size is no longer a global invariant — it is version-
        # conditional (fixed 3185/3665/4717 for v4/5/6, but variable in 46B
        # steps for v8). Following the 0x13C7 precedent for variable-size
        # codes, the size relationship is enforced in the parser body (the
        # joint (size,version) gate for v4/5/6; the (len % 46)==35 +
        # header-anchor gate for v8) rather than via an exploding/incorrect
        # payload_size enum here.
        "version": {"enum": [0x04, 0x05, 0x06, 0x08]},
    },
)
def parse_0x147d(log_time: int, data: bytes) -> Diag0x147D | None:
    if len(data) < 16:
        return None
    # v8 (#N audit follow-up): hard gate on byte 0 (version) BEFORE
    # reading scope_id at bytes [1:4]. Audit flagged 'scope_id = data[1]
    # | … first' as the silent-mis-parse hazard. Corpus: version is
    # 0x05 on 3665B (mdm9x07/sdx20) and 0x06 on 4717B (sdx55) — the
    # version is locked to the size class. Reject anything outside the
    # observed (size, version) pair.
    sz = len(data)
    version = data[0]
    # Explicit Layer-1 version gate (audit-visible). The joint (size,
    # version) constraint below is the tighter invariant; this looser
    # `data[0] not in {…}` form is what the #N audit regex looks for.
    if data[0] not in (0x04, 0x05, 0x06, 0x08):
        return None
    # v10 (#N): v=0x08 is the variable-size 46B-stride form (SDX55/SDX62).
    # It does NOT participate in the fixed-size joint gate below; instead it
    # is recognized by the (len % 46)==35 size relationship + the carried-
    # forward header anchors. A v=0x08 record failing either rejects (None)
    # rather than mis-decoding through the fixed-size path.
    if version == _NAVDB147D_V08_VERSION:
        return _parse_0x147d_v08(log_time, data)
    # v9 (#N): v=0x04 ↔ 3185B is the MC7455 (MDM9x30) rung below the
    # existing ladder. Header + body record tags are byte-identical to the
    # v=0x05/0x06 format (verified: [0]=0x04, [4]=0x00, [5:7] header-state
    # word, [7]=0x00, and body tags [17]=0x09/[22]=0x08/[24]=0x03/[30]=0x04
    # with the 19B-rec[+2:6] == 6B-tail[+2:6] bipartite invariant intact).
    if not (
        (sz == 3185 and version == 0x04)
        or (sz == 3665 and version == 0x05)
        or (sz == 4717 and version == 0x06)
    ):
        return None
    scope_id = data[1] | (data[2] << 8) | (data[3] << 16)
    marker_bytes_5_7 = unpack_from('<H', data, 5)[0]
    sig_1091_ok = marker_bytes_5_7 == _NAVDB147D_SIG_1091
    size_class = _147d_size_class(len(data))

    body_slot_table_start: int | None = None
    body_slot_stride: int | None = None
    body_slots: list[bytes] | None = None
    slot_0_sdx55_format_ok: bool | None = None
    slot_c_sdx55_format_count: int | None = None
    slot_0_sdx55_f32_at_0: float | None = None
    slot_0_sdx55_f32_at_8: float | None = None
    slot_0_sdx55_f32_at_16: float | None = None
    slot_0_sdx55_f32_at_32: float | None = None
    if size_class in ('mc7455_3185', 'mdm9x07_3665', 'sdx55_4717'):
        body_slot_table_start = _NAVDB147D_SLOT_TABLE_START
        body_slot_stride = _NAVDB147D_SLOT_STRIDE
        body_slots = []
        off = _NAVDB147D_SLOT_TABLE_START
        while off + _NAVDB147D_SLOT_STRIDE <= len(data):
            body_slots.append(bytes(data[off:off + _NAVDB147D_SLOT_STRIDE]))
            off += _NAVDB147D_SLOT_STRIDE

    # SDX55-only slot-format validators. MDM9x07 slots do not share these
    # constants (see docstring); leave as None to signal "not applicable".
    if size_class == 'sdx55_4717' and body_slots is not None:
        slot0 = body_slots[0]
        slot_0_sdx55_format_ok = all(
            slot0[o] == v for o, v in _NAVDB147D_SDX55_SLOT0_CONSTS.items()
        )
        slot_c_sdx55_format_count = sum(
            1 for si in _NAVDB147D_SDX55_SLOTC_INDICES
            if si < len(body_slots) and all(
                body_slots[si][o] == v for o, v in _NAVDB147D_SDX55_SLOTC_CONSTS.items()
            )
        )
        # v5: 4 marker-backed slot-0 f32 decodes
        slot_0_sdx55_f32_at_0  = unpack_from('<f', slot0, 0)[0]
        slot_0_sdx55_f32_at_8  = unpack_from('<f', slot0, 8)[0]
        slot_0_sdx55_f32_at_16 = unpack_from('<f', slot0, 16)[0]
        slot_0_sdx55_f32_at_32 = unpack_from('<f', slot0, 32)[0]

    return Diag0x147D(
        log_time=log_time,
        version=data[0],
        scope_id=scope_id,
        marker_bytes_5_7=marker_bytes_5_7,
        sig_1091_ok=sig_1091_ok,
        size_flag=data[7],
        size_class=size_class,
        payload_size=len(data),
        body_raw=bytes(data[16:]),
        body_slot_table_start=body_slot_table_start,
        body_slot_stride=body_slot_stride,
        body_slots=body_slots,
        slot_0_sdx55_format_ok=slot_0_sdx55_format_ok,
        slot_c_sdx55_format_count=slot_c_sdx55_format_count,
        slot_0_sdx55_f32_at_0=slot_0_sdx55_f32_at_0,
        slot_0_sdx55_f32_at_8=slot_0_sdx55_f32_at_8,
        slot_0_sdx55_f32_at_16=slot_0_sdx55_f32_at_16,
        slot_0_sdx55_f32_at_32=slot_0_sdx55_f32_at_32,
        # v1-compat — pre-existing consumers rely on these fields existing.
        counter_hi=data[1],
        counter_lo=data[2],
        sub_counter=data[5],
    )


def _parse_0x147d_v08(log_time: int, data: bytes) -> Diag0x147D | None:
    """v=0x08 variable-size 46B-stride form (#N, 2026-05-29).

    Structural-recognition landing (see module constants for the corpus
    evidence). Gate: ``len(data) % 46 == 35`` (the universal size signature)
    plus the carried-forward header anchors ([4]=0, [6]=0x10, [7]=0,
    [8:16]=0). A record failing either is rejected so a format drift surfaces
    as a no-parse miss instead of a plausible-but-garbage decode.

    The 46B slot stride is exposed (confirmed by within-record autocorrelation
    + the exact 46B size quantum), but ``body_slots`` stays raw: the absolute
    slot-table start is not uniquely determinable from size arithmetic alone
    and slots carry no cross-record locked columns. Per-slot ephemeris decode
    is deferred (needs symbolic/baseline RE).
    """
    if len(data) % _NAVDB147D_SLOT_STRIDE != _NAVDB147D_V08_SIZE_MOD:
        return None
    if any(data[o] != v for o, v in _NAVDB147D_V08_HEADER_ANCHORS.items()):
        return None
    if any(b != 0 for b in data[8:16]):
        return None
    scope_id = data[1] | (data[2] << 8) | (data[3] << 16)
    marker_bytes_5_7 = unpack_from('<H', data, 5)[0]
    return Diag0x147D(
        log_time=log_time,
        version=data[0],
        scope_id=scope_id,
        marker_bytes_5_7=marker_bytes_5_7,
        sig_1091_ok=marker_bytes_5_7 == _NAVDB147D_SIG_1091,
        size_flag=data[7],
        size_class="sdx62_v08_var",
        payload_size=len(data),
        body_raw=bytes(data[16:]),
        # Stride confirmed; absolute table start + per-slot decode deferred.
        body_slot_table_start=None,
        body_slot_stride=_NAVDB147D_SLOT_STRIDE,
        body_slots=None,
        # SDX55 fixed-size slot validators do not apply to the variable form.
        slot_0_sdx55_format_ok=None,
        slot_c_sdx55_format_count=None,
        slot_0_sdx55_f32_at_0=None,
        slot_0_sdx55_f32_at_8=None,
        slot_0_sdx55_f32_at_16=None,
        slot_0_sdx55_f32_at_32=None,
        # v1-compat — pre-existing consumers rely on these fields existing.
        counter_hi=data[1],
        counter_lo=data[2],
        sub_counter=data[5],
    )
