"""GNSS NMEA-over-DIAG parser (0x1384).

Wraps NMEA sentences from the GNSS engine as DIAG log frames.  This is
significant because the DIAG path carries NMEA types (Galileo $GA*,
combined $GN*, SBAS $PQ*) that may be absent from the AT NMEA port
(see #N — EG18-NA NMEA output gaps).

## Format versions

Two on-the-wire format versions identified by the leading version byte.
The v1 layout is the original Sierra/older-Qualcomm shape; v2 inserts
two bytes (``fix_quality`` + reserved zero) between the bitmap and the
sentence-length field but is otherwise identical, including a fixed
200-byte NMEA body.

### v1 — 208 bytes (`version = 0x32`)

    Byte  0:        u8   version = 0x32
    Bytes 1..4:     u32 LE  client_id (firmware-baked vendor magic)
    Bytes 5..6:     u16 LE  nmea_bitmap (16-bit sentence-type selector)
    Byte  7:        u8   nmea_length
    Bytes 8..207:   200 B  NMEA sentence (null-terminated ASCII + padding)

### v2 — 210 bytes (`version = 0x02`)

    Byte  0:        u8   version = 0x02
    Bytes 1..4:     u32 LE  client_id
    Bytes 5..6:     u16 LE  nmea_bitmap
    Byte  7:        u8   fix_quality (flag, 0 or 1) — added in v2
    Byte  8:        u8   reserved (zero) — added in v2
    Byte  9:        u8   nmea_length
    Bytes 10..209:  200 B  NMEA sentence (null-terminated ASCII + padding)

## Observed values across the corpus (422,364 records / 14 chipset families)

Corpus walk 2026-06-26 (#N re-check): 749,057 records / 204 captures.

| version | client_id  | size | chipsets                     | records          |
|---------|------------|------|------------------------------|-----------------:|
| 0x02    | 0x00000DA3 | 210  | most chipsets (except below) | 705,661 (94.21%) |
| 0x02    | 0x00001389 | 210  | sim7600 / sim8202            |  17,226 ( 2.30%) |
| 0x02    | 0xFFFFFFFF | 210  | rxm-g1 (proprietary $PQW*)   |      26 (<0.01%) |
| 0x32    | 0x00000DA3 | 208  | mc7455 only                  |   6,964 ( 0.93%) |
| 0x32    | 0x00002329 | 208  | mc7700 (SWI9200X / MDM9200)  |   8,911 ( 1.19%) |

``client_id`` is firmware-baked vendor magic, independent of ``version``:
SimCom emits 0x00001389; the Sierra MC7700 (an older MDM9200-class part)
emits 0x00002329 and uses the older v1/208-byte layout; the Compal RXM-G1
emits the all-ones sentinel 0xFFFFFFFF on its proprietary $PQW* sentences;
every other vendor (Quectel, most Sierra, Telit, Inseego, Foxconn) emits
0x00000DA3.

## Decoded sentence types

This parser extracts the raw NMEA sentence and additionally parses
the fields of known sentence types (GGA, RMC, GSV, GSA, VTG, GNS,
GLL, DTM) into structured dataclasses accessible via the `parsed`
field.

v5 (#N #N <redacted-ref> ASCII re-walk, 29k records / 15 vendors):
added GLL + DTM dispatch.  The walk found these two STANDARD NMEA
types recurring in the corpus (GLL ~136, DTM ~147) but falling through
to ``parsed=None`` — GLL in particular carries lat/lon and this code
is ``wigle_direct``.  Proprietary ``$PSTIS`` (empty marker) and
``$PQXFI`` (Qualcomm XTRA fix-info; same $PQ* family as 0x1C7C/0x1375)
remain pass-through raw — their structured decode belongs with the
proprietary-GNSS codes, not here.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_CGPS_PDSM_EXT_STATUS_NMEA_REPORT_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        LOG_CGPS_PDSM_EXTENDED_STATUS_NMEA_REPORT
            source: qxdm_3_12_714_2017_diag_log_codes
        LOG_INTERNAL_CGPS_PDSM_EXTENDED_STATUS_NMEA_REPORT
            source: qxdm_3_12_714_2017_diag_log_codes
        LOG_SNSD_ERROR
            source: qxdm_3_12_714_2017_diag_log_codes
        LOG_CGPS_PDSM_EXTERNAL_STATUS_NMEA_REPORT
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from diaggrok.registry import register


# ---------------------------------------------------------------------------
# Parsed NMEA sentence dataclasses
# ---------------------------------------------------------------------------

@dataclass
class NmeaGGA:
    """GGA — Global Positioning System Fix Data."""
    utc_time: str              # HHMMSS.ss
    latitude: float | None     # Decimal degrees (negative = South)
    longitude: float | None    # Decimal degrees (negative = West)
    fix_quality: int           # 0=invalid, 1=GPS, 2=DGPS, 4=RTK, 5=float RTK
    num_satellites: int
    hdop: float | None
    altitude_m: float | None   # Altitude above MSL in meters
    geoid_sep_m: float | None  # Geoid separation in meters
    dgps_age: float | None     # Age of differential correction
    dgps_station_id: str       # Reference station ID

    def to_dict(self) -> dict[str, Any]:
        return {
            'sentence_type': 'GGA',
            'utc_time': self.utc_time,
            'latitude': self.latitude,
            'longitude': self.longitude,
            'fix_quality': self.fix_quality,
            'num_satellites': self.num_satellites,
            'hdop': self.hdop,
            'altitude_m': self.altitude_m,
            'geoid_sep_m': self.geoid_sep_m,
        }


@dataclass
class NmeaRMC:
    """RMC — Recommended Minimum Navigation Information."""
    utc_time: str              # HHMMSS.ss
    status: str                # A=active, V=void
    latitude: float | None     # Decimal degrees
    longitude: float | None    # Decimal degrees
    speed_knots: float | None  # Speed over ground in knots
    course_deg: float | None   # Course over ground in degrees true
    date: str                  # DDMMYY
    mag_variation: float | None
    mode: str                  # A=autonomous, D=DGPS, E=estimated, N=not valid

    def to_dict(self) -> dict[str, Any]:
        return {
            'sentence_type': 'RMC',
            'utc_time': self.utc_time,
            'status': self.status,
            'latitude': self.latitude,
            'longitude': self.longitude,
            'speed_knots': self.speed_knots,
            'course_deg': self.course_deg,
            'date': self.date,
            'mode': self.mode,
        }


@dataclass
class NmeaSvInfo:
    """Single satellite info within a GSV sentence."""
    prn: int                   # Satellite PRN number
    elevation_deg: int | None  # Elevation in degrees (0-90)
    azimuth_deg: int | None    # Azimuth in degrees (0-359)
    snr_dbhz: int | None       # Signal-to-noise ratio in dB-Hz

    def to_dict(self) -> dict[str, Any]:
        return {
            'prn': self.prn,
            'elevation_deg': self.elevation_deg,
            'azimuth_deg': self.azimuth_deg,
            'snr_dbhz': self.snr_dbhz,
        }


@dataclass
class NmeaGSV:
    """GSV — Satellites in View."""
    total_messages: int        # Total number of GSV messages in this set
    message_number: int        # This message number (1-based)
    total_svs: int             # Total satellites in view
    satellites: list[NmeaSvInfo] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            'sentence_type': 'GSV',
            'total_messages': self.total_messages,
            'message_number': self.message_number,
            'total_svs': self.total_svs,
            'satellites': [sv.to_dict() for sv in self.satellites],
        }


@dataclass
class NmeaGSA:
    """GSA — GNSS DOP and Active Satellites."""
    mode_auto: str             # M=manual, A=automatic
    fix_type: int              # 1=no fix, 2=2D, 3=3D
    sv_ids: list[int]          # Up to 12 active satellite PRNs
    pdop: float | None
    hdop: float | None
    vdop: float | None
    system_id: int | None      # NMEA 4.11: 1=GPS, 2=GLONASS, 3=Galileo, 4=BeiDou

    def to_dict(self) -> dict[str, Any]:
        return {
            'sentence_type': 'GSA',
            'mode_auto': self.mode_auto,
            'fix_type': self.fix_type,
            'sv_ids': self.sv_ids,
            'pdop': self.pdop,
            'hdop': self.hdop,
            'vdop': self.vdop,
            'system_id': self.system_id,
        }


@dataclass
class NmeaVTG:
    """VTG — Track Made Good and Ground Speed."""
    course_true: float | None   # Course over ground, degrees true
    course_mag: float | None    # Course over ground, degrees magnetic
    speed_knots: float | None   # Speed over ground in knots
    speed_kmh: float | None     # Speed over ground in km/h
    mode: str                   # A=autonomous, D=DGPS, E=estimated, N=not valid

    def to_dict(self) -> dict[str, Any]:
        return {
            'sentence_type': 'VTG',
            'course_true': self.course_true,
            'course_mag': self.course_mag,
            'speed_knots': self.speed_knots,
            'speed_kmh': self.speed_kmh,
            'mode': self.mode,
        }


@dataclass
class NmeaGNS:
    """GNS — GNSS Fix Data (NMEA 4.10+ multi-constellation)."""
    utc_time: str              # HHMMSS.ss
    latitude: float | None     # Decimal degrees
    longitude: float | None    # Decimal degrees
    mode_indicator: str        # Mode per constellation (e.g. "AAN" = GPS auto, GLONASS auto, Galileo none)
    num_satellites: int
    hdop: float | None
    altitude_m: float | None
    geoid_sep_m: float | None
    dgps_age: float | None
    dgps_station_id: str

    def to_dict(self) -> dict[str, Any]:
        return {
            'sentence_type': 'GNS',
            'utc_time': self.utc_time,
            'latitude': self.latitude,
            'longitude': self.longitude,
            'mode_indicator': self.mode_indicator,
            'num_satellites': self.num_satellites,
            'hdop': self.hdop,
            'altitude_m': self.altitude_m,
            'geoid_sep_m': self.geoid_sep_m,
        }


@dataclass
class NmeaGLL:
    """GLL — Geographic Position, Latitude/Longitude."""
    latitude: float | None     # Decimal degrees (negative = South)
    longitude: float | None    # Decimal degrees (negative = West)
    utc_time: str              # HHMMSS.ss
    status: str                # A=valid, V=invalid
    mode: str                  # A=autonomous, D=DGPS, E=estimated, N=not valid

    def to_dict(self) -> dict[str, Any]:
        return {
            'sentence_type': 'GLL',
            'latitude': self.latitude,
            'longitude': self.longitude,
            'utc_time': self.utc_time,
            'status': self.status,
            'mode': self.mode,
        }


@dataclass
class NmeaDTM:
    """DTM — Datum Reference."""
    local_datum: str           # e.g. "W84", "P90"
    lat_offset_min: float | None   # Latitude offset, minutes
    lon_offset_min: float | None   # Longitude offset, minutes
    alt_offset_m: float | None     # Altitude offset, meters
    ref_datum: str             # Reference datum (e.g. "W84")

    def to_dict(self) -> dict[str, Any]:
        return {
            'sentence_type': 'DTM',
            'local_datum': self.local_datum,
            'lat_offset_min': self.lat_offset_min,
            'lon_offset_min': self.lon_offset_min,
            'alt_offset_m': self.alt_offset_m,
            'ref_datum': self.ref_datum,
        }


# ---------------------------------------------------------------------------
# NMEA field parsing helpers
# ---------------------------------------------------------------------------

def _parse_float(s: str) -> float | None:
    """Parse a float field, returning None for empty strings."""
    if not s:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def _parse_int(s: str) -> int | None:
    """Parse an integer field, returning None for empty strings."""
    if not s:
        return None
    try:
        return int(s)
    except ValueError:
        return None


def _parse_latlon(value: str, hemisphere: str) -> float | None:
    """Parse NMEA latitude (DDMM.MMMM) or longitude (DDDMM.MMMM) to decimal degrees.

    Returns negative for S/W hemispheres.
    """
    if not value or not hemisphere:
        return None
    try:
        # Find the decimal point to split degrees from minutes
        dot_pos = value.index('.')
        # Degrees are everything before the last 2 digits before the dot
        deg_digits = dot_pos - 2
        if deg_digits < 1:
            return None
        degrees = int(value[:deg_digits])
        minutes = float(value[deg_digits:])
        result = degrees + minutes / 60.0
        if hemisphere in ('S', 'W'):
            result = -result
        return result
    except (ValueError, IndexError):
        return None


def _strip_checksum(sentence: str) -> str:
    """Strip the *XX checksum suffix from an NMEA sentence."""
    idx = sentence.find('*')
    if idx >= 0:
        return sentence[:idx]
    return sentence


# ---------------------------------------------------------------------------
# Sentence parsers
# ---------------------------------------------------------------------------

def _parse_gga(fields: list[str]) -> NmeaGGA | None:
    """Parse GGA fields: time,lat,N/S,lon,E/W,quality,numSV,hdop,alt,M,sep,M,age,stn."""
    if len(fields) < 15:
        return None
    return NmeaGGA(
        utc_time=fields[1],
        latitude=_parse_latlon(fields[2], fields[3]),
        longitude=_parse_latlon(fields[4], fields[5]),
        fix_quality=int(fields[6]) if fields[6] else 0,
        num_satellites=int(fields[7]) if fields[7] else 0,
        hdop=_parse_float(fields[8]),
        altitude_m=_parse_float(fields[9]),
        geoid_sep_m=_parse_float(fields[11]),
        dgps_age=_parse_float(fields[13]),
        dgps_station_id=fields[14] if len(fields) > 14 else '',
    )


def _parse_rmc(fields: list[str]) -> NmeaRMC | None:
    """Parse RMC fields: time,status,lat,N/S,lon,E/W,spd,cog,date,mv,mvE/W,mode."""
    if len(fields) < 12:
        return None
    return NmeaRMC(
        utc_time=fields[1],
        status=fields[2],
        latitude=_parse_latlon(fields[3], fields[4]),
        longitude=_parse_latlon(fields[5], fields[6]),
        speed_knots=_parse_float(fields[7]),
        course_deg=_parse_float(fields[8]),
        date=fields[9],
        mag_variation=_parse_float(fields[10]),
        mode=fields[12] if len(fields) > 12 else '',
    )


def _parse_gsv(fields: list[str]) -> NmeaGSV | None:
    """Parse GSV fields: numMsg,msgNum,numSV,[prn,elev,az,snr]*4."""
    if len(fields) < 4:
        return None
    total_messages = _parse_int(fields[1]) or 0
    message_number = _parse_int(fields[2]) or 0
    total_svs = _parse_int(fields[3]) or 0

    satellites = []
    # Each satellite takes 4 fields starting at index 4
    i = 4
    while i + 3 < len(fields):
        prn = _parse_int(fields[i])
        if prn is None:
            break
        satellites.append(NmeaSvInfo(
            prn=prn,
            elevation_deg=_parse_int(fields[i + 1]),
            azimuth_deg=_parse_int(fields[i + 2]),
            snr_dbhz=_parse_int(fields[i + 3]),
        ))
        i += 4

    return NmeaGSV(
        total_messages=total_messages,
        message_number=message_number,
        total_svs=total_svs,
        satellites=satellites,
    )


def _parse_gsa(fields: list[str]) -> NmeaGSA | None:
    """Parse GSA fields: mode,fixType,sv1..sv12,pdop,hdop,vdop[,systemId]."""
    if len(fields) < 18:
        return None
    mode_auto = fields[1]
    fix_type = int(fields[2]) if fields[2] else 1

    # SV IDs are in fields 3..14 (12 slots)
    sv_ids = []
    for i in range(3, 15):
        if i < len(fields) and fields[i]:
            sv = _parse_int(fields[i])
            if sv is not None:
                sv_ids.append(sv)

    pdop = _parse_float(fields[15]) if len(fields) > 15 else None
    hdop = _parse_float(fields[16]) if len(fields) > 16 else None
    vdop = _parse_float(fields[17]) if len(fields) > 17 else None
    # NMEA 4.11 system ID is field 18 (after vdop)
    system_id = _parse_int(fields[18]) if len(fields) > 18 else None

    return NmeaGSA(
        mode_auto=mode_auto,
        fix_type=fix_type,
        sv_ids=sv_ids,
        pdop=pdop,
        hdop=hdop,
        vdop=vdop,
        system_id=system_id,
    )


def _parse_vtg(fields: list[str]) -> NmeaVTG | None:
    """Parse VTG fields: cogt,T,cogm,M,spdN,N,spdK,K,mode."""
    if len(fields) < 9:
        return None
    return NmeaVTG(
        course_true=_parse_float(fields[1]),
        course_mag=_parse_float(fields[3]),
        speed_knots=_parse_float(fields[5]),
        speed_kmh=_parse_float(fields[7]),
        mode=fields[9] if len(fields) > 9 else '',
    )


def _parse_gns(fields: list[str]) -> NmeaGNS | None:
    """Parse GNS fields: time,lat,N/S,lon,E/W,mode,numSV,hdop,alt,sep,age,stn."""
    if len(fields) < 13:
        return None
    return NmeaGNS(
        utc_time=fields[1],
        latitude=_parse_latlon(fields[2], fields[3]),
        longitude=_parse_latlon(fields[4], fields[5]),
        mode_indicator=fields[6],
        num_satellites=int(fields[7]) if fields[7] else 0,
        hdop=_parse_float(fields[8]),
        altitude_m=_parse_float(fields[9]),
        geoid_sep_m=_parse_float(fields[10]),
        dgps_age=_parse_float(fields[11]),
        dgps_station_id=fields[12] if len(fields) > 12 else '',
    )


def _parse_gll(fields: list[str]) -> NmeaGLL | None:
    """Parse GLL fields: lat,N/S,lon,E/W,time,status,mode."""
    if len(fields) < 7:
        return None
    return NmeaGLL(
        latitude=_parse_latlon(fields[1], fields[2]),
        longitude=_parse_latlon(fields[3], fields[4]),
        utc_time=fields[5],
        status=fields[6],
        mode=fields[7] if len(fields) > 7 else '',
    )


def _parse_dtm(fields: list[str]) -> NmeaDTM | None:
    """Parse DTM fields: localDatum,subDatum,latOff,N/S,lonOff,E/W,altOff,refDatum."""
    if len(fields) < 9:
        return None
    lat_off = _parse_float(fields[3])
    if lat_off is not None and fields[4] in ('S', 'W'):
        lat_off = -lat_off
    lon_off = _parse_float(fields[5])
    if lon_off is not None and fields[6] in ('S', 'W'):
        lon_off = -lon_off
    return NmeaDTM(
        local_datum=fields[1],
        lat_offset_min=lat_off,
        lon_offset_min=lon_off,
        alt_offset_m=_parse_float(fields[7]),
        ref_datum=fields[8],
    )


# Map sentence type suffix to parser
_SENTENCE_PARSERS = {
    'GGA': _parse_gga,
    'RMC': _parse_rmc,
    'GSV': _parse_gsv,
    'GSA': _parse_gsa,
    'VTG': _parse_vtg,
    'GNS': _parse_gns,
    'GLL': _parse_gll,
    'DTM': _parse_dtm,
}


def parse_nmea_sentence(sentence: str) -> Any | None:
    """Parse a complete NMEA sentence string into a structured dataclass.

    Returns None if the sentence type is not recognized or parsing fails.
    """
    stripped = _strip_checksum(sentence)
    fields = stripped.split(',')
    if not fields:
        return None

    # Identify sentence type: last 3 chars of talker field (e.g. "$GPGGA" → "GGA")
    talker = fields[0]
    if len(talker) < 4:
        return None
    # Handle $PQGSA (proprietary) — sentence type is last 3 chars
    sentence_type = talker[-3:]

    parser = _SENTENCE_PARSERS.get(sentence_type)
    if parser is None:
        return None
    try:
        return parser(fields)
    except (ValueError, IndexError):
        return None


# ---------------------------------------------------------------------------
# Top-level dataclass and parser
# ---------------------------------------------------------------------------

@dataclass
class Diag0x1384:
    """GNSS NMEA sentence wrapped in a DIAG log frame (0x1384)."""
    log_time: int
    version: int                  # byte 0 — 0x32 (v1) or 0x02 (v2)
    client_id: int                # u32 LE bytes 1..4 (firmware-baked vendor magic)
    nmea_bitmap: int              # u16 LE bytes 5..6 — sentence-type selector
    fix_quality: int | None       # byte 7 (v2 only); None on v1
    nmea_length: int              # byte 7 (v1) or byte 9 (v2)
    nmea_sentence: str            # Raw decoded NMEA string
    nmea_talker: str              # First field (e.g., "$GPGGA")
    parsed: Any | None = None     # Structured parse of known sentence types

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            'type': 'Diag0x1384',
            'log_time': self.log_time,
            'version': self.version,
            'client_id': self.client_id,
            'nmea_talker': self.nmea_talker,
            'nmea_sentence': self.nmea_sentence,
            'nmea_bitmap': self.nmea_bitmap,
            'fix_quality': self.fix_quality,
        }
        if self.parsed is not None:
            d['parsed'] = self.parsed.to_dict()
        return d


# ---------------------------------------------------------------------------
# Ground-truth recipe (#N) — EG95-NA (Quectel, MDM9x07), authored offline
# from parser source + corpus_index. hw_run_performed=False: every field is a
# hypothesis until a hardware verification run captures the log alongside the
# paired AT/NMEA reference (diag_groundtruth.py --needs-work).
#
# 0x1384 is the cleanest GNSS anchor in the EG95 corpus: it WRAPS the GNSS
# engine's NMEA sentences inside the DIAG frame, so it grounds two ways —
#   (1) the structured `parsed.*` scalars ground numerically vs AT+QGPSLOC=2;
#   (2) the raw `nmea_sentence` should be byte-comparable (same talker+type+
#       fix epoch) to AT+QGPSGNMEA output on the AT port.
# Target version is 0x02 (210 B) — confirmed on EG95-NA (2,945 records, the
# LG290P-paired gnss_comparison_2026-05-07 capture). v1/0x32 is mc7455-only.
# vendor name LOG_CGPS_PDSM_EXT_STATUS_NMEA_REPORT_C confirms the GNSS/CGPS
# subsystem — title and name agree.

@register(
    0x1384,
    name="0x1384",
    description="NMEA sentences from GNSS engine via DIAG — includes Galileo/BeiDou/SBAS types missing from AT NMEA port (#N)",
    version=8,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail="Clean-room RE from EG18-NA SDX20 V2; v4 aligns field naming with the on-the-wire v1/v2 spec — version, client_id (u32), nmea_bitmap (u16) — and dispatches both format versions. v5 (#N <redacted-ref> ASCII re-walk, 29k records / 15 vendors) adds GLL + DTM structured dispatch (standard NMEA types found recurring but unparsed; GLL carries lat/lon). $PSTIS/$PQXFI proprietary sentences stay raw pass-through.",
    source_url="",
    issues=(),
    primary_issue=None,
    # Envelope fields identified + parsed: version, client_id, nmea_bitmap,
    # fix_quality (v2-only), nmea_length, nmea_sentence (full structured NMEA
    # via parse_nmea_sentence — GGA/RMC/GSV/GSA/VTG/GNS).
    fields_identified=6, fields_parsed=6,
    # ASCII audit (#N, Quectel slice): 654/654 records carry NMEA
    # sentences ($GPVTG/$GAVTG/$GPGSV/$PSTIS) — the structured NMEA-
    # passthrough code, parsed via parse_nmea_sentence below.
    ascii_kinds=("nmea",),
    # WiGLE tagging (#N NMEA-carrier focus list): NmeaGGA exposes
    # latitude/longitude/altitude_m/num_satellites/hdop/utc_time at dataclass
    # level via .parsed; NmeaRMC + NmeaGNS likewise expose lat/lon/utc/date.
    # Periodic ~1 Hz cadence per sentence type. Validated 422,364 records /
    # 14 chipset families (corpus walk 2026-05-07).
    wigle_direct=True,
    wigle_roles=("position", "gnss-quality", "timing-anchor:periodic"),
    field_invariants={
        # Validated against 422,364 records / 143 captures / 14 chipset
        # families (corpus walk 2026-05-07, #N follow-up).
        #
        # version: 0x02 (v2 layout, 210 B) dominates the corpus at 97.49%;
        # 0x32 (v1 layout, 208 B) is mc7455-only at 2.51%.  v2 inserts a
        # fix_quality byte + reserved zero between the bitmap and the
        # sentence-length field.
        "version": {
            "enum": [0x02, 0x32],
        },
        # client_id (u32 LE bytes 1..4) is firmware-baked vendor magic.
        # Tracked here so corpus regression catches a new client_id appearing
        # on a new firmware — which is exactly what the 2026-06-26 re-check
        # did (#N, corpus grown to 749,057 records).  Observed set, all
        # corpus-attested + modem-attributed + parse-valid:
        #   0x00000DA3  most chipsets (Quectel/Sierra/Telit/Inseego/Foxconn)
        #   0x00001389  SimCom (sim7600 / sim8202)
        #   0x00002329  Sierra MC7700 (SWI9200X / MDM9200) — v=0x32, 8,911
        #               records, 100% NMEA-checksum-valid (added 2026-06-26)
        #   0xFFFFFFFF  Compal RXM-G1 all-ones sentinel on proprietary $PQW*
        #               sentences — F3-verified nmea_sentence (added 2026-06-26)
        "client_id": {
            "enum": [0x00000DA3, 0x00001389, 0x00002329, 0xFFFFFFFF],
        },
    },
)
def parse_0x1384(log_time: int, data: bytes) -> Diag0x1384 | None:
    if len(data) < 10:
        return None

    version = data[0]
    # Layer-1 version gate (#N / #N). The dispatch below has
    # `if version == 0x32 / else` shape, where `else` was previously
    # untyped — relying on the trailing `nmea_start < 0` check to
    # implicitly reject unknown versions. Make the rejection explicit
    # so the audit regex sees the gate.
    if version not in (0x02, 0x32):
        return None
    client_id = data[1] | (data[2] << 8) | (data[3] << 16) | (data[4] << 24)
    nmea_bitmap = data[5] | (data[6] << 8)

    # v1 (208 B): no fix_quality byte; sentence-length at byte 7;
    #             NMEA $ starts at byte 8; body is 200 B.
    # v2 (210 B): fix_quality at byte 7; reserved zero at byte 8;
    #             sentence-length at byte 9; NMEA $ at byte 10; body 200 B.
    if version == 0x32:
        fix_quality: int | None = None
        nmea_length = data[7]
        search_start = 8
    else:
        fix_quality = data[7]
        nmea_length = data[9]
        search_start = 10

    nmea_start = data.find(b'$', search_start)
    if nmea_start < 0:
        return None

    # Find end of NMEA: CR/LF line ending, null terminator, or end of data
    nmea_end = len(data)
    for terminator in (b'\r\n', b'\r', b'\n', b'\x00'):
        pos = data.find(terminator, nmea_start)
        if 0 <= pos < nmea_end:
            nmea_end = pos

    nmea_sentence = data[nmea_start:nmea_end].decode('ascii', errors='replace')
    nmea_talker = nmea_sentence.split(',')[0] if ',' in nmea_sentence else nmea_sentence

    # Parse the NMEA fields into a structured object
    parsed = parse_nmea_sentence(nmea_sentence)

    return Diag0x1384(
        log_time=log_time,
        version=version,
        client_id=client_id,
        nmea_bitmap=nmea_bitmap,
        fix_quality=fix_quality,
        nmea_length=nmea_length,
        nmea_sentence=nmea_sentence,
        nmea_talker=nmea_talker,
        parsed=parsed,
    )
