"""0x1587 — GNSS tracking detail (variable: 52/85/115 bytes on SDX55).

Header-only; 5 known versions {0x0C..0x10} with per-version sentinel
byte at offset 19; body unparsed (#N).

Split from `gnss_demod.py` per #N tier-2 batch 12.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_EVENT_IPSEC_CHILD_SA_REKEY_DONE
        source: qxdm_3_12_714_2017_diag_log_codes (authority: community)
    aliases:
        RESERVED
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from diaggrok.registry import register

LOG_GNSS_TRACKING_1587 = 0x1587

# Layer-1 version gate (closure-rigor pass 2026-05-23, <redacted-ref> #N).
# 5 versions observed across the 142,127-record corpus walk (2026-05-08):
# 0x0C (4,245), 0x0D (21,188), 0x0E (25,288), 0x0F (70,688), 0x10 (20,718).
# Any other byte-0 value indicates a firmware-format change and must be
# rejected at parse time rather than silently decoded into the per-
# version sentinel slot at offset +19 (which will be a stale value).
# When a v0x11 capture is RE'd, ADD 0x11 here AND to the matching
# field_invariants enum on @register below.
_KNOWN_VERSIONS = frozenset({0x0C, 0x0D, 0x0E, 0x0F, 0x10})


@dataclass
class Diag0x1587:
    """GNSS tracking detail report (0x1587).

    Variable-length: 20-byte header + N × variable body entries.

    ## Cross-corpus version distribution (2026-05-08, 142,127 records)

    The original 2026-04-12 FN980m-only RE session declared byte 0
    "always 0x0F" and byte 19 "always 0x26". Both were small-N
    premature conclusions. Corpus walk overturns:

        offset 0 (version):   0x0F (49.7%), 0x0E (17.8%), 0x0D (14.9%),
                              0x10 (14.6%), 0x0C (3.0%) — 5 versions
        offset 19 ('sentinel'): 0x26 (49.7%), 0x1F (17.8%), 0x19 (14.9%),
                              0x27 (14.6%), ... — distribution mirrors
                              version exactly, suggesting byte 19 is a
                              per-version sentinel/tail-marker.

    Per the core-memories rule "size invariance ≠ format invariance":
    a future v=0x11 record (next sequential version) is the expected
    failure mode. The ``field_invariants={"version": {"enum": [...]}}``
    declaration on ``@register`` rejects unknown versions as None,
    surfacing a parse-rate drop instead of silent garbage. Add 0x11 to
    the enum once a v=0x11 capture is RE'd.

    Body sizes observed (corpus-wide): 30..200 B with concentrations
    at 32, 65, 95, 96 B (totaling 52/85/115/116 B with 20-byte header).

    ## 20-byte header fully mapped (2026-05-31 <redacted-ref>)

    The 2026-05-23 parser named only bytes 0,1,2,19 and **silently
    dropped offsets 3..18**. A version-conditional walk
    (`/tmp/walk_1587_header.py`, 73,887 DLF records) characterizes every
    dropped byte so the record no longer hides data (user directive:
    "know WHAT data is in the message"). The `marker_6` invariant below
    was then validated against the **full corpus** — 199,121 records via
    the format-detecting iterator (DLF+HDLC) — with 0 violations.
    Per-offset finding (offsets relative to record start):

        +3  byte_3   counter/index, 6..151 uniq per version — MIRRORS +13
        +4  flag_4   state flag {0x00 dom, 0x01..0x04 minority} — MIRRORS +14
        +5  state_5  GNSS tracking-state byte {0x6b..0x74, 0xff}, 100%
                     nonzero, per-version modal (v0E peaks 0x6d, v10 peaks
                     0x72). Same 0x6d..0x72+0xff signature as #N byte+20
                     — likely a shared chipset-firmware GNSS state indicator.
        +6  marker_6 low-cardinality marker — exactly {0x05, 0x09, 0xff}
                     across ALL 199,121 records, full corpus (declared as an invariant).
                     0xff is the uninitialized-sentinel value.
        +7..+12      mid_raw — 6 high-entropy bytes (256 uniq each, ~99%
                     nonzero): per-SV counters / measurement deltas. Opaque.
        +13 byte_13  identical distribution to +3 (mirror pair).
        +14 flag_14  identical distribution to +4 (mirror pair).
        +15..+18     zero-padding: 0x00 across 100% of all records / versions.
        +19 sentinel per-version tail-marker (existing).

    The +3≡+13 / +4≡+14 mirror suggests the header carries a repeated
    field pair at a +10 stride. mid_raw and the body remain semantically
    opaque (DIAG×AT-correlation-gated); every header byte is now named.
    """
    log_time: int
    version: int           # byte 0 — one of {0x0C, 0x0D, 0x0E, 0x0F, 0x10}
    counter_hi: int        # byte 1
    counter_lo: int        # byte 2
    byte_3: int            # byte 3 — counter/index; mirrors byte_13
    flag_4: int            # byte 4 — state flag; mirrors flag_14
    state_5: int           # byte 5 — GNSS tracking-state byte (#N-parallel)
    marker_6: int          # byte 6 — marker, enum {0x05, 0x09, 0xff}
    mid_raw: bytes         # bytes 7..12 — high-entropy counter/measurement (opaque)
    byte_13: int           # byte 13 — mirror of byte_3
    flag_14: int           # byte 14 — mirror of flag_4
    pad_15_18: bytes       # bytes 15..18 — confirmed zero-padding (corpus-wide)
    sentinel: int          # byte 19 — per-version, distribution mirrors version
    body_size: int
    body_raw: bytes

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1587',
            'log_time': self.log_time,
            'version': self.version,
            'counter_hi': self.counter_hi,
            'counter_lo': self.counter_lo,
            'byte_3': self.byte_3,
            'flag_4': self.flag_4,
            'state_5': self.state_5,
            'marker_6': self.marker_6,
            'mid_hex': self.mid_raw.hex(),
            'byte_13': self.byte_13,
            'flag_14': self.flag_14,
            'pad_15_18_hex': self.pad_15_18.hex(),
            'sentinel': self.sentinel,
            'body_size': self.body_size,
            'payload_size': 20 + self.body_size,
        }


# Ground-truth recipe (#N). Authored offline (session <redacted-ref>) — NOT
# hardware-verified. SIM8202G-M2 (SIMCom SDX55) is the recommended target.
# Authored for v=0x0F, the most-attested version corpus-wide (49.7%); the
# 5 versions {0x0C..0x10} are sequential firmware-rev sentinels, not
# chipset-locked, so the validator confirms the exact byte-0 value the
# SIM8202G-M2 firmware emits at capture time and re-stamps `version` if it
# differs. Names-block honesty: the community QXDM name on this code
# (LOG_EVENT_IPSEC_CHILD_SA_REKEY_DONE / RESERVED) is bogus index noise —
# an IPsec event name for a code whose observation (state_5 GNSS
# tracking-state byte, gnss_demod cluster) is unambiguously GNSS. Per
# precedence observation > community, this grounds against the GNSS engine.

@register(
    LOG_GNSS_TRACKING_1587, domain="gnss",
    name="0x1587",
    description="GNSS tracking detail report (0x1587); header-only; 5 known versions {0x0C..0x10} with per-version sentinel byte at offset 19; body unparsed (#N)",
    version=4,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    # Pin the canonical tracker explicitly so the IDT-header resolver does
    # NOT free-text-scrape the comparative "#N-parallel" reference in
    # source_detail: #N is 0x14E0's tracker (a sibling GNSS code), cited
    # here only to compare tracking-state-byte signatures, not as an 0x1587
    # tracker. #N is this code's tracker. (Fixes #N IDT drift.)
    issues=(),
    source_detail=(
        "v4 (2026-05-31, <redacted-ref>): mapped the full 20-byte header — "
        "offsets 3..18 were previously SILENTLY DROPPED (body_raw started "
        "at +20). Version-conditional walk of 73,887 records names every "
        "byte: +3/+13 mirror-pair counter, +4/+14 mirror-pair state flag, "
        "+5 GNSS tracking-state byte ({0x6b..0x74,0xff}, #N-parallel), "
        "+6 marker enum {0x05,0x09,0xff} (NEW invariant — exactly 3 values "
        "corpus-wide), +7..+12 high-entropy counter/measurement (opaque), "
        "+15..+18 confirmed zero-padding. mid_raw + body remain opaque "
        "(DIAG×AT-gated). "
        "v3 (2026-05-23, <redacted-ref> closure-rigor): added layer-1 byte-0 "
        "version gate matching the existing layer-2 field_invariants enum. "
        "v2 (2026-05-08, <redacted-ref>): corpus walk surfaced 5 sequential "
        "versions {0x0C..0x10} with per-version byte-19 sentinel "
        "correlation, overturning the v1 small-N invariance claims at "
        "offsets 0 and 19. v1: Clean-room RE from FN980m SDX55 DLF "
        "capture (#N)."
    ),
    source_url="",
    # 11 named header scalars decoded (version, counter_hi, counter_lo,
    # byte_3, flag_4, state_5, marker_6, byte_13, flag_14, sentinel,
    # body_size). mid_raw (+7..+12) and body_raw (+20..) remain opaque —
    # the record is NOT 100% decoded; parse_0x1587 returns `T | None` so
    # the completeness guard (test_no_fraudulent_completeness_claims)
    # correctly does not treat 11/11 as a full-record completeness claim.
    fields_parsed=11,
    fields_identified=11,
    # version is genuinely polymorphic — 5 sequential format revisions
    # observed across the corpus. Per core-memories "size invariance ≠
    # format invariance": this enum is the protection against silent
    # mis-parse on a future v=0x11 record. ADD 0x11 (and any later
    # values) here when a new version's body is RE'd. (#N)
    #
    # marker_6 (byte +6) takes EXACTLY {0x05, 0x09, 0xff} across all
    # 199,121 records / 5 versions (2026-05-31 full-corpus walk). 0xff is the
    # uninitialized-sentinel value. A 4th value would signal a firmware
    # format change — surfaced as an enum violation.
    field_invariants={
        "version":  {"enum": [0x0C, 0x0D, 0x0E, 0x0F, 0x10]},
        "marker_6": {"enum": [0x05, 0x09, 0xFF]},
    },
)
def parse_0x1587(log_time: int, data: bytes) -> Diag0x1587 | None:
    """Parse a 0x1587 GNSS tracking detail record (#N).

    Layer-1 first-byte version-gate: only the 5 corpus-observed versions
    {0x0C..0x10} are accepted; anything else returns None.  The matching
    layer-2 ``field_invariants={"version": {"enum": [...]}}`` on the
    @register call provides a backstop via ``check_invariants()``.
    """
    if len(data) < 20:
        return None
    if data[0] not in _KNOWN_VERSIONS:
        return None
    return Diag0x1587(
        log_time=log_time,
        version=data[0],
        counter_hi=data[1],
        counter_lo=data[2],
        byte_3=data[3],
        flag_4=data[4],
        state_5=data[5],
        marker_6=data[6],
        mid_raw=data[7:13],
        byte_13=data[13],
        flag_14=data[14],
        pad_15_18=data[15:19],
        sentinel=data[19],
        body_size=len(data) - 20,
        body_raw=data[20:],
    )
