"""0x1893 - MCS_CXM coexistence manager low-priority arbitration log (#N, #N).

CAMP: coexistence (domain="coex"). NOT GNSS. Two-variant typed parser.

Split from `lte_misc.py` per #N tier-3 batch 16.

**F3-grounded subsystem identity (2026-07-13, #N Tier-3 CXM correlation):**
the firmware's Coexistence-Manager logger `cxm_trace.c` prints
`MCS_CXM: CXM entered cxm_send_log. Log Code: 0x1893` from its own commit path
(the qdb-resolved runtime value names the code), observed across five
SDX55-class modems (RM500Q-AE / FN980 / SIM8202GM2 / T99W640). 0x1893 sits in
the contiguous CXM priority block 0x1892-0x1895
(SMEM_DATA / LOW_PRIO / MEDIUM_PRIO / HIGH_PRIO), matching the community
zukgit-2025 name `LOG_MCS_CXM_LOW_PRIO`. Sibling 0x1894 is the same CXM family
(#N), and its payload is likewise a slotted arbitration table.

**Prior "GNSS measurement-engine status" framing is DISPROVEN (superseded here).**
It was an ungrounded guess: the #N chain had already *rejected* the QXDM
"GNSS_ME_NAVIC_MEAS" title as not matching the records (MDM9207 EG25-G has no
NavIC yet still emits this code), and the only HW-validation attempt (#N,
RM520N-GL <redacted-ref> 5174) came back PARTIAL/negative - `occupied_count`
modals at 14 (the structural slot max) regardless of satellites-in-view
(12-21), i.e. it does NOT track satellite count as a GNSS measurement log
would. The firmware CXM commit-path oracle settles it: this is a coexistence
arbitration table, not a GNSS measurement report. See #N / DIAG_LOG_INDEX
`disproven_names` for 0x1893.

Two layout variants distinguished by total payload size:
  888B: SDX5x/SDX62 (62B header + 14×59B slots). version_b=0x02.
  873B: MDM9607 EG25-G (61B header + 14×58B slots). version_b=0x01.

Field offsets within header and slot are identical between variants
through marker_14; only the trailing pad byte differs. The 14 slots are
CXM arbitration slots (not GNSS measurement slots); per-slot field
semantics (marker_a/b, status_flag, timestamp_u40) remain opaque CXM
internals with no vendor-command reference.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_MCS_CXM_LOW_PRIO
        source: qualcomm_firmware_f3_log_emission_oracles (authority: vendor_official)
    aliases: (none recorded)
    disproven_names (WRONG - explicitly refuted, do NOT use):
        LOG_EVENT_CPC_CONFIG_ACTION
            source: qxdm_3_12_714_2017_diag_log_codes (refuted by: qualcomm_firmware_f3_log_emission_oracles)
            reason: Community QXDM-2017 name for an unrelated subsystem (WCDMA Continuous Packet Connectivity config action). Firmware cxm_trace.c commits 0x1893 through the MCS_CXM (Coexistence Manager) logger, proving it is a CXM low-priority arbitration log packet - wrong subsystem, not merely older.

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


# Ground-truth recipe (#N framework; recorded on #N, subsystem corrected
# on #N). HONEST SCOPE: `occupied_count` is the number of active (non-zero
# timestamp) CXM arbitration slots; it modals at the structural max of 14 and
# does NOT track any external observable (the #N HW run found no satellite-
# count correlation, one of the signals that refuted the old GNSS framing). The
# per-slot fields (marker_a/b, status_flag, timestamp_u40) are opaque CXM
# internals with no vendor-command reference, so they are deliberately NOT
# grounded. version = 0x01 is the DIAG payload version byte; the RM520N-GL emits
# the 888-byte (version_b=0x02) SDX62 form.

@dataclass
class CxmArbSlot1893:
    """One CXM arbitration slot in a 0x1893 record (59 B)."""
    occupied: bool
    timestamp_u40: int   # [+0..+4] little-endian u40, 0 if slot empty
    marker_a: int        # [+8]  expected 0x06 when occupied
    marker_b: int        # [+11] expected 0x01 when occupied
    status_flag: int     # [+14] varies (0x00, 0x04, ...)

    def to_dict(self) -> dict[str, Any]:
        return {
            'occupied': self.occupied,
            'timestamp_u40': self.timestamp_u40,
            'marker_a': self.marker_a,
            'marker_b': self.marker_b,
            'status_flag': self.status_flag,
        }


@dataclass
class Diag0x1893:
    """MCS_CXM low-prio arbitration log (0x1893) - 62 B header + 14 × 59 B slots."""
    log_time: int
    version: int       # [0]  const 0x01
    version_b: int       # [1]  const 0x02
    seq_lo: int          # [2]
    counter: int         # [3..6] u32 LE
    flag_7: int          # [7]
    flag_11: int         # [11] state flag; varies in {0x00, 0x06} corpus-wide
    marker_14: int       # [14] const 0x01
    flag_17: int         # [17]
    slots: list[CxmArbSlot1893]
    occupied_count: int
    payload_size: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1893',
            'log_time': self.log_time,
            'version': self.version,
            'version_b': self.version_b,
            'seq_lo': self.seq_lo,
            'counter': self.counter,
            'flag_7': self.flag_7,
            'flag_11': self.flag_11,
            'marker_14': self.marker_14,
            'flag_17': self.flag_17,
            'occupied_count': self.occupied_count,
            'slots': [s.to_dict() for s in self.slots],
            'payload_size': self.payload_size,
        }


_CXM_1893_NUM_SLOTS = 14
# Two layout variants - distinguished by total payload size.
# 888B: SDX5x/SDX62 (62B header + 14×59B slots). version_b=0x02.
# 873B: MDM9607 EG25-G (61B header + 14×58B slots). version_b=0x01.
# Field offsets within header and slot are identical between variants
# through marker_14; only the trailing pad byte differs.
_CXM_1893_VARIANT = {
    888: (62, 59, 0x02),  # (header_len, slot_len, expected_version_b)
    873: (61, 58, 0x01),
}


def _parse_1893_slot(data: bytes, base: int) -> CxmArbSlot1893:
    # u40 LE timestamp = lower 5 bytes treated as u64 with high 3 bytes 0
    ts_bytes = data[base : base + 5] + b"\x00\x00\x00"
    ts_u40 = unpack_from("<Q", ts_bytes, 0)[0]
    occupied = ts_u40 != 0
    return CxmArbSlot1893(
        occupied=occupied,
        timestamp_u40=ts_u40,
        marker_a=data[base + 8],
        marker_b=data[base + 11],
        status_flag=data[base + 14],
    )


@register(
    0x1893, domain="coex",
    name="0x1893",
    description=(
        "MCS_CXM coexistence-manager low-priority arbitration log (0x1893) - "
        "two-variant typed parser. 888B SDX5x/SDX62 (62B+14×59B) and 873B "
        "MDM9607 EG25-G (61B+14×58B), shared field semantics. F3-grounded as "
        "CXM (not GNSS) via cxm_trace.c commit-path oracle (#N, #N)"
    ),
    version=6,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room RE. 888B layout validated across 6 chipsets/vendors "
        "(SDX55 EM9190/FN980/RM500Q-AE, SDX62 RM520N-GL, MDM9640 EP06A, "
        "SDX20 LM960) by 2026-04-30 corpus pass on 2,084 records. "
        "v3 (2026-04-30): byte[11] reclassified marker_11 const → flag_11 "
        "state flag - strict 0x06 guard was silently dropping ~62% of "
        "valid 888B records (entire RM500Q-AE LG290P 2026-04-28 capture, "
        "92/102 records of EM9190 SWIX55C_03.17.04.00 2026-04-29). "
        "v4 (2026-05-04): added EG25-G MDM9607 873B variant (track 2 of "
        "#N) - same field positions through marker_14, distinguished by "
        "version_b (0x01 vs 888B's 0x02). marker_a (slot +8) NOT pinned "
        "across variants: 888B always 0x06 when occupied, 873B varies "
        "{0x00, 0x06} within a single record."
    ),
    source_url="",
    fields_identified=10,
    fields_parsed=10,
    issues=(),
    # Layer-2 plausibility - corpus walk 2026-05-22 against 17,210 records:
    #   version (offset 0): 0x01 across 100% of records
    #   version_b (offset 1): 0x01 on 873B (MDM9607 EG25-G) / 0x02 on 888B (SDX5x/SDX62)
    #   marker_14 (offset 14): 0x01 across 100% of records, both variants
    # The parser already returns None on mismatch (lines 141-143); declaring
    # these as field_invariants makes the audit toolchain catch corpus-scale
    # violations without modifying parser dispatch.
    field_invariants={
        "version": {"enum": [1]},
        "version_b": {"enum": [1, 2]},
        "marker_14": {"enum": [1]},
    },
)
def parse_0x1893(log_time: int, data: bytes) -> Diag0x1893 | None:
    variant = _CXM_1893_VARIANT.get(len(data))
    if variant is None:
        return None
    header_len, slot_len, expected_version_b = variant
    if data[0] != 0x01 or data[1] != expected_version_b:
        return None
    if data[14] != 0x01:
        return None
    counter = unpack_from('<I', data, 3)[0]
    slots: list[CxmArbSlot1893] = []
    occupied = 0
    for i in range(_CXM_1893_NUM_SLOTS):
        slot = _parse_1893_slot(data, header_len + i * slot_len)
        slots.append(slot)
        if slot.occupied:
            occupied += 1
    return Diag0x1893(
        log_time=log_time,
        version=data[0],
        version_b=data[1],
        seq_lo=data[2],
        counter=counter,
        flag_7=data[7],
        flag_11=data[11],
        marker_14=data[14],
        flag_17=data[17],
        slots=slots,
        occupied_count=occupied,
        payload_size=len(data),
    )
