"""0x117E -- GPS multi-peaks verbose searcher record (compact + extended).

Identity (#N, corrected 2026-05-28): the prior RE labelled this "LTE
ML1 per-subframe measurement" from a single SDX55 capture, but that was
an unverified hypothesis that contradicts the **vendor_official**
Qualcomm name ``LOG_SRCH_GPS_MULTI_PEAKS_VERBOSE_INFO_C`` (and the QXDM
alias ``LOG_INTERNAL_GPS_VERBOSE_MULTIPEAK_VERSION_2``). An 8-chipset
corpus walk found 0x117E fires densely and **exclusively inside GNSS
captures** (gnss_comparison / gnss_diag / warm_gnss_restart) across
every vendor -- consistent with a GPS searcher code, not LTE ML1. The
byte-level GPS semantics (SV / peak / Doppler fields) are still
unresolved (T0/T1); this parser exposes the validated structural shell
only.

Two distinct record formats share this code:

* **Compact** (payload_size 55 / 58 / 62, chipset-dependent base):
  validated header below. byte[0] is NOT a version -- it is uniformly
  distributed over 0..255 (it is the low byte of the u16 at [0:2]); the
  earlier "version 9" reading was a single-capture coincidence.
      [0:2]   u16  record_seq      fast counter (byte0 uniform; ~50% locally monotonic -> wraps)
      [2:6]   u32  reserved_2_6    INVARIANT 0x00000000 (8/8 chipsets, ~28K records)
      [6]     u8   len_marker      == payload_size - 8  (0x32@58B, 0x36@62B; 8/8 chipsets)
      [7]     u8   == 0x00         (8/8 chipsets)
      [8:10]  u16  tag             INVARIANT 0x0066 (8/8 chipsets, ~28K records)
      [10:12] u16  varies per record
      [36:40] u32  timestamp       near-unique / monotonic
      [48:52] u32  measurement_raw varies per record
      [52:56] u32  field_52        small-range index (card 8 on some chipsets -> the "0-7" the old RE saw; up to ~64 on others)
* **Extended** (payload_size 152 / 268 / 568 / 1928 / 5208 / 10248 ...):
  a DIFFERENT layout -- the compact header constants do NOT hold
  (``[2:6] != 0`` and ``[8:10] != 0x0066`` on 0/N extended records). Not
  yet reverse-engineered; exposed as a structural passthrough
  (payload_size + raw record_seq only). The old docstring's "1308B
  extended multi-subframe accumulation" was never validated.

The compact invariants are enforced as a parse-time drift guard (return
None) scoped to the compact size class only -- so a future-firmware
layout change surfaces as a parse-rate drop (core-memory: layer-2
invariant rejection), while the still-unmapped extended records are not
falsely rejected.

Cross-chipset evidence: eg18na, telit/lm960 (SDX20); rm500q, telit/fn980,
em9190, sim8202g-m2 (SDX55); mc7411 (MDM9x50); em9291 (SDX62).

Split from lte_misc.py per #N tier-3 batch 10.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_SRCH_GPS_MULTI_PEAKS_VERBOSE_INFO_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        LOG_INTERNAL_GPS_VERBOSE_MULTIPEAK_VERSION_2
            source: qxdm_3_12_714_2017_diag_log_codes
        RESERVED
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register

# Compact-class structural invariants, validated 8/8 chipsets over ~28K
# base-size records (#N <redacted-ref> 2026-05-28 walk).
_COMPACT_MAX = 80          # compact sizes are 55/58/62; next size class is >=152
_RESERVED_2_6 = 0x00000000  # u32 @ [2:6]
_TAG = 0x0066               # u16 @ [8:10]


@dataclass
class Diag0x117E:
    """0x117E -- GPS multi-peaks verbose searcher (compact + extended).

    Compact-only fields are ``None`` on extended records, whose layout is
    not yet reverse-engineered.
    """

    log_time: int
    payload_size: int
    is_compact: bool
    record_seq: int               # u16 @ [0:2]
    reserved_2_6: int | None      # compact: invariant 0
    len_marker: int | None        # compact: == payload_size - 8
    tag: int | None               # compact: invariant 0x0066
    timestamp: int | None         # compact: near-unique / monotonic
    measurement_raw: int | None   # compact: per-record measurement
    field_52: int | None          # compact: small-range index

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x117E',
            'log_time': self.log_time,
            'payload_size': self.payload_size,
            'is_compact': self.is_compact,
            'record_seq': self.record_seq,
            'reserved_2_6': self.reserved_2_6,
            'len_marker': self.len_marker,
            'tag': self.tag,
            'timestamp': self.timestamp,
            'measurement_raw': self.measurement_raw,
            'field_52': self.field_52,
        }


@register(0x117E, domain="gnss",
    name="0x117E",
    description=(
        "0x117E -- GPS multi-peaks verbose searcher (per vendor_official "
        "LOG_SRCH_GPS_MULTI_PEAKS_VERBOSE_INFO_C). Compact 55/58/62B form: "
        "record_seq + validated structural shell (reserved [2:6]==0, "
        "len_marker [6]==size-8, tag [8:10]==0x0066) + timestamp / "
        "measurement / index. Extended forms (152..10248B) are a different, "
        "not-yet-RE'd layout (structural passthrough)."
    ),
    version=4, author="Luke Jenkins", author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v4 (2026-06-11, <redacted-ref> #N): declared version_less=True — byte-0 "
        "is the low byte of the u16 record_seq at [0:2] (uniform 0..255 over "
        "8 chipsets / ~28K records), NOT a DIAG version; the compact-class "
        "reserved_2_6==0 + tag==0x0066 drift guard already rejects foreign "
        "compact payloads. No version axis exists. "
        "v3 (2026-05-28, <redacted-ref> N=3, #N): corrected identity + "
        "overturned single-capture 'constants'. 8-chipset corpus walk "
        "(eg18na, telit/lm960 SDX20; rm500q, telit/fn980, em9190, "
        "sim8202g-m2 SDX55; mc7411 MDM9x50; em9291 SDX62), ~28K compact "
        "records. Findings: (1) byte[0] is uniformly distributed over "
        "0..255 in every capture -> NOT a version (the prior version=data[0] "
        "and 'version 9' were wrong); it is the low byte of the u16 "
        "record_seq at [0:2]. (2) The prior 'config_id=0x65' is wrong: "
        "u32[2:6]==0 on 8/8 chipsets. (3) byte[6] == payload_size-8 "
        "(0x32@58B / 0x36@62B) -- a length marker, not 'freq_config'. "
        "(4) u16[8:10]==0x0066 on 8/8 chipsets (the prior 0x01000066 "
        "over-fit a single capture; only the low half is invariant). "
        "(5) [36:40] is near-unique/monotonic (timestamp -- the one prior "
        "claim that holds); [52:56] card is 8 on some chipsets (the '0-7' "
        "the old RE saw) but up to ~64 on others. (6) Extended records "
        "(152/268/568/1928/5208/10248B) do NOT satisfy the compact "
        "constants ([2:6]!=0 and [8:10]!=0x0066 on 0/N) -> a distinct, "
        "un-RE'd layout; exposed as passthrough. (7) Identity: all "
        "carrying captures are GNSS captures; combined with the "
        "vendor_official GPS-multipeaks name, the prior 'LTE ML1 "
        "per-subframe' label is dropped. Compact invariants enforced as a "
        "parse-time drift guard scoped to size<=80. GPS field semantics "
        "remain unresolved (T0/T1). "
        "Prior: v2 SDX55 live-capture RE (RM500Q-AE, 2026-04-13) -- "
        "single-capture, now superseded."
    ),
    source_url="",
    issues=(),
    fields_identified=7,
    fields_parsed=7,
    # byte-0 is the low byte of the u16 record_seq counter at [0:2] (uniform
    # 0..255 over 8 chipsets / ~28K records), NOT a DIAG version — RE-proven
    # in the v3 walk (see docstring). The compact-class reserved_2_6 + tag
    # drift guard already rejects foreign payloads; there is no version axis to
    # gate. version_less=True graduates 0x117E off the #N worklist.
    version_less=True,
)
def parse_0x117e(log_time: int, data: bytes) -> Diag0x117E | None:
    n = len(data)
    if n < 2:
        return None

    record_seq = unpack_from('<H', data, 0)[0]
    payload_size = n
    is_compact = n <= _COMPACT_MAX

    reserved_2_6 = len_marker = tag = None
    timestamp = measurement_raw = field_52 = None

    if is_compact:
        if n >= 6:
            reserved_2_6 = unpack_from('<I', data, 2)[0]
            # Drift guard (8/8 chipsets, ~28K records): a compact record
            # whose [2:6] is non-zero is not a 0x117E compact record we
            # understand -> reject so the regression is visible.
            if reserved_2_6 != _RESERVED_2_6:
                return None
        if n >= 7:
            len_marker = data[6]
        if n >= 10:
            tag = unpack_from('<H', data, 8)[0]
            if tag != _TAG:
                return None
        if n >= 40:
            timestamp = unpack_from('<I', data, 36)[0]
        if n >= 52:
            measurement_raw = unpack_from('<I', data, 48)[0]
        if n >= 56:
            field_52 = unpack_from('<I', data, 52)[0]

    return Diag0x117E(
        log_time=log_time,
        payload_size=payload_size,
        is_compact=is_compact,
        record_seq=record_seq,
        reserved_2_6=reserved_2_6,
        len_marker=len_marker,
        tag=tag,
        timestamp=timestamp,
        measurement_raw=measurement_raw,
        field_52=field_52,
    )
