"""0x18F5 - GNSS QZSS/SBAS measurement report, 30B header + N x 71B per-SV blocks, all v=0x00 (#N).

CAMP: GNSS (domain="gnss"). NOT LTE - the "LTE measurement" in the original bulk
registration was a mis-label. The F3 grounding below confirms the name, now
promoted to the firmware-build canonical LOG_GNSS_QZSS_SBAS_MEASUREMENT_REPORT_C
(vendor_official) under #N: the SDX-generation firmware's own
mc_gnssmeasreport.c emits the symbolic F3 "Log packet allocation for
LOG_GNSS_QZSS_SBAS_MEASUREMENT_REPORT_C failed", outranking the former community
zukgit-2025 non-_C form.

Split from `lte_misc.py` per #N tier-3 batch 18.

**F3-grounded subsystem identity (2026-07-12 `<redacted-ref>` deep-F3 pass, #N):**
co-temporal F3 (+/-300 ticks per record, EG18-NA MDM9x55 qdb f1007b36, 248
records) **independently confirms the QXDM canonical name
LOG_GNSS_QZSS_SBAS_MEASUREMENT_REPORT.** The two highest-density co-temporal
files are the firmware's own `mc_gnssmeasreport.c` (13.2% of its prints fall in
the record window) and `nf_sbas.c` (34.5% - the SBAS navigation filter), plus
`mc_gnsssearchstrategy.c`, `nf_navsolution.c`, `nf_wls.c`, `mgp_gpm.c`,
`mc_receiver.c`. This is a GNSS QZSS/SBAS per-SV measurement report, NOT an LTE
measurement (the registration label is a bulk artifact). The -pi/2 f32 sentinel
at block-rel 48 (Qualcomm GNSS not-computed-angle) is corroborated by this
GNSS-measurement-engine grounding.

Promoted from `_simple_parser` stub on 2026-05-08 per #N on the basis
of the 2026-05-08 corpus walk (18,322 records / 100 captures).
Single-version code (v=0x00) with 3 size variants — but unlike the strict
chipset-gen split of 0x1894/0x18E1, here the **same chipset can emit
different sizes**: Telit LM960 + FN980m records appear at both 101B and
172B in the same captures, suggesting a per-event size encoding rather
than chipset discrimination.

  profile      | records | share | observed on
  -------------+---------+-------+--------------------------------------
  172 / 0x00   | 10,464  | 57.1% | FN980m, LM960 (some), RM500Q,
                                   RM520NGL, EM9190, EM7511 (mixed),
                                   EG18-NA (mixed)
  101 / 0x00   |  6,792  | 37.1% | EM7511, EG18-NA, SIM7600NA, EG12-GT,
                                   LM960 (some), FN980m (carrier-bound)
  243 / 0x00   |     75  |  0.4% | LM960 wardriving 2026-03-26 only

Structural geometry resolved 2026-05-30 (#N, <redacted-ref>): since 71 is
prime and the size enum is {101, 172, 243}, the only header/block split
consistent with all three sizes is a fixed **30-byte header + N*71-byte
block array** (101=30+71, 172=30+2*71, 243=30+3*71). Confirmed against
all three committed fixtures (remainder 0 in every case). The f32 at
block-relative offset 48 decodes to -pi/2 (-1.5707963) on every block of
every fixture across MDM9x55 / SDX55 / SDX20 — a cross-chipset angle
sentinel. Per-field RE inside the 71-byte block is otherwise open (#N).

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_GNSS_QZSS_SBAS_MEASUREMENT_REPORT_C
        source: qualcomm_firmware_f3_log_emission_oracles (authority: vendor_official)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register

# --- Ground-truth recipe (#N) -------------------------------------------
# ⚠ SUBSYSTEM FLIP: the parser module is *titled* "LTE measurement", but the
# QXDM canonical name is LOG_GNSS_QZSS_SBAS_MEASUREMENT_REPORT and three
# independent structural signals agree it is GNSS, not LTE: (1) the geometry is
# a 30B header + N×71B per-record blocks (classic per-SV/per-signal measurement
# array), and (2) the f32 at block-rel offset 48 is a corpus-CONSTANT -pi/2 —
# the canonical Qualcomm GNSS "not-computed angle" (elevation/azimuth) sentinel.
# So this recipe grounds against GNSS references (NMEA + Sierra GPS AT), NOT LTE.
# Target: Sierra Wireless EM9291 (SDX62, SWIX65C_02.17.08.00) — emits 0x18F5 and
# has LG290P-referenced GNSS comparison captures (gnss_comparison_2026-05-2x)
# usable as ground truth for SV-count / per-SV cross-checks.

_18F5_VARIANTS: dict[tuple[int, int], str] = {
    (172, 0x00): "lte_meas_172_v00",   # 30B header + 2 blocks
    (101, 0x00): "lte_meas_101_v00",   # 30B header + 1 block (base)
    (243, 0x00): "lte_meas_243_v00",   # 30B header + 3 blocks
}

# Structural geometry resolved 2026-05-30 (#N, <redacted-ref>). Since 71 is prime
# and the corpus size-enum is {101, 172, 243}, the only header/block split
# consistent with all three sizes is a fixed 30-byte header followed by a
# variable count of 71-byte measurement blocks:
#     101 = 30 + 1*71   172 = 30 + 2*71   243 = 30 + 3*71
# This refines the earlier "101 base + appended 71B blocks" framing into a
# clean header + N-block array (same shape as 0x19BB / 0x19EB).
_18F5_HEADER_LEN = 30
_18F5_BLOCK_LEN = 71

# Block-relative offset 48 carries a little-endian f32 that decodes to
# -1.5707963 (== -pi/2) on EVERY block of EVERY fixture across three distinct
# chipsets (eg18na MDM9x55, fn980 SDX55, lm960 SDX20). A -pi/2 angle is the
# canonical Qualcomm GNSS "not-computed" sentinel for an elevation/azimuth
# field (radians). Exposed as a named per-block field; NOT yet declared as a
# layer-2 registry invariant pending a full-corpus offset sweep (#N).
_18F5_BLOCK_ANGLE_OFF = 48


@dataclass
class Gnss18F5Block:
    """Single 71-byte measurement block inside a 0x18F5 record.

    The record is ``30B header + N*71B blocks`` (N = 1/2/3 for the
    101/172/243B size variants). Only the cross-chipset f32 sentinel at
    block-relative offset 48 is named so far; the rest of the 71B is
    preserved as ``raw`` for downstream per-field RE (#N).
    """
    block_index: int
    angle_rad_48: float   # f32 @ block-rel 48 — cross-chipset -pi/2 sentinel
    raw: bytes            # full 71B block payload


@dataclass
class Diag0x18F5:
    """GNSS QZSS/SBAS measurement report (0x18F5): 30B header + N*71B block array, all v=0x00.

    CAMP: GNSS (domain="gnss") - NOT LTE. QXDM LOG_GNSS_QZSS_SBAS_MEASUREMENT_REPORT.

    QXDM canonical name is ``LOG_GNSS_QZSS_SBAS_MEASUREMENT_REPORT``; the
    fixed 30-byte header followed by a variable count of 71-byte blocks is
    consistent with a per-SV / per-signal measurement array. Body-field RE
    inside each 71-byte block is open scope (#N) beyond the -pi/2 angle
    sentinel at block-relative offset 48.
    """
    log_time: int
    version: int
    variant: str
    raw_header: bytes        # 30B header (includes version byte at offset 0)
    block_count: int         # derived: (payload_size - 30) // 71
    blocks: list[Gnss18F5Block]
    payload_size: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x18F5',
            'log_time': self.log_time,
            'version': self.version,
            'variant': self.variant,
            'block_count': self.block_count,
            'payload_size': self.payload_size,
            'blocks': [
                {
                    'block_index': b.block_index,
                    'angle_rad_48': b.angle_rad_48,
                }
                for b in self.blocks
            ],
        }


@register(
    0x18F5,
    name="0x18F5",
    domain="gnss",
    description="GNSS QZSS/SBAS measurement report (0x18F5): 30B header + N x 71B per-SV blocks, 3 size variants, all v=0x00. F3-confirms QXDM LOG_GNSS_QZSS_SBAS_MEASUREMENT_REPORT (mc_gnssmeasreport.c + nf_sbas.c), NOT LTE (#N)",
    version=2,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Cross-chipset corpus walk (2026-05-08, #N): 18,322 records / "
        "100 captures. 3 size variants, all v=0x00: 172B (mixed-chipset, "
        "57.1%), 101B (mixed-chipset, 37.1%), 243B (LM960 wardriving "
        "2026-03-26 only, 0.4%). Same chipset emits different sizes in "
        "the same capture session — per-event encoding, not chipset "
        "discrimination. 71-byte stride between 101→172→243 suggests "
        "fixed structured blocks appended per emission. Original 17B "
        "stub size was a single-FN980m-record artifact. "
        "2026-05-30 (#N <redacted-ref>): geometry resolved to a fixed 30B "
        "header + N*71B block array (101=30+71, 172=30+2*71, 243=30+3*71; "
        "71 is prime so this split is unique). Block-relative offset 48 "
        "carries an f32 == -pi/2 (db 0f c9 bf) — corpus-confirmed CONSTANT "
        "across all 26,968 records / 49 captures (block-0 offset 78), a "
        "fixed unfilled-angle sentinel rather than a live measurement."
    ),
    source_url="",
    fields_identified=6,
    fields_parsed=6,
    issues=(),
    field_invariants={
        "version": {"enum": [0x00]},
        "payload_size": {"enum": [101, 172, 243]},
    },
)
def parse_0x18f5(log_time: int, data: bytes) -> Diag0x18F5 | None:
    n = len(data)
    if n < 1:
        return None
    if data[0] != 0x00:
        return None
    key = (n, data[0])
    variant = _18F5_VARIANTS.get(key)
    if variant is None:
        return None
    # Geometry is guaranteed by the size whitelist above, but re-derive it
    # defensively so the block array stays correct if a new size variant is
    # ever added to _18F5_VARIANTS.
    body_len = n - _18F5_HEADER_LEN
    if body_len < 0 or body_len % _18F5_BLOCK_LEN != 0:
        return None
    block_count = body_len // _18F5_BLOCK_LEN
    blocks: list[Gnss18F5Block] = []
    for i in range(block_count):
        off = _18F5_HEADER_LEN + i * _18F5_BLOCK_LEN
        blk = data[off:off + _18F5_BLOCK_LEN]
        angle = unpack_from('<f', blk, _18F5_BLOCK_ANGLE_OFF)[0]
        blocks.append(Gnss18F5Block(
            block_index=i,
            angle_rad_48=angle,
            raw=bytes(blk),
        ))
    return Diag0x18F5(
        log_time=log_time,
        version=data[0],
        variant=variant,
        raw_header=bytes(data[:_18F5_HEADER_LEN]),
        block_count=block_count,
        blocks=blocks,
        payload_size=n,
    )
