"""ME Position Fix parser (0x14D8).

Split from gnss_position.py per #N tier-2 batch 4 (no shared helper —
MePositionFix is independent of 0x1476 PositionReport at the struct
level; the cross-references in this docstring are correlations only).

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_TEMPERATURE_MONITOR_LOG
        source: qxdm_3_12_714_2017_diag_log_codes (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.codes import LOG_GNSS_ME_POSITION_FIX
from diaggrok.registry import register

# Ground-truth capture recipes (#N / #N / #N lane 0x14D8). ONE version
# observed: version_byte==1 across the whole RE corpus (field_invariants below),
# so every modem's recipe is keyed at version=1.
#
# Honest scope: this code's lat/lon/alt are HARDCODED 0.0 (bytes 20..43 are
# invariantly zero, #N) — they are NOT parsed, so they are deliberately
# absent from the field map. The decoded payload is GNSS measurement-engine
# *state*, so the recipes ground engine-state quantities, not position.
# field_3_high16 is the burst-family/sub-stage field #N wants validated.
#
# #N per-modem fan-out — KEYED, not consolidated. Coverage is counted per
# recipe_key = (version, make, model, firmware); per the campaign definition of
# done, listing a modem in another recipe's emitting_modems does NOT satisfy its
# cell. So 0x14D8 carries ONE GroundTruth PER emitting modem (23 recipes),
# matching the keyed pattern the sibling lanes 0xB111/B113/B114 use. (This
# supersedes the earlier single-recipe + per-modem-Source form from session
# 2cf7, which only credited the keyed RM520N-GL cell.) Each recipe grounds the
# same 4 GNSS-engine-state fields against that modem's own vendor GNSS dialect:
#   Quectel  -> AT+QGPSLOC=2 (+ AT+QGPSGNMEA="GSA"/"GGA" SV/fix cross-check)
#   Telit    -> AT$GPSACP  (field 6 fix 0/2/3; NMEA-style lat/lon NOT used here)
#   Sierra   -> AT!GPSLOC? (+ AT!GPSSATINFO? SV count, AT!GPSSTATUS? state)
#   SIMCom   -> AT+CGNSSINFO (<fix> mode + SV count)
#   QMI-only -> QMI_LOC GetEngineState  (Casa/Foxconn/Inseego/Wistron: vendor
#               GNSS-AT dialect not in the poller allow-list, all Qualcomm QMI)
# Authoring is OFFLINE — every field is status="hypothesis" (no modem in hand,
# no capture taken; a later hardware run flips hw_run_performed + the statuses).

# (slug, make, model, firmware-build-that-emitted-v1, dialect)


# ---------------------------------------------------------------------------
# Dataclass
# ---------------------------------------------------------------------------

@dataclass
class Diag0x14D8:
    """ME Position Fix status (0x14D8).

    Two size variants observed:

    - **20 B short form** (FN980m SDX55, version byte = 1): 5 x u32 header
      at offsets 0, 4, 8, 12, 16. Emitted at ~6 Hz on FN980m (1761 records
      in a 5-minute capture).
    - **104 B long form** (EG18-NA SDX20 V2 + EM7511 SDX20/MDM9650 +
      MC7455 MDM9x30 + MC7411 SDX50M + SIM7600NA-H MDM9x07 + LM960
      SDX20 + EG25-G MDM9207 + EC25 MDM9207 + EP06A MDM9207 +
      EG12-GT MDM9207, version byte = 1): same 20-byte header
      followed by 84 zero bytes. MC7411 added 2026-05-24 (#N):
      cross-firmware sweep on SWI9X50C 01.14.03.00 / 01.14.07.00 /
      01.14.22.00_unit2 yielded 1,847+ records all 104B/v=0x01, no
      new size class or version observed — confirms SDX50M emits the
      same long-form layout as its MDM9x30/SDX20 siblings. The 84-byte tail is **always zero** on **12,047
      observed records / 35 chipset+firmware buckets / 5 vendors**
      (corpus-wide sweep, 2026-05-04 <redacted-ref>, #N - graduates
      the 597-record / 4-chipset bound from <redacted-ref>). The
      surveyed buckets span every LM960 firmware on disk
      (32.01.110/120/140/150/1X0), both EM7511 firmwares
      (01.08.04 / 01.14.22), both EG12-GT firmwares
      (A13M4G / A14M4G), and three EG25-G firmwares. Reserved /
      padding for a format variant that no observed firmware writes.
      Emitted at ~0.4 Hz on EG18-NA and at a bursty ~0.6 Hz avg on
      em7511.

    ## Burst pattern varies by chipset + firmware (#N, 2026-04-20)

    0x14D8 emits a per-stage **measurement engine** status record. The
    number of stages per fix cycle and the (field_2, field_3, field_4_i32)
    tuple per stage is chipset- and firmware-dependent.

    **em7511 01.14.22.00 SDX20/MDM9650** (2026-04-19 high-signal capture,
    295 records, 44 bursts observed, 5-stage):

        1. (0, 1, -50)   "initializer"
        2. (6, 0,   0)
        3. (1, 4, +25+/-1)
        4. (0, 2, +25+/-1)
        5. (7, 0, +25+/-1)

    The ``-50`` initializer is em7511-specific and does **not** appear on
    other SDX20 variants (LM960, EG18-NA). Between bursts: heartbeat with
    (0, 0, +25+/-1).

    **LM960A18 32.01.150 SDX20** (2026-04-20 Unit 4 TMUS gnss-compare,
    136 records, 34 bursts, 4-stage - reclassified from "3-stage +
    heartbeat" after 2026-04-21 intra-burst timing RE, #N follow-up):

        1. (0, 0, +24..25)  - "heartbeat" / cycle start
        2. (0, 1, +24..25)  - stage 1 (opens burst, ~837 us after 1)
        3. (6, 0,   0)      - stage 2 (same log_time as stage 3)
        4. (1, 4, +24..27)  - stage 3 (same log_time as stage 2)

    All four stages fire within ~1 ms of each other, then the cycle
    repeats **every ~10 seconds** (inter-burst gap 524M ticks at the
    52.4288 MHz diag-tick clock).  LM960 does NOT emit em7511's stage 4
    (0, 2, ...) or stage 5 (7, 0, ...) - only 3 of em7511's 5 active
    stages plus the universal (0,0) heartbeat that em7511 also emits
    between bursts.

    Cross-correlation against contemporaneous 0x1476 PositionReport
    (1,129 records, median time-offset 4.6 s) shows **``field_3_u32``
    does NOT track the PositionReport's SV count** - field_3 in {0, 1, 4}
    while 0x1476 consistently reports 3 SVs in the list.  Confirms the
    2026-04-19 hypothesis that the legacy ``sv_used`` name is misleading.

    ``field_4_i32`` = 0 is a **stage-2 sentinel** on LM960 (emitted only
    when (f2,f3)=(6,0); all other stages have field_4_i32 in [24,27]).
    This sign-locked sentinel value is the strongest argument for the
    signed-i32 interpretation over the legacy bitmask interpretation.

    **EG18-NA SDX20 V2** (EG18NAPAR01A06M4G, 124 records, 3-stage) matches
    LM960's 3-stage pattern exactly: (0,1), (6,0), (1,4) + (0,0) heartbeat.

    **MC7455 SWI9X30C_02.24.03.00 MDM9x30** (2026-05-03 LG290P-paired
    stationary, 156 records, 3-stage - first-ever 0x14D8 observation on
    MDM9x30 Sierra; #N <redacted-ref>):

        1. (0, 0, +30..31)  - heartbeat / cycle-start
        2. (0, 1, +30..31)  - stage A
        3. (6, 0,   0)      - stage-B sentinel (universal)

    Missing LM960's `(1, 4, +25)` stage-3 - narrower 3-stage burst.
    `field_4_i32` stable at 30-31 deg C across the 5-min stationary capture,
    consistent with the thermal-zone interpretation. Byte +12 in {0x00,
    0x01} - narrower than the LM960/EG18-NA/EM7511 bucket ({0x00, 0x01,
    0x04}) and the EG25-G/EP06A/SIM7600NA bucket ({0x00, 0x01, 0x02});
    MDM9x30 is its own byte-+12 bucket.

    **EP06A 01.009.01.009 SDX20** (2026-04-15, 145 records, 5-stage with
    different tuples from em7511): (0,1), (6,0), (6,1), (1,2) + heartbeat.

    **MC7411 SDX50M** (SWI9X50C 01.14.03.00 / 01.14.07.00 / 01.14.22.00_unit2,
    2026-05-25 session, #N — densest SDX20-class signature observed,
    617 records across 3 firmware buckets, 6-stage burst):

        1. (0, 0, +25..+34)  - heartbeat / cycle start (thermal-bearing)
        2. (0, 1, +125)      - stage A, **f4 pinned at +125 constant**
                               across all firmwares; does NOT track ambient
        3. (6, 0,    0)      - stage B, universal SDX20 zero sentinel
                               (is_sdx20_stage2_sentinel)
        4. (1, 4, +25..+34)  - stage C, thermal-bearing
        5. (0, 2, +25..+34)  - stage D, thermal-bearing (matches EM7511)
        6. (7, 0, +25..+34)  - stage E, thermal-bearing (matches EM7511)

    MC7411 is a strict **superset of the EM7511 5-stage pattern** plus the
    novel `(0, 1, +125)` stage A.  The `+125` constant is NOT a member of
    the per-firmware cold-start magic family (those are negative:
    -40/-45/-50) — it does not drift with ambient temperature and appears
    unchanged across the three observed firmware revisions.  It also does
    not match the universal `-273` value-unavailable sentinel.  Semantic
    TBD; the test
    `test_mc7411_stage_a_f4_constant_across_thermal_stages` locks in the
    decoupling from ambient so we notice if a future capture invalidates
    the "MC7411-specific magic constant" framing.

    Engine_generation classifier returns ``sdx20`` for all six MC7411
    stages — the 104-byte payload rule (length-based discriminator) is
    decisive for the SDX50M generation, same as for SDX20-V2 and MDM9x30
    siblings.

    **SIM7600NA-H LE20B01SIM7600NA_210506 MDM9x07/SIMCom** (2026-05-04
    LG290P-paired stationary, 124 records, 4-stage; #N <redacted-ref>):

        1. (0, 0, +33..34)  - heartbeat
        2. (0, 1, +52..54)  - stage A  <- bimodal-f4 outlier band
        3. (1, 2, +35..39)  - stage B (byte +12 = 0x02)
        4. (6, 0,   0)      - stage-C sentinel (universal)

    `field_4_i32` is **bimodal**: the `(0, 1)` stage runs ~17 deg C above the
    `(0, 0)` and `(1, 2)` stages on the same record stream in a single
    5-min stationary capture - far outside the +/-1 deg C inter-pair envelope
    SDX55/SDX62 satisfies on their thermal-bearing tuples (see "Within-
    pair delta" evidence below). Either SIM7600NA exposes **two thermal
    zones** (CPU/RF) on different stages, or the temperature
    interpretation does not generalize across all stages on MDM9x07/
    SIMCom. Open: needs a second SIMCom MDM9x07 capture to disambiguate.

    **SDX55-class (FN980, EM9190, RM500Q, RM520N-GL R03, Wistron LV55,
    SIM8202GM2)** uses a different layout entirely. Two structural markers separate the
    SDX55 family from SDX20-class:

    - ``field_1`` (offset +4) takes values in {1, 2} on every SDX55-class
      capture (~82% record-2, ~17% record-1 corpus-wide), with most
      captures showing intra-capture variance. SDX20-class chipsets
      (LM960, EG18-NA, EG25-G, EP06A, MDM9650 EM7511, EG12-GT, sim7600na,
      M2000) emit ``field_1 == 1`` in 100% of records - never 2. So
      ``field_1 == 2`` anywhere in a capture is a positive SDX55-family
      tell. (#N RTCM-revisit pass, <redacted-ref>.)

    - ``field_3`` (offset +12, u32 LE) on SDX55 takes a structured
      4-bit field at positions 16..19 with a constrained co-occurrence
      pattern. Corpus offset +14 (= field_3 byte 2) takes a stable
      6-value distribution across every SDX55-class capture:

         offset+14  field_3 upper-bucket   note
         --------  --------------------   ---------------
         0x00      0x00000                ~50%, low-byte-only
         0x02      0x20000                ~40%, bit 17 set
         0x04      0x40000                ~10%, bit 18 set
         0x08      0x80000                ~3%, bit 19 set
         0x09      0x90000                ~3%, bits 16+19 set
         0x0a      0xa0000                ~3%, bits 17+19 set

      The earlier "131072-262145 (0x20000-0x40001) - high bit set" framing
      undercounted the variant set: values up to 0xa0000 also appear in
      ~9% of SDX55 records. Bits 16/17/18 appear mutually exclusive;
      bit 19 co-occurs with bit 16 (=0x09) or bit 17 (=0x0a) but never
      with bit 18. (#N corpus pass, <redacted-ref>.)

    - The ``hrde`` ASCII tag (field_2 == 0x68726465 LE = 1701081704) is
      **SDX55-family-wide**, not FN980-specific: observed on FN980,
      EM9190 (SWIX55C 03.17.09.00), RM500Q (<redacted-firmware>),
      Wistron LV55 (3.33.101.0), SIM8202GM2 (2026-05-20 wardrive,
      4,832 records / 100% 20B / 151 hrde-tagged records on the
      ``f1=1`` minority class), and several wardriving SDX55 captures.
      Never observed on any SDX20-class capture. (#N RTCM-revisit
      <redacted-ref>; SIM8202GM2 added 2026-05-25 <redacted-ref>, #N.)

    **Corpus-wide invariants** (138 captures, 71,482 records):

    - ``field_0 == 1`` always (offset +0 = 0x01).
    - **Offset +15 is always 0x00**, so ``field_3`` uses at most 24 bits
      across both SDX20 and SDX55 layouts. (#N <redacted-ref>.)

    **SDX62 (RM520N-GL R03 ``RM520NGLAAR03A03M4G_A0.303.A0.303``)** - denser
    per-stage emission than SDX20, with a fix-cycle stage pair instead of
    the SDX20 4-/5-stage burst.  From the 2026-04-22 wardrive capture
    (17,787 records, 1,338.9 sec capture, DIAG tick rate ~58 Mticks/sec;
    #N, #N):

        Tuple (num_engines, field_3_low16, field_4_i32)  Count        Stage role
        --------------------------------------------------------------------------
        (7, 0, 0)                                        7,032 (39.5%) Heartbeat / idle
        (2, 4, +25..+32)                                 2,593 (14.6%) Fix-cycle stage A
        (2, 6, +25..+32)                                 2,593 (14.6%) Fix-cycle stage B
        (7, N, 0) for N=1..12                            293 each      ME-counter sweep
        (0, 2, -40)                                      293           Initializer / sweep head
        (0, 0, +pos), (0, 1, +pos)                       293 each      Early-stage singletons
        (8, 0, -273) [high16=8 OR 10]                    586           Value-unavailable sentinel
        (0, 0, -273), (0, 1, -273) [high16=4]            196 each      Engines-off sentinel
        (9, 0, -273) [high16=0]                          98            Retry-stage rare outlier

    Fix-cycle stages A `(2, 4, +)` and B `(2, 6, +)` are always emitted
    ~10 us apart (median 551 ticks) at ~1.8 Hz pair cadence; both carry
    positive `field_4_i32` measurements in the +24..+32 magnitude range.
    The `(7, 0, 0)` heartbeat fires at ~5.3 Hz (every ~190 ms) - much
    denser than LM960's ~0.4 Hz heartbeat. Total emission rate ~13 Hz
    vs SDX55 FN980m's ~6 Hz and LM960's ~0.5 Hz.

    **`field_4_i32` on `(num_engines=2, field_3_low16 in {4, 6})` records
    is modem temperature in deg C** (#N followup, 2026-04-25 - promoted
    from T1 generic to T2 Engineering interpretation).  Cross-family
    note: the same `(num_engines=2, field_3_low16 in {4, 6})` tuple
    coordinates appear on **both** SDX55 (with `engine_state=2`) and
    SDX62 (with `engine_state=1`) - different engine_state value but
    identical (f2, f3_low) signature.  SDX55 EM9190 records at this
    coordinate also satisfy the within-pair temperature equality and
    bounded inter-pair delta (range 22-27 deg C, mostly stable around the
    capture-environment ambient).  Evidence on SDX62/R03:

    1. Within-pair (10 us apart): `f4_b - f4_a == 0` for **82.8%** of
       2,593 pairs; the rest differ by +/-1 - both records measure the
       same instantaneous quantity.
    2. Inter-pair delta bounded: `|f4_a(i) - f4_a(i-1)| <= 1` for
       **100%** of consecutive pairs - textbook smooth physical
       quantity.  A bitmask, state-flag, or counter would not be
       bounded +/-1 between consecutive emissions.
    3. Capture-quartile mean trajectory: 25.6 -> 26.0 -> 27.7 -> 31.2 -
       a 5-6 deg C warming curve over 22 minutes of driving operation,
       exactly the heating profile of a modem warming up under
       sustained vehicle-interior load.
    4. Range 24..32 deg C consistent with a vehicle-interior thermal
       envelope (cool-start parked -> highway driving load).

    The `-273` sentinel that triggers `is_sdx55_invalid_sentinel` is
    finally coherent under this interpretation: it's "value
    unavailable" expressed as absolute zero in deg C (-273 deg C = 0 K).
    The `-40` initializer (293 records on SDX62/R03 with signature
    `(es=1, f2=0, f3_low=2)`) and the EM9190 `-45` and EM7511 `-50`
    initializers are likely cold-start sentinels emitted before the
    thermal sensor stabilizes - see the **Initializer sentinels**
    subsection below for the consolidated cross-chipset catalog.

    **The temperature interpretation holds across three chipset
    generations** (#N followup, 2026-04-25), though the
    "temperature-bearing tuple" fingerprint differs by family:

    - **SDX20 LM960** (`32.01.150`): stage-3 `(num_engines=1,
      field_3_low16=4, f4_i32=+24..29 deg C)` - confirmed on the
      2026-03-20 wardrive (31 records all at 29 deg C, 100% delta=0
      hold rate; thermally-stable indoor capture).
    - **SDX55 EM9190**: `(num_engines=2, field_3_low16 in {4, 6})`
      with `engine_state=2` - 22+22 records at 26-27 deg C in the
      2026-04-22 wardrive.
    - **SDX62 RM520N R03**: `(num_engines=2, field_3_low16 in {4, 6})`
      with `engine_state=1` - 2,593+2,593 records at 24-32 deg C in
      the same 2026-04-22 wardrive (5-6 deg C warming over 22 min).

    The `(num_engines, field_3_low16)` coordinates differ between SDX20
    (`f2=1, f3_low=4`) and SDX55/SDX62 (`f2=2, f3_low in {4, 6}`), so the
    fix-cycle stage layout evolved between MDM9650 -> SDX55. But the
    underlying `field_4_i32 = thermal-zone deg C` semantic on the active
    fix-cycle stage is preserved across all three generations.

    The `(7, N, 0)` ladder is actually a **single atomic 36-record burst**
    (NOT a periodic counter) emitted every ~4.6 seconds.  All 293 sweeps
    in the corpus are byte-identical:

        low16 sequence: [0, 1, 2, 3, ..., 12, 0, 0, 0, 0, 0, ...]
                         |<--13 records,-->||<-- 23 records,  -->|
                         |  low16 = 0..12  ||   all low16 = 0    |

    The full 36-record burst emits within ~200 us (intra-record spacing
    ~5 us, ~310 ticks).  The first 13 records sweep low16 monotonically
    0..12, then the last 23 records hold at low16=0 - consistent with a
    36-channel ME state-dump where channels 0..12 are "active" (carrying
    a small index value) and channels 13..35 are "padded" (low16=0).
    This is the strongest evidence that `field_3_low16` is a sub-stage
    or channel index, not a sat count (#N).  A naive
    "one fix per record" interpretation would massively overcount on
    SDX62/R03 since ~20% of records belong to these atomic state-dump
    bursts.

    **High-16 flag semantics on SDX62/R03** (#N follow-up, 2026-04-25):
    `field_3_high16 != 0` is **100% correlated** with the SDX55-family
    `field_4_i32 = -273` "value-unavailable" sentinel (978/978 records).
    The bits classify the cause:

    - `bit 2 (high16=4)`: engines-off cause; only fires with
      `num_engines=0`
    - `bit 3 (high16=8)`: engines-on / ME-unavailable; only with
      `num_engines=8`
    - `bit 1 (high16=2)`: secondary-record marker; only co-occurs with
      bit 3 (never alone, never with bit 2)

    Bit 0 and `high16 in {2, 6, 12, 14, 16+}` are NEVER observed in the
    17,787-record SDX62/R03 corpus. The high16-tagged records emit in
    same-cause **pairs** ~6 us apart (median 342 ticks): a primary record
    then a secondary with bit 1 set. Only ~5.5% of all records carry a
    non-zero high16 flag - the unavailability path is rare on SDX62/R03.

    **The `f4=-273` invariant is SDX62-SPECIFIC, but bits 2/3 are
    cross-family.** Cross-validation against the parallel SDX55 captures
    from the same 2026-04-22 wardrive (EM9190 SWIX55C 1,320 records,
    FN980 32 records; #N 2026-04-25 followup) revealed the bits
    decompose by chipset family as follows:

    *Universal across SDX55 + SDX62 (the "post-SDX20 era"):*

    - `bit 2 (high16=4)` correlates with `num_engines = 0` on **both**
      chipsets (SDX55 EM9190: 176/176 high16=4 records have num_engines=0;
      SDX62 RM520N: 392/392 high16=4 records have num_engines=0)
    - `bit 3 (high16=8)` correlates with `num_engines = 8` on **both**
      chipsets (SDX55: 132/132 high16 in {8,9,10} have num_engines=8;
      SDX62: 586/586 high16 in {8,10} have num_engines=8)

    These two bits appear to encode the engine-fanout state regardless
    of firmware generation - bit 2 = "no engines reporting" and bit 3 =
    "max engines (8) reporting".

    *SDX55-specific extensions:*

    - `bit 1 (high16=2, alone)`: 46.7% of EM9190 records - fires when
      `engine_state=2 AND num_engines=0`, NOT a "secondary marker" as
      on SDX62.  Likely an "engine_state=2 / waiting-for-engines" phase
      indicator.  NEVER observed on SDX62.
    - `bit 0 (rare, only in high16=9)`: bits 0+3 combined, 44 EM9190
      records, all with num_engines=8 and f4=-273.  Bit 0 is NEVER
      observed on SDX62, so any odd high16 value cleanly discriminates
      SDX55 from SDX62.
    - `high16 != 0` overall rate: ~70% on SDX55 vs 5.5% on SDX62 -
      because SDX55's majority `engine_state=2` regime exercises bit 1
      heavily, while SDX62's `engine_state=1` regime barely touches
      high16 except for the rare value-unavailable path.

    *SDX62-specific specialization:*

    - The `high16 != 0 => field_4_i32 = -273` invariant: 100% on SDX62
      (978/978 records) but only 33-52% on SDX55.  SDX55 emits e.g.
      `(high16=4, f4=+23)` records freely - those would be invariant
      violations under SDX62 rules.
    - `bit 1` as a "secondary-record marker" (only co-occurring with
      bit 3, never alone): SDX62-only.  On SDX55 bit 1 fires alone.

    The conclusion: bits 2 and 3 are firmware-stable engine-count
    indicators; bit 1's semantic and the f4 invariant are chipset
    specializations.  Future SDX65/SDX75 captures may reveal further
    bit assignments or specializations.

    The 5-record sequence interpretation (one record per ME stage) is the
    best current hypothesis but the exact semantic of each stage remains
    unverified. See the ``Field naming warning`` section below.

    ## Bytes 20..43 (legacy "optional position block") are never populated (#N)

    The dataclass exposes ``lat``, ``lon``, ``alt`` fields and a
    ``has_position`` property carried over from an earlier RE pass that
    speculated bytes 20..43 might hold a 3 * float64 ECEF position
    block. **No observed firmware writes that region.** Corpus-wide
    sweep (#N <redacted-ref>, 2026-05-04): 0 of 12,047 104B records
    across 35 chipset+firmware buckets / 5 vendors had a non-zero byte
    anywhere in [+20..+103] (a strict superset of the lat/lon/alt
    block). SDX55/SDX62 emit only the 20B short form, so [+20..+103]
    doesn't even exist on those chipsets.

    Populated position output across every Qualcomm GNSS chipset in
    the corpus lives in **0x1476 PositionReport**, not here. The
    parser does NOT unpack [+20..+43] — ``lat``/``lon``/``alt`` are
    set to 0.0 unconditionally; the fields are retained only for
    back-compat with downstream consumers that read them. Treat
    ``has_position`` as always False on the current corpus.

    Per the project's strict-closure policy (structure ≠ closure):
    knowing the byte LOCATIONS of a hypothetical position block but
    never observing it populated does NOT count as "parsing those
    fields". The 0x14D8 parser legitimately decodes the 5×u32 header
    + payload_size; the lat/lon/alt fields are unbound carryover.

    ## Initializer sentinels - per-firmware cold-start markers in `field_4_i32` (#N)

    `field_4_i32` carries the modem thermal-zone temperature in deg C on
    fix-cycle stages (see "field_4_i32 = thermal-zone deg C" above), but
    several distinct **sentinel** values appear on non-fix-cycle records.
    They fall into three structurally distinct families:

        Family                      Value(s)         Predicate
        --------------------------  ---------------  ----------------------------
        Universal "value-unavail"   -273 (= 0 K)     is_sdx55_invalid_sentinel
        Per-firmware cold-start     -40 / -45 / -50  (none - magic-number lookup)
        SDX20 zero-stage-2          0 on (6, 0, _)   is_sdx20_stage2_sentinel

    The first and third families are **structural** - they have predicate
    properties that test specific tuple signatures and apply across every
    capture from their chipset family.  The middle family is **firmware-
    specific magic numbers**: each chipset/firmware emits its own
    distinct negative integer in `field_4_i32` for a brief warm-up window
    before the thermal sensor stabilizes, with the magic value being a
    firmware constant rather than a structurally-derivable predicate.

    **Per-firmware cold-start initializer catalog** (consolidated from
    session `e24b` cross-chipset analysis, formalized in #N / session
    `697c` 2026-04-30):

        Chipset / firmware                          Sentinel    Tuple signature  Count
        ------------------------------------------  ---------   ----------------------------------------  -----
        SDX20 LM960A18 32.01.150                    (none)*     uses (6, 0, 0) zero-sentinel for stage 2  -
        SDX20 EM7511 01.14.22.00                    -50         (es=1, f2=0, f3_low=1, f3_hi=0)           per em7511 stage table
        SDX55 EM9190 SWIX55C 03.17.09.00            -45         (es=2, f2=1, f3_low in {0, 1}, f3_hi=0)   88 (2026-04-22 wardrive)
        SDX55 FN980m                                -40         mixed signatures, small sample            3
        SDX62 RM520N-GL R03 (A0.303.A0.303)         -40         (es=1, f2=0, f3_low=2, f3_hi=0)           293 (2026-04-22 wardrive)

    *LM960A18 has no negative initializer - it uses the SDX20 zero-stage-2
    sentinel `(num_engines=6, field_3_low16=0, field_4_i32=0)` instead, a
    structurally distinct mechanism (caught by `is_sdx20_stage2_sentinel`).
    EG18-NA SDX20 V2 and EP06A SDX20 likewise lack a negative initializer
    in their respective stage tables - the negative-magic family is an
    SDX20-EM7511 + SDX55 + SDX62 subset, not a universal SDX20 trait.

    All five magic values (-40, -45, -50) sit comfortably below any
    plausible operating temperature, supporting the "pre-thermal-
    stabilization sentinel" interpretation.  Each value is firmware-
    stable: every capture from a given chipset/firmware emits the same
    initializer integer, which is what makes them magic-number lookup
    constants rather than chipset-derivable.

    **Implications for downstream consumers** (e.g. temperature stat
    aggregators): when computing temperature statistics on a capture, all
    three sentinel families must be filtered out - leaving them in
    skews the mean toward absolute zero (-273) or toward each chipset's
    cold-start value (-40 / -45 / -50).  The `is_sdx55_invalid_sentinel`
    and `is_sdx20_stage2_sentinel` predicates cover families 1 and 3; the
    per-firmware magic family currently has no predicate (a future
    `is_initializer_sentinel(chipset, firmware)` lookup could be added,
    but the magic value differs by chipset so it cannot be a structural
    predicate).  The cleanest filter today is "exclude
    `is_sdx55_invalid_sentinel`, `is_sdx20_stage2_sentinel`, and the
    per-firmware initializer value if you know the chipset/firmware."

    ## Field naming warning (#N)

    The 5 u32 fields at offsets 0..19 have inherited names from an earlier
    RE pass that was **never confirmed against source code or an external reference**.
    Field values observed empirically:

    - ``field_0_u32`` (offset 0): always 1 on every observed record.
      Previously named ``fix_type`` but meaning unverified.
    - ``field_1_u32`` (offset 4): 1 or 2 on observed records. Previously
      ``engine_state``.
    - ``field_2_u32`` (offset 8): small integers 0..9 plus occasional
      outliers. Previously ``num_engines``.
    - ``field_3_u32`` (offset 12): cross-chipset burst-family + sub-stage
      state; previously named ``sv_used`` (#N). On SDX20 (LM960,
      EG18-NA, EM7511, EP06A) values are small integers 0..7. On SDX55
      (FN980m, EM9190) and SDX62 (RM520N-GL) the high 16 bits encode a
      burst-family indicator (see :attr:`field_3_high16`) and the low 16
      bits an sub-stage index. Cross-correlation against concurrent
      0x1476 PositionReport (#N, 2026-04-21+) confirmed values do NOT
      track satellite-used counts on any observed chipset. The
      ``sv_used`` attribute is preserved as a read-only property for
      backwards compatibility but DO NOT pass ``sv_used=`` to the
      constructor in new code - use ``field_3_u32=``.
    - ``field_4_i32`` (offset 16): **signed int32** carrying **modem
      thermal-zone temperature in deg C** on the fix-cycle stage records
      (#N 2026-04-25 followup, T2-Engineering). Confirmed on SDX62
      RM520N R03 via three independent invariants on 2,593 (2,4,+) ->
      (2,6,+) consecutive pairs: within-pair equality 82.8%, inter-pair
      |delta| <= 1 in 100% of cases, monotonic 5-6 deg C warming over a
      22-min vehicle wardrive. Sentinels in the same field: -273 deg C
      (= 0 K) is the "value-unavailable" placeholder
      (:attr:`is_sdx55_invalid_sentinel`); -40/-45/-50 are per-firmware
      cold-start markers emitted before the thermal sensor stabilizes
      (RM520N R03: -40, EM9190 SWIX55C: -45, EM7511 01.14.22.00: -50).
      See the **Initializer sentinels** subsection above (#N) for
      the consolidated cross-chipset catalog with tuple signatures and
      the structural-vs-magic-number distinction.
      Other tuples on the same chipset (heartbeat, sweep, initializer)
      may carry different signed measurements rather than temperature
      - semantic on those tuples remains TBD.  Previously named
      ``fix_flags`` (which would imply a bitmask, but the values are
      signed integers and behave as a smoothly-varying measurement).

    The legacy field names (``fix_type``, ``engine_state``, ``num_engines``,
    ``sv_used``, ``fix_flags``) remain as dataclass attributes for
    backward compatibility but should be treated as unverified. The
    ``to_dict()`` output surfaces both the legacy names and the honest
    ``field_N_*`` names to let consumers choose.
    """
    log_time: int
    # Legacy names (unverified; see docstring). The historical ``sv_used``
    # name was renamed to ``field_3_u32`` in 2026-04 after SDX55 + SDX62
    # evidence (#N) showed it carries burst-family state, not satellite
    # count. A ``sv_used`` property below preserves the legacy attribute
    # name for read access - DO NOT pass ``sv_used=`` as a constructor
    # kwarg in new code; use ``field_3_u32=``.
    # u32 at offset 0. Surfaced via ``version_byte`` property as the
    # honest layout-version semantic — the field is constant-1 across the
    # full RE corpus but should be read as "structural version byte" so
    # rejection on a future v=0x02 firmware reads as a layout-version bump,
    # not as "the firmware emitted a different fix-type" (#N).
    fix_type: int
    engine_state: int   # u32 at offset 4
    num_engines: int    # u32 at offset 8
    field_3_u32: int    # u32 at offset 12 - burst-family state, NOT sv count
    fix_flags: int      # u32 at offset 16 - actually varies as signed i32
    # Legacy optional position block (24 B ddd at offsets 20..43)
    lat: float          # degrees (0.0 if no fix or payload < 44 bytes)
    lon: float          # degrees (0.0 if no fix or payload < 44 bytes)
    alt: float          # meters  (0.0 if no fix or payload < 44 bytes)
    # Raw record size (bytes). Observed values: 20 (SDX55/SDX62 short form),
    # 44 (legacy MDM9607 with position block), 104 (SDX20 V2 padded long
    # form). Used by :meth:`engine_generation` to distinguish SDX62 from
    # SDX20 in the ambiguous field-only zone (#N). Defaults to 20 when
    # a record is synthesized from legacy callers that don't supply it.
    payload_size: int = 20

    @property
    def has_position(self) -> bool:
        return self.lat != 0.0 or self.lon != 0.0

    @property
    def version_byte(self) -> int:
        """Layout-version byte (u32 at offset 0, constant 1 across the RE corpus).

        Aliased to :attr:`fix_type` for back-compat. Named ``version_byte``
        in :meth:`to_dict` output + :data:`field_invariants` so a future
        unknown-version rejection reads as a layout-version bump (extend
        the enum after RE), not as a semantic "different fix-type" hint.
        See #N + the #N ``sentinel_0f`` (now ``version_byte``)
        precedent on 0x14CE.
        """
        return self.fix_type

    @property
    def field_4_i32(self) -> int:
        """Signed i32 interpretation of the legacy ``fix_flags`` field.

        Observed range on FN980m: -40 to +239. The signed-integer reading
        is more consistent with the observed data than a bitmask
        interpretation. Semantic still unknown (#N).
        """
        return self.fix_flags - (1 << 32) if self.fix_flags >= (1 << 31) else self.fix_flags

    @property
    def engine_generation(self) -> str:
        """Coarse chipset-generation label - best-available per-record call.

        Discriminators in priority order:

        1. ``payload_size == 104`` -> ``sdx20``. SDX20 V2 (EG18-NA,
           EM7511, LM960, EP06A, EG25-G OCPU - anything MDM9x07 /
           MDM9650 era) emits the 104-byte padded form exclusively.
           Confirmed across the full 2026-04-* fixture corpus: every
           SDX20 record is 104 bytes and no SDX55/SDX62 record ever is.
           This is the decisive SDX20 signal.
        2. ``engine_state == 2`` -> ``sdx55`` (SDX55/SDX65 majority
           state; observed as majority on FN980m, EM9190, RM500Q,
           Wistron LV55). Only reachable when ``payload_size != 104``.
        3. ``engine_state == 1`` AND ``num_engines > 0xFFFF`` ->
           ``sdx55``. Catches the FN980m/EM9190 "hrde" ASCII-tagged
           records (num_engines = 0x65647268 = 1701081704). Verified
           against the 2026-04-22 EM9190 capture: all 109 engine_state=1
           records on EM9190 carry the hrde tag.
        4. ``engine_state == 1`` AND (``num_engines in {2, 8, 9}`` OR
           ``(sv_used >> 16) & 0xFFFF != 0``) -> ``sdx62``. SDX62-R03
           fingerprints observed on RM520N-GL (2026-04-22 wardrive,
           2,770 records) and never on SDX20 or SDX55.
        5. ``engine_state == 1`` AND ``payload_size == 20`` -> ``sdx62``.
           Length-based exclusion: SDX20 always emits 104-byte records,
           and SDX55 with engine_state==1 always carries the hrde tag
           (caught by #N). The remaining 20-byte engine_state=1 records
           with small num_engines are SDX62 - this branch covers the
           ~60% of SDX62 records where fingerprints #N don't fire
           (#N, validated on 2,770 RM520N records).
        6. ``engine_state == 1`` with other ``payload_size`` -> ``sdx20``
           (legacy MDM9607-era captures with optional 44-byte position
           block, or future variants).

        Values of ``engine_state`` outside {1, 2} return ``'other'``.
        """
        # Rule 1 - length-based SDX20 detection
        if self.payload_size == 104:
            return 'sdx20'
        # Rule 2 - SDX55 majority state
        if self.engine_state == 2:
            return 'sdx55'
        if self.engine_state == 1:
            # Rule 3 - FN980m/EM9190 hrde ASCII-tagged records
            if self.num_engines > 0xFFFF:
                return 'sdx55'
            # Rule 4 - SDX62-specific field fingerprints
            if self.num_engines in (2, 8, 9):
                return 'sdx62'
            if (self.field_3_u32 >> 16) & 0xFFFF:
                return 'sdx62'
            # Rule 5 - length-based SDX62 exclusion (20-byte form on
            # engine_state==1 without hrde tag is SDX62 by elimination)
            if self.payload_size == 20:
                return 'sdx62'
            # Rule 6 - legacy variants
            return 'sdx20'
        return 'other'

    @staticmethod
    def classify_corpus(records) -> str:
        """Return the authoritative engine-generation for a batch of records.

        Per-record :meth:`engine_generation` is ambiguous between SDX20 and
        SDX62 for records where ``field_1==1 AND field_2 in {0, 7} AND
        field_3 < 0x10000`` - on SDX62/R03 this is ~60% of records, and
        they look identical to real SDX20 records at the struct level.

        This batch classifier resolves the ambiguity: if *any* record in
        the batch carries an SDX62 fingerprint, the whole batch is
        classified as ``'sdx62'`` (#N). Otherwise the majority
        per-record label wins.

        Typical usage: pass in all 0x14D8 records from one capture
        session. A 10+ record sample is usually enough to trip a SDX62
        fingerprint if the source is SDX62.
        """
        from collections import Counter
        labels = Counter()
        for r in records:
            labels[r.engine_generation] += 1
        if labels.get('sdx62', 0) > 0:
            return 'sdx62'
        if not labels:
            return 'other'
        return labels.most_common(1)[0][0]

    @property
    def is_sdx55_invalid_sentinel(self) -> bool:
        """True iff ``field_4_i32 == -273`` - SDX55 "value-not-available" sentinel.

        Corpus observation (2026-04-21p, 6,893 records):

          FN980m               500/1761  (28.4%)
          EM9190 SWIX55C_04    260/611   (42.6%)
          EM9190 SWIX55C_09    286/656   (43.6%)
          RM500Q (mixed SDX55) 165/450   (36.7%)
          Wistron LV55          44/91    (48.4%)
          RM520N-GL a03/a08    ~21-22/~400 (~5-6%, residual mixed-gen state)

        On pure SDX20 chipsets (LM960, EG18-NA, EM7511, etc.) this
        sentinel is **never** observed - zero occurrences across 2,000+
        records.  The value -273 is noteworthy (absolute-zero Celsius
        in Kelvin terms - likely a "value unavailable" placeholder).
        """
        return self.field_4_i32 == -273

    @property
    def is_sdx20_stage2_sentinel(self) -> bool:
        """True iff ``(field_2, field_3, field_4_i32) == (6, 0, 0)``.

        This tuple is the SDX20 burst **stage-2** marker documented in
        the module-level burst-pattern RE.  Corpus observation
        (2026-04-21p) shows a strikingly consistent ~25% stage-2 rate
        across SDX20 chipsets -

          EG25-G 30.201          18/72   (25.0%)
          EG25-G A0.301          19/76   (25.0%)
          EG18-NA A06            81/323  (25.1%)
          EG12-GT                 4/16   (25.0%)
          LM960 32.01.110        26/104  (25.0%)
          SIM7600NA               4/16   (25.0%)
          EP06A 01.009           34/170  (20.0%)
          EM7511 01.14.22        97/641  (15.1%)

        Exactly the fraction expected from a 4-stage emission cycle
        (1 in 4 records is the stage-2 marker).  On SDX55 chipsets the
        triple-sentinel is absent - a cleanly complementary cross-gen
        invariant to ``is_sdx55_invalid_sentinel``.
        """
        return (self.num_engines == 6
                and self.field_3_u32 == 0
                and self.field_4_i32 == 0)

    @property
    def sv_used(self) -> int:
        """**Deprecated** legacy alias for :attr:`field_3_u32` (#N).

        The original RE pass named this offset ``sv_used`` on the
        assumption that it counted satellites used in the fix. That
        interpretation was disproven across SDX55 (FN980m, EM9190),
        SDX62 (RM520N-GL), and SDX20 (LM960, EG18-NA, EM7511) corpora:
        field_3 carries a burst-family / stage-index state value, not
        a satellite count.

        Kept as a read-only property so existing consumers continue
        to work. Do not pass ``sv_used=`` to the dataclass constructor
        in new code - use ``field_3_u32=``.
        """
        return self.field_3_u32

    @property
    def field_3_high16(self) -> int:
        """High 16 bits of field_3_u32 - burst-family indicator.

        Cross-chipset, not SDX55-only (#N, 2026-04-23):

        - **SDX55** (FN980m, EM9190): high16 in {0, 2, 4, 8, 9, 10};
          ``2`` is the modal value (~47% on EM9190), other values are
          burst-family transitions. ``0x0002`` -> "primary" family,
          ``0x0004`` -> "secondary" family.
        - **SDX62** (RM520N-GL): same encoding, different distribution.
          high16 in {0, 4, 8, 10} with ``0`` modal (~95%); the 293-count
          cycles in {8, 10} suggest a fixed periodic toggle.
        - **SDX20** (LM960, EG18-NA, EM7511, EP06A): always 0 - field_3
          stays small (0..7) on this generation, no burst-family bits set.
        """
        return (self.field_3_u32 >> 16) & 0xFFFF

    @property
    def field_3_low16(self) -> int:
        """Low 16 bits of field_3_u32 - sub-stage index within the burst
        family. On SDX55, observed 0..6 for family 0x0002 and 0..1 for
        family 0x0004. On SDX62 the low16 distribution is similarly
        small-integer; on SDX20 the entire field is small so low16 is
        the field's full value."""
        return self.field_3_u32 & 0xFFFF

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x14D8',
            'log_time': self.log_time,
            # #N: ``version`` is the canonical field-invariant key (byte0
            # layout-version, #N). ``version_byte`` retained below as a
            # back-compat alias for consumers mid-migration.
            'version': self.fix_type,
            'version_byte': self.fix_type,
            # Legacy names (kept for back-compat, do not trust semantically)
            'fix_type': self.fix_type,
            'engine_state': self.engine_state,
            'num_engines': self.num_engines,
            'sv_used': self.field_3_u32,  # legacy alias (#N) - burst-family state, not SV count
            'fix_flags': self.fix_flags,
            # Honest field names - see #N for field semantic investigation
            'field_0_u32': self.fix_type,
            'field_1_u32': self.engine_state,
            'field_2_u32': self.num_engines,
            'field_3_u32': self.field_3_u32,
            'field_4_u32': self.fix_flags,
            'field_4_i32': self.field_4_i32,
            # v5 cross-chipset invariants (2026-04-21p #N)
            'engine_generation': self.engine_generation,
            'is_sdx55_invalid_sentinel': self.is_sdx55_invalid_sentinel,
            'is_sdx20_stage2_sentinel': self.is_sdx20_stage2_sentinel,
            'field_3_high16': self.field_3_high16,
            'field_3_low16': self.field_3_low16,
            # Raw record size - used by engine_generation for length-based
            # SDX20 vs SDX62 discrimination (#N).
            'payload_size': self.payload_size,
            'lat': self.lat,
            'lon': self.lon,
            'alt': self.alt,
        }


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

@register(LOG_GNSS_ME_POSITION_FIX,
    name="0x14D8",
    description="Measurement engine status: fix type, engine state, SV count, fix flags",
    version=10,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Binary capture analysis; 2026-04-21p 6,893-record / 20-source "
        "corpus scan - added engine_generation (sdx20/sdx55 classifier "
        "from field_1), cross-chipset sentinel validators "
        "(is_sdx55_invalid_sentinel field_4=-273 forall SDX55 family; "
        "is_sdx20_stage2_sentinel (f2,f3,f4)=(6,0,0) forall ~25% of SDX20 "
        "records), and field_3 high16/low16 split for SDX55 burst-family/"
        "sub-stage decode (#N). v3 2026-04-22: length-aware "
        "engine_generation - payload_size=104 -> SDX20, payload_size=20 -> "
        "SDX55/SDX62 disambiguation via hrde tag + field fingerprints "
        "(#N - fixes 2,770 RM520N SDX62 records previously mis-labeled "
        "as sdx20). v4 2026-05-08 (#N): declare field_invariants from "
        "<redacted-ref> 165,972-record corpus - fix_type==1 (24,317/24,317 "
        "verified on subset; 0 violations on full corpus), payload_size "
        "in {20, 104} (size dispatch); 84-byte tail [+20..+103] is all-"
        "zero on 12,047/12,047 104B records (#N corpus sweep). "
        "2026-05-16 #N tier-2 batch 4 split - promoted from gnss_position.py. "
        "v5 2026-05-26 (#N): surface byte0 as ``version_byte`` (alias of "
        "legacy ``fix_type``) in to_dict() + field_invariants, so rejection "
        "of a future v=0x02 record reads as a layout-version bump (extend "
        "the enum after RE) instead of a semantic 'different fix-type' "
        "diagnostic. Dataclass attr ``fix_type`` retained for test/back-compat. "
        "v6 2026-06-02 (#N): promote the 4/27 RTCM-revisit byte+15==0 "
        "invariant to an enforced range check field_3_u32 in [0, 0x00FFFFFF], "
        "re-validated 473,834/473,834 records (+69% over the 2026-05-14 "
        "279,728 baseline). byte+1==0 is subsumed by version_byte==1; "
        "104B byte+14==0 is size-conditional (20B SDX55/SDX62 carry a "
        "nonzero burst-family byte) so it is not flat-declarable. "
        "v7 2026-06-03 (#N version-compliance): rename the field_invariants "
        "key version_byte -> the canonical 'version' (compliance contract — "
        "every version-aware parser keys its log-version enum on "
        "field_invariants['version']) and add the matching Layer-1 byte-0 gate "
        "`if data[0] != 1: return None` the prior parser lacked (it returned a "
        "populated dataclass unconditionally). byte0 v=0x01 attested across "
        "899,438 corpus records / all chipset buckets. to_dict() now emits "
        "'version' (canonical) alongside 'version_byte' (retained alias). No "
        "field-map or recipe change — key/gate compliance only. "
        "v8 2026-06-11 (#N 5govalidate): promote the T99W640 (SDX72) recipe "
        "to hw_run_performed=True — first SDX72 observation (3711 records, 100% "
        "parse, all v=1/20B; engine_generation -> sdx62). engine_state refuted "
        "as fix-state (const generation marker), fix_flags refuted as validity "
        "flags (field_4_i32 thermal degC, 37..40 @ 100% smooth on the SDX72 "
        "(ne=2,f3_low in {9,10}) fix-cycle tuple), num_engines/field_3_high16 "
        "partial (engine-fanout bits confirmed; fix progression untestable, "
        "engine stayed acquiring). No parser-body change."
    ),
    source_url="",
    issues=(),
    primary_issue=None,
    # Identified fields (corpus-validated):
    #   5 × u32 header (fix_type, engine_state, num_engines,
    #     field_3_u32, fix_flags) — all parsed
    #   payload_size (size dispatch) — parsed
    #   5 × derived classifier fields (engine_generation, 2x sentinel
    #     booleans, field_3_high16/low16) — computed from parsed bytes
    # Total: 11 fields actually decoded from payload bytes + computed.
    #
    # The dataclass also exposes lat/lon/alt for back-compat but the
    # parser hardcodes them to 0.0 — they are NOT parsed from bytes
    # [+20..+43] because that region is invariantly zero across the
    # full 12,047-record corpus sweep (#N). Counting them as
    # "parsed" would be fraudulent per the strict-closure rule
    # (knowing where a hypothetical field WOULD live ≠ extracting
    # observed data from it). See dataclass docstring "Bytes 20..43"
    # section. (#N 2026-05-22 closure-rigor pass.)
    fields_identified=11,
    fields_parsed=11,
    field_invariants={
        # ``version`` is the canonical field-invariant key (#N compliance
        # contract; renamed from the non-canonical ``version_byte`` alias).
        # byte0 is the layout-version byte (#N) — fix_type u32 @ +0,
        # corpus-attested v=0x01 across 899,438 records. The parser body
        # enforces a matching Layer-1 gate (`if data[0] != 1: return None`)
        # so a future v=0x02 firmware layout is rejected, reading as
        # "extend the enum after RE", not "different fix-type observed".
        "version": {"enum": [1]},
        "payload_size": {"enum": [20, 104]},
        # ``field_3_u32`` upper bound — byte+15 (bits 24-31) is 0x00 on
        # 473,834/473,834 records (2026-06-02 #N re-walk, +69% over the
        # session-14bf 2026-05-14 baseline of 279,728). So field_3_u32
        # never uses its top byte: max observed value is 0x00FFFFFF.
        # This promotes the corpus-validated "byte+15 == 0x00" invariant
        # from the 4/27 RTCM-revisit comment into an enforced range check.
        # field_3_u32 IS emitted in to_dict() (so the check is reachable —
        # cf. the silent-skip hole at registry.py check_invariants L584).
        #
        # NOT declared here (and why):
        #  - byte+1 == 0x00 (100%): subsumed by ``version_byte`` == 1,
        #    which already constrains the whole bytes[0:4] u32 to
        #    01 00 00 00, hence byte+1 == 0.
        #  - 104B records byte+14 == 0x00: size-CONDITIONAL, not flat-
        #    expressible. 20B (SDX55/SDX62) records legitimately carry a
        #    nonzero byte+14 as the burst-family fingerprint (corpus dist
        #    {0x00, 0x02, 0x04, 0x08, 0x09, 0x0a, 0x05}); a flat const/enum
        #    would wrongly reject valid 20B records. Enforced instead by
        #    the parser's size dispatch + engine_generation classifier.
        "field_3_u32": {"range": [0, 0x00FFFFFF]},
    },
    wigle_direct=True,
    wigle_roles=("position", "timing-anchor:on-fix"),
)
def parse_0x14d8(log_time: int, data: bytes) -> Diag0x14D8 | None:
    """Parse a LOG_GNSS_ME_POSITION_FIX (0x14D8).

    20-byte header: fix_type, engine_state, num_engines, field_3_u32, fix_flags.
    field_3_u32 was previously named ``sv_used`` (#N) - preserved as a
    read-only property alias.
    Bytes 20-43 (vendor-spec'd): lat (f64), lon (f64), alt (f64) - never
    populated in any observed capture. Corpus-wide sweep (#N, <redacted-ref>): 0/12,047 104B records across 35 chipset+firmware buckets / 5
    vendors had a non-zero byte anywhere in the [+20..+103] tail (a strict
    superset of the lat/lon/alt block). SDX55/SDX62 only emit 20B.
    Populated position output across every chipset observed lives in 0x1476
    PositionReport, not here. The lat/lon/alt fields on this dataclass are
    retained at 0.0 for backward compat with consumers that read them.
    """
    if len(data) < 20:
        raise ValueError(f"Diag0x14D8 too short: {len(data)}")
    # #N / #N Layer-1 version gate. byte0 is the layout-version byte
    # (fix_type u32 @ +0; LE low byte), corpus-attested v=0x01 across
    # 899,438 records / every chipset bucket (sidecar byte0 histogram).
    # Reject any other byte0 BEFORE structural decode so a future v=0x02
    # firmware layout surfaces as None rather than being silently
    # mis-parsed as v=1 — the silent-mis-decode hazard behind #N/#N
    # and the project's "size invariance ≠ format invariance" core-memory.
    # The full-u32 fix_type==1 constraint is still enforced at Layer-2 via
    # check_invariants (to_dict emits ``version``); this is the fast
    # byte-0 prefilter the static/dynamic gate ratchets require.
    if data[0] != 1:
        return None
    vals = unpack_from('<IIIII', data)
    return Diag0x14D8(
        log_time=log_time,
        fix_type=vals[0],
        engine_state=vals[1],
        num_engines=vals[2],
        field_3_u32=vals[3],
        fix_flags=vals[4],
        lat=0.0,
        lon=0.0,
        alt=0.0,
        payload_size=len(data),
    )
