"""0x1899 — split from gnss_nav_db.py per #N tier-3.

See module body for the per-code RE history and field map.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_EVENT_PM_BATT_TEMP_OUT_OF_RANGE
        source: qxdm_3_12_714_2017_diag_log_codes (authority: community)
    aliases:
        LOG_GNSS_GEOFENCE_MOTION_DETECTION_WIFI_STATE
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


# ---------------------------------------------------------------------------
# 0x1899 — GNSS status tick (108B fixed, 106/108 bytes constant) (#N)
# ---------------------------------------------------------------------------
# Cross-chipset RE corpus (2026-04-20/21): 3380 records across 6 chipset
# generations — LM960 SDX20, EG18-NA SDX20 V2, EP06A MDM9x07, FN980m
# SDX55, EM7511 MDM9650, plus GNSS-diag 5-min captures across Verizon /
# TMO / ATT / generic and cold-reset post sessions.  Across this corpus,
# only bytes [1] and [2] actually vary:
#
#   - `byte[1]` — free-running u8 counter (all 256 values observed).
#     Empirical delta analysis: **+1 per record, 635/635 consecutive
#     deltas on the two biggest captures** — this is a strict
#     `+1 mod 256` frame counter, one tick per 0x1899 record.
#   - `byte[2]` — 5-state status-machine field.  Distribution across the
#     3380-record corpus: {0: 2601 (77%), 1: 657 (19%), 2: 109 (3%),
#     3: 9 (0.3%), 4: 4 (0.1%)}.
#
# Status-machine interpretation (2026-04-21 RE):
#
#     value  observed contexts
#     -----  -----------------------------------------------------------
#     0      pre-fix / idle — dominant state before first fix
#     1      tracking — steady-state after fix acquisition.  Every capture
#            transitions 0→1 at most once and stays in 1 until end.
#     2      post-cold-reset recovery — only seen in
#            `gnss_cold_reset_post_2026-04-12.dlf.gz` following a run of
#            value 1; transition 1→2 after the reset.
#     3, 4   LM960-only (SDX20) extension states — observed only on
#            LM960 32.01.110 firmware.  Probable vendor-specific extra
#            states (power-save / AGPS-injection); semantics TBD.
#
# The empirical invariant "within any capture the status sequence is
# monotonic non-decreasing in {0,1,2}" holds on all 47 captures that
# contain 0x1899 records — useful as a corruption-detection heuristic.
#
# All 106 other bytes are bit-exact constants across 6 chipsets,
# including the values previously named status_flag_10, rate_ms, and
# status_flag_85. Those names remain for back-compat but are really
# cross-chipset CONSTANTS, not runtime-variable flags:
#
#   - `status_flag_10` = 0x01 at [10]  → cross-chipset CONSTANT
#   - `rate_ms`        = 1000 (0x03E8) at [58:60] → CONSTANT u16 LE
#   - `status_flag_85` = 0x03 at [85]  → cross-chipset CONSTANT
#
# Field map (v4):
#
#     [0]       u8     version            = 0x02 (CONSTANT across chipsets)
#     [1]       u8     counter            u8 frame counter, +1 mod 256
#     [2]       u8     status_byte_2      state enum (see above)
#     [3:10]    7B     reserved           all zero (CONSTANT)
#     [10]      u8     status_flag_10     = 0x01 (CONSTANT)
#     [11:58]  47B     reserved           all zero (CONSTANT)
#     [58:60]  u16LE   rate_ms            = 1000 (CONSTANT)
#     [60:85]  25B     reserved           all zero (CONSTANT)
#     [85]      u8     status_flag_85     = 0x03 (CONSTANT)
#     [86:108] 22B     reserved           all zero (CONSTANT)

# Status-byte-2 enum mapping.  See docstring above for evidence.
GNSS_STATUS_1899_STATES: dict[int, str] = {
    0: 'idle_pre_fix',
    1: 'tracking',
    2: 'post_cold_reset_recovery',
    3: 'lm960_ext_state_3',
    4: 'lm960_ext_state_4',
}


# Reserved-zero byte positions (101 bytes).  Bytes 3..9 (7), 11..57 (47),
# 60..84 (25), 86..107 (22) = 101 bytes total.  These must be 0x00 on
# every observed 0x1899 record (verified across 4154 records from 6+
# chipsets 2026-04-21).
_RESERVED_ZERO_OFFSETS: tuple[int, ...] = tuple(
    list(range(3, 10)) + list(range(11, 58)) + list(range(60, 85)) + list(range(86, 108))
)


@dataclass
class Diag0x1899:
    """GNSS status tick report (0x1899) — 108B, every byte accounted for (#N)."""
    log_time: int
    version: int
    counter: int                     # u8 frame counter, +1 mod 256 per record
    status_byte_2: int               # raw state enum value
    status_byte_2_name: str          # mapped name from GNSS_STATUS_1899_STATES or 'unknown_<n>'
    status_flag_10: int
    rate_ms: int
    status_flag_85: int
    all_invariants_ok: bool          # True iff 4 named constants match AND all
                                     # 101 reserved-byte positions are zero;
                                     # verified across 4154 records / 6 chipsets
                                     # in the 2026-04-21 corpus
    payload_size: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x1899',
            'log_time': self.log_time,
            'version': self.version,
            'counter': self.counter,
            'status_byte_2': self.status_byte_2,
            'status_byte_2_name': self.status_byte_2_name,
            'status_flag_10': self.status_flag_10,
            'rate_ms': self.rate_ms,
            'status_flag_85': self.status_flag_85,
            'all_invariants_ok': self.all_invariants_ok,
            'payload_size': self.payload_size,
        }


# --- Ground-truth recipe (#N) -------------------------------------------
# Authored offline (<redacted-ref>, hypothesis-only). 108B GNSS status tick:
# 106/108 bytes are constant, so only two fields carry information and both
# ground by CORRELATION — byte[1] counter (strict +1/record cadence) and
# byte[2] 5-state fix-state machine (co-varies with engine fix progression).
# NAME CAVEAT: the names-block is ambiguous — canonical
# LOG_EVENT_PM_BATT_TEMP_OUT_OF_RANGE (community) vs alias
# LOG_GNSS_GEOFENCE_MOTION_DETECTION_WIFI_STATE (community), neither
# vendor-official. The empirical RE (split from gnss_nav_db; byte[2] states map
# 1:1 to GNSS fix acquisition) is OBSERVATION-grounded, which outranks community
# per #N — hence this recipe grounds it as a GNSS status tick. SIM8202G-M2
# (SIMCom SDX55, v=0x02) is the recommended target.

@register(
    0x1899,
    name="0x1899",
    description="GNSS status/heartbeat tick — 108B, every byte accounted for (#N)",
    version=7,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "RE across LM960 + EG18-NA + EP06A + FN980m + EM7511 + MC7455 + "
        "cold-reset (2026-04-20/21, #N) — 4154 records validated; 106/108 "
        "bytes bit-exact constant; byte[1]=+1/rec u8 counter, byte[2]=5-state "
        "machine {idle,tracking,post_reset_recovery,ext3,ext4}. "
        "v5 (2026-04-21): all_invariants_ok validator — every byte now "
        "explicitly accounted for. "
        "v6 (2026-05-11, #N audit follow-up — Wave 3 G2): PROMOTED soft "
        "`all_invariants_ok` boolean storage to a hard `return None` rejection "
        "at top of parser body BEFORE the existing `status_byte_2 = data[2]` "
        "read. Audit flagged 'status_byte_2 = data[2] first; soft "
        "all_invariants_ok storage instead of reject' as the silent-mis-parse "
        "hazard. Same anti-pattern as #N (0x137A) fixed in <redacted-ref>. "
        "Corpus walk (24,873 records / 133 captures / 7+ QCA gens): all 4 "
        "named constants (version=2, status_flag_10=1, rate_ms=1000, "
        "status_flag_85=3) plus 101 reserved-zero positions hold corpus-wide. "
        "Promoted all 4 named constants to layer-2 field_invariants. "
        "all_invariants_ok field is retained for back-compat and is now "
        "always True on every record the parser accepts."
    ),
    source_url="",
    issues=(),
    # Every byte accounted for: 2 varying bytes (counter, status_byte_2) + 4
    # named constants (version=2, status_flag_10=1, rate_ms=1000,
    # status_flag_85=3) + 101 reserved-zero bytes verified by
    # all_invariants_ok.  All 9 emitted fields are parsed on every record.
    fields_identified=9,
    fields_parsed=9,
    field_invariants={
        # v6 (#N audit follow-up): the 4 named constants are now both
        # hard-rejected at layer-1 AND declared at layer-2. payload_size
        # is the 108B fixed-size dispatch.
        "version": {"enum": [2]},
        "status_flag_10": {"enum": [1]},
        "rate_ms": {"enum": [1000]},
        "status_flag_85": {"enum": [3]},
        "payload_size": {"enum": [108]},
    },
)
def parse_0x1899(log_time: int, data: bytes) -> Diag0x1899 | None:
    if len(data) < 108:
        return None
    if data[0] != 2:
        return None
    # v6 (#N audit follow-up): PROMOTED soft `all_invariants_ok` boolean
    # storage to a hard `return None` rejection BEFORE any other byte read.
    # Audit flagged 'status_byte_2 = data[2] first; soft all_invariants_ok
    # storage instead of reject' as the silent-mis-parse hazard. Corpus
    # (24,873 records / 133 captures): 4 named constants + 101 reserved-zero
    # bytes hold corpus-wide. Reject any record that fails any of them.
    invariants_ok = (
        data[0] == 2
        and data[10] == 1
        and unpack_from('<H', data, 58)[0] == 1000
        and data[85] == 3
        and all(data[i] == 0 for i in _RESERVED_ZERO_OFFSETS)
    )
    if not invariants_ok:
        return None
    status_byte_2 = data[2]
    return Diag0x1899(
        log_time=log_time,
        version=data[0],
        counter=data[1],
        status_byte_2=status_byte_2,
        status_byte_2_name=GNSS_STATUS_1899_STATES.get(status_byte_2, f'unknown_{status_byte_2}'),
        status_flag_10=data[10],
        rate_ms=unpack_from('<H', data, 58)[0],
        status_flag_85=data[85],
        all_invariants_ok=True,
        payload_size=len(data),
    )


