"""LTE ML1 Serving Cell Measurement Response parser (0xB193).

0xB193 -- LTE ML1 Serving Cell Meas Response
    Per-cell serving cell measurements: EARFCN, PCI, RSRP, RSRQ.
    Emitted periodically when the log mask is subscribed.
    Fixed 528-byte payload (version 1, subpacket version 36) on SDX20.

Reverse-engineered from SDX20 (LM960) DLF captures, validated against
AT+CSQ survey data from 2026-04-05 wardrive sessions.

Payload structure (528 bytes):
    [0]      u8   version (1)
    [1]      u8   num_subpackets (typically 1)
    [2:4]    u16  system frame number
    [4]      u8   subpacket_id (25)
    [5]      u8   subpacket_version (36)
    [6:8]    u16  subpacket_size (524, includes 4-byte subpacket header)

Subpacket data (offset 8, 520 bytes):
    [0:4]    u32  EARFCN (low 18 bits)
    [4:6]    u16  num_cells
    [6:8]    u16  num_rx_antennas

Per-cell record (offset 8 within subpacket data, i.e. payload offset 16):
    [0:4]    u32  bitpacked: PCI = low 9 bits
    ...      intermediate measurement/timing data
    [56:58]  u16  RSRP raw (RSRP_dBm = -raw / 10.0)
    [60:62]  s16  RSRQ (dB, primary)
    [62:64]  s16  RSRQ (dB, secondary Rx)

Cell record size: 512 bytes (520 - 8 header) / num_cells when num_cells=1.
With num_cells > 1, per-cell record size is (subpacket_data_len - 8) / num_cells.

Techplayon QXDM field reference (sources/web/2026-04-07_techplayon_qxdm-log-packets.wacz),
canonical names per docs/qualcomm/techplayon-field-validation.md (#N Track 1)
+ docs/qualcomm/techplayon-cross-refs.md (#N Track 2):
    0xB193 — LTE ML1 Serving Cell Meas Response
        earfcn, pci, serving_cell_index, cell_timing_offset,
        rsrp_inst_rx0_dbm, rsrp_inst_rx1_dbm, rsrp_combined_dbm,
        rsrq_rx0_db, rsrq_rx1_db, rsrq_instantaneous_db,
        rssi_rx0_dbm, rssi_rx1_dbm, rssi_instantaneous_dbm,
        residual_freq_error_hz, ftl_snr_rx0_db, ftl_snr_rx1_db

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_LTE_ML1_SERVING_CELL_MEAS_RESPONSE
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass, field
from struct import unpack_from
from typing import Any

from diaggrok.codes import LOG_LTE_ML1_SERVING_CELL_MEAS_RSP
from diaggrok.registry import register


@dataclass
class LteMl1ServingCellMeasEntry:
    """A single per-cell measurement from 0xB193.

    ``rsrp``/``rsrq`` are validated ground-truth-matched values ONLY for the
    serving cell of a record (``serving_flag == 1``). On v59 (SDX62) multi-cell
    records the non-serving (neighbour) cells carry validated ``pci``/``earfcn``
    but their cell+44 RSRP/RSRQ field is ~3-8 dB low vs AT+QENG ground truth
    (#N, refuted 2026-07-09), so neighbour ``rsrp``/``rsrq`` are gated to
    ``None`` rather than emitting a known-wrong value.
    """
    pci: int
    earfcn: int
    rsrp: float | None  # dBm (None when not validated for this cell/version: v18, v48, or v59 neighbour)
    rsrq: float | None  # dB (primary Rx; None when not decoded/validated for this cell)
    serving_flag: int | None = None  # v59: bit15 of the PCI word; 1 = serving/primary cell of the record
    meas_type: str | None = None     # v59: RX-antenna mask -> "intra_2rx" (0x3) / "inter_4rx" (0xF)

    def to_dict(self) -> dict[str, Any]:
        return {
            'pci': self.pci,
            'earfcn': self.earfcn,
            'rsrp': self.rsrp,
            'rsrq': self.rsrq,
            'serving_flag': self.serving_flag,
            'meas_type': self.meas_type,
        }


@dataclass
class Diag0xB193:
    """LTE ML1 Serving Cell Measurement Response (0xB193)."""
    log_time: int
    version: int
    subpacket_version: int
    earfcn: int
    num_cells: int
    payload_size: int = 0
    entries: list[LteMl1ServingCellMeasEntry] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0xB193',
            'log_time': self.log_time,
            'version': self.version,
            'subpacket_version': self.subpacket_version,
            'earfcn': self.earfcn,
            'num_cells': self.num_cells,
            'payload_size': self.payload_size,
            'entries': [e.to_dict() for e in self.entries],
        }


# Minimum payload: 2-byte outer header + 4-byte subpacket header + 8-byte
# subpacket data header = 14 bytes. Realistic payloads are 528 bytes.
_MIN_PAYLOAD = 14
# Offset of subpacket data within payload.
_SUBPACKET_DATA_OFFSET = 8
# Size of the per-carrier header within subpacket data (EARFCN + counts).
_CARRIER_HEADER_SIZE = 8
# Minimum per-cell record size needed to extract PCI + RSRP + RSRQ.
# PCI at cell offset 0, RSRP at cell offset 56, RSRQ at cell offset 64.
_MIN_CELL_RECORD = 66

# v59 (SDX62 RM520N-GL / RG520N) per-cell BITFIELD layout (#N, RE'd
# 2026-07-02 from the 28,879-record diag_at_correlate_20260607T062541Z capture
# via bit-slice correlation against time-aligned AT QENG/QRSRP/QRSRQ truth,
# cross-checked against the UE's own RRC MeasurementReport and the 2026-06-17
# weak-signal F3 capture). Per-cell record (148 B stride from sp+8):
#   cell+0   u32  valid-RX-antenna bitmask (0x3 = 2-RX intra meas,
#                 0xF = 4-RX inter-freq gap meas)
#   cell+4   u8[4] antenna indices (ffff0100 on 2-RX, 03020100 on 4-RX)
#   cell+8   u32  bits 0..8 PCI, bit 15 = serving-cell flag
#   cell+28  u32  bits 0..11 rsrp_inst_rx0 (raw/16 - 180 dBm; carrier-level,
#                 repeated in every cell of the record on the 2-RX subtype)
#   cell+32  u32  bits 0..11 rsrp_inst_rx1 (raw/16 - 180 dBm; carrier-level)
#   cell+44  u32  bits 0..11 per-cell inst RSRP; bits 12..23 per-cell
#                 combined/filtered RSRP (raw/16 - 180 dBm)  <- entries.rsrp
#   cell+56  u32  bits 20..31 per-cell RSRQ (raw/16 - 30 dB) <- entries.rsrq
# These replace the 2026-06-06 EMPIRICAL byte scales (rsrp byte@cell+59 =
# raw/2-99, rsrq byte@cell+26 = raw-37), which were a strong-signal coincidence
# REFUTED at weak signal by #N (~24 dB error at true RSRP -117): the new
# bitfields decode that same weak-signal capture to -117.6 (F3 truth -117.1)
# and reproduce +QRSRP -117,-119 per-antenna exactly via cell+28/cell+32.
_V59_SUBPACKET = 59
_V59_RSRP_WORD_OFF = 44   # u32 whose bits 12..23 carry combined RSRP
_V59_RSRQ_WORD_OFF = 56   # u32 whose bits 20..31 carry RSRQ
_V59_MIN_CELL_RECORD = 60  # need the full u32 at cell+56

# v48 (SDX55: RM500Q-AE / LV55 / EM9190, #N/#N/#N) — the +4 carrier-header
# drift. The SDX55 v48 carrier header is 12 B (EARFCN u32 @sp+0, num_cells u16
# @sp+4, then 4 more bytes), NOT the 8 B the legacy `>= 48` branch assumed — so
# the per-cell array starts at sp+12, shifting serving PCI from the legacy sp+8
# (decodes the 0xffff0100 carrier tail -> low9 256) to sp+12 (true PCI). Validated
# 2026-06-19 (<redacted-ref>, RM500Q-AE WLSN, SIM-less LTE LIMSRV AT&T): decoded PCI
# {473,37,277} == AT+QENG="servingcell" <pcid> across reselections + co-captured
# verified 0xB116 config_word. Expressed as pci_off=4 over the 8 B base (mirrors
# how v59 lands its PCI via pci_off=8), so cell_offset(8)+4 == the true sp+12.
# RSRP/RSRQ stay None: the RSRP-tracking field is located at in-cell +24 (raw
# INCREASES with power — 473 raw~1160 > 37 ~1106 > 277 ~1038 tracking true
# -107/-110.5/-111 dBm, an energy-like quantity, same converted-energy semantics
# as 0xB192's neighbour rsrp, #N), but its energy->dBm scale is NOT lockable in
# a narrow ~4 dB capture — decoded None (not guessed), pending a wider-RSRP-spread
# co-temporal-$QCRSRP capture.
_V48_SUBPACKET = 48
_V48_PCI_OFF = 4

# v18 (MDM9207: EG25-G / EC25 family, #N) — older small-regime carrier-header
# layout. Unlike v36/v48/v59 (which carry a num_cells count at sp+4 followed by
# per-cell records), v18 packs the serving cell INLINE in the carrier header and
# has NO num_cells field at sp+4 — reading sp+4 as a u16 count yields garbage
# (e.g. 0x1136 = 4406). The serving cell is: EARFCN @ sp+0 (u32, low 18 bits),
# serving PCI @ sp+4 (u32, low 9 bits). Reverse-engineered + validated 2026-06-10
# on EG25-G @ A0.301.A0.301 (SIM-less LTE LIMSRV, <redacted-ref>): EARFCN 2050 +
# PCI 310 == AT+QENG="servingcell" AND the co-captured already-verified 0xB116
# serving-PCI field (310) — cross-DIAG + AT agreement. The per-cell RSRP/RSRQ
# byte layout is NOT yet RE'd for v18, so v18 entries carry pci+earfcn with
# rsrp/rsrq=None. Only the serving cell is observed SIM-less (no neighbours
# camped); larger v18 payloads (multi-cell) are not yet characterised.
#
# RSRP-field search (2026-06-27, #N/#N): scanned the 100B v18 payload at
# every i8/i16/u16/i32 offset against the co-captured AT ground truth on
# 20260622T2135Z-EG25-G (AT QENG servingcell RSRP -100..-104, RSSI -67..-71,
# RSRQ -11..-13 over the poll). RESULT — the v18 RSRP field is NOT locatable
# from this capture: the only fields whose value sits near the AT RSRP are
# CONSTANT across all 245 records (payload off=7 i16 == -1024 == -102.4 dBm at a
# /10 scale; off=21 i8 == -105) and therefore do NOT track the AT's ~4 dB RSRP
# variation, while every field that DOES vary spans the full byte range (noise).
# So a stable-RSRP capture cannot disambiguate the field even WITH AT truth —
# this sharpens #N's "capture-gated" to a specific requirement: a v18 capture
# with a WIDE serving-RSRP sweep (≥15-20 dB, e.g. a drive/attach) so the true
# field separates from the constant look-alikes. rsrp/rsrq stay None.
_V18_SUBPACKET = 18


# Ground-truth recipe (#N). RM520N-GL (SDX62) emits the single corpus-wide
# version v=1; every to_dict() entry field is a decoded physical quantity with a
# known scale, so this grounds by direct numeric equality against the LTE serving
# row of AT+QENG="servingcell" — the cleanest validation kind.

@register(LOG_LTE_ML1_SERVING_CELL_MEAS_RSP, domain="lte-signal",
    name="0xB193",
    description="Serving cell PCI, EARFCN, RSRP, RSRQ from 0xB193 subpacket — 7-size variable-length family, v=1 corpus-wide (#N). v13: carrier-header EARFCN F3-verified 100%% on SDX55 v48 (#N). v17: MC7411 (SDX50M sp35) earfcn F3-hardened vs rflte_mc_rx.c channel:66786. v18: SDX55 v48 +4 carrier-header PCI FIX (pci_off=4, true sp+12) — serving PCI REFUTED→VERIFIED on RM500Q-AE WLSN (#N/#N/#N). v19: EM7565 (MDM9x50 X16) v0x01/sp35 per-modem recipe — serving earfcn+pci VERIFIED on CBRS B48 (#N, <redacted-ref> 1b-sib re-key). v22: SDX62 v59 per-cell RSRP/RSRQ re-RE'd as bit-exact 12-bit fields (raw/16-180 dBm @cell+44 b12..23; raw/16-30 dB @cell+56 b20..31), replacing the #N-refuted byte scales (#N).",
    version=24,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v22 (2026-07-02, #N, host <redacted-host>): v59 SDX62 per-cell RSRP/RSRQ "
        "BITFIELD RE — exhaustive bit-slice correlation of the per-cell u32 words "
        "against time-aligned AT QENG=\"neighbourcell\"/QRSRP/QRSRQ truth on the "
        "28,879-record RM520N-GL diag_at_correlate_20260607T062541Z capture (7 "
        "distinct truth cells spanning -93..-119 dBm). Pinned: per-cell combined "
        "RSRP = 12-bit @cell+44 bits12..23, raw/16-180 dBm (serving r=0.77, mean "
        "err -0.55 dB); per-cell RSRQ = 12-bit @cell+56 bits20..31, raw/16-30 dB "
        "(serving r=0.93, mean err -0.33 dB); per-antenna carrier-level "
        "rsrp_inst_rx0/rx1 = 12-bit @cell+28/cell+32 bits0..11 (match +QRSRP "
        "PRX/DRX exactly, e.g. -117.7/-119.3 vs -117,-119 on the #N capture); "
        "cell+0 = valid-RX-antenna mask (0x3 intra / 0xF inter-freq gap meas). "
        "Cross-checked: UE's own RRC MeasurementReport (qcsuper pcap, 06:30:44Z) "
        "rsrp -95/rsrq -15.75 vs decoded serving -94.81/-16.50; the 2026-06-06 "
        "held-out capture QENG anchors; and the #N weak-signal F3 capture "
        "where the old empirical byte scale read -93 vs true -117.1 — the new "
        "field decodes -117.6 (also fixes the CFW-3212 v10 divergence, which was "
        "the same byte-scale artifact). SCAT 2024+ does NOT decode v59 (prints "
        "'Unknown ... subpacket version 59') so the oracle check used the RRC "
        "MeasurementReport channel instead. DIAG per-cell values are "
        "instantaneous/L1-filtered: weak NEIGHBOUR rows can sit 4-6 dB below "
        "QENG's own neighbour numbers (QENG applies different filtering); "
        "serving-cell values match all references to <=1 dB. "
        "-- v20 (2026-06-21, #N <redacted-ref>, host <redacted-host>): LM960 v0x01 serving "
        "pci/earfcn/rsrp ALL re-confirmed on two owned dual-mask DIAG+F3 captures "
        "(unit e3296e3 @ CBRS B48, 19728 records): entries.pci CONST 451 == F3 "
        "SM_ASdiv serving PCI 451; entries.earfcn CONST 55340 == AT#RFSTS; "
        "entries.rsrp -85.4 == F3 SM_ASdiv ant0 -85.3 dB / LL RSRP rx0 -85 (qdb "
        "2f5667ef 100%). Pure same-cell re-confirmation of the already-verified "
        "fields. -- v18 (2026-06-19, #N/#N/#N <redacted-ref>, host <redacted-host>): SDX55 "
        "v48 +4 CARRIER-HEADER FIX. The SDX55 v48 carrier header is 12 B not 8 B, "
        "so the per-cell array starts at sp+12; v48 now uses pci_off=4 (true sp+12) "
        "and decodes serving PCI {473,37,277} == AT+QENG=\"servingcell\" + 0xB116 "
        "across a 244.7s reselecting RM500Q-AE WLSN capture (192/193) — entries.pci "
        "REFUTED→VERIFIED, entries.earfcn re-confirmed on 3 cells. entries.rsrp/rsrq "
        "now decode None (was -50/-3.5 garbage): RSRP energy located at in-cell +24 "
        "(raw rises with power, tracks per-cell true RSRP) but scale unlockable in a "
        "narrow ~4 dB capture → PARTIAL. F3 qdb 404921d3 resolution 1.0 (NB_MEAS + "
        "quectel_led rsrp=-109 witnesses). "
        "v16 (2026-06-15, #N F3-grounding, host <redacted-host>): LM960A18 v0x01 entries.rsrp PROMOTED partial->VERIFIED — the firmware's OWN F3 (lte_ml1_common_rssi_ind.c:1075 + lte_ml1_sm_conn_wb_stm.c:3587, qdb 2f5667ef) logs serving RSRP=-85 / RSSI=-58 for PCI 451; decoded rsrp -84.1 == F3 RSRP (within 1 dB), 27 dB off RSSI, RESOLVING the 2026-06-07-vs-06-14 RSRP/RSSI conflict (B66 no-SIM refutation was a weak-cell artifact). -- v15 (2026-06-14, #N <redacted-ref>, host <redacted-host>): LM960A18 v0x01 "
        "recipe ADVANCED on a SIM-camped registered UETN B48 capture (EARFCN "
        "55340, e3296e3) — entries.pci promoted partial->VERIFIED (decoded const "
        "451 == external same-cell QMI GetCellLocationInfo PCI 451 from the bench "
        "EM7565 on identical cell 0x08384B4A); entries.rsrp downgraded "
        "refuted->PARTIAL (B48 registered decodes -84.1 == AT RSRP -84 within 1 dB, "
        "CONTRADICTING the 2026-06-07 B66 RSSI-match refutation — cross-cell "
        "conflict, needs resolution); entries.earfcn re-confirmed on a 2nd band "
        "(55340). F3 100% vs qdb 2f5667ef (lte_ml1_dlm_ard*). "
        "v14 (2026-06-14, #N <redacted-ref>, host <redacted-host>): added a Sierra "
        "MC7411 (SDX50M / Snapdragon X20) v0x01 sibling — subpacket_version 35 "
        "(0x23), which decodes serving pci/earfcn CORRECTLY (no SDX55 v48 drift). "
        "LIMSRV B66 EARFCN 66786 / serving PCI 236. entries.pci VERIFIED (236), "
        "entries.earfcn VERIFIED (66786, u32 >65535), entries.rsrp REFUTED "
        "(-65..-77 vs true -100; ≈ AT RSSI -68 — per-cell RSRP scale bug), "
        "entries.rsrq/num_cells PARTIAL. "
        "Cross-chipset corpus walk (2026-05-08, #N): 18,401 records / 125 captures. "
        "Single version (v=1) corpus-wide; seven payload sizes split across two regimes — "
        "small (100/160/164/180 B, 55.4%) when zero/few neighbor cells are reported, "
        "large (496/512/528 B, 44.6%) with serving cell + 1-3 neighbors. "
        "Subpacket v36 = SDX20 (LM960); v48 = SDX55 — RSRP/RSRQ offsets dispatched accordingly "
        "(⛔ the v48 per-cell offsets were corpus-derived WITHOUT LV55 ground truth and are "
        "HW-REFUTED on the LV55, see v9 below). "
        "v59 = SDX62 (RM520N-GL, #N): per-cell record grew (PCI@cell+8; multi-cell payload "
        "sizes 312/460/608). [Historical: the 2026-06-06 empirical byte scales RSRP@cell+59=raw/2-99 / "
        "RSRQ@cell+26=raw-37 were a strong-signal coincidence, refuted by #N and REPLACED by the "
        "bit-exact 12-bit fields in v22 above.] "
        "v18 = MDM9207 (EG25-G/EC25, #N, <redacted-ref> 2026-06-10): the older small-regime "
        "carrier-header layout with NO num_cells at sp+4 — the serving cell is packed inline "
        "(EARFCN @ sp+0 low-18-bits, PCI @ sp+4 low-9-bits). Decoded by the _V18_SUBPACKET branch "
        "(earfcn VERIFIED 2050; pci VERIFIED 2026-06-10 run 2 — varying (earfcn,pci) (2300,242)+(5035,144) "
        "each AT-QENG-neighbourcell-matched, 3 distinct PCIs across two SIM-less runs prove tracking; "
        "rsrp/rsrq=None pending v18 RSRP byte-scale RE). Before this, v18 records were "
        "mis-parsed (sp+4 read as a u16 num_cells = 4406) and yielded zero entries. "
        "Body parser handles num_cells=0 and short small-regime payloads gracefully. "
        "v8 (<redacted-ref> 2026-06-10, anti-monopoly rotation onto the EM7455): the "
        "MDM9230 (Sierra EM7455, M.2 twin of the MC7455) ALSO emits subpacket v18 — "
        "the same small-regime layout as the MDM9207 EG25-G — 183/183 idle records, "
        "earfcn VERIFIED (CONST 2300 == AT!LTEINFO serving EARFCN), pci PARTIAL "
        "(CONST 236 == AT!LTEINFO serving PCI but single-value this run; cross-"
        "corroborated by same-capture 0xB116/0xB192). Second chipset family on v18. "
        "v9 (<redacted-ref> <redacted-ref>, 2026-06-10, LV55-focused round): FIRST hardware "
        "validation of the Wistron LV55 (SDX55) subpacket-v48 per-cell decode — and it "
        "REFUTES the current offsets. Camped Verizon B66 (EARFCN 66536), serving PCI 310 "
        "(independently: JSONRPC pci_4g=310, co-captured 0xB116 config_word=310, 0xB0C0 "
        "pci=310), but entries.pci decoded 256 / rsrp -56 / rsrq -3.5 (true rsrp -113, "
        "rsrq -16 from JSONRPC). Root cause: the SDX55 v48 per-carrier header is 12 B "
        "([8:20]) not the 8 B (_CARRIER_HEADER_SIZE) the >=48 branch assumes — the true "
        "PCI 310 is the u32 at payload offset 20 (0x1136 & 0x1FF), the parser reads "
        "offset 16 (256). entries.pci/rsrp/rsrq REFUTED on SDX55; earfcn 66536 (carrier-"
        "header field, before the shift) PARTIAL (no independent EARFCN readback on the "
        "LV55 reference FW). FIX (follow-up on #N): an SDX55 v48 branch with a 12-byte "
        "carrier header, regression-checked against the other v48 SDX55 emitters before "
        "promotion. "
        "v10 (<redacted-ref> <redacted-ref>, 2026-06-11, cfw3212-scoped): added a Casa "
        "Systems CFW-3212 (SDX62 via Quectel RG520N-NA OpenCPU) subpacket-v59 sibling of "
        "the RM520N-GL v59 cell — SAME SDX62 silicon so the v59 per-cell offsets port "
        "directly. LIMSRV cell-search HW run: entries.pci=236 + entries.earfcn=2300 == "
        "AT+QENG=\"servingcell\" EXACTLY (194/194), cross-anchored by co-captured 0xB116 "
        "config_word=236 → pci/earfcn VERIFIED on a 2nd SDX62 modem + Casa firmware. The "
        "v59 EMPIRICAL byte rsrp/rsrq scales DIVERGE on this FW (rsrp ~-90 vs AT -106, "
        "rsrq ~-20 vs AT -11..-14) → rsrp/rsrq PARTIAL: the coarse single-byte scale is "
        "firmware/cond-dependent, a per-FW re-RE follow-up on #N. "
        "v12 (<redacted-ref> 2026-06-12, RM500Q-AE recommended-target round): SECOND SDX55 "
        "v48 hardware run — Quectel RM500Q-AE (WLSN soft-SIM), LTE-LIMSRV on AT&T B66 "
        "EARFCN 66986 / serving PCI 473. REPRODUCES the LV55 SDX55 carrier-header drift "
        "exactly and adds the direct same-modem AT+QENG anchor LV55 lacked: "
        "entries.earfcn=66986 (81/81) == AT+QENG serving EARFCN + F3 rflte_mc_rx_tune "
        "channel:66986 (qdb GUID 404921d3) → earfcn VERIFIED (upgrades the family earfcn "
        "from LV55's unanchored partial); entries.pci=256 (true 473 via AT+QENG + 0xB116 "
        "config_word=473), rsrp≈-50 (true ≈-109/-110), rsrq=-3.5 const (true ≈-14) all "
        "REFUTED by the same +4 carrier-header offset — second-modem confirmation that "
        "the SDX55 v48 12-byte-header fix is needed before pci/rsrp/rsrq ground on this "
        "silicon."
    ),
    source_url="",
    issues=(),
    primary_issue=None,
    fields_identified=6,
    fields_parsed=6,
    field_invariants={
        "version": {"enum": [1]},
        # 608 = the 4-cell v59 size class (267 records in the 2026-06-07
        # RM520N-GL correlate capture; serving + 3 neighbours at 148 B stride).
        "payload_size": {"enum": [100, 160, 164, 180, 312, 460, 496, 512, 528, 608]},
    },
    wigle_direct=True,
    wigle_roles=("signal", "pci-earfcn-bridge", "rat-context"),
)
def parse_0xb193(
    log_time: int, data: bytes
) -> Diag0xB193 | None:
    """Parse 0xB193 -- LTE ML1 Serving Cell Measurement Response.

    Extracts per-cell PCI, EARFCN, RSRP, and RSRQ from the subpacket
    payload. Supports version 1 with subpacket version 36.

    Returns None if the payload is too short or version is unsupported.
    """
    if len(data) < _MIN_PAYLOAD:
        return None

    version = data[0]
    if version != 1:
        return None
    num_subpackets = data[1]

    if num_subpackets < 1:
        return Diag0xB193(
            log_time=log_time,
            version=version,
            subpacket_version=0,
            earfcn=0,
            num_cells=0,
            payload_size=len(data),
        )

    # Subpacket header: id(u8), version(u8), size(u16)
    subpacket_version = data[5]
    subpacket_size = unpack_from('<H', data, 6)[0]

    # Subpacket data starts at offset 8
    sp = data[_SUBPACKET_DATA_OFFSET:]
    if len(sp) < _CARRIER_HEADER_SIZE:
        return None

    # Carrier header
    earfcn_raw = unpack_from('<I', sp, 0)[0]
    earfcn = earfcn_raw & 0x3FFFF

    if earfcn > 262143:  # max LTE EARFCN
        return None

    # v18 (MDM9207) has no num_cells at sp+4 — that u32 is the serving PCI.
    # Decode the serving cell inline from the carrier header (#N).
    if subpacket_version == _V18_SUBPACKET:
        v18_pci = unpack_from('<I', sp, 4)[0] & 0x1FF
        v18_entries: list[LteMl1ServingCellMeasEntry] = []
        if v18_pci <= 503:
            # RSRP/RSRQ scale not yet RE'd for v18 -> None (honest, not guessed).
            v18_entries.append(LteMl1ServingCellMeasEntry(
                pci=v18_pci, earfcn=earfcn, rsrp=None, rsrq=None,
            ))
        return Diag0xB193(
            log_time=log_time,
            version=version,
            subpacket_version=subpacket_version,
            earfcn=earfcn,
            num_cells=len(v18_entries),
            payload_size=len(data),
            entries=v18_entries,
        )

    num_cells = unpack_from('<H', sp, 4)[0]

    entries: list[LteMl1ServingCellMeasEntry] = []

    if num_cells == 0 or len(sp) <= _CARRIER_HEADER_SIZE:
        return Diag0xB193(
            log_time=log_time,
            version=version,
            subpacket_version=subpacket_version,
            earfcn=earfcn,
            num_cells=num_cells,
            payload_size=len(data),
        )

    # Calculate per-cell record size from remaining subpacket data
    cell_data_len = len(sp) - _CARRIER_HEADER_SIZE
    cell_record_size = cell_data_len // num_cells if num_cells > 0 else 0

    # Per-cell field layout depends on subpacket version. The carrier header /
    # cell stride math above is version-agnostic (cell_record_size already comes
    # out 148 B on v59); only the in-cell field offsets drift.
    #   v36 (SDX20 LM960): PCI@cell+0, RSRP u16@cell+56, RSRQ u16@cell+64
    #   v48 (SDX55 LV55):  PCI@cell+0, RSRP u16@cell+64, RSRQ u16@cell+76/78
    #   v59 (SDX62 RM520N-GL, #N): the per-cell record grew; PCI moved to
    #     cell+8 (bit15 = serving flag) and RSRP/RSRQ are BITPACKED 12-bit
    #     fields in the per-cell u32 words: combined RSRP at cell+44 bits
    #     12..23 (raw/16 - 180 dBm), RSRQ at cell+56 bits 20..31 (raw/16 - 30
    #     dB). Pinned by bit-slice correlation against time-aligned AT
    #     QENG/QRSRP/QRSRQ truth on 28,879 records, confirmed by the UE's own
    #     RRC MeasurementReport and by the #N weak-signal F3 capture
    #     (decodes -117.6 vs F3 truth -117.1 dBm, where the former empirical
    #     byte scale read -93). See the _V59_* constants block for the full
    #     per-cell word map (antenna mask, per-antenna rx0/rx1 RSRP).
    if subpacket_version == _V59_SUBPACKET:
        pci_off = 8
        min_cell_record = _V59_MIN_CELL_RECORD
    elif subpacket_version == _V48_SUBPACKET:
        # SDX55 12 B carrier header: PCI at the +4-shifted slot (== true sp+12).
        # RSRP/RSRQ scale not yet RE'd for this layout -> None (honest, not guessed).
        pci_off = _V48_PCI_OFF
        min_cell_record = _V48_PCI_OFF + 4  # just enough to read the PCI u32
    elif subpacket_version >= 48:
        pci_off, rsrp_off, rsrq_off = 0, 64, 76
        min_cell_record = max(rsrq_off + 2, _MIN_CELL_RECORD)
    else:
        pci_off, rsrp_off, rsrq_off = 0, 56, 64
        min_cell_record = max(rsrq_off + 2, _MIN_CELL_RECORD)

    for i in range(num_cells):
        cell_offset = _CARRIER_HEADER_SIZE + i * cell_record_size
        if cell_offset + min_cell_record > len(sp):
            break

        # PCI: low 9 bits of u32 at the version-dependent cell offset
        pci_raw = unpack_from('<I', sp, cell_offset + pci_off)[0]
        pci = pci_raw & 0x1FF

        if pci > 503:
            continue

        serving_flag = None
        meas_type = None

        if subpacket_version == _V59_SUBPACKET:
            # serving/primary cell of the record = bit15 of the PCI word;
            # meas_type from the cell+0 RX-antenna mask (0x3 = 2-RX intra-freq,
            # 0xF = 4-RX inter-freq gap). (#N)
            serving_flag = (pci_raw >> 15) & 1
            mask = unpack_from('<I', sp, cell_offset)[0]
            meas_type = {0x3: "intra_2rx", 0xF: "inter_4rx"}.get(mask, f"0x{mask:x}")
            # Bit-exact 12-bit fields (see #N + the _V59_* constants block).
            # raw == 0 means the field is unpopulated -> None (keep pci/earfcn).
            rsrp_raw = (unpack_from('<I', sp, cell_offset + _V59_RSRP_WORD_OFF)[0]
                        >> 12) & 0xFFF
            rsrq_raw = unpack_from('<I', sp, cell_offset + _V59_RSRQ_WORD_OFF)[0] >> 20
            rsrp = round(rsrp_raw / 16.0 - 180.0, 2) if rsrp_raw else None
            rsrq = round(rsrq_raw / 16.0 - 30.0, 2) if rsrq_raw else None
            # cell+44/cell+56 are ground-truth-validated ONLY for the serving
            # cell; on non-serving (neighbour) cells they read ~3-8 dB low vs
            # concurrent AT+QENG (#N, refuted on a 2026-07-09 RM520N-GL-AP
            # dual-mask capture). Gate neighbour signal to None rather than emit
            # a known-wrong value; pci/earfcn stay (neighbour identity IS valid).
            if serving_flag != 1:
                rsrp = None
                rsrq = None
        elif subpacket_version == _V48_SUBPACKET:
            # SDX55 v48: RSRP-tracking field located (in-cell +24, energy-like)
            # but its energy->dBm scale is not lockable yet -> None, not guessed.
            rsrp = None
            rsrq = None
        else:
            # RSRP: u16 at version-dependent offset, scaled as -raw/10.0 dBm
            rsrp_raw = unpack_from('<H', sp, cell_offset + rsrp_off)[0]
            rsrp = -rsrp_raw / 10.0
            # RSRQ: u16 at version-dependent offset, scaled as (raw-60)/2.0 dB
            rsrq_raw = unpack_from('<H', sp, cell_offset + rsrq_off)[0]
            rsrq = (rsrq_raw - 60) / 2.0

        # RSRP range filter only applies to versions that decode a dBm value;
        # None-RSRP versions (v18, v48) still emit the verified pci/earfcn.
        if rsrp is not None and not (-140.0 <= rsrp <= -30.0):
            continue

        # 2 decimals is lossless for every decoded scale: /10 (v36), /2
        # (v36 rsrq) and the v59 1/16-dB quanta.
        entries.append(LteMl1ServingCellMeasEntry(
            pci=pci,
            earfcn=earfcn,
            rsrp=round(rsrp, 2) if rsrp is not None else None,
            rsrq=round(rsrq, 2) if rsrq is not None else None,
            serving_flag=serving_flag,
            meas_type=meas_type,
        ))

    return Diag0xB193(
        log_time=log_time,
        version=version,
        subpacket_version=subpacket_version,
        earfcn=earfcn,
        num_cells=num_cells,
        payload_size=len(data),
        entries=entries,
    )
