"""GNSS/RF state flag (0x197F) — 4B fixed, constant state word.

Sibling pair with 0x1980 — both codes emit an identical 4-byte payload
during airplane-mode and SIM power-cycle transitions. All 39 observed
records (30 airplane + 9 SIM per code) carry the same constant u32 value
0xC002F2A0. The two codes appear in the same events with the same
counts, suggesting they are the same state word reported by two
different subsystems simultaneously.

Layout (4 B fixed):
    [0:4]  u32 LE  state_word — observed constant 0xC002F2A0 across all records

## byte-0 RE'd version-less (#N, 2026-06-11)

byte-0 is **not** a DIAG version field — it is the **low byte of the
constant u32 `state_word`** (0xC002F2A0 LE ⇒ byte-0 == 0xA0). The entire
4-byte payload is a single all-constant state word across 39/39 observed
records; there is no version axis to gate. The parser already rejects any
foreign payload via the strict `state_word` enum gate (strictly stronger
than a byte-0 gate would be), so a `field_invariants["version"]={enum:[0xA0]}`
declaration would be semantically false (0xA0 is a constant fragment, not a
version) while adding zero protection. Declared `version_less=True` to
graduate 0x197F off the #N compliance worklist as an evidenced
conclusion, mirroring the 0x117B precedent (#N).

Closure: #N.

Split from lte_misc.py per #N tier-3 batch 11.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: RESERVED
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


@dataclass
class Diag0x197F:
    """0x197F — GNSS/RF state flag, 4B fixed, constant state word."""
    log_time: int
    state_word: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x197F',
            'log_time': self.log_time,
            'state_word': self.state_word,
            'state_word_hex': f'{self.state_word:08x}',
        }


@register(
    0x197F, domain="gnss",
    name="0x197F",
    description="GNSS/RF state flag (0x197F) — 4B fixed, constant u32 during mode transitions (#N)",
    version=1,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room RE from 39 EM7511 MDM9650 records (airplane + SIM cycle) "
        "2026-04-20 — all-constant payload 0xC002F2A0 (#N)"
    ),
    # Payload is a single u32 (state_word). Every observed record has
    # identical value 0xC002F2A0 across 39 EM7511 samples; "constant field"
    # still counts as an identified + parsed semantic field. (#N)
    fields_identified=1,
    fields_parsed=1,
    field_invariants={"state_word": {"enum": [0xC002F2A0]}},
    # RE-proven version-less (#N): byte-0 is the low byte of the constant
    # u32 state_word (0xA0), NOT a DIAG version. The state_word enum gate below
    # already rejects every foreign payload; gating byte-0 would be redundant
    # and semantically wrong. See the byte-0 RE note in the module docstring.
    version_less=True,
)
def parse_0x197f(log_time: int, data: bytes) -> Diag0x197F | None:
    if len(data) < 4:
        return None
    state_word = unpack_from('<I', data, 0)[0]
    if state_word != 0xC002F2A0:
        return None
    return Diag0x197F(
        log_time=log_time,
        state_word=state_word,
    )
