"""0x148E — Small GNSS status report (18B fixed; corpus-validated byte map).

Cross-chipset RE corpus (2026-05-08, 34,393 records / 177 captures /
15 chipset families).  18-byte fixed-size payload.

Corpus-wide invariants:
  [0]  = 0x01 (1798/1798 sampled records on 50-capture sample —
                   likely 100% corpus-wide)
  [12] = 0x00
  [13] = 0x00
  [15] = 0x00
  [16] = 0x00
  [17] = 0x00

Varying bytes (multi-valued across corpus):
  [1]    param_a — multi-modal (top: 0x48 36.8%, 0x40 14.1%, 0x54 12.8%);
                    most values have low 2 bits zero (4-byte aligned hint)
  [2:4]  u16LE counter1 — wraparound counter; increments by 5 per record
                           on M2000 captures, by 1280 per record on FN980
                           cold-reset
  [4]    code4 — small varying enum (0x00 dominant, 0x01 also seen)
  [5:7]  u16LE value_a
  [7:9]  u16LE field_b — values like 0x7fff (signed-int-max-ish) on FN980
                           cold-reset + M2000 + EG18-NA captures; 0x0000 on
                           85%+ of corpus-wide records (when GNSS not
                           actively measuring?). Plausibly a sentinel-or-
                           measurement field.
  [9]    count_c — small varying int
  [10]   code10 — small varying enum
  [11]   code11 — small enum (M2000 shows 0x04 dominant, then 0x01/0x02/0x05)
  [14]   aux14 — multi-valued in some captures (most are 0x00)

v1 (2026-04-12) RE from a single FN980m SDX55 capture exposed
version + param_a + counter + flags + count_a/b/c/d.  v2 (2026-05-08):
- Adds field_b (bytes 7-8 u16LE) that v1 missed entirely
- Adds aux14 (byte 14) that v1 missed entirely
- Fixes to_dict() bug — v1 dataclass had `flags` field but to_dict()
  silently dropped it (8 fields in dataclass, 7 keys in dict)
- Adds defensive reserved-zero validation at bytes [12, 13, 15, 16, 17]

Split from `gnss_demod.py` per #N tier-2 batch 12.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_GNSS_CC_PERFORMANCE_STATS_C
        source: qualcomm_diag_log_codes_h (authority: vendor_official)
    aliases:
        RESERVED
            source: qxdm_itemtype_list_zukgit_2025_04_03

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from diaggrok.registry import register

LOG_GNSS_STATUS_148E = 0x148E

_148E_VERSION = 0x01


# Ground-truth capture recipe (#N / #N — <redacted-ref> 2026-06-07). ONE recipe:
# v=0x01 on the Telit LM960A18 (SDX20), corpus-attested (34 LM960 captures).
# Authored OFFLINE, hw_run_performed=False — a later hardware run flips it.
#
# Vendor name (LOG_GNSS_CC_PERFORMANCE_STATS_C, qualcomm_diag_log_codes_h /
# vendor_official) identifies this as GNSS-engine performance stats — mostly
# opaque internal counters with NO clean AT reference, so this is a low-ground,
# discovery-grade recipe (honest by design, per #N). The one field with a
# discernible external signal is field_b: the corpus shows it reads ~0x7fff on
# captures where GNSS is actively measuring (FN980 cold-reset, M2000, EG18-NA)
# and 0x0000 on 85%+ of records (engine idle) — a candidate 'actively-measuring'
# indicator that can be correlated to GNSS active/fix state via AT$GPSP?/
# AT$GPSACP. counter1 is a per-record wraparound counter (epoch/measurement
# cadence) grounded only loosely as a monotonic base. param_a/code4/value_a/
# count_c/code10/code11/aux14 are opaque performance-stat bytes with no AT
# reference and are intentionally not grounded. version is structural (0x01).
#
# NOT YET VALIDATED. The bench LM960 (e3296e3) can't validate it now: the DIAG
# port fails the diaggulp log-mask handshake (#N/#N), so no 0x148E stream
# is capturable yet.

@dataclass
class Diag0x148E:
    log_time: int
    version: int           # byte 0 — constant 0x01
    param_a: int           # byte 1 — multi-valued code
    counter1: int          # bytes [2:4] u16LE — wraparound counter
    code4: int             # byte 4 — small varying enum (NEW v2 — v1 missed)
    value_a: int           # bytes [5:7] u16LE
    field_b: int           # bytes [7:9] u16LE (NEW v2 — v1 missed)
    count_c: int           # byte 9
    code10: int            # byte 10 — small varying enum (NEW v2 — v1 missed)
    code11: int            # byte 11
    aux14: int             # byte 14 (NEW v2 — v1 missed)
    payload_size: int

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x148E',
            'log_time': self.log_time,
            'version': self.version,
            'param_a': self.param_a,
            'counter1': self.counter1,
            'code4': self.code4,
            'value_a': self.value_a,
            'field_b': self.field_b,
            'count_c': self.count_c,
            'code10': self.code10,
            'code11': self.code11,
            'aux14': self.aux14,
            'payload_size': self.payload_size,
        }


@register(
    LOG_GNSS_STATUS_148E,
    name="0x148E",
    issues=(),
    description="Small GNSS status report (0x148E) — 18B fixed; corpus-validated byte map",
    version=2,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v1 (2026-04-12) RE from FN980m SDX55 only.  v2 (2026-05-08) "
        "cross-validated against 34,393-record corpus / 177 captures / "
        "15 chipset families.  Adds field_b (bytes 7-8 u16LE) and aux14 "
        "(byte 14) that v1 missed; fixes to_dict() omission of `flags`; "
        "adds defensive reserved-zero invariants at bytes [12, 13, 15, "
        "16, 17]."
    ),
    source_url="",
    fields_identified=11, fields_parsed=11,
    # Layer-2 invariants from the 2026-05-08 cross-chipset corpus walk
    # (34,393 records / 177 captures / 15 chipset families). version is
    # corpus-wide 0x01; payload_size is strictly 18B. The parser already
    # Layer-1-gates both (size != 18 → None, byte[0] != 0x01 → None);
    # declaring here per #N sweep so the invariant is visible to
    # downstream Layer-2 audit consumers (parser_corpus_summary,
    # diaggrok_corpus_sweep). Byte-level reserved-zero invariants at
    # [12,13,15,16,17] are also Layer-1-enforced but live in fixed body
    # offsets, not in surfaced field names — left out of the enum since
    # there's no corresponding to_dict key.
    field_invariants={
        "version": {"enum": [0x01]},
        "payload_size": {"enum": [18]},
    },
)
def parse_0x148e(log_time: int, data: bytes) -> Diag0x148E | None:
    if len(data) != 18:
        return None
    if data[0] != _148E_VERSION:
        return None
    # Defensive: corpus-wide reserved-zero invariants at bytes
    # [12, 13, 15, 16, 17] — non-zero indicates framing collision with
    # another 0x14xx code.  Bytes [4] and [10] DO vary across the
    # corpus and must NOT be asserted constant.
    if data[12] != 0 or data[13] != 0:
        return None
    if data[15] != 0 or data[16] != 0 or data[17] != 0:
        return None
    counter1 = data[2] | (data[3] << 8)
    value_a = data[5] | (data[6] << 8)
    field_b = data[7] | (data[8] << 8)
    return Diag0x148E(
        log_time=log_time,
        version=data[0],
        param_a=data[1],
        counter1=counter1,
        code4=data[4],
        value_a=value_a,
        field_b=field_b,
        count_c=data[9],
        code10=data[10],
        code11=data[11],
        aux14=data[14],
        payload_size=len(data),
    )
