"""0x7160 — GNSS-engine-start cluster sibling (#N), cross-chipset header-only stub.

Cluster: 0x7153/0x7154/0x7155/0x7156/0x7160 fire together during the
GNSS-engine-start critical section. Siblings 0x7155 (slot-table) and
0x7156 (empty-buffer twin) are RE'd; 0x7160 is the largest record of
the cluster and remains structurally unresolved beyond the header.

## Cross-chipset corpus (2026-05-20)

`tools/diag_code_info.py 0x7160` shows the code is NOT LM960-only as
the original #N title implies. It fires across **3 chipset
generations / 3 vendors / 2 size classes**:

| Modem        | Chipset | Firmware                  | Records | Payload size | byte0 |
|--------------|---------|---------------------------|---------|--------------|-------|
| LM960A18     | SDX20   | 32.01.1X0                 | 3       | **8004**     | 0x01  |
| MC7411       | SDX20   | SWI9X50C_01.14.22.00_unit2| 8       | **8004**     | 0x01  |
| FN980m       | SDX55   | M0H.030282 / AT&T profile | 16      | **9004**     | 0x02  |
| RM520N-GL    | SDX62   | RM520NGLAAR03A03M4G       | 4       | **9004**     | 0x02  |

**Clean chipset-keyed (size, version) split** — no overlap. Same shape
as 0x1C6E (#N) and 0x1636 — byte 0 is the version field, the
payload-size step (+1000 B between v1→v2) likely encodes a per-entry
field added in the SDX55-era IPA/GNSS stack.

Header bytes:
  - byte[1] = 0x01     (sub-flag, role TBD — corpus-invariant)
  - bytes[2:4] = entry_count (LE u16), high byte (byte[3]) corpus-invariant 0x00

## 2026-06-26 re-walk (N=31 → 514) — two prior claims REFUTED

A fresh corpus walk (514 records / 54 captures, incl. a new RM520N-GL
survey `<redacted-pii>` with 69 records and a new Sierra
EM7565 emitter) overturns the 2026-05-20 framing:

1. **entry_count is NOT "corpus-invariant 100".** It is dynamic —
   observed values {70 (0x46), 100 (0x64)} with INTRA-capture variance
   (one survey emits both). The prior `entry_count != 100` hard gate was
   silently dropping 97/514 records (18.9%), including ALL 69 RM520N-GL
   survey records. Gate relaxed to the real invariant (high byte 0x00).

2. **The "100 × 90-byte entries" stride hypothesis is REFUTED.** On an
   entry_count=70 RM520N-GL record, the body region past the predicted
   70×90=6300 boundary is 69% non-zero (not zero-padded), and the body
   carries a clean **12-byte repeating substructure**
   (`XX XX 20 07 | e0 ff 0f 00 | YY YY f6 ff`) that flows through the
   boundary. So entry_count does NOT index a 90 B/entry table. The
   per-entry body layout remains unresolved (new lead: the 12 B stride).

## "Size invariance ≠ format invariance" hedge

Per `core-memories.md`: a future SDX65/SDX72 firmware can ship version
0x03 in the same 9004-byte envelope under a new struct layout. This
parser declares `field_invariants={"version": {"enum": [1, 2]}}` so
a record with `byte[0] not in {1, 2}` returns None and surfaces as a
no-parser miss instead of being silently mis-decoded as v2.

Likewise, the (size, version) tuple is enforced inside the body —
v1/9004 or v2/8004 records reject. The corpus has not yet shown
mismatched tuples, so any future occurrence should be investigated as
a real chipset variant before relaxing the gate.

## Next steps (tracked on #N)

- 4-byte-header confirmed. The 80 B/90 B per-entry stride hypothesis is
  REFUTED (see re-walk note above); the body instead shows a 12-byte
  repeating substructure — decode that next (does entry_count count a
  subset of the 12 B records? 9000 B / 12 = 750 candidate slots).
- Cross-reference techplayon + SCAT for canonical
  name (range 0x71xx is Qualcomm's Sensor / Location subsystem).
- Promote to T1 once the 12 B-stride body substructure is RE'd and
  entry_count's role (count of what?) is grounded.

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: LOG_UMTS_NAS_PPLMN_LIST
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


_LOG_CODE = 0x7160

# Cross-chipset (size, version) tuples observed across the corpus
# as of 2026-05-20 (#N).  Layer-1 gate; mismatched tuples return
# None.  Layer-2 invariant on the version enum below catches any
# silent drift if the gate is ever bypassed.
_VERSION_SDX20 = 0x01
_VERSION_SDX55_PLUS = 0x02
_SIZE_V1 = 8004
_SIZE_V2 = 9004
_OBSERVED_VERSIONS: tuple[int, ...] = (_VERSION_SDX20, _VERSION_SDX55_PLUS)
_VERSION_TO_SIZE = {
    _VERSION_SDX20: _SIZE_V1,
    _VERSION_SDX55_PLUS: _SIZE_V2,
}

# Header constants stable across all modems / both versions.
# byte[1] = sub-flag (role TBD, corpus-invariant 0x01).
_EXPECTED_SUB_FLAG = 0x01
# bytes[2:4] = entry_count (LE u16). NOT a constant — 2026-06-26 re-walk
# (N=514) shows it is DYNAMIC: observed {70, 100} with *intra-capture*
# variance (one survey capture emits both 0x46 and 0x64). The prior
# "corpus-invariant 100" claim is refuted; the only invariant is the
# high byte (data[3]) == 0x00 (entry_count <= 255) corpus-wide.
_ENTRY_COUNT_HI_INVARIANT = 0x00  # data[3] — corpus-wide 0x00 (N=514)
_ENTRY_COUNT_MAX = 0xFF           # high-byte-zero => value fits in a byte


@dataclass
class Diag0x7160:
    """0x7160 — GNSS-engine-start cluster sibling, header-only stub (#N)."""
    log_time: int
    version: int            # byte[0] — 0x01 (SDX20) | 0x02 (SDX55+)
    sub_flag: int           # byte[1] — corpus-invariant 0x01
    entry_count: int        # bytes[2:4] LE u16 — DYNAMIC count (obs {70,100}); hi byte 0x00
    payload_size: int
    body_raw: bytes

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": "Diag0x7160",
            "log_time": self.log_time,
            "version": self.version,
            "sub_flag": self.sub_flag,
            "entry_count": self.entry_count,
            "payload_size": self.payload_size,
        }


# Ground-truth recipe (#N). v1 (8004B / byte0=0x01) is the SDX20 profile
# the MC7411 + LM960 emit. The parser is header-only (version, sub_flag=0x01,
# entry_count=100) — all structural constants, no field carries a physical
# quantity an AT command returns. So this is a TRIGGER-CORRELATION recipe: the
# value being validated is that a 0x7160 v1 record is emitted at GNSS-engine
# start, captured in the SAME sky-fix session as 0x188E (which validates the
# per-SV measurements). Names-block canonical (LOG_UMTS_NAS_PPLMN_LIST,
# community) is a mis-attribution — the cross-modem cluster RE (#N) places
# this firmly in the GNSS-engine-start critical section.

@register(
    _LOG_CODE,
    name="0x7160",
    description=(
        "GNSS-engine-start cluster sibling — header-only stub (#N). "
        "Chipset-keyed (size, version) split: 8004 B / v=1 on SDX20 "
        "(LM960, MC7411, EM7565), 9004 B / v=2 on SDX55+ (FN980m, "
        "RM520N-GL). Header: version, sub_flag=0x01, entry_count "
        "(DYNAMIC u16, obs {70,100}, hi byte 0x00). Per-entry body NOT "
        "decoded; the 90 B/entry stride hypothesis is REFUTED (#N)."
    ),
    version=3,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "Clean-room header RE across 4-modem / 3-vendor / 2-chipset "
        "corpus extracted 2026-05-20: LM960A18 SDX20 32.01.1X0, "
        "MC7411 SDX20 SWI9X50C_01.14.22.00, FN980m SDX55 M0H.030282 "
        "(AT&T profile 10), RM520N-GL SDX62 RM520NGLAAR03A03M4G. "
        "Clean chipset-keyed (size, version) split — same pattern as "
        "0x1C6E (#N) and 0x1636. Per-entry layout not yet RE'd. "
        "v3 (2026-06-26, #N): added an RM520N-GL (SDX62) v2/9004B "
        "GroundTruth recipe — the Quectel owner cannot run the MC7411 "
        "v1 Sierra-AT recipe, and RM520N-GL emits a different version "
        "byte (v2), so it gets its own per-(modem,version) recipe "
        "(triggered, hw_run_performed=False, fields hypothesis)."
    ),
    source_url="",
    issues=(),
    fields_parsed=4,        # version + sub_flag + entry_count + payload_size
    fields_identified=4,
    # Layer-2 invariant — catches a future v3 firmware that ships
    # the same 8004 or 9004 byte envelope under a new struct layout.
    # See `core-memories.md` ("size invariance ≠ format invariance").
    field_invariants={
        "version": {"enum": list(_OBSERVED_VERSIONS)},
        "sub_flag": {"enum": [_EXPECTED_SUB_FLAG]},
        # entry_count is DYNAMIC (obs {70,100}, intra-capture variance) —
        # only the high-byte-zero structural bound is corpus-invariant.
        "entry_count": {"range": (0, _ENTRY_COUNT_MAX)},
    },
)
def parse_0x7160(log_time: int, data: bytes) -> Diag0x7160 | None:
    """Parse the 4-byte header of a 0x7160 record.

    Returns None if:
      - payload length is not 8004 (v1) or 9004 (v2)
      - byte[0] (version) is not in {0x01, 0x02}
      - (version, len(data)) tuple does not match the observed split
        (v1 must be 8004 B; v2 must be 9004 B)
      - byte[1] (sub_flag) is not 0x01
      - byte[3] (entry_count high byte) is not 0x00 (entry_count > 255)

    Each of these guards rejects rather than silently mis-decoding a
    record that drifts from the observed corpus.  When a future capture
    surfaces a record this parser rejects, the no-parser miss is the
    signal that the corpus invariants need re-validation against the
    new chipset/firmware family.
    """
    if len(data) < 4:
        return None

    version = data[0]
    if version not in _OBSERVED_VERSIONS:
        return None
    if len(data) != _VERSION_TO_SIZE[version]:
        return None

    sub_flag = data[1]
    if sub_flag != _EXPECTED_SUB_FLAG:
        return None

    # entry_count is a DYNAMIC u16 count (obs {70, 100}, intra-capture
    # variance) — do NOT gate on a specific value (the prior `!= 100`
    # gate silently dropped 97/514 records, incl. all 69 RM520N-GL
    # survey records). The only structural reject is the corpus-wide
    # high-byte-zero invariant (data[3] == 0x00).
    if data[3] != _ENTRY_COUNT_HI_INVARIANT:
        return None
    entry_count = unpack_from("<H", data, 2)[0]

    return Diag0x7160(
        log_time=log_time,
        version=version,
        sub_flag=sub_flag,
        entry_count=entry_count,
        payload_size=len(data),
        body_raw=data,
    )
