"""GNSS_ME_RF_BP_AGC (0x163D) — skeleton parser (#N).

Periodic AGC measurement record from the GNSS RF Bandpass family
(`GNSS_ME_RF_BP_*` codes 0x163D / 0x163E / 0x163F).

Two coexisting (size, version) forms observed across the corpus
(24,021 records / 60 captures, session `6d96` RTCM-revisit):

| Form        | Count          | Where seen                                 |
|-------------|----------------|--------------------------------------------|
| 61 B v=0x04 | 21,934 (91.3%) | every modem family in the corpus           |
| 60 B v=0x03 |  2,087 ( 8.7%) | ONLY Quectel EG25-G fw EG25GGBR07A08M2G_30.201 (older than A0.301) |

Parser accepts both forms — field layout up through byte +19 is
identical.  Structural fields (version, sub_version, +2..9 counters,
chain_id at +19, payload_size) decode on both forms.  The 61B v=0x04
form additionally decodes (<redacted-ref>-05-30, 57,721-record walk):

- ``agc_pair_a``/``agc_pair_b`` (+29..30 / +31..32 u16-LE) — a near-equal
  two-chain AGC measurement (median |a-b| = 0 across 11/12 modems)
- ``rf_metric_a``/``rf_metric_b`` (+41..44 / +45..48 BE-f32) — bounded
  dB-plausible metrics clustering at {8, 20, 32, 63} (unit SNR/CN0/AGC-
  gain still TBD)

These are ``None`` on the 60B v=0x03 form (no corpus coverage at those
offsets).  The trailing per-band block (+50..+60) remains opaque pending
AT-side cross-validation; a rejected +49/+53 u16 pair is documented in
``source_detail`` v6.

## Family note — chain_id is RF-state-dependent

`chain_id` at +19 takes 4+ distinct values across the corpus
(0x4c 60.4%, 0x55 20.8%, 0x4e 18.7%, plus rare 0x00/0xc0/0xc6).
At least 8 captures show the byte varying within a single capture
(e.g. one LM960 32.01.150 capture has 206×0x4c + 98×0x55).  Earlier
"chipset-generation marker" (`11d0`) and "per-modem RX-chain marker"
(`1c59`) interpretations have both been retracted — the byte is
RF-state-dependent (likely active-band / antenna-routing / RX-path
index) and is NOT a stable identifier.

Sibling code 0x163E (JAMMER) carries the same chain_id state at a
different offset (+11); see `diag_0x163e.py`.  Sibling 0x163F (NOTCH)
exhibits a separate chipset-generation populated/all-zero body story.

Test fixtures (per (chipset, code) cross-validation):
- `<redacted-pii>`  (61 B, v=0x04)
- `<redacted-pii>`   (61 B, v=0x04)
- `<redacted-pii>`  (61 B, v=0x04)

=== names-block:start (auto-generated by tools/inject_names_block_parsers.py) ===

Names by source (from sources/DIAG_LOG_INDEX.yaml):
    canonical: RESERVED
        source: qxdm_itemtype_list_zukgit_2025_04_03 (authority: community)
    aliases: (none recorded)

Source-precedence (#N): vendor_official > observation >
community (specification) > community (reference).
=== names-block:end ===
"""
from __future__ import annotations

from dataclasses import dataclass
from struct import unpack_from
from typing import Any

from diaggrok.registry import register


LOG_GNSS_ME_RF_BP_AGC = 0x163D

# 61B v=0x04 body field offsets, RE'd 2026-05-30 <redacted-ref> session over a
# 57,721-record corpus walk (tools/diag_163d_body_re.py +
# diag_163d_pair_float_verify.py). All gated to the 61B form — the 60B v=0x03
# form (older EG25-G fw, 2,087 records) has no corpus coverage at these
# offsets, so they stay None there.
_AGC_PAIR_A_OFF = 29   # u16-LE, near-equal to _b (two-chain AGC measurement)
_AGC_PAIR_B_OFF = 31   # u16-LE
_RF_METRIC_A_OFF = 41  # BE-f32, bounded ~8..64 (dB-plausible; unit TBD)
_RF_METRIC_B_OFF = 45  # BE-f32, bounded ~20..64 (dB-plausible; unit TBD)
_V4_BODY_MIN_LEN = 49  # need bytes through +48 for rf_metric_b


@dataclass
class Diag0x163D:
    """GNSS RF Bandpass AGC status (0x163D) — skeleton parser (#N).

    Two coexisting record formats observed in the corpus (24,021 records):

    - **61 B, version=0x04** — majority (21,934 / 91.3%); seen on every
      modem family in the corpus
    - **60 B, version=0x03** — minority (2,087 / 8.7%); seen only on
      Quectel EG25-G with firmware ``EG25GGBR07A08M2G_30.201.30.201``
      (older fw than the A0.301 generation)

    Parser accepts both forms — the field layout up to byte +19 is
    identical between the two.  Only structural fields (version,
    sub_version, counters at +2..9, chain_id at +19, payload size) are
    decoded; the float SNR fields, AGC counter pair, and trailing
    per-band block remain opaque pending AT-side cross-validation.
    """
    log_time: int
    version: int                # +0   — 0x04 (61B form) or 0x03 (60B form)
    sub_version: int            # +1   — 0x00 cross-corpus (likely subtype)
    counter_a: int              # +2..5  signed counter (varies)
    counter_b: int              # +6..9  signed counter (varies, often -3/-2)
    chain_id: int               # +19  — RF-state-dependent byte (see module docstring)
    payload_size: int
    raw: bytes                  # full payload retained for downstream RE
    # --- 61B v=0x04 form only (None on the 60B v=0x03 form, which has no
    #     corpus coverage at these offsets) ---
    agc_pair_a: int | None      # +29..30 u16-LE — near-equal two-chain AGC measurement
    agc_pair_b: int | None      # +31..32 u16-LE — paired with agc_pair_a (med|Δ|≈0)
    rf_metric_a: float | None   # +41..44 BE-f32 — bounded ~8..64 (dB-plausible; unit TBD)
    rf_metric_b: float | None   # +45..48 BE-f32 — bounded ~20..64 (dB-plausible; unit TBD)

    def to_dict(self) -> dict[str, Any]:
        return {
            'type': 'Diag0x163D',
            'log_time': self.log_time,
            'version': self.version,
            'sub_version': self.sub_version,
            'counter_a': self.counter_a,
            'counter_b': self.counter_b,
            'chain_id': self.chain_id,
            'agc_pair_a': self.agc_pair_a,
            'agc_pair_b': self.agc_pair_b,
            'rf_metric_a': self.rf_metric_a,
            'rf_metric_b': self.rf_metric_b,
            'payload_size': self.payload_size,
            'parser_status': 'skeleton+agc-pair+rf-metrics',
            'parser_note': (
                f'{self.payload_size}B v={self.version:#04x}; chain_id is '
                'RF-state-dependent (varies within a single capture) — '
                'do not treat as a stable per-modem identifier. 61B form: '
                'agc_pair_a/b (+29/+31 u16-LE) are a near-equal two-chain '
                'measurement; rf_metric_a/b (+41/+45 BE-f32) are bounded '
                'dB-plausible metrics (cluster {8,20,32,63}; physical unit '
                'SNR/CN0/AGC-gain TBD). See #N.'
            ),
        }


# Ground-truth recipe (#N) — EC25/EG25 family (MDM9607). GNSS RF bandpass AGC.
# This is a DISCOVERY recipe: no AT/QMI command returns GNSS front-end AGC gain
# or the rf_metric floats, so every field grounds by CORRELATION against an
# observable RF quantity, not value-equality.
# ⚠️ VERSION/BUILD: the body fields below (agc_pair_*, rf_metric_*) decode ONLY
# on the 61B v=0x04 form. EG25-G firmware 30.201 emits the OLDER 60B v=0x03 form
# where these offsets are uncovered (parser returns None), so this recipe targets
# the v=0x04 form on a newer A0.301 build (which we own); validate on A0.301+, not
# 30.201. cond="sky-fix": AGC/rf_metric track the live GNSS RF environment.

@register(
    LOG_GNSS_ME_RF_BP_AGC,
    name="0x163D",
    description=(
        "GNSS_ME_RF_BP_AGC (0x163D) — periodic AGC measurement; "
        "two coexisting forms (61B v=0x04 majority, 60B v=0x03 minority on "
        "older EG25-G fw); chain_id at +19 is RF-state-dependent, not stable (#N)"
    ),
    version=6,
    author="Luke Jenkins",
    author_url="https://github.com/lukejenkins",
    source_type="re",
    source_detail=(
        "v6 (2026-05-30, <redacted-ref> session — #N body field decode): walked "
        "57,721 0x163D 61B records (tools/diag_163d_body_re.py + "
        "diag_163d_pair_float_verify.py) across 12 modem groups. Promotes "
        "four previously-opaque body fields, all gated to the 61B v=0x04 "
        "form (the 60B v=0x03 form has no corpus coverage at these offsets "
        "→ None):\n"
        "(1) agc_pair_a (+29..30 u16-LE) and agc_pair_b (+31..32 u16-LE) are "
        "a NEAR-EQUAL two-chain AGC measurement: median |a-b| = 0 for 11/12 "
        "modems (em7511 = 2), per-modem med_a == med_b for ALL 12, and the "
        "pair agrees within 5 LSB on 80-100% of records (incl. SDX62 "
        "rm520ngl 99.6%). Same 'two RF chains sampling the same quantity' "
        "motif seen in sibling 0x163F (meas_block_a≈_b) and 0x1646 "
        "(rf_metric_1≈_2).\n"
        "(2) rf_metric_a (+41..44 BE-f32) and rf_metric_b (+45..48 BE-f32) "
        "are bounded floats: 100% finite, ~100% within 0..1000 across ALL 12 "
        "modems (SDX62 included), values clustering at dB-plausible {8, 20, "
        "32, 63}. This CONFIRMS the prior comment's 'float SNR fields at "
        "+41..+48 (BE-f32)' hypothesis at 57k-record scale. Named "
        "structurally (rf_metric_*) — exact physical unit (SNR vs CN0 vs AGC "
        "gain, all in dB) remains TBD pending RTCM-paired RFI ground truth.\n"
        "(3) REJECTED: a candidate +49..50 / +53..54 u16-LE pair — median "
        "|a-b| of 768..4352 and <10% within-5-LSB on every modem but eg12gt; "
        "NOT a near-equal pair, left opaque.\n"
        "fields_parsed 6→10; issue stays OPEN per no-close-partial (structural "
        "decode, physical units still TBD).\n"
        "v5 (closure-rigor pass): added field_invariants={'version': "
        "{'enum': [0x03, 0x04]}} so layer-2 invariant rejection makes any "
        "future v=0x05 firmware visible instead of silently mis-parsing as "
        "v=0x04 or v=0x03. Core-memory rule applies: 'size invariance ≠ "
        "format invariance' — a future v=0x05 in the same 61B size would "
        "ship a new struct layout and the existing parser would return "
        "plausible-looking but wrong counter_a / counter_b / chain_id "
        "values from bytes that now mean something else. Enum bound to the "
        "two corpus-verified versions (24,021+ records, sessions 6d96 / "
        "3a73).\n"
        "v4 (2026-04-27, <redacted-ref> RTCM-revisit redo via "
        "tools/parser_corpus_summary.py): walked 24,021 records across 60 "
        "captures. Two findings supersede the v3 claims:\n"
        "(1) Two record forms coexist: 61B v=0x04 (21,934 records, all "
        "modem families) and 60B v=0x03 (2,087 records, ONLY on EG25-G "
        "firmware EG25GGBR07A08M2G_30.201.30.201). The v3 claim '61B fixed "
        "size cross-chipset, version=0x04 invariant' was true only because "
        "the v3 sample didn't include the older EG25-G firmware.\n"
        "(2) chain_id at +19 takes 4+ distinct values across the corpus: "
        "0x4c (60.4%), 0x55 (20.8%), 0x4e (18.7%), plus rare outliers "
        "(0x00, 0xc0, 0xc6). chain_id varies WITHIN single captures on at "
        "least 8 captures (e.g. one LM960 32.01.150 capture has 206×0x4c + "
        "98×0x55; one EM9190 capture has 1786×0x4e + 17×0x4c). The v3 "
        "'per-modem RX-chain marker' interpretation is also wrong — same "
        "modem reports different chain_ids in different captures AND within "
        "one capture. The byte is RF-state-dependent (likely tracking "
        "active band / antenna routing / RX path index), not a stable "
        "identifier."
    ),
    fields_parsed=10,
    fields_identified=10,
    issues=(),
    field_invariants={"version": {"enum": [0x03, 0x04]}},
)
def parse_0x163d(log_time: int, data: bytes) -> Diag0x163D | None:
    """Parse a LOG_GNSS_ME_RF_BP_AGC (0x163D) payload — skeleton (#N)."""
    if len(data) < 20:
        return None
    if data[0] not in (0x03, 0x04):
        return None

    # 61B v=0x04 body fields (None on the 60B v=0x03 form — no corpus coverage)
    agc_a = agc_b = None
    rf_a = rf_b = None
    if data[0] == 0x04 and len(data) >= _V4_BODY_MIN_LEN:
        agc_a = unpack_from('<H', data, _AGC_PAIR_A_OFF)[0]
        agc_b = unpack_from('<H', data, _AGC_PAIR_B_OFF)[0]
        rf_a = unpack_from('>f', data, _RF_METRIC_A_OFF)[0]
        rf_b = unpack_from('>f', data, _RF_METRIC_B_OFF)[0]

    return Diag0x163D(
        log_time=log_time,
        version=data[0],
        sub_version=data[1],
        counter_a=unpack_from('<i', data, 2)[0],
        counter_b=unpack_from('<i', data, 6)[0],
        chain_id=data[19],
        payload_size=len(data),
        raw=bytes(data),
        agc_pair_a=agc_a,
        agc_pair_b=agc_b,
        rf_metric_a=rf_a,
        rf_metric_b=rf_b,
    )
