version = 1
cond = "idle"
modem_make = "Quectel"
modem_model = "EG18-NA"
modem_firmware = "EG18NAPAR01A06M4G"

[[field_map]]
parser_field = "entries.pci"
quantity = "lte_neighbor_physical_cell_id"
sources = [
    { kind = "at", value = "AT+QENG=\"neighbourcell\"" },
    { kind = "qmi", value = "QMI_NAS GetCellLocationInfo" },
]

[[field_map]]
parser_field = "entries.earfcn"
quantity = "lte_neighbor_earfcn"
sources = [
    { kind = "at", value = "AT+QENG=\"neighbourcell\"" },
]

[[field_map]]
parser_field = "entries.rsrp"
quantity = "lte_neighbor_rsrp_dbm"
sources = [
    { kind = "at", value = "AT+QENG=\"neighbourcell\"" },
]

[[field_map]]
parser_field = "entries.rsrq_rx0"
quantity = "lte_neighbor_rsrq_db_rx0"
sources = [
    { kind = "at", value = "AT+QENG=\"neighbourcell\"" },
]

[[field_map]]
parser_field = "entries.rsrq_rx1"
quantity = "lte_neighbor_rsrq_db_rx1"
sources = [
    { kind = "at", value = "AT+QENG=\"neighbourcell\"" },
]

[[field_map]]
parser_field = "num_cells"
quantity = "lte_neighbor_cell_count"
sources = [
    { kind = "at", value = "AT+QENG=\"neighbourcell\"" },
]
